### ISSUE TITLE
[Spell] warrior t10 bonus spell Furry

### ISSUE THREAD

**Issue by tsuff** [WoWManiaUK/Redemption#1021]
Warr t10 4piece set bonus spell is double proc of
http://wotlk.openwow.com/spell=46915
it procs but when u use your
http://wotlk.openwow.com/spell=47475
both stacks are used instantly at once wich in essence makes bonus opsolite

**Comment by Grindall** [comment]
I made an issue about the prot version of the warrior tier set, yet it seems to be deleted now...could someone tell me why?

**Comment by fvicaria** [comment]
Make sure you have this aura:
http://www.wow-mania.com/armory/?spell=70847

**Comment by wrezee** [comment]
I have the same issue.

I also talked to some other Fury Warriors and they got the same problem.

Seems like it's a server-wide issue.

**Comment by LooneyBin** [comment]
Can confirm that the 4 set bonus is infact **not** working as intendet.

408 Bloodthirst/Whirlwind/Heroic Strike, and that gave me 50 procs.
Rarely get the 2 procs, maybe 20% of the time, instead of 100%.
And both procs are used when casting Slam once.

Been using the dummies in Org, and random mobs in Icecrown to test on.

**Comment by elagen** [comment]
4 piece bonus - You have a 30% chance for your Bloodsurge and Sudden Death talents to grant 2 charges of their effect instead of 1, reduce the global cooldown on Execute or Slam by 0.5 seconds, and for the duration of the effect to be increased by 100%.

The only Thing broken here is The double Proc being consumed on 1 slam
