### ISSUE TITLE
[Raid] Gothik the Harvester - Gate opens early

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#1074]
This issue is different from #900 but it may be caused by how it was fixed.

Now, the gates open on wave 17, but the fight still goes on and Gothik is killable. However the gates should not open before the boss has 30% according to wowwiki (I cannot confirm this, on the Naxx runs we did before #900 was an issue, gates seemed to open once the boss had tp'ed to each side once). The gates opening early isn't too much of a problem. However the healer on the "right" side of the gates was taking massive damage from something invisible, which did not appear in the combat log. The healer took over 800k damage in a two minute long fight (more exactly he got healed for that amount, since the damage didn't appear in the logs) and was barely keeping himself alive with 6.4k gs... Once gothik was down, the damage on him stopped.
I guess it may be the same kind of bug as the Brann encounter in Halls of Stone #843 but on this encounter, nothing pops up in the logs.

**Comment by Feryk** [comment]
I ran this a few times with GM mode on Dev to see any invisible mobs.  However, there were none for each run.  The other player did take lots of damage from Spectral Trainee however, but this was because they had built up from the kills I was performing on the left side.  The only issue I can find here is when the gate opens.

http://wow.gamepedia.com/Gothik_the_Harvester#10-man_Strategy

"Gothik will continue to go back and forth between the two sides until he reaches 30%, at which point the gate in the middle will open up."

Per Gamepedia, the gate opens when Gothik hits 30%.  However, it opened with my tests before he teleported down.

**Comment by philoudu16** [comment]
Did u have anyone on the right side that was able to get any aggro through healing? If it's an invisible something, it will probably only start attacking once something aggros it, and since it's invisible/untargetable that means only heals will generate threat towards them (like the spirits in the Devourer of Souls encounter).

**Comment by Feryk** [comment]
The gate still opens before Gothik ever teleports down.

**Comment by VA-L** [comment]
https://www.youtube.com/watch?v=rUYaMf6Utus

**Comment by Feryk** [comment]
Re-opening this due to incorrect information.  The video Val linked above is post-original content after 3.3.5, in which Gothik's phases were modified.  However, original content shows the gate opening when Gothik hits 30% HP and not before:

https://www.youtube.com/watch?v=BzyD8HYKBrg

http://wowwiki.wikia.com/wiki/Gothik_the_Harvester_(original)

"Gothik teleports from side to side of the room every 30-45 seconds, and will open the center gate at 30-35% health allowing the full raid to kill him."

**Comment by philoudu16** [comment]
Most Wowhead comments which date back from 3.3.5 explain the mechanics were indeed different depending on if there were people on both sides or not. So it is normal for the gates to open early on the video Val linked.
The video and wowwiki links Feryk posted are both for the Vanilla Naxx encounter though...

According to this video (which is for the right expansion and with a group on each side), the gates indeed open when the boss reaches ~30% hp (25% according to the player who made the video)
https://www.youtube.com/watch?v=XtRuhZjbA3E

**Comment by philoudu16** [comment]
Either this is fixed already (on red) or it does not happen every time. This time the fight happened exactly as it should ( no invis mobs, and the gates opening when the boss reaches ~30%)
