### ISSUE TITLE
[Raid] Hodir - Ulduar

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#1089]
This post concerns Hodir in Ulduar (the 10 man version at least)
http://fr.wowhead.com/npc=32845/hodir

First of all, the first time you do this fight, the four flash freezes (in which friendly mobs should be trapped) are there, but not the friendly mobs, and the flash freezes evade, which means the adds can not be freed and buff you.
These freezes contain adds as they should when the fight resets after a wipe.

Similar issue, after the first flash freeze, the adds seem to disappear and the flash freezes evade again, which stops you from freeing them and getting buffs for the rest of the fight.

Finally, the boss' aggro seems very random. He was switching targets very fast running around after who ever pleased him.

**Comment by Lucronick** [comment]
Guild Wicked did a run in Ulduar and noticed the same issue. We attempted to kill and wiped. After we all released and ran back from the beginning of the dungeon, the NPCs were there and we were able to kill Hodir.

**Comment by AdultswimKoda** [comment]
Adult swim can confirm this.  
3 different times the boss has no Agro table  and runs around tweaking out.

**Comment by Noahcoke** [comment]
I just tried the boss now.
The aggro is not random anymore. 
The friendly npcs are there from the beginning as it can be seen here:
https://gyazo.com/8f785efc90ac38982fb3cf358f71726e

The only issue is that once the npcs are freed, they gain stacks from the Debuff "Biting Cold" http://www.wowhead.com/spell=62038/biting-cold, since they barely move or dont move at all, they will die rather quickly. Alternative you free them a bit later into the fight and they die once the ice is broken.

**Comment by Noahcoke** [comment]
Not fixed yet but new bugs:
The fight doesnt start when you attack the Iceblock where the Npcs are trapped inside. 
If you start the fight by manually attacking Hodir himself, the fight starts but Hodir doesnt move at all and just stands still. He uses his abilities but remains on one spot.
Once the trapped Npcs are freed they wont move either and seem to be evading: once they take damage they instantly get healed. They dont use any of their abilities.

**Comment by fvicaria** [comment]
Nothing changed to have new bugs. We need to do it in a group.
A lot of the mechanics will change if you are only one.
