### ISSUE TITLE
[Quest] The Killing Time (id: 13371)

### ISSUE THREAD

**Issue by gagaula123** [WoWManiaUK/Redemption#1227]
After returning in Stormwind with Bolvar's shield you can follow a series of quests.First Jaina opens a portal to Orgrimar and you speak with Thral.That quest works fine,but when you can back in Stormwind and accept the next quest Jaine is supposed to open a portal to the entrance of Undercity swers.She doesn't do that and the quest can't be completed.I tried going there by foot but the NPC is not there

**Comment by fvicaria** [comment]
Can you link quest and npc please.

**Comment by gagaula123** [comment]
http://www.wowhead.com/quest=13371/the-killing-time and http://wowwiki.wikia.com/wiki/Broll_Bearmantle

**Comment by Noahcoke** [comment]
I have done the questline now and the required quests to get there until i reached "The killing time". It is as described that Jaina wont summon any portal to Undercity and initiate the Fight there. 

Another issue that showed up was: 
Upon returning to Bolvar (http://de.wowhead.com/npc=27872/hochlord-bolvar-fordragon) and returning the quest "Return to Angrathar" (http://www.wowhead.com/quest=12499/return-to-angrathar) the cinematic sequence starts. In that sequence bolvar and saurfang die. After the cinematic is done the phasing for the wrathgate works fine, since Alextrazsa shows up as usual. But upon returning to the horde and alliance side, both Saurfang and Bolvar are still alive standing there, which shouldnt be. 

Summed up: Bug occurs as described & Phasing isnt working it should be.

**Comment by captainloozer** [comment]
Confirmed, did all the quests leading up to this one and Jaina has no dialog for opening a portal.
![killingtime](https://user-images.githubusercontent.com/9828794/29495423-7ed0cdea-8584-11e7-95d3-3b6c7acfee7c.PNG)

**Comment by dominichello** [comment]
@fvicaria  is this still under development ? Ran into the quest today after hitting 114/115 dragonblight quests :'(

**Comment by VA-L** [comment]
Alright, this quest can't be done anymore, there's no way to grab informations on retail about this one.
The only way to get some is by watching videos of it or with wowhead comments.

The event that follows the killing time quest is long (way more than 30 minutes), this one will be a huge work in progress project and i'll/we'll need as much informations as possible from all of you.
Keep in mind that the phasing starts from the Killing Time quest and the phase can't be found anymore so we'll probably have to guess it.

This one is probably the best quest event in the game (for 3.3.5) so we'll appreciate your help.

**Comment by Magabro** [comment]
The Killing Time Alliance Perspective:
https://www.youtube.com/watch?v=iMtiwygE13s

Battle for the Undercity Alliance Perspective:
https://www.youtube.com/watch?v=PxvQKCJagoI

Battle for the Undercity Horde Perspective:
https://www.youtube.com/watch?v=thvM9fd-pJA

**Comment by fvicaria** [comment]
https://www.youtube.com/watch?v=iMtiwygE13s

**Comment by GMWeeble** [comment]
Working.
