### ISSUE TITLE
[Quest] Herald of War

### ISSUE THREAD

**Issue by Yarien62** [WoWManiaUK/Redemption#1246]
http://www.wowhead.com/quest=13257/herald-of-war

High Overlord Saurfang doesn't open a portal for Orgrimmar and no "?" on Thrall and no event... (even if i come "manually" to Orgrimmar)

Description on Wowhead : When you are sent by Saurfang to Orgrimmar, a scripted event occurs when you speak with Thrall. A "wave" animation accompanies a Stormwind mage portal appearing, the Korkron guard rush to the portal, Thrall calls them back and Jaina Proudmoore appears. The following dialogue then occurs, and all the lines are fully voice acted (and the voice actress for Sylvanas sounds very slightly different then usual)

**Comment by Noahcoke** [comment]
I did the questchain until i reached the point described in the issue. I could complete the quest, the portal to undercity appear. Thrall, Jaina and Vol'jin waiting there. I could complete the quest at Vol'jin and get the new one "The battle for the undercity" (http://www.wowhead.com/quest=13267/the-battle-for-the-undercity). But instead of starting the encounter, it automatically completed the quest. This may be a unique bug on dev though. 

In particular, the issue itself is confirmed to be fixed.
