### ISSUE TITLE
[Achievement] "Burning Hot Pole Dance" and "Torch Juggler"

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1311]
Those two Mid Summer achievement is not work at the moment.
- For "Burning Hot Pole Dance" (http://www.wowhead.com/achievement=271/burning-hot-pole-dance), i have tried wearing the whole mid summer set (http://www.wowhead.com/item-set=785/midsummer-reveler)  (with 3 pieces, even tried to wear a head pieces reward from stealing flame at enemy capital)  and try to dance at the burning hot pole, at first i tried to dance like normal, and the dance automatic stop very quick ( it should be auto stop, but not that quick), i tried on keep clicking on the pole to reset dance time, keeping my character to dance at the pole continuously, but that didn't work too, after 2 min of dance continuously with the set on, i didn't get the achievement.
- For "Torch Juggler" (http://www.wowhead.com/achievement=272/torch-juggler), the Juggling Torch you throw on the air disapear and never drop down, so you can't jog those, any attemp only make you loss your Juggling Torch (which is buy at vendor, for 5 Burning Blossom each).

**Comment by fvicaria** [comment]
Can you confirm in Dev please.

**Comment by squalllh1989** [comment]
Update in 22/6: I don't know if this is fixed or not, now i can actually get the achievement "Burning Hot Pole Dance" without the set, you just go to the hot pole and dance there, you get the archive event with no summer set

**Comment by fvicaria** [comment]
Still working on it in dev.

**Comment by BleakSenpai** [comment]
http://www.wowhead.com/achievement=272/torch-juggler works properly BUT, you need 2 prerequisite quests done before being able to do the achievement. The quests enable you or teach you to catch the torches in the air instead of falling on the ground. The quests are http://wow-mania.com/armory/?quest=11922 which works, and the second one http://wow-mania.com/armory/?quest=11923 which does NOT. Without these quests, the player will not be able to catch the torches or Juggle to complete the achievement.
After doing them, as I have tested, the player can juggle only 15 (Not necessary to get 40) and keep spamming and juggling until the achievement is complete.
