### ISSUE TITLE
[Quest] The Chain Gun And You

### ISSUE THREAD

**Issue by Rukynd** [WoWManiaUK/Redemption#1318]
Unable to use the chain gun to complete the quest 'The Chain Gun And You'.  I have tried everything I could think of to fix this issue (abandon, reload ui, log out, exit game).  I opened a ticket and GM Aroma was unable to help me because I had already done everything that they would suggest.  So Aroma suggested that I post here so that someone else can check and fix this problem.

**Comment by Dennisreneholm** [comment]
I got this error aswell, i had a GM complete it for me, but i experience the exact same as OP described

**Comment by fvicaria** [comment]
Just tested this on dev and it works perfectly.
Quest has pre-requisites. 
![image](https://user-images.githubusercontent.com/9414661/27515403-19e84da6-599a-11e7-8b5b-e8cacbaea097.png)

I did them and had absolutely no problem.

**Comment by TehSkyum** [comment]
This is still an issue. When I click the guns, I get a buff called "Chain Gun Commander" but I don't actually enter the gun. I tried everything Rukynd said as well (abandon and retake, reload, relog, even removed the buff and tried clicking again), except for asking a GM (since they always tell us to post it in here first).
