### ISSUE TITLE
[Quest] Supplies to Auberdine

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1386]
Hello! I´d like to report a bugged quest named "Supplies to Auberdine" in Ashenvale. When I obtain the quest, NPC don´t move so I cannot escort him and thus the quest cannot be completed. Please fix that one. Thanks a lot.

**Comment by Fuzzykitten37** [comment]
http://www.wowhead.com/quest=976/supplies-to-auberdine
Worked fine on dev server for me. It took him maybe 5 seconds to start moving but it was mainly because he was speaking.
![wowscrnshot_071517_044811](https://user-images.githubusercontent.com/29960115/28238505-f95ffe40-691a-11e7-90d2-825275ebb489.jpg)
![wowscrnshot_071517_045025](https://user-images.githubusercontent.com/29960115/28238507-fb215bca-691a-11e7-87fa-12a53fa13d0e.jpg)
![wowscrnshot_071517_045231](https://user-images.githubusercontent.com/29960115/28238508-ffdff14e-691a-11e7-82e0-2317b2ef9e03.jpg)
![wowscrnshot_071517_045516](https://user-images.githubusercontent.com/29960115/28238511-02d53f58-691b-11e7-96cb-74eaee87832d.jpg)
![wowscrnshot_071517_045708](https://user-images.githubusercontent.com/29960115/28238512-0b285866-691b-11e7-8e58-870eebc7edb1.jpg)
![wowscrnshot_071517_045802](https://user-images.githubusercontent.com/29960115/28238513-0cff714c-691b-11e7-8357-16396331b100.jpg)
