### ISSUE TITLE
Pathing issue with npcs that patrol. 

### ISSUE THREAD

**Issue by s-scoltock** [WoWManiaUK/Redemption#1443]
I have noticed some ranged mobs (Quillboar hunters and Bael'dun Foreman in the Barrens) when aggroed they enter combat but still patrol whist attacking you hunters fire arrows & foremen torch toss.  This is a bit frustrating as it makes some spells out of range periodically.

**Comment by fvicaria** [comment]
Can you give me some specific name or id for the mob.

**Comment by s-scoltock** [comment]
It was one of the tribes of Quilboars in the Barrens so either Razormane
Hunter or Bristleback hunter (maybe both I'm at work at the moment and
Ashenvale last night 😋)

The other was the Bael'dun Foremen from the Gann's Reclamation quest

**Comment by s-scoltock** [comment]
It was one of the tribes of Quilboars in the Barrens so either Razormane Hunter or Bristleback hunter

The other was the Bael'dun Foremen from the Gann's Reclamation quest

**Comment by tvshadowz** [comment]
This has been observed in certain dungeons aswell, I believe it is a pathing issue. I'll try to test out fixes.

**Comment by s-scoltock** [comment]
Cheers Shadowz

**Comment by tvshadowz** [comment]
I'll test out a fix for it and try to apply it where necessary. As Janitor said, can you please link the NPC ids of those who are experiencing this issue as it would help us alot. 

To find a specific npc id just link the wow-head link here in these comments.

Thanks!

**Comment by Ergaro** [comment]
I am afraid the issue is quite common - i don't remember exact npcs, but i saw the problem couple of times - in Outland and Northend too.
The last npc i can remember was in Borean Tundra:
http://www.wowhead.com/npc=25719/coldarra-spellbinder

The issue is quite a problem, becaouse it leads sometimes to very big pulls - when you are fighting some nps, and "the wanderer" goes into you, and then instead of stopping it goes into another group of mobs you haven't pulled yet)

**Comment by s-scoltock** [comment]
I had some in Thousand needles too

http://www.wowhead.com/npc=4119/elder-cloud-serpent
