### ISSUE TITLE
[Quest] The Left Piece of Lord Valthalak's Amulet

### ISSUE THREAD

**Issue by Tallrasha** [WoWManiaUK/Redemption#1482]
I have problem with summoning Isalien with Brazier of Beckoning. She just did not appear. http://www.wow-mania.com/armory/?quest=8967. Can you please look at it?

**Comment by tvshadowz** [comment]
Hi there Tallrasha! 

In future could you use http://www.wow-mania.com/armory/ to link the quest and any items used with it to help us testers out as much as you can! 

This will be looked at as soon as I can, thanks for the report!

**Comment by Tallrasha** [comment]
Will do! Thanks

**Comment by tvshadowz** [comment]
Hi there Tallrasha! 

From the screenshot below you can see that this issue was tested on the dev server no matter how many Braziers of Beckoning were used, Isalein did not spawn. 

![wowscrnshot_081617_133806](https://user-images.githubusercontent.com/30256554/29363558-67a8d9e0-8288-11e7-98a1-e9bda1694643.jpg)

Thanks for the report!
