### ISSUE TITLE
"Taretha's Diversion" quest.

### ISSUE THREAD

**Issue by Pitypalaty** [WoWManiaUK/Redemption#1497]
Quest link: http://www.wowhead.com/quest=10283/tarethas-diversion

I am stucked with this quest unfortunately, so i'd like to ask a GM to remove it from me, so i can get the quest again and after a restart or a server update i can complete it, hopefully.

Character name: Pitypalaty (contact Pilly if you can't reach the other one)

Thank you in advance!

**Comment by tvshadowz** [comment]
Hi there Pitypalaty!

Please follow this link on how to properly report a bug https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue . 

We'll need you to be specific as to what the issue is and whether it is just the fact that you can't abandon the quest. 

Thanks for the report!

**Comment by Pitypalaty** [comment]
Can't you just contact me in-game?:DDD it's my 2nd ticket in 30 minutes...

**Comment by tvshadowz** [comment]
I understand it may be your second ticket in 30 minutes but you have not filled out the bug reports well enough for us to understand the issue. Until you do so we aren't aware of what is needed to be fixed.
