### ISSUE TITLE
RDF Exp and Gold rewards

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#1504]
So the way it's intended to work is that the first RDF you complete each day gives you a greater EXP and gold reward than all the rest you complete afterwards.

Issue: On a leveling character that runs RDF, the first RDF every day gives absolutely zero exp or gold right now (they are also missing from the reward chart when you log in), still provides satchel and maniac point though.
The follow up RDFs provide the normal base exp and gold you would get for that level.

Rewards also bug out when "switching" up to the next level bracket (on lvl 16, 26, 36 etc), at these points your exp and gold gain should adjust to being 10 levels higher, however here what happens is you lose the reward for the next RDF again. (the exp and gold disappears, satchel and maniac point stays) 
For the followup RDFs it appears again, adjusted to the new level range you're in.

It might seem unimportant as this only affects levelers, but you essentially lose reward every 1 out of 5 RDF on average, on top of not getting the "extra" for completing the first of the day.

**Comment by tvshadowz** [comment]
Hi there Dranah! 

Exp should increase depending on the level rather than daily participation but here's what I found. 

1. The first RDF of the day gives the basic raw amount of exp depending on your level and then if its effected by double exp weekend. See exp table [here ](http://wowwiki.wikia.com/wiki/Dungeon_Finder)

2. Follow up dungeons do give bonus exp on completion with a satchel and maniac points as seen by the screenshots below. 

**Before the first daily RDF**
![wowscrnshot_081917_120713](https://user-images.githubusercontent.com/30256554/29486484-87442e28-84de-11e7-9fb7-856b17e31458.jpg)

**Before the second RDF**
![wowscrnshot_081917_125140](https://user-images.githubusercontent.com/30256554/29486485-8bd20b0e-84de-11e7-9c4b-c684e1372e57.jpg)

As this works properly on dev I presume it will be copies over. 

Thanks for the report!
