### ISSUE TITLE
[Quest] For Great Honor - PvP quest. #8367

### ISSUE THREAD

**Issue by Unstoppablee** [WoWManiaUK/Redemption#1510]
Hello.

I think that I have problem with this quest.
To complete it you need to give NPC Mark of Honors from BG's.

I took one of those in Orgrimmar and one in Sattrath.
The one from Orgrimmar is completed, but I can't turn it, no question mark at NPC.
I believe that is same NPC where it starts, but it can't be turned. (Horde Warbringer)

Anyway I checked in Orgrimmar (completed), Undercity, Sattrath and Dalaran. (According to Amytis (GM) it can be completed and taken anywhere. So I'd like you guys to test it, because it can't be turned.

Thanks a lot.
Best regards.

Link: 
http://wow-mania.com/armory/?quest=8367

Another quest with 6 mark (didn't completed yet):
http://wow-mania.com/armory/?quest=13476

**Comment by captainloozer** [comment]
Unstoppablee,

Thank you for your report.  I've found when manually adding the quest you linked (8367), after getting all 4 marks, the quest shows complete.  However, when approaching the horde warbringer in Undercity, he does not allow me to turn in that quest.  However, he does allow me to pick up a different quest, one for 6 marks instead of 4:

http://wow-mania.com/armory/?quest=13476

Additionally, with that quest as well, I have all the marks as shown and I am not able to turn it in using the Horde Warbringer in Undercity, which is where I originally picked up the quest.

![image](https://user-images.githubusercontent.com/9828794/29497314-80624d88-85ab-11e7-9ba6-9437b70ac5f4.png)

**Comment by captainloozer** [comment]
Tested in Orgrimmar, same result

![image](https://user-images.githubusercontent.com/9828794/29497355-fa67a8c6-85ab-11e7-8a78-04a3d89c1b99.png)

**Comment by Unstoppablee** [comment]
So on next update, it will be fixed? Since it is fixed in dev. 
Thank you all.

Best regards.

**Comment by tvshadowz** [comment]
Fix confirmed in dev

![testd](https://user-images.githubusercontent.com/30256554/29507741-47cfa3dc-8649-11e7-963e-056770d0e9b5.png)

**Comment by Unstoppablee** [comment]
Let me know when it is fix od Redemption.
Thank you.

**Comment by tvshadowz** [comment]
When release 43 is deployed to live, it will be put on redemption.

**Comment by Unstoppablee** [comment]
I was able to turn quest in Dalaran now. Will try tomorrow to turn another one in Orgrimmar.

**Comment by tvshadowz** [comment]
This should be fixed in all major cities.

**Comment by Unstoppablee** [comment]
Thank you.
