### ISSUE TITLE
Not an issue... just a suggestion to consider.. 

### ISSUE THREAD

**Issue by TheGreyMouser** [WoWManiaUK/Redemption#1535]
Currently .vip revive leaves playes with 10 minutes of rez sickness.  Perhaps having this work similar to a warlock soulstone would be an option.  
A) Players would find this more beneficial and
B) More players would subscribe to vip for this feature, generating more revenue to help you guys run the server. *or buy beer*... which ever.

**Comment by tvshadowz** [comment]
Hey TheGreyMouser! 

Just wanted to say thank you so much for the recommendation, I'll make sure to forward this on because it's something that should be happening. 

In future suggestions are more appreciated [here ](https://www.wow-mania.com/forum/viewforum.php?f=15&sid=4a3a59818513fdbe68260789809843d0) in the WoW-Mania forum.  

But again, thank you for the suggestion! :)
