### ISSUE TITLE
Transmog display issue

### ISSUE THREAD

**Issue by Rakann** [WoWManiaUK/Redemption#1542]
I have recently bought a transmog for my sword and the problem is that it doesnt show while it's idle, only when using it 

![wowscrnshot_082917_151738](https://user-images.githubusercontent.com/31417726/29820586-a507bd52-8ccd-11e7-8688-6465999d0a8f.jpg)
![wowscrnshot_082917_151745](https://user-images.githubusercontent.com/31417726/29820590-a89fa88a-8ccd-11e7-814f-9d8fd087bfb8.jpg)

I already cleared the cache and even redownloaded the launcher but it's still there

**Comment by fvicaria** [comment]
I need more info than that...
I need the transmog name/id, the item you are transmogging.

Certain transmogs will act like that and there is no way to change. It's just a limitation of the client.
We will be releasing a new client next month and it may solve it but not guaranteed.

In any case there won't be anything done on this since it is not a server-side issue but a limitation of the client itself.

**Comment by Rakann** [comment]
​
I saved the set and used it on another weapon with the same result

**Comment by tvshadowz** [comment]
Hi Rakann, 

please provide more information on this bug so we're able to help yourself and other individuals experiencing this issue. If this isn't done this post will remain closed. 

Thanks!
