### ISSUE TITLE
Corpses (mob,beast,npc) despawning to fast.

### ISSUE THREAD

**Issue by TheGreyMouser** [WoWManiaUK/Redemption#1550]
When killing multiple targets, such as in a group of mobs, the corpses despawn to fast to be looted and/or skinned.  I noticed this issue before, and again today while killing and skinning talbucks outside Shattrah, in Nagrand. (exit through Aldo tunnel to Nagrand).  There was a pack of about 9 talbucks.  I killed and skinned 2, when I attacked the 3rd the remaining 6 attacked me. After killing these, I had only time to skin 4 of the 7.   In blizzard, these corpses stay in place quite a bit longer, so you can sometimes get "free" leather in quest zones.    Probably a bit of a compensation, since you don't have to fight ore or herb nodes to farm them.   This would be a real issue in "hot" farming spots, such as dragonkin in wetlands (near the wagons) where the spawn rate is fairly constant.  (Normally you can skin while the dragonkin are fighting the ogres, so the respawn is a challenge, but not really a hindrance)
I am not sure what the despawn rate in Blizzard WoW is, but 2 to 5 minutes should be a decent enough time for despawn timers.  Time to loot, skin, maybe grab a couple free leathers, but not little the ground with animal corpses. 
Thanks in advance for looking into this.

**Comment by captainloozer** [comment]
Hello TheGreyMouser, and thank you for your report!

I went to Nagrand to test your issue and I can confirm that the Talbuk bodies are despawning roughly one minute after killed.  Whether they are lootable or not seems to make no difference.  This is shown in the video below.

https://youtu.be/ukiCnXZMEb0

However, what I cannot confirm is if this intended or not.  I will leave this open long enough for Janitor to confirm whether or not this is intentional.

**Comment by fvicaria** [comment]
Fixed. The decay time is 2min.

**Comment by TheGreyMouser** [comment]
Thanks.  I thought it was kind of fast.


________________________________
