### ISSUE TITLE
[Quest] On Ruby Wings

### ISSUE THREAD

**Issue by ManiaLightmare** [WoWManiaUK/Redemption#1552]
http://www.wow-mania.com/armory/?quest=12498

[Ruby Beacon of the Dragon Queen](http://www.wow-mania.com/armory/?item=38302) should be usable in Wyrmrest Temple, The Dragon Wastes, Galakrond's Rest or the Wicked Coil

Only seems to work in Wyrmrest Temple and The Dragon Wastes.  In the coil or rest it will tell you it is not usable here.

**Comment by captainloozer** [comment]
Hi ManiaLightmare, and thank you for your report.

I was able to use the Becon in Kalakrond's rest, as shown in the screenshot.
![image](https://user-images.githubusercontent.com/9828794/29992930-36650966-8f6d-11e7-9394-b18f9adeab4a.png)


However, I was not able to use the Beacon in the Wicked Coil.  
![image](https://user-images.githubusercontent.com/9828794/29992945-9f35d4b6-8f6d-11e7-9bed-c4eabf77d44f.png)

It is possible, however, to use the beacon in Galakrond's Rest then fly to Wicked Coil which is close by.  That should allow you to complete the quest, however, since I can confirm that the quest item says it should be usuable in the Wicked Coil, and I can confirm that it isn't, I will confirm this issue and pass it on to the devs.

**Comment by fvicaria** [comment]
Working in dev.
![image](https://user-images.githubusercontent.com/9414661/29995270-befd2ff4-8fdd-11e7-8289-86ff3bb1043d.png)
