### ISSUE TITLE
[Spell] Improved Devotion Aura

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#1592]
Hello! There is probably a problem when stacking 2 talents: http://www.wow-mania.com/armory/?spell=63646 and http://www.wow-mania.com/armory/?spell=20140. The first one should improve healing done by me by 5 %, healing on me by additional 5 % and the second one all healing on me (plus party/raid members) by additional 6 %. So in total all healing done by me when I´m also a target should be either 16 % or 16,865 % (1,05x1,05x1,06).

However, as you can see on my screenshots below the effect of the Improved Devotion Aura talent is nearly zero. Without aura, everything seems working fine - 16 330 HP means the basic Judgement of Light heals for 2 % health + Divinity talent = 16330x0,02x1,1 = 359. But when I add aura, this healing should be improved by additional 6 %, so in total should be something like 380, but its only 362. It means the effect is only 1 % instead of 6 %.

The same effect is on the Draenei spell Gift of the Naaru - without aura it heals for 641 each tick and when aura is added then it is only 647 instead of about 679 (so again 1 % instead of 6).

Is this correct? I haven´t read that this cannot stack. In fact it stacks, but the effect of the aura is far lower than it should be. I deleted cache and restarted the game but problem persists.
![obr1](https://user-images.githubusercontent.com/30184491/30252285-e69fce34-966f-11e7-89bd-01c3fc981634.png)
![obr2](https://user-images.githubusercontent.com/30184491/30252288-f92a8c9c-966f-11e7-99bb-ba6b7dfa68a5.png)
![obr3](https://user-images.githubusercontent.com/30184491/30252291-09b1f956-9670-11e7-928d-3d5164e05d15.png)
![obr4](https://user-images.githubusercontent.com/30184491/30252294-1db570fe-9670-11e7-9f96-864f795132a8.png)
![obr5](https://user-images.githubusercontent.com/30184491/30252305-4ed3d928-9670-11e7-939f-8f355d293a90.png)

**Comment by captainloozer** [comment]
Hi cathyr1  and thank you for your report.

I have tested your theory and have come up with the same results.  You are correct in that it seems that Judgement of Light healing is only increased by 1% with improved devotion aura, even though the tooltip says it should increase by 6%.  What I'm not sure of is if judgement of light healing should be affected by it or not since the judgement tooltip says 2% of total health.  Increasing the amount of spellpower I have (through using blessing of might) did not increase the total healing of judgement of light heals.  I would assume since it is not affected by spellpower then it might not be affected by healing talents either, but I will let Janitor make the call on that.  If that is the case, receiving even the small 1% of healing from the aura would be in fact a "beneficial" bug.  For now, I will confirm the issue since I was able to reproduce.

The following talents and spells are involved.

Talent: Improved Devotion Aura - 20140
http://www.wow-mania.com/armory/?spell=20140

Debuff Spell - Judgement of Light - 20185
http://www.wow-mania.com/armory/?spell=20185

Spell - Judgement of Light - 20271
http://www.wow-mania.com/armory/?spell=20271

**Comment by cathyr1** [comment]
You can also test flash of light or holy light spells but they have range so it will be hard to find out if they are afflicted or not. That´s why I´ve tested just Judgement of Light and also Gift of the Naaru with the same effect. Maybe you can try also Seal of Light.

**Comment by captainloozer** [comment]
I also tested again with no points in Divinity (ID 63464) and I was able to get the full 6% extra healing from devotion aura.  So it seems that the two talents are indeed NOT stacking.  Devotion aura's 6% healing overwrites the 5% from divinity.  This would only affect protection paladins in this case.  Some additional testing will need to be done with other classes that may have a talent that increases healing done to themselves and see if having devotion aura applied to them returns the same results.

**Comment by captainloozer** [comment]
With both divinity and improved devotion aura, the "healing effects on you by 5%" of divinity is canceled out.  It does not stack just as the druid tree of life aura does not stack with it.  However, the "all healing done by you" part of it is working.  On a target dummy, each time I got a heal from judgment of light it was the same.  I steadily added 1 point to Divinity and tried again and I watched it increase.

So in a nutshell, the Increases all healing done by you part of divinity will apply, regardless of Improved Devotion Aura is applied or not.  The increases all healing effects on you does not stack.  This would be the same for druid tree of life and other similar buffs.

Again, I will wait and see what janitor says in regards to this because I have found several references online stating that divinity should indeed stack with Improved Devotion Aura and Improved Tree of life.  The fact that they are not the same percentages is a hint of that as well.

**Comment by captainloozer** [comment]
In this post I will list references to where I have seen people saying this should work.  Janitor, delete the post when you're done with it if you'd rather not have external links.

https://www.getmangos.eu/forums/topic/3511-divinity-improved-devotion-aura/
http://www.mmo-champion.com/threads/679355-Improved-Devotion-aura
http://www.mmo-champion.com/threads/705276-Improved-devo-aura-JoL

**Comment by captainloozer** [comment]
Recent testing shows that the improved devotion aura talent is no longer giving ANY bonus healing.  This test was done without any points in divinity.

![image](https://user-images.githubusercontent.com/9828794/30290318-7d8139f8-96f4-11e7-9744-d44600bdbd3f.png)

**Comment by captainloozer** [comment]
After doing some further testing, I can also confirm that divinity does not stack with Tree of Life (34123) either, and it should.  Tree of Life and Improved Devotion Aura have the same affects regarding 6% increased healing and should NOT stack, however the paladin's individual talent of divinity should increase healing received by 5% and is unique and should stack with either of these aura buffs.

**Comment by captainloozer** [comment]
Another find:

http://www.wow-mania.com/armory/?spell=63650  -  Divinity

http://www.wow-mania.com/armory/?spell=34123  -  Tree of Life

On the tree of life page, you can see where it says that it has a coexistent behavior with Improved devotion aura (Strongest effect is applied), however Divinity does not.

**Comment by cathyr1** [comment]
Now when I downloaded the new version, the effect of the aura is zero (instead of 1 % what was before) as you posted in one of your previous posts.

**Comment by captainloozer** [comment]
Cathyr1,

We're still working on it, I will update the issue when I've been able to test the new changes.  It will not get left like this.

**Comment by captainloozer** [comment]
Tested again after recent changes made in dev.  Improved Devotion (3 points) is now once again correctly granting 6% healing again, but still does not stack with divinity (5 points).

**Comment by Keader** [comment]
https://github.com/WoWManiaUK/Redemption/issues/1592#issuecomment-328615525 wrong xD
Whats happening in current code is:

Tree of Life, Improved Devotion Aura and Divinity has same effect (SPELL_AURA_MOD_HEALING_PCT)
Core just get 1 aura (with high value) and apply on spell cast
So... if you has Divinity (max points) and Improved Devotion Aura (max points), core you grab Improved Devotion Aura and ignore Divinity points :/
(same issue with Tree of Life + Divinity)
