### ISSUE TITLE
[Item] Heirlooms Cannot Be Refunded

### ISSUE THREAD

**Issue by NateAngeles** [WoWManiaUK/Redemption#1609]
Upon purchasing an heirloom item from George Maniac with MP, if the user logs out the refund timer on the item will expire immediately upon logging in. The user is unable to equip or refund the item, without the typically "unable to equip" or "unable to sell" Blizzard warning. The item turns gray and the refund timer disappears from the item.

**Comment by squalllh1989** [comment]
Confirmed, after buy an heirloom item from George Maniac with MP, at first you got 2 hours to refund, after a relog, the item can no longer be refund, i can still use the item normally, tho. Also, you can't refund the Dread pirate ring (http://www.wow-mania.com/armory/?item=50255) right after i buy the item, it didn't have the option to be refunded, not sure if it is because normally you can only obtain it throught the kaluak fishing derby or not.
- First picture, right after buy the heirloom Tattered Dreadmist Mantle (http://www.wow-mania.com/armory/?item=42985) with 25 mp:
![wowscrnshot_091417_090357](https://user-images.githubusercontent.com/27235989/30409011-917651d4-992c-11e7-9fa1-00cbbfcf08c4.jpg)
You can see it got 1 hours and 59 min refundable.

- Second picture, after a relog right after, took like 40 second:
![wowscrnshot_091417_090433](https://user-images.githubusercontent.com/27235989/30409032-b2ef2840-992c-11e7-9682-15cd7c506f1c.jpg)
 Now it's not refundable anymore.

**Comment by fvicaria** [comment]
As is.
