### ISSUE TITLE
Shadow Cleave (Attumen the Huntsman - Karazhan)

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#1619]
Hello,
Attumen the Huntsman's (http://www.wowhead.com/npc=16152) Shadow Cleave (http://www.wowhead.com/spell=29832) is dealing incredible amount of damage at the moment. (15-20k instead of intended 4k, oneshotting any level 70 tank)

Bear in mind the wowhead links are sort of outdated, but according to the gamepedia description (https://wow.gamepedia.com/Attumen_the_Huntsman), the base damage should be 4k, which can be further mitigated by def cds and resistance then.

**Comment by Dranah** [comment]
Forgot: here's a screenshot of the damage dealt from the death log (17k + 3k absorbed)
https://imgur.com/6DZydtg

**Comment by captainloozer** [comment]
Engaged Midnight and was hit by shadow cleave by Attumen for 20011 Shadow damage.

![image](https://user-images.githubusercontent.com/9828794/30515524-13ebe30e-9aef-11e7-98c3-44988d77a043.png)

**Comment by fvicaria** [comment]
THat is correct

**Comment by captainloozer** [comment]
Tested just now after the last restart

![image](https://user-images.githubusercontent.com/9828794/30516012-bf4d2d9e-9af8-11e7-93f6-7e603a5dfd1b.png)

**Comment by captainloozer** [comment]
Okay I may have found the problem.  

Here is shadow cleave at the begining of the fight, where he is not mounted
![image](https://user-images.githubusercontent.com/9828794/30520809-9655630c-9b7a-11e7-9354-bacb5b601257.png)

Here is shadow cleave later in the fight after he mounts midnight 
![image](https://user-images.githubusercontent.com/9828794/30520812-a31b36ac-9b7a-11e7-90c7-b7cffb7b0cb9.png)

Attumen is actually two NPC's, one mounted and one not.  

http://www.wow-mania.com/armory/?npc=16152
http://www.wow-mania.com/armory/?npc=15550

Maybe this has something to do with it.  Removing fixed in dev for now, but I'm sure it'll be fixed once Janitor has a chance to inspect this.

**Comment by captainloozer** [comment]
Unmounted damage 
![image](https://user-images.githubusercontent.com/9828794/30521524-89c05370-9b86-11e7-88e4-5344b120aefd.png)


Mounted damage 

![image](https://user-images.githubusercontent.com/9828794/30521535-b143e29a-9b86-11e7-8c53-5bfe014bc04f.png)


Confirmed fixed in dev
