### ISSUE TITLE
[Raid] The ruby sanctum

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1643]
Halion (http://www.wow-mania.com/armory/?npc=39863) currently have bugged phase, while in phase 2 and 3, some people in the shadow realm can see and be seen by both realm and got hit by both realm, which result in they got killed in shadow realm by physical halion's fire breath which is really bad.

**Comment by captainloozer** [comment]
squalllh1989, hello and thank you for your report.

Confirmed.  I tested this with another player on Dev.  I could see him at times during phase 2 while he was inside and I was outside.  He was taking damage from outside even though he couldnt see it, and I was getting instant killed by cutters even though I was on the outside.  It seems as if the phases are meshed together somehow.

While I was able to revive my testing partner enough times to finish the fight, I highly doubt even any solid group would be able to pull this off in it's current state.  The fight is "doable" as in it is possible to kill him, but highly unlikely due the extreme amounts of extra damage taken on both sides, half of it being unavoidable since you can't see it.

**Comment by captainloozer** [comment]
I've also heard that this is not happening on heroic mode.  Will test that and report back with my findings.

**Comment by squalllh1989** [comment]
nah, member of group therapy told me that this happen also in their heroic mode too, but didn't sure about that, so yeah, you better test it out, thank you for your work.

**Comment by captainloozer** [comment]
I tested Heroic mode shortly after.  It was hard to tell what was going on because I only had a few people to test with me, but it was definitely exhibiting the same problems.

**Comment by BatuMania** [comment]
It is happening on heroic yes,during 20 attempts on 25 Heroic halion we've had 2 people who could see both realms all the time and it was always the same 2 people.

**Comment by Ukhozii** [comment]
I can confirm that it seems like it's always the same people one can see in both shadow and real world (we had about 5-7 people we could see that was in shadow, I memorised 3 of them and they were always part of the "Vissible from real realm" group that were actually in shadow). Those could also be healed from the real world. However, the damage problem seems to affect everyone. A friend of mine got tailswiped in real while the boss was in shadow. Those in shadow are killed by fire etc.
I hope the added info might help

**Comment by fvicaria** [comment]
Since this is nearly impossible to test in a controlled manner I will mark it as fixed. Let's see if we get feedback from Redemption.

**Comment by goldstinger** [comment]
Risen was doing it on 10 normal, we can still see people in shadow realm from the physical realm.

**Comment by hotdoggidy** [comment]
Killed Halion 25nm on sunday. we did not get hit by cutters in Physical realm during P3. No cheats were involved.
