### ISSUE TITLE
[NPC] Coren Direbrew - Missing Dialogue 

### ISSUE THREAD

**Issue by Hulkster-WowMania** [WoWManiaUK/Redemption#1645]
http://www.wow-mania.com/armory/?npc=23872

During the brewfest event, players can queue for Coren Direbrew, which takes you into BRD where you should be able to talk to him and a dialog option starts the fight.  Currently, there is no dialog available, so the fight cannot start.  Players are then forced to leave the group since there's nothing that can be done about it since he's friendly.

![image](https://user-images.githubusercontent.com/9828794/30619074-05201cf2-9d63-11e7-81c4-49ec610d8fbc.png)

**Comment by captainloozer** [comment]
Okay so after doing some more digging, I was wrong about how this boss fight starts.  It requires a daily quest called Insult Coren Direbrew (http://www.wow-mania.com/armory/?quest=12062) in order to start the fight.  Someone must be on this quest to insult him so that he becomes hostile.

The following is a guide I've been working on to explain how to do this on the wow-mania forums but I'm coming up with some problems of my own that prevent this from happening.

_____________________________________________________________________________'

Guide to killing coren direbrew


**ALLIANCE**

Pick up Welcome to Brewfest! (http://www.wow-mania.com/armory/?quest=11442) and turn in to get your free beer.  This is right outside of Ironforge.
Talk to Darna Honeybock (http://www.wow-mania.com/armory/?npc=27584) in Kharanos and pick up Save Brewfest! (http://www.wow-mania.com/armory/?quest=12318)

(This is where the problems start.  Darna Honeybock is nowhere to be found in Kharanos.  At this point, you can go no further in the quest chain.)

Queue RDF for Coren Direbrew which should take you into BRD.  Turn Save Brewfest! to the Brewfest Spy
(http://www.wow-mania.com/armory/?npc=26719) and pick up http://www.wow-mania.com/armory/?quest=12062

(This part is also messed up because the Brewfest Spy NCP is also missing.)

The person with the daily quest, Insult Coren Direbrew, begins the dialog and starts the fight, where he will turn hostile and the group can kill him for loot.



**HORDE**

Pick up Welcome to Brewfest! (http://www.wow-mania.com/armory/?quest=11447) and turn in to get your free beer.  This is right outside of Orgrimmar.
Talk to Slurpo Fizzykeg (http://www.wow-mania.com/armory/?npc=28329) in Razor Hill and pick up Save Brewfest! (http://www.wow-mania.com/armory/?quest=12318)

(I have not checked to see if Slurpo Fizzykeg exists where he is supposed to be, I will return later with my findings)

Queue RDF for Coren Direbrew which should take you into BRD.  Turn Save Brewfest! to the Brewfest Spy
(http://www.wow-mania.com/armory/?npc=26719) and pick up http://www.wow-mania.com/armory/?quest=12062

(This part is also messed up because the Brewfest Spy NCP is also missing.)

The person with the daily quest, Insult Coren Direbrew, begins the dialog and starts the fight, where he will turn hostile and the group can kill him for loot.

**Comment by goldstinger** [comment]
Just checked Razor Hill, looks like Slurpo Fizzykeg is also missing.

**Comment by captainloozer** [comment]
@goldstinger   Thanks for confirming that for me.

**Comment by rjbick** [comment]
Save Brewfest! from Darna Honeybock, Kharanos (Removed in 3.3.5a)

**Comment by rjbick** [comment]
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(23872, 0, 0, 'This is an insult! An affront! They deny us participation in time-honored dwarven traditions!', 12, 0, 100, 15, 0, 0, 22376, 0, 'Coren Direbrew SAY_INTRO'),
(23872, 1, 0, 'Are we going to hide in our mountain and let those swill-peddlers have their little shindig without us?!', 12, 0, 100, 15, 0, 0, 22388, 0, 'Coren Direbrew SAY_INTRO2'),
(23872, 2, 0, 'DAMN RIGHT! We''ll show ''em why you don''t cross the Dark Iron dwarves!', 12, 0, 100, 15, 0, 0, 22389, 0, 'Coren Direbrew SAY_INTRO3'),
(23872, 3, 0, 'You''ll pay for this insult, $c!', 12, 0, 100, 15, 0, 0, 25921, 0, 'Coren Direbrew SAY_INSULT');

Missing?

**Comment by captainloozer** [comment]
That's what I originally thought, but according to GM Saintz, that's not the case here.  However, it makes more sense that the dialog from Coren is just missing, which would explain the missing NPCs.  Not to mention that making his dialog available right off the bat would be a much easier fix.

**Comment by goldstinger** [comment]
I do believe it is a situation lost in expansion; Dungeon Finder wasn't introduced until patch 3.3.0, yet the questline was available since patch 2.4.3.8601, which was during The Burning Crusade. For people that didn't have Dungeon Finder yet, there was the questline. For everything afterwards, there was the Dungeon Finder.

**Comment by captainloozer** [comment]
Right, that's why I thought for sure they had taken those quests out by the time you could just queue for it, but Saintz made me question myself.  I'll rename the issue again to it's original so it fits the real problem.

**Comment by Hulkster-WowMania** [comment]
Confirmed fixed in dev. Dialogue works, Coren becomes hostile, loot dropped.

https://youtu.be/c_juNVXHoBM
