### ISSUE TITLE
[Quest] Conquest Pit: Bear Wrestling

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#1647]
Hello,
when attempting to do the quest Conquest Pit: Bear Wrestling! (http://www.wowhead.com/quest=12427), the mob simply disappears when you kill it, no corpse, no kill credit, though you do get experience for the kill. Re-tried multiple times, took pets off attack (so the killing blow must have been done by a player for certain), also restarted/cleared cache etc, no success to complete quest.

Unsure if the other quests in the pit chain are behaving the same way (since i couldn't get past this one) but i'll leave the links here anyway, if you may look into them.
http://www.wowhead.com/quest=12428
http://www.wowhead.com/quest=12429
http://www.wowhead.com/quest=12430
http://www.wowhead.com/quest=12431

**Comment by squalllh1989** [comment]
All of the quest in this chain having same issue, especially when you are in a party, it seem only the one that deal the finishing blow will get count, no other in the party got credit.

**Comment by fvicaria** [comment]
This is a known core issue. Unfortunately, sometimes you have to do the quest multiple times.

**Comment by Hulkster-WowMania** [comment]
Although I have experienced this issue in the past, I can confirm that it is doable on dev.  Did the quest chain with 2 characters in a row with no problems.  As Janitor said, sometimes you just have to do it multiple times in order to get credit in a group, but by myself and with no pets, I get credit for each kill.
