### ISSUE TITLE
Gadgetzan quest "Bungle in the Jungle (Part 2 of 2)" will not complete.

### ISSUE THREAD

**Issue by DarthLuca** [WoWManiaUK/Redemption#1667]
The quest "Bungle in the Jungle (Part 2 of 2)" given by Alchemist Pestlezugg in Gadgetzan will not complete. I have the items in inventory and the quest items in the log show as Complete (and quest shows as Complete). But when I return to A.P. he shows white question mark and quest option "Continue" is still greyed out.
Note: I also have quest "Un'Goro soil (part 2 of 2)" [from Thunder Bluff - Ghede] in my log (so I actually have 7 soil samples (5+2)) and while in Un'Goro I did not notice any 'Soil samples (piles of soil) to collect. Could there be a conflict between the quests??

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/30780511-48435f68-a104-11e7-9bc8-510a1ab7f3dc.png)


Worked fine for me. This could be because you had multiple quests that required the same items.
If that is the case just get one at a time. You can collect all the items at once but only get one quest at a time or you may have problems.
