### ISSUE TITLE
My Thema is some kind of Issue in THe Halls of Reflection 

### ISSUE THREAD

**Issue by Sonyabladee** [WoWManiaUK/Redemption#1691]
Okey so we finish the 10 waves with the 2 Bosses everything was normal . AFter that we start the Runn with Lady Jaina. When we done the runn the Gunnship arrive but didnt shoot the Lich King. they just stay and do nothing. we go to the Gunnship we thinked we done the run . But surprisse chest is there but we cannot loot him. after we weight like 5 min still nothing. I go close to Jayna and just click on her. She have option to beginn that Run again . But we already done that run . One shaman from the party wanted to see what will happend if he Click on Jayna. Well he Click and  Lich King kill us all. after we go inside again we saw the Lich King and Jayna are in position for new Runn. I will upload Fotos on everything so you can see my story to. 
![wowscrnshot_093017_133810](https://user-images.githubusercontent.com/32413884/31045746-991a977c-a5ea-11e7-898c-db739622ee5c.jpg)
![wowscrnshot_093017_134233](https://user-images.githubusercontent.com/32413884/31045748-9934e38e-a5ea-11e7-931c-37f0e5ce8ff1.jpg)
![wowscrnshot_093017_141232](https://user-images.githubusercontent.com/32413884/31045743-9918dd6a-a5ea-11e7-8887-72bc49440b09.jpg)
![wowscrnshot_093017_141236](https://user-images.githubusercontent.com/32413884/31045745-991a0456-a5ea-11e7-9439-8781b39e05aa.jpg)
![wowscrnshot_093017_141411](https://user-images.githubusercontent.com/32413884/31045747-991f7e7c-a5ea-11e7-8362-5a9056e31c82.jpg)
![wowscrnshot_093017_141429](https://user-images.githubusercontent.com/32413884/31045744-9919aac4-a5ea-11e7-9127-5e9402bfde35.jpg)
![wowscrnshot_093017_141445](https://user-images.githubusercontent.com/32413884/31045749-9938bc0c-a5ea-11e7-85d4-c7b84c74df6c.jpg)

**Comment by squalllh1989** [comment]
I can confirm that this problem is real. I have this same problem before in horde side, like 2-3 times, but it's happen at random so i don't think we can reproduce it. The problem happen after you finish the lich king's chase, then at the end, there is an option to start the run again when you talk to Jaina/Sylvanas , after you do that, the lich king wipe out the group just like when you fail the run and let jaina/sylvanas die. In worse case, when you run in the instance again, the lich king will keep the zone-wide aoe damage happen, and you can't complete the run anymore.

**Comment by fvicaria** [comment]
I have added some minor changes to try to force the chest to be lootable. I will be up after restart Wednesday.
