### ISSUE TITLE
[Dungeon] Violet Hold

### ISSUE THREAD

**Issue by mantman** [WoWManiaUK/Redemption#1709]
In instance of Violet Hold i noticed that when mob Portal Keeper spawns and is not killed fast, the first pair of 3 adds spawn and spawn again and again, leading to an army of adds, that lead to wipe. After running inside, you can see adds trying to destroy an non existant crystal and the NPCs guards that talk to start event, are present -even if you managed to kill 2 bosses-. If you start instance, portal adds die but portal keepers do not ergo in making a circle of endless wipes.

**Comment by squalllh1989** [comment]
Confirmed in dev, after the wipe because of portal add, the instance does not reset and the add keep on spawning, i can still kill all the add that spawned and the keeper, but the portal is still open and keep on spawning add, so it's will make it a really challenge. I think the instance just need a reset when the party wipe.

**Comment by fvicaria** [comment]
What is the NPC id or link please?
