### ISSUE TITLE
Formula: Large Prismatic Shard

### ISSUE THREAD

**Issue by aadalid** [WoWManiaUK/Redemption#1723]
I noticed to a GM in game, and he brought me here.
I saw in wow head that the NPC **Egomis**, located in Exodar should sell this formula, but she doesnt. 
http://www.wowhead.com/npc=16722/egomis

Thank you so much!!

**Comment by squalllh1989** [comment]
Hello aadalid, thank you for reporting your problem here which can help the server to improve by fix bug arround.
About the problem you reported: the [formula you are looking for](http://www.wow-mania.com/armory/?item=22565) is a limited supply item (you can see a number of **(1)** in the page you linked, which is the number of max storage the seller will stock), which mean, if some one buy it out, you will need to wait for the NPC to restock it again until you can buy it. I used a char i have in aliance and to go check on the npc you said and this is what i can see to prove that the npc have the item normally, just you are unlucky that someone already buy it before you came.
![wowscrnshot_101217_095310](https://user-images.githubusercontent.com/27235989/31477040-f907edd6-af33-11e7-91f0-c61bee6c9afc.jpg)
