### ISSUE TITLE
[Issue] Warlock Pets not attacking sometimes

### ISSUE THREAD

**Issue by Sihsboy** [WoWManiaUK/Redemption#1730]
I raised a ticket in game and got GM Weeble to have a look at it, he advised to post here. 

My Voidwalker will, maybe 1 in 4-5 times, not attack an enemy when told to. He'll move to it and then circle round and both he and the creature will be a little too far apart to attack each other, and also won't cast Torment. It can be corrected by getting them to move by switching stance or telling to follow and reissuing attack order, but mid battle or when pulling mobs this can either go unnoticed or unmanaged.

**Comment by Katherwind** [comment]
I can confirm that there is a problem with both warlock and hunter pets.  My experience has been that the fights will start as normal with the pet attacking.  After a while the pet will stop attacking, lose aggro , and the mob will come after me.  As a hunter, if I feign death, the mob will go back to the pet and the pet will start attacking as normal.  As a warlock, I was unable to get the pet to take aggro again even after casting the pet taunts.   I did not try telling the pet to follow and reissue the attack command as I was not aware of this workaround.
The only thing I was able to notice is that the bug does tend to happen more when the mob and the pet are on what appears to be different terrain levels no matter how minute the level difference is.  Otherwise, I have no clue what might be causing the bug or how to reproduce it except to try to test it in a zone that has many different terrain levels vs an entirely flat zone.

**Comment by fvicaria** [comment]
Can someone test this one, please.

**Comment by Sihsboy** [comment]
What would you need to see as the test? I have OBS installed so could make a video on it. It was very easy to trigger it for the GM, only took 2 attempts.

**Comment by fvicaria** [comment]
Sorry I meant our test team...
We just need independent confirmation and some steps on how to reproduce it consistently.

**Comment by squalllh1989** [comment]
This problem still persis, when i played on a warlock, i send the pet to the mob to attack and taunt it, some time the pet is out of range for it melee hit and abilty cast range, but it didn't come closer to it target by it self and just sit there, you must call it back to you and send it to the target again, or you can come to the pet with the mob that aggro on you. If you send the pet to the mob and didn't attack it, you some time can see the pet and the mob looking and targetting at each other (aggroed), but they didn't do anything, no hit, no ablity cast, when you click on the pet's ablity to force cast it, you got a "out of range" message, guess it's a problem of path finding.

**Comment by fvicaria** [comment]
Is the mob at a higher level? (z axis)

**Comment by squalllh1989** [comment]
no, there is a mob that at 1 level lower than me too
