### ISSUE TITLE
[Quest] A Cold Front Approaches

### ISSUE THREAD

**Issue by AnotherMoron** [WoWManiaUK/Redemption#1742]
http://www.wow-mania.com/armory/?quest=13070

The quest ender Siegemaster Fezzik (http://www.wow-mania.com/armory/?npc=30657) dosen't turn in.

It's the typical quest of go and talk to somebody else to turn in.

**Comment by squalllh1989** [comment]
Hi AnotherMoron, thank you very much for report the problem here to help improve the server.
About your problem, what race / class do you play ? I have done this quest on 5 of my character and have no problem with turning this quest in, maybe it's a problem with a certain combo of race / class maybe, can you tell us so we can test this out with the most accurate, and, if you can provide a screen shot when you have the problem, it will help us a lot to try reproduce the problem, thank you.

**Comment by fvicaria** [comment]
You have to enter the hut. If it did not go yellow move about in and out and wait a few seconds.

![image](https://user-images.githubusercontent.com/9414661/31605602-863d0c54-b25e-11e7-90f9-b10ba7384bee.png)
