### ISSUE TITLE
[Talent] Fingers of Frost

### ISSUE THREAD

**Issue by Hajzlopuc** [WoWManiaUK/Redemption#1807]
Hello,

Fingers of Frost talent on frost mage does not work properly. It gives you buff for 2 charges but in reality it only gives you 1 usable charge, 2nd charge is still there visible but cannot be triggered (actually it does eat the charge but with no additional effect (act like frozen))

talent id - 44545

I already found this issue here few times closed with 'Won't fix' label. Not sure why.
So I was wondering if you could show me the script.

**Comment by squalllh1989** [comment]
Thank you for reporting this problem, how ever, this problem is reported [here](https://github.com/WoWManiaUK/Redemption/issues/1514) before, and, sadly, won't be fix, this make a huge disadvance to frost mage, i know, my main char is a mage too, but there's nothing we can do about this now, hope it can be take a look on and fix in the future. Anyway, please search for the problem before making a new one, thank you very much.

**Comment by Hajzlopuc** [comment]
I did search. If you read my whole post you would know. Can I find script anywhere?

**Comment by Hajzlopuc** [comment]
I have noticed that it gives me buff 
http://www.wow-mania.com/armory/?spell=74396 insted of 
http://www.wow-mania.com/armory/?spell=44544

Can I actually see the script or something to work with? I would really like to see 2 core talents of frost mage working.

**Comment by squalllh1989** [comment]
Thank you very much for your helping, now finally maybe i will be able to play my mage in pvp better
