### ISSUE TITLE
Its all fun and games quest

### ISSUE THREAD

**Issue by JennyTheLuxray** [WoWManiaUK/Redemption#1835]
the ocular seems to not take any damage. when i used the item the channel would stop before it did any damage

**Comment by Hajzlopuc** [comment]
This is the quest right? 
http://www.wow-mania.com/armory/?quest=12892

How have you tried this? 
You should fly close to it (blue eye at the very top of building ), it will start cast something on you, you gotta take this damage in order to do damage (but you are killing him faster than he is, so you shouldn't die)
