### ISSUE TITLE
[Quest] The Fallen Sisters

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#1851]
Quest: http://www.wowhead.com/quest=11314/the-fallen-sisters

I have to use Lurielle's Pendant on Chill Nymphs, but when I try to use it it says "Invalid target".

Screenshots: https://i.imgur.com/lR5cFod.jpg https://i.imgur.com/7vulmqG.jpg

I use the Launcher.

**Comment by fvicaria** [comment]
This quest works.  What happens is that some players fail to convert it and die, leaving the NPC in a bad state. A GM needs to go and kill the NPC and respawn it.

**Comment by NightSeekerr** [comment]
Then I guess I'll wait.

**Comment by squalllh1989** [comment]
I still have the problem with this quest, those nymp is FRIENDLY to me, which mean i CAN NOT ATTACK THEM, when i try to do so, i got a "invalid target", so i can't lower their hp to make them "weakened", and if i used the pendan on any of those friendly nymp, i get a "invalid target". This is absolutly not i'm doing wrong, i have done this quest many time on diffrent char, i know how to do it right, but the problem is those nymp are now friendly to me, which should not happen. And it's not one of them, all of them is friendly to me so it's not NPC in bad state. I have this state for 1 month before, and after 1 month, i got in, try to do this quest again and it still in this state. This maybe the quest broken or maybe my char is in bad state in some way for this quest, i don't know.
![wowscrnshot_121017_181639](https://user-images.githubusercontent.com/27235989/33804404-9a84c55a-ddd6-11e7-9b4a-b4af5ef63f17.jpg)

**Comment by fvicaria** [comment]
This only happens if you leave it and don't finish the quest. I will check in a bit.

**Comment by squalllh1989** [comment]
Well, when i first get the quest, it's already like this, i reported one time in the past [here](https://github.com/WoWManiaUK/Redemption/issues/1809)

**Comment by fvicaria** [comment]
Yes because someone before you did it and messed it up. I fixed it for now. I tried all 3 cases, died etc. It seems to work. I really don't know what can cause it.

**Comment by squalllh1989** [comment]
yes it work now, thank you. So we know it's a npc messed problem and need gm to fix it when it happen then :D

**Comment by fvicaria** [comment]
Killing the npc solves it. But I still don't know how to reproduce it.

**Comment by squalllh1989** [comment]
Wait i think i know what happened now, after i use the pendant to get my quest done, those nymp that i used pendant on should disapear, as they was awakened and back to her sister, after a while another hostite one will apear. But what happen is that nymp run away, and come back after a while, this time she is friendly to me. So my guess is that those nymp got used by some one before me, and they won't respawn so when i come i got bugged one.

**Comment by fvicaria** [comment]
I did that. That is the normal behavior if all goes right. I waited for the respawn on the same spot.  The mob respawned as hostile as it should.

**Comment by squalllh1989** [comment]
![wowscrnshot_121017_193612](https://user-images.githubusercontent.com/27235989/33804911-7b8a8f58-dde1-11e7-8a98-9e665e5a74ee.jpg)
In this picture, i mark two nymp. The hostite one is the one that respawn after your reset, and the friendly one is the one i used the quest item on, she run away, and now come back patrol like normal

**Comment by fvicaria** [comment]
they should go away and despawn.

**Comment by squalllh1989** [comment]
Yes, they should. But that's not what happened, i just try it: they run away and then come back after.

**Comment by fvicaria** [comment]
Try now.

**Comment by fvicaria** [comment]
OK it will need a restart. Please try on dev.

**Comment by squalllh1989** [comment]
It work good now.

**Comment by Yhato794** [comment]
I tried this quest today on redemption, still bugged the nymphs are friendly can't be targetted

**Comment by fvicaria** [comment]
Retry after restart please.

**Comment by squalllh1989** [comment]
This issue is back, most of the nymph is currently stuck in friendly, most likely the problem is the same as before: they didn't despawn after being rescue, so the new nymph in hostile state didn't spawn.
