### ISSUE TITLE
Grand Marshal's battle hammer vs arcanite reaper heirloom

### ISSUE THREAD

**Issue by Igotpooedon** [WoWManiaUK/Redemption#1855]
Hi, i just noticed that the grand marshals battle hammer dosnt add as much dmg as it should be.

im playing a lvl 60 human paladin with maxed lvl in both 2h axe and 2h mace.

With blessing of might my dmg in character screen with arcanite reaper heirloom (no enchant) is 569-744 dmg

With blessing of might my dmg in character screen with  Grand Marshals battle hammer is 630-764 dmg

Arcanite reaper heirloom has 206-310 dmg at lvl 60 and has  25str, 38 stam and 25 crit rating.
Grand marshals battle hammer has 235-353 dmg 26str,41 stam and 14 crit rating 
the differance is 29-43 dmg 1str,3stam and -9 crit rating if you compare the two weapons it looks like the min dmg is added correctly but the max dmg is way of as it only adds 20 dmg on my character screen while the 29 min dmg is adding 61 dmg.

**Comment by Igotpooedon** [comment]
forgot to write that i have no enchant on the battle hammer

**Comment by Hajzlopuc** [comment]
It's DPS what matters. Or average swing damage if you want to calculate like that. Battle hammer have lower spread with same attack speed. If more damage was added to its maximum, it would have too much average hit damage. Do you understand? (Im not native english speaker, I'm not sure if it is understandable)

Base weapon numbers:
Battle hammer - (353+235)/2 = 294 average hit per swing (/3.80 attack speed = 77.36 dps)
Arcanite reaper - (310+206)/2 = 258 average hit per swing (/3.80 = 67.89 dps)

Your numbers with blessing used:
Battle hammer - (764+630)/2 = 697 average hit per swing (183.42 dps)
Arcanite reaper - (744+569)/2 = 656.5 average hit per swing (172.76 dps)

**Comment by fvicaria** [comment]
@Hajzlopuc Let me know if you are interested in joining the test team, we are always looking for people.
Just send me a message on skype (Skypename: wow-mania.com)

**Comment by Igotpooedon** [comment]
@Hajzlopuc sry i dont understand a singel thing you wrote but hey, im not a genius.
I just find it really odd that i gain so much more from the +29 minimum dmg (61  dmg in char screen) while +43 maximum dmg only gives me +20 dmg in char screen

**Comment by Hajzlopuc** [comment]
@Igotpooedon 
You can't judge that from min-max weapon damage like that because they have different spread. And it's all about DPS. Attack power also adds you flat DPS. Check your DPS numbers by mouseovering on damage line on character screen. 
 
Okay, imagine 2 extreme weapons 
**A** - 100-100 with 4.00 attack speed 
**B** - 1-199 with 4.00 attack speed 
 
They both have 25 DPS 
(100+100)/2 = 100   /4.00 = 25 
(1+199)/2 = 100   /4.00 = 25 
 
Let's say you have no haste and have attack power just to increase you DPS by 75 (because that's how attack power works, gains you flat DPS, you can also see that if you mouseover on attack power on character screen) 
25+75 = 100 
That would make your new DPS 100 with both of these weapons. 
Now see how would damage have to change to reach 100 dps. 
**A** would have to be 400-400 with 4.00 attack speed 
**B** would have to be 1-799 with 4.00 attack speed 
 
(400+400)/2 = 400   /4.00 = 100 
(1+799)/2 = 400   /4.00 = 100 
 
That means weapon **A** would be added 300-300 and weapon **B** 0-600 but _**DPS-wise it's the same**_. 
So the lesser the MIN damage is, the more you have to add to its MAX because it is balanced aroud DPS and DPS only. 
I'm not sure if you gonna understand this one, it's pretty hard to explain for me maybe someone could do better job explaining but believe me that's how it works. Don't worry you are not losing your DPS. 
My IGN is Kokotka, you can whisper me any time.

@fvicaria 
I sent a message also with proof included.
