### ISSUE TITLE
[Dungeon] Hall of Stone's Brann Bronzebeard Encounter

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#187]
So in this fight, you're supposed to fight group of adds, while face statues around the room shoot at you
(http://www.wowhead.com/npc=89750/brann-bronzebeard#encounter) known as the Tribunal Security, so, each one of those faces does something while only one of them gets an additional feature on heroic.

Also, mobs that you fight are supposed to cast various spells based on which one, for example the warrior casts cleave and charge and whatsoever, as written on the wowhead topic.

**Comment by Kalasbyxan** [comment]
In Halls of Stone (http://www.wow-mania.com/armory/?zone=4264) you find Brann Bronzebeard (http://www.wow-mania.com/armory/?npc=28070) who offers the quest Halls of Stone (http://www.wow-mania.com/armory/?quest=13207). When accepting the quest and talking to Brann, you start to follow him to the Tribunal where an event takes place.

The first thing I notice is Brann fighting an invisible Abedneum (http://www.wow-mania.com/armory/?npc=30899). This is the face over the Tribunal Control Console. After killing the Abedneum Brann proceeds to start the event. During the event, Abedneum, Kaddrak and Marnak (the three faces) does not attack as they should. See https://www.youtube.com/watch?v=9x5sliYDPXU at 8:15. The faces should glow red and attack, one after another activating. It does glow white and does not attack (http://i.imgur.com/nd8bWsW.jpg).

Throughout the fight, the Dark Rune Protector (http://www.wow-mania.com/armory/?npc=27983), Dark Rune Stormcaller (http://www.wow-mania.com/armory/?npc=27984), Dark Rune Warrior (http://www.wow-mania.com/armory/?npc=27960) and Iron Golem Custodian (http://www.wow-mania.com/armory/?npc=27985) only attack with normal melee attacks, not abilities as listed here (http://www.wowhead.com/npc=89750/brann-bronzebeard#encounter).

After the event is complete, Bran talks to Abedneum, Kaddrak and Markan and then enables the next part of the quest by talking to him. He disappear and should meet players outside the door of Sjonnir the Ironshaper (http://www.wow-mania.com/armory/?npc=27978) and unlock it upon conversation. He is not found outside of the door, which is already opened, and Brann is dead at the camp where he's first found. When killing Sjonnir the quest is complete and instead of Brann appearing for hand in, he is still dead and players can't complete the quest (unless they find Brann in the world, where he instead can reward the quest).

**Comment by fvicaria** [comment]
Is this one still valid?

**Comment by Kalasbyxan** [comment]
Yes, still working as described as per information from world chat.

**Comment by Hulkster-WowMania** [comment]
![image](https://user-images.githubusercontent.com/9828794/30867654-33071104-a2a2-11e7-906a-2c6a3a625d85.png)
