### ISSUE TITLE
[Quest] Territorial Trespass

### ISSUE THREAD

**Issue by iggapres** [WoWManiaUK/Redemption#1871]
This is a bump of issue #899, as it seems the bug reappeared.

The quest: http://www.wowhead.com/quest=13051/territorial-trespass
The issue: once the egg set on the ground, Veranus should appear with Thorim on its back. But nothing happens. I waited 15 minutes on top of this mountain and still nothing.

GM Mobius directed me to write this bug report.

**Comment by Plege** [comment]
just did the quest without any issue, after i placed the egg the dragon flew in and the quest completed.
due to a comment on one post i took a few steps away from the nest after i placed the egg, not sure if that has any significance on triggering the event. however quest worked fine and can be completed

**Comment by Plege** [comment]
![image](https://user-images.githubusercontent.com/24266043/33229365-d0666eae-d1cd-11e7-801e-f8491bffc6f9.png)

**Comment by iggapres** [comment]
I found a way to have this quest work all the time.

Once the egg on the ground, if Veranus does not come, fly towards the south (from where she sould come) and she will appear.

The quest will be completed this way.
