### ISSUE TITLE
[Quest]The Last Line of Defense - Argent Vanguard, Icecrown

### ISSUE THREAD

**Issue by Icethorne** [WoWManiaUK/Redemption#1917]
Let the pictures speak for themselves. 
This cannon always seemed to be in place the entire time
![wowscrnshot_120717_225830](https://user-images.githubusercontent.com/34362527/33751736-8bc3b85e-dba2-11e7-8295-3475d2e66501.jpg)
This cannon started out in the right place but eventually bugged out to where you cannot shoot out of the guard tower
![wowscrnshot_120717_225821](https://user-images.githubusercontent.com/34362527/33751759-ab0a3ab2-dba2-11e7-85a4-164eec691c24.jpg)
![wowscrnshot_120717_225840](https://user-images.githubusercontent.com/34362527/33751763-b17b91f2-dba2-11e7-8170-3724d7116736.jpg)
![wowscrnshot_120717_225858](https://user-images.githubusercontent.com/34362527/33751767-b7c1b262-dba2-11e7-8f6a-ce75131f608f.jpg)
![wowscrnshot_120717_225903](https://user-images.githubusercontent.com/34362527/33751768-baddc454-dba2-11e7-8f0f-916483cc13e5.jpg)
I still have the phase active as I have not turned in the quest but I was able to complete it.
-Update- 
The first cannon bugged out as I was hanging around
![wowscrnshot_120717_230602](https://user-images.githubusercontent.com/34362527/33751842-4a1f4d40-dba3-11e7-95f4-3153e0a02673.jpg)

**Comment by fvicaria** [comment]
Fixed.

**Comment by PsycsX** [comment]
I am experiencing the same issue at the moment.

![wowscrnshot_120917_193244](https://user-images.githubusercontent.com/25711390/33800864-db7f0a8a-dd17-11e7-8252-4ba69602ad3b.jpg)

Once I get in, I can't shoot out.

The one by the quest giver seems to be on top sometimes, but sinks down.

**Comment by lastbullet00** [comment]
This issue is up again (the cannons fall under those things and can't be used):
![image](https://user-images.githubusercontent.com/34487562/35767202-73ceb84a-08f0-11e8-8488-957515ced144.png)
![image](https://user-images.githubusercontent.com/34487562/35767205-7a4be9b8-08f0-11e8-9680-7eb209cfe2c9.png)
![image](https://user-images.githubusercontent.com/34487562/35767207-8157018e-08f0-11e8-97da-45ef5194d6e4.png)
![image](https://user-images.githubusercontent.com/34487562/35767208-87627612-08f0-11e8-9213-3a98dfeeb133.png)

**Comment by fvicaria** [comment]
I will move the cannons again. Give me a min.

**Comment by Yhato794** [comment]
uhm the cannon are again in the towers could you fix it again plz :D
