### ISSUE TITLE
[Raid] Ruby Sanctum Baltharus the Warborn

### ISSUE THREAD

**Issue by CrustyMuffin** [WoWManiaUK/Redemption#1940]
During our encounter against Baltharus the Warborn in RS 25nm i´ve noticed something that might be a bug (http://www.wowhead.com/npc=39751/baltharus-the-warborn#abilities). During the fight he puts "Enervating Brand" (http://www.wowhead.com/spell=74502/enervating-brand) on random players, debuff will continus to stack on the boss as long as players with "Enervating Brand" are within 12 yards of each other. The problem we faced was, that the boss increases his stack way too fast. During the fight, Baltharus got to 60-90 stack within a few seconds, even with us spreading, his stacks should increase at a much slower rate.

**Comment by StefanelStan** [comment]
Hello.
I have watched and rewarch videos of Baltharus and the stacking of enervating brand and how it should work. (one video example here EG: https://www.youtube.com/watch?v=aGP7fMflpjY )
On wow mania, on 25 the bosses get the stacks way too fast and way too high.
On 25 it went to 50-170 stacks in seconds with best efforts of staying away from each other,
Also, the mechanic implies that it ticks every 2 seconds for 10 seconds (so max 5 stacks/player IF it stays away from other player with the brand). It does not work. It went to 7-8 stacks when I was alone and nobody around.

**Comment by fvicaria** [comment]
As is

**Comment by CrustyMuffin** [comment]
How can that be? I´ve done Rs 25 several times and i´ve never seen the boss getting 60-90 stacks. On our tries he got those stacks within 2-3 seconds, there is no way people melee´s can get away from the boss in 0,5 seconds to make it work. We even tried with no melee´s on him and we still couldn´t keep him under 70 stacks.

**Comment by fvicaria** [comment]
Nothing has changed there in at least 3 months. So whatever is there has been like that for ages. Try this week and let me know.

**Comment by StefanelStan** [comment]
Clearly something has been changed to the RS25 version because last time in July when I killed it and the attempt from yesterday, there were several things happening:
1. As we entered, we could see the 2 dark spheres rotating around the big circle (the 2 spheres that are on shadow realm)
2. The bosses get enlarged by the siphoned might (the buff that is applied on the boss by the stacks of enervating brand)
3. The stacks are going up way too high: one boss has 180 stacks which is impossible: this would mean the the whole raid had 7 stacks of the enervating brand on them which is not possible!
The only explanation is that the bosses share the same pool of enervating brand: boss1 casts brand1 on player1,2,3, boss2 (copy of boss1) casts brand2 on player4,5,6 BUT boss1 gets the debuff bonus from ALL 6 players instead of just player1,2,3.

**Comment by CrustyMuffin** [comment]
There was also no way to get away from him in time since he enlaged himself and his hitbox faster than people could run away from him. A lot of timehis hitbox became so big, that i stood 30-40 yards away from the center of his hitbox and he still could hit me.

**Comment by fvicaria** [comment]
I will re-check this today.
