### ISSUE TITLE
Death Knight Frost talents Aren't adding up correctly

### ISSUE THREAD

**Issue by Drakothraen** [WoWManiaUK/Redemption#1950]
Frost Death Knight Talents are supposed to add up like so. 20% from Icy Talons + 20% from Improved Icy Talons and +5% for just you for a total of 45% attack speed haste. OR as in the actual number calculation is 
2.6(original weapon speed)/ (1+(Percentage Icy talons 20/100)) * (1+(Percentage of Icy Talons improved 20/100))* (1+(percentage of improved for just you 5/100))

2.6/ (1.2) * (1.2) * (1.05)

2.6/ 1.512 = New weapon speed of 1.719 or ~ 1.72 per second
Now add Haste rating to it also(mine is 11.70%)
2.6/ ((1.512) * (1.117))
2.6 /  1.6889 = 1.5394~ New Weapon Speed

Currently with above stats I have 1.85 attack speed with my 2.6 weapons

https://www.desmos.com/scientific
http://wowwiki.wikia.com/wiki/Haste

**Comment by Hajzlopuc** [comment]
Hello,

Yes seems to be bugged, for some reason you get only 20% + 5% bonus

**BUT**

I have a question for you. Did you apply frost fever before you wrote down your attack speed? Because first part work only if frost fever is applied.

2.6 / (1.2 * 1.05 * 1.117) = 2.6 / 1.407 = 1.85

Since patch 3.3.3 it should stack.
https://blue.mmo-champion.com/topic/158-please-clarify-this-dk-note-iit/
