### ISSUE TITLE
[Dungeon] The nexus

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#1964]
The event to unfrozen the last boss of the dungeon, [Keristrasza](http://www.wowhead.com/npc=26723/keristrasza) is currently bugged. As you can see in my screenshot below, after all 3 boss is killed, you can active the 3 crystal arround her, that is supposed to unfrozen her and let you fight her. But currently it's not. I'm marking the spark above the orb that appear when you active them, so you can clearly see that they are actived, along side with the frozen debuff of the boss still remain.
![1](https://user-images.githubusercontent.com/27235989/34119940-7f6a90ca-e456-11e7-8c08-ccfefb3b8c6f.png)

**Comment by nimavf** [comment]
[Keristrasza](http://www.wowhead.com/npc=26723/keristrasza#comments) is the last boss of [The Nexus](http://www.wowhead.com/the-nexus). In order to attack her, the group must unlock the 3 Containment Spheres which can only be activated after the death of the respective bosses.
The 3 Containment Spheres are:
1- [Anomalus' Containment Sphere](http://www.wowhead.com/object=188527/anomalus-containment-sphere)
2-[Telestra's Containment Sphere](http://www.wowhead.com/object=188526/telestras-containment-sphere)
3- [Ormorok's Containment Sphere](http://www.wowhead.com/object=188528/ormoroks-containment-sphere)
What is happening now, is that when you click on all 3 Containment Spheres, The boss remains Un-attackable.
Actually after like 15 sec the object is reseted and click-able again.
