### ISSUE TITLE
[Raid] Rotface

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#2032]
When attempting rotface he sometimes at a random point starts to evade. Not able to be killed by players and needs a reset by a GM. Or if raid wipes.

When reseting the boss it buggs him in another way. When the raid attempts to fight him again after a short period in the fight he teleports everyone inside the raid to the enterance.

**Comment by Keader** [comment]
Teleport everyone means that some boss before Rotface is not killed
my guess is Deathbringer...
Next time that it happens, can you test something for me?

use this command in game:

.i get 2
.i get 3

Check if return DONE for both

**Comment by fvicaria** [comment]
How often does this happen and how can we reproduce it?

**Comment by GMWeeble** [comment]
No this issue does happen when Rotface is killed and repsawned. Same with Festergut. I do think it is because you respawn a boss that is killed and has mechanics leading up to Proffesor. So if he is respawned he does teleport players back. But this is not the issue. 

Issue is that Rotface gets stuck unreset after a wipe.

**Comment by Keader** [comment]
Respawned by some GM or respawned by server?

**Comment by fvicaria** [comment]
Why would it be killed and respawned? It should never be killed by a GM in the first place.

**Comment by GMWeeble** [comment]
If the boss is unkillable by players I need to respawn it. And to respawn him I need to kill him.

**Comment by Keader** [comment]
"unkillable by players"
In what situation?

**Comment by GMWeeble** [comment]
When the raid Wipes the boss does not reset. Instead he just stands where he was when the raid wiped and is evading everything.

**Comment by fvicaria** [comment]
It just needs testing now.

**Comment by squalllh1989** [comment]
Well first of all, i know about the bug that GMWeeble mentioned, sometimes, randomly, when the raid wipe at rotface, he will not reset, instead he keep the hp remain that the raid fight him reduce him to before they wipe, or regen a bit  after the raid wipe (example: the raid wipe when he got 20% hp left, he can stand there with 20% hp, or regen to 25, 28, 30, 36% instead of reset to 100% hp), then he just stand arround (usually not in the right position that he should stand when not pulled), every attack and skill cast on him will be evaded. The raid can't do anything in this case and will need to make a ticket call for help to a gm. I don't know how gm deal with this bug as usually everyone in the raid will need to get out of icc before gm fix the bug.
The problem for the testing is, since the evade bug out and incorrect reset is randomly, i can't seem to be reproceduce this bug, tried many way like fight a bit then die, reduce his hp then die, etc, he still reset perfectly.

**Comment by TheManiax** [comment]
I couldn't reproduce either
Any info about how to reproduce it would be appriciated
But for now, Best way is to send a Dev to check the boss while it happens on red
Needs GM + Dev association

**Comment by fvicaria** [comment]
I think the best approach to this one now is see how it behaves in a real raid.

**Comment by GMWeeble** [comment]
Val and I were able to reproduce the issue. When he does slime spray he evades. So if a wipe happens during the slime spray he will stay evading (not normal evade)

**Comment by fvicaria** [comment]
He does not evade. He just clears the target. I doubt this is the reason.

**Comment by squalllh1989** [comment]
this is exactly what this problem is:
![wowscrnshot_010818_024714](https://user-images.githubusercontent.com/27235989/34653431-55510918-f41e-11e7-91be-29e4b402b0f8.jpg)
Just got this right now, posting this while waiting for ticket :D

**Comment by VA-L** [comment]
Yep, it's already fixed on dev.

- Rotface now evades correctly.
- Players no longer loose the target of the boss during the slime spray.
- Increased the speed rate of the Big Oozes (it was way too slow).
- The Little Oozes are now vulnerable to snare effects (as it should be).

**Comment by squalllh1989** [comment]
Tested and confirm, all fix work beside the evades one work correctly (can't confirm the evades since i can't reproduce it).

**Comment by GMWeeble** [comment]
You need to be atleast 2. I dont think we did mannage with one only.

**Comment by squalllh1989** [comment]
well i test with 2 toon while dual box, and can see perfectly all other fix work, just can't intendly make him bug out so can't test that.
