### ISSUE TITLE
[Boss] Ulduar's Kologarn

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2038]
Kologarn: http://www.wow-mania.com/armory/?npc=32930
Right Arm: http://www.wow-mania.com/armory/?npc=32934
Left Arm: http://www.wow-mania.com/armory/?npc=32933
Achievement: http://www.wow-mania.com/armory/?achievement=2951

Issue: Kologarn's arms are in the opposite direction (Right arm is left, left arm is right), Right arm (that's positioned on the left) has a bugged gripping mechanic where if you're dropped off the grip, you'll end up under the boss.
Another issue is that killing the boss will not despawn the arms, and if they are left alive you are stuck in combat for the rest of the raid, it also makes the Achievement "Open Arms" impossible to do.

**Comment by Keader** [comment]
@sirikfoll xD

**Comment by squalllh1989** [comment]
The fix is not working yet
- If you gripped by the right arm, and the arm is damaged, you are dropped to the boss 's feet, and you can't get up by yourself (unless you can fly back up like a gm or a warlock summon you up)
![wowscrnshot_010618_161156](https://user-images.githubusercontent.com/27235989/34638484-db12e204-f2fe-11e7-9770-d196239849aa.jpg)
- The chest (his body) can't be target at all by player, making him can't be killed at all.
![wowscrnshot_010618_162305](https://user-images.githubusercontent.com/27235989/34638513-8ec691c4-f2ff-11e7-895c-f8da02c3039f.jpg)
![wowscrnshot_010618_161457](https://user-images.githubusercontent.com/27235989/34638514-908b3b22-f2ff-11e7-94dc-1078cffbdfb7.jpg)
Only in gm mode that you are able to see his body's hp:
![wowscrnshot_010618_163214](https://user-images.githubusercontent.com/27235989/34638516-975710d4-f2ff-11e7-83f5-7f89b0ab491a.jpg)

**Comment by fvicaria** [comment]
I will revert this and keep it as it is for the moment.

**Comment by VA-L** [comment]
- Fixed multiple spawns of arms.
- Kologarn now despawns when evading.
- Arms will despawn when kologarn dies.
- Rubble adds will now search for players directly after being summoned.
- If a player is gripped by the right arm, he will now be correctly launched at the proper position.
- Fixed a visual issue on Kologarn's body.
- Fixed a visual issue on Kologarn's arms.
- All Kologarn's achievements have been added and can be obtained as it should.

Up to test !

**Comment by squalllh1989** [comment]
All fix work pefectly in dev now.
