### ISSUE TITLE
[Boss] Mimiron-Ulduar

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#2127]
I don't know why my posts were all closed for Mimiron I specifically asked Weeble to look at them and he said that they were fine. For some reason you want me to log only one issue at a time makes no sense you would think that you would want them all logged so you can work on them. But I will take the same approach to how I posted a few days ago where I will list all the issues in the same post instead of splitting them all up. It took me an hour to write those detailed posts that you asked me to do, so that we can all work together towards fixing Ulduar, so maybe a little more explaination before you delete them would be appreciated. If you have to fix one of them I'd choose number 6 since its currently the most game breaking of all of them.

There are a number of issues with Mimiron that need to be fixed.

1)First issue is with the area that you teleport to called the Spark of Imagination. Currently all the adds that are surrounding the center of the room the bombs do not move at all, and also they do not explode when coming into contact with players that try to cross the pass to get to Mimiron. This is supposed to be like the pathway in Naxxaramus where you try to get to patchwork where when the slimes cross the path if you touch them they explode and kill you in 1 shot. Instead these bombs will stay in place and if you get close or attack them all they do is attack you back and even if you kill them there is no explosion. 

2)The second issue we encountered with the Mimiron fight is one that is supposed to make phase 1 and 4 more challenging. During phase one and 4 he is supposed to be spreading mines around him with gaps in them for the melee group to run through when he does his overcharge ability. Currently in the 5 attempts we did on this boss this week we never saw any mines.
http://www.wowhead.com/spell=63027/proximity-mines

3)In phase one on hardmode fire spawns on the ground and starts moving towards players that are closest to him in the room. This is fine and works as intended. The issue is that halfway through the first phase mimiron is supposed to cast a spell called Flame Suppressant which removes all the fire on the floor and will slow the cast time of the raid by 50% for 8 seconds. Currently we have not seen him do this ability. This makes the second phase of this encounter extremely difficult as almost the entire floor is covered in fire and we can't get close to dps him until he casts frost bomb. Currently makes fighting him on hardmode undoable if you don't have really good coordination with your raid to keep the fires under control, and also if you don't dps him down fast enough as fires will continue to spawn every 30 seconds.
http://www.wowhead.com/spell=64570/flame-suppressant

4)Phase 2 has an issue with the visuals of the Laser Barrage spell that he is supposed to cast. There is supposed to be a constant stream of lasers that fire into the wall opposite Mimiron. Currently these beams appear to go into the ground just infront of him and it makes the encounter difficult since you can't tell where you are supposed to stand. You end up thinking that you are in the right place and all of a sudden you just get one shot. This needs to be fixed so that melee and ranged no where to stand throughout the encounter, especially with the limited floor space that you have available due to the fire that is on the ground.

Here's a link to the spell
http://www.wowhead.com/spell=63414/spinning-up

5) EDIT removed this issue as I screwed up on which phase the adds are supposed to appear.

6)There is an issue where after the group wipes a fight that when you go to press the self destruct button, nothing will happen. You will hear the voice that says 'this area will self destruct in 10 minutes, but fire won't spawn, the boundaries on the outside of the area won't engage which normally lock everyone inside the room, and Mimiron won't hop into his tank and start attacking. We didn't know what was going on so we went to the tank to try and kill it, which we managed to do with no abilities from Mimiron going off ,and nothing happened for Phase 2.

**Comment by hotdoggidy** [comment]
for issues number 6. is this after a normal attempt? or after wiping to Hardmode?

**Comment by Bartok14** [comment]
Can you provide a reference that this fight is only doable once on Hard mode because on retail my guild there was able to do multiple attempts. Subsequently you can do as many attempts as you want for the other keepers hard mode fights so I don't think Blizzard would limit only Mimiron to one attempt. Also I have read forum posts of others talking about doing him multiple times in a week and wiping and never having this issue. 

The main issue with number 6 is I think that when you press the button sometimes after a wipe is that Mimiron himself isn't resetting correctly. He didn't seem to hop into the tank from what I remember yesterday, and I think we just ended up killing him with splash damage. Maybe in dev try respawning Mimiron himself to see if you can reset the fight.

**Comment by Bartok14** [comment]
For issued number six, I just realised that Mimiron's guardian spirit in in the chamber of Ulduar that overlooks Yogg Saron. Somehow it seems we managed to kill Mimiron without him dropping anything and also without the Hard Mode phase initiating properly. I think the reason for this is that Mimiron himself didn't reset correctly after the wipe and was standing outside the Mark 2 Tank when we DPS'd him down. therefore there wasn't the correct trigger for the loot drop and the achievement for the hard mode. Maybe try killing him a few times to see if he resets correctly and if not that might be the problem with that phase of the fight. As for the fires not spawning correctly on the ground I'm not sure why that would have happened but it might be related to the above issue.

**Comment by Dranah** [comment]
1st issue confirmed, trash mobs don't patrol or explode.

2nd issue is half-legit, the boss in p1 does spawn proximity mines, but the frequency is very scarce. 
How it should work: The first set of mines should be laid 5-6sec after Mimiron becomes active, next ones follow with 35sec intervals. The previous mines also blow themselves up at the 35sec mark, right before the new set is spawned.
How it works at the moment: The first cast arrives only 35-40sec after Mimiron begins attacking (a geared group trying for hardmode has likely finished phase1 by this time). The intervals for next ones appears to be 65~ seconds instead of the intended 35.

3rd issue confirmed, Flame Suppressant isn't being cast, preventing melees from attacking. Frost bomb is the only means to remove fire right now.

4th issue confirmed, the visual of the spell is wrong. Ranged dps in the distance may have trouble tracking the path of the laser as the boss turns.
How it should work: the visual of the beam should reach from the boss to the walls of the room.

As for issue 6, Hard-mode is certainly NOT one-attempt, but the fight appears to be resetting properly for me, and starting over as intended when you push the button again.
Please add more information on which phase/mob you wiped on that try when it broke, also if anyone in the raid used combat wipes (feign death, invisibility, vanish?) because I cannot reproduce this.

**Comment by Dranah** [comment]
Additional problems:

1. Phase 3 Emergency Fire bots http://www.wow-mania.com/armory/?npc=34147 are idle, they spawn but don't do anything. This means your only means to remove fire in this phase is also Frost bomb.
How it should work: These mobs should patrol and extinguish fire all around the room. Also damage players with their extinguish spray if they walk too close.
2. Phase 3 Bomb bots don't explode. They just aggro and attack you like a regular melee mob.
How it should work: bomb bots should run towards a nearby target (they do not have an aggro table) and just explode on them.
3. Wiping during phase3 leaves the room full of the bots already spawned. 
How it should work: They should despawn as the fight ends.
4. Aerial Command Unit http://www.wow-mania.com/armory/?npc=33670 isn't possible to move by outranging his attacks, in fact his Plasma ball reaches you anywhere.
How it should work: Plasma Ball http://www.wow-mania.com/armory/?spell=63689 should have a 30 yard range, making the boss move closer to his aggro target when he moves further than 30 yards.

**Comment by Bartok14** [comment]
So for the issue number 6 we had about 5 attempts that week and then we died during phase 2, I'm not sure if there was a hunter or rogue that either vanished or feigned death. What happened though was that mimiron did not reset correctly and when we pushed the button nothing happened. I think we then killed mimiron before he hoped into his tank becasue again nothing was happening. We didn't get any loot or anything and essentially he just went to the room overlooking yogg saron and just stayed there as a keeper. I'm not sure why he didn't reset correctly.

**Comment by Dranah** [comment]
Well, here's what i found: 
It is possible to reset the fight in a manner that both Mimiron and the Leviathan MK II are attackable after the combat ends. (Normally, only Mimiron would be!) 
Engaging the boss while in this state (both npcs attackable) can sometimes malfunction.
Hard mode not beginning properly is just one out of colourful problems that can arise, though it does not happen every time.

One issue lies in the fact that the Leviathan MK II does not immediately aggro to the raid as he is formed. Instead, he will remain in the center of the room, not being pulled until someone attacks him, even tough the timers are already running. If you wipe to the fire or feign death in this state, the boss will reset in the above manner every time.

**Comment by VA-L** [comment]
- Bombs Bots outside Mimiron's room will now have their correct paths and will explode if someone is close to them (2yd), they have no aggro table.
- Flame Suppressant was casted more than once on P1, it's now casted only once.
- Flame Suppressant was an instant cast on P2, it now has 2 sec cast.
- Barrage Laser is now correctly shown.
- Emergency Fire Bots will now look for flames and extinguish them.
- Bomb Bots will now explode if it reaches a target.
- Bomb Bots will now have 50k HP on HardMode.
- Adds are correctly despawned if there's a raid wipe.
- Aerial Command Unit will now be able to move during the fight and Plasma Ball has now a 30 yards range.

**Comment by Dranah** [comment]
UPDATE:
Most of boss abilities now work as intended.
Fix for Phase1 Flame suppressant still has to be applied for 10man difficulty (works on 25).

Aerial Command Unit's movement/aggro/general behavior still needs fix.
 - ACU must stay in the air and not descend to players unless a magnetic core is used
 - ACU must respond to players overaggroing each other (also someone dropping threat with threatwipes) and change target accordingly. Currently he only responds to taunts.
 - ACU must follow his target until he is in 30yrds range for plasma ball and not go closer afterwards.
 - ACU must descend and stay on the ground when Magnetic Core is used. When the effect expires, he must fly up again and continue his attacks and movement as before.

**Comment by Keader** [comment]
"ACU must stay in the air and not descend to players unless a magnetic core is used"
It needs Hover Mode working, and is not implemented in current core yet

**Comment by Dranah** [comment]
@Keader Before recent changes ACU descended only a few yards on each cast and then quickly adjusted his position to get back up. Val told me it's because Hovering is broken, but it wasn't a huge problem. What I described now is that he faceplants the floor after every cast and never readjusts his position. If we can get it back to working as the first state, that would be "good enough".

**Comment by Dranah** [comment]
UPDATE:
- Flame suppressant in phase1 now works as an instant spell, but works (workaround - as is)
- Phase3 and Phase4 Aerial Command Unit still unresponsive to aggro numbers (need fix)
- Phase3 ACU now adjusts aerial position after casts and doesn't hit the floor anymore (fixed)
- Phase3 ACU isn't correctly rooted by Magnetic cores. He gets stuck halfway between ground and his normal air level (needs fix)
- Phase3 ACU still gets closer to the range tank after each cast (tweaking issue)

**Comment by Dranah** [comment]
Update:
- Phase3 ACU movement is now acceptable (fixed)
- Magnetic cores work on him as intended (fixed)
- Phase3 ACU still ignores threat numbers and keeps shooting his current target until something forces him to deselect (taunts / feign death / out of range)

**Comment by Dranah** [comment]
UPDATE:
- Phase3 ACU threat and aggro now works as intended (fixed)
- Phase3 ACU movement is broken again, he comes down to melee range to shoot, instead of staying up and keeping 20-30 yard distance (need fix)
- Phase4 ACU now isn't shooting plasma balls at all (need fix)
- Phase4 Laser barrage visual breaks when the V-07-TR-0N is not in the center of the room (tweaking issue)

**Comment by philoudu16** [comment]
UPDATE:

- Phase 2 Mimiron is spinning the wrong way round while shooting Laser Barrage (should be clockwise, currently counter clockwise).
- Phase 3 ACU still comes down to melee range after a little while.
- Phase 3 to Phase 4 transition doesn't seem to be consistent. It seems like too much burst damage won't trigger it.
- Phase 4 Laser barrage visual still breaks if V-07-TR-0N is not in the center of the room. (and is spinning the wrong way round like in phase 2)

**Comment by Dranah** [comment]
@philoudu16 
1. Phase3 ACU movement is as good as it gets, he sometimes descends a few yards, but adjusts his level afterwards and flies back up. 
The reason he "comes to melee range after a while" is that he stops adjusting his distance when he reaches 100k health (300k on 25man). This is intentional, because his overregulated movement is the reason behind breaking the transition from phase 3 to phase4. This way he removes regulation as the phase is about to end to prevent him breaking the transition.
2. The transition gets stuck if you kill him faster than half second after his health drops below 100k (300k on 25man respectively), because he has no time to turn off his regulations. This is a damage output that an actual raid cannot reach even with Magnetic Core active.
3. The Phase4 laser visual problem is left as tweaking, there is currently no fix without breaking the textures altogether in the instance
4. I have no idea if anyone cares which way the laser is spinning, it doesn't anyhow affect the fight. But if Val feels like doing a hotfix on it, i won't stop him.
Either way this fight is as blizzlike as it can be atm.

**Comment by philoudu16** [comment]
Weird, we actually managed to break the transition on redeption three days ago on 10 man (without even having the magnetic core active)

**Comment by Dranah** [comment]
that could be a previous version of the fix , released early :/ that one didn't have the safety belts it has now
either way we may rise the limit just to be sure
