### ISSUE TITLE
[Instance] Culling of Stratholme

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2132]
Hello,
I'd like to report an issue that arose recently in the dungeon Culling of Stratholme http://www.wow-mania.com/armory/?zone=4100.

Earlier the moment you finished the last mob of each wave, the new wave spawned at its designed location immediately as intended.
Now, there is a delay before a new wave spawns, that isn't consistent, sometimes 4-5 seconds, sometimes 30, sometimes nearly a minute. 
This can cause problems with completing the timed run for this http://www.wow-mania.com/armory/?achievement=1817 and the bronze drake. There are already several parts of the event that you just can't speed up, for example Arthas can't walk faster, and now you waste around 4minutes total on the unintended wait times.

**Comment by Magabro** [comment]
Tested with help of **_# Unstoppable_** on Redemption:

It appears that in order to trigger waves 3 and 7 (these waves spawn near the town hall on the right side of map) a player from the group must pass out of the "Festival Lane" area and enter "The Culling of Stratholme" area.  We waited almost 2 minutes for wave 7 to spawn and the wave did not spawn until **Unstoppable** moved through this zone transition area.  Screen shots below:

Waves 3 and 7 spawn here:
![wowscrnshot_012218_090642](https://user-images.githubusercontent.com/34353250/35233980-889f868c-ff54-11e7-80c2-aea2a17dffd2.jpg)

But not until you move across the line shown here:
![wowscrnshot_012218_090811](https://user-images.githubusercontent.com/34353250/35234239-4e4cd63c-ff55-11e7-996f-6898495ef320.jpg)

**Comment by fvicaria** [comment]
The pauses are intentional and related to distances. I will even them out a bit.
