### ISSUE TITLE
Shamans Lava Burst issue, again.

### ISSUE THREAD

**Issue by Munja357** [WoWManiaUK/Redemption#2146]
I dont know why, but someone is deleting my posts, but elemental shamans have an issue with Lava Burst. Basicly Lava Burst should crit everytime when you have flame shock active on target, and it doesn't crit everytime. Ive tested it. Can you tell us what is the problem, and why you keep deleting my posts?

**Comment by LooneyBin** [comment]
maybe they delete your post when you make a new one every 10 mins?

**Comment by Munja357** [comment]
Nope, this is 2nd one. And i cant see that anyone confirmed that they will fix this problem!

**Comment by Munja357** [comment]
They moved another's guy post to closed, but problem isnt fixed yet.

**Comment by larian** [comment]
made a post about it yesterday and with screenshots to proof but seems post is gone

**Comment by TheManiax** [comment]
We have fixed it.
It will be fixed on Redemption realm tomorrow.
search before posting.

**Comment by Magabro** [comment]
Hi Munja357.

Your posts have not been deleted.

These 2 posts contained no information and were closed.
https://github.com/WoWManiaUK/Redemption/issues/2143
https://github.com/WoWManiaUK/Redemption/issues/2145


A Developer responded to this post stating that the issue was, has been fixed in development, and the fix will be live on redemption at some point in the next day or so.
https://github.com/WoWManiaUK/Redemption/issues/2144

It would be very useful if you read and followed the posting guidelines.

**Comment by Munja357** [comment]
That was accidantly posted, and i got my answer, tyvm for fast response, fix is comming.

**Comment by TheManiax** [comment]
![wowscrnshot_012218_195140](https://user-images.githubusercontent.com/14857593/35231367-d2cf7a1a-ffad-11e7-802c-ba758d0c4a5b.jpg)
Just to make you sure it is fixed ;)

**Comment by fvicaria** [comment]
I swear to god one more lava burst issue logged I will get perma ban!
