### ISSUE TITLE
[Boss] Rotface Heroic - Vile Gas

### ISSUE THREAD

**Issue by philoudu16** [WoWManiaUK/Redemption#2185]
I know this issue has already been reported (#1131) and at the time, you weren't able to reproduce the issue, but I was wondering if you could check it again now your team seems to be bigger and you work really well on the fixes :)

The issue is that the mages' mirror images can get the Vile Gas debuff, dealing damage to players around them, making the mirror image totally unusable for mages since the images follow you (which means you lose dps, and you have to watch your aggro more than normal).

Links to boss and spells:
http://www.wowhead.com/npc=36627/rotface
http://www.wowhead.com/spell=72272/vile-gas which triggers http://www.wowhead.com/spell=69244/vile-gas

If you need extra people for testing, feel free to contact me in game (in game name Zunrin)

**Comment by Dranah** [comment]
My test shows neither heroic Rotface, neither Festerguts original Vile Gas can be cast on Mirror images. They can't even be affected by its area effect when its cast on the mage nearby.

**Comment by Dranah** [comment]
- The bug is still present, but you need a death log to track the damage coming from the mirror images, as it is not shown anywhere else. 
- Also, the Mirror images are NEVER the original target for the Vile gas (it will always show to target a player), but they are affected by it, and their Vile gas debuffs will damage nearby players (the vomitting part). That will essentially kill the mage with 3 images vomitting on him.
The problem is basically that pets and Mirror Images should not be affected by the debuff at all, because the splash damage they cause can wipe the raid.

Proof: https://imgur.com/GbYkzcv

**Comment by Sugarconepk** [comment]
The same debuff applies to any shaman totems.

**Comment by fvicaria** [comment]
Applied some changes. Re-test please.

**Comment by Dranah** [comment]
No more damage incoming from Mirror images on the death log, nor a trace of the debuff on them.

**Comment by WhitephoenixTheBunny** [comment]
Same as shaman's totem... forgot tell here :P
