### ISSUE TITLE
[Boss] Mimiron - Ulduar

### ISSUE THREAD

**Issue by Unstoppablee** [WoWManiaUK/Redemption#2251]
Issue:
Phase 2:
P3Wx2 Laser Barrage does not show the right direction of the shooting, shows as if the body is shooting towards the ground, and on next P3Wx2 Laser Barrage casts, it shows that he's shooting the barrage in the opposing (wrong) direction.

Spell ID: http://www.wow-mania.com/armory/?spell=63274

Phase 3:
Boss evades all attacks and does not progress at phase 3 (Aerial Command Unit) into phase 4 (Leviathan Mk II + VX-001 + Aerial Command Unit, all three combined) when you drop the Helicopter to 1 hp, causing it to freeze and making the raid get stuck in combat + fight in progress, or the enrage (shut-down) happens as it wipes the raid and it still implies the fight is in progress.

Aerial Command Unit ID: http://www.wow-mania.com/armory/?npc=33670

Phase 4:
When wiping on phase 4, the Vehicle (Leviathan Mk II) becomes untargetable, while everything else doesn't reset which causes a raid over.

**Comment by fvicaria** [comment]
How come this was not detected here: #2127
It was marked fixed and confirmed

**Comment by Dranah** [comment]
Issue 1: cannot reproduce
Issue2: Is a known problem that can happen if you manage to take out the last 200k (500k on 25man mode) health of the aerial unit in LESS than 1second. Otherwise cannot happen. Have no idea how you push that kind of damage without exploit.
Issue3: Cannot reproduce without further details/information.

**Comment by Ashamedlol** [comment]
@Dranah If you use the magnetic core and you have 7 dpsers, it's very easy to push such damage.

**Comment by Dranah** [comment]
@Ashamedlol 
In order to push that 200k over 1second assumes each of your 7 dps lands 29k damage in the very last second of the fight. Possible? Yes, but not "very easy" to produce to say the least.
Anyway perhaps Janitor can build in a mechanism to prevent overdpsing. As I said this is a workaround because aerial NPC movement is simply not possible otherwise.

**Comment by Ashamedlol** [comment]
Still has the mentioned bugged and has new bugs: 
1) When wiped, Mimiron stays on top of the vehicle and is killable, killing him will cause no boss encounter to progress and a bugged raid as you can't progress to General Vezax and Yoggsaron without an encountered Mimiron.

2) Walking to the boom bots (http://www.wow-mania.com/armory/?npc=33836) or attacking them outside of the Mimiron area gets you stuck in combat permanently.

3) The alarm (DO NOT PUSH THE BUTTON!!!) npc is invisible and chases you to eternity.
