### ISSUE TITLE
[Dungeon] Hakkari God

### ISSUE THREAD

**Issue by flumby** [WoWManiaUK/Redemption#2262]
When doing the Sunken temple the item 10460 [Hakkari Blood] is not dropped by Hakkari Bloodkeeper.

When this blood is manually added into our inventory, we cannot use them on any of the 4 braziers which you are suppose to use it on to spawn the Hakkari God boss (Avatar of Hakkar).

![36330687-a09f8a94-1362-11e8-9988-9e39fd51675b](https://user-images.githubusercontent.com/31921098/36331756-0a90b83e-1367-11e8-8033-2e2adfc33ca9.png)

**Comment by philoudu16** [comment]
The encounter is simply not really scripted.

**How it should work:** (copy pasted a wowhead comment from before the cata rework)
The fight with the Avatar of Hakkar requires the use of either the Egg of Hakkar or Yeh'kinya's Scroll.
First off, make sure all of your party is in the summoning room, for once the event begins gates will seal you off from the rest of the instance and anyone caught outside the gates won't be in to help you.
Before the summoning begins, gather up the rest of the party together in a corner of the room beside one of the four flames. Also, in order to make looting the necessary blood off of the Hakkari Bloodkeepers easier, the leader can set the loot options to "Free-For-All." That way anyone can loot the blood and use it to douse the flames, or you can assign one person to be solely responsible for taking the blood and dousing the flames.
When the avatar has been summoned, a variety of mobs will appear in waves. So long as you stick to the corners of the room, you can control how many of these mobs will aggro your party at a time. Along with these will be one of the Hakkari Bloodkeepers. Once you kill it, loot the blood, and douse a flame, a Nightmare Suppressor dragonkin will spawn and attempt to channel energy to banish the Avatar away. This is a bad thing because if it succeeds the event will end and you won't be able to resummon the Avatar during the current run. So as soon as it appears it should be engaged into a fight and defeated. Between waves it is possible to fall out of combat, so the opportunity to replenish mana and mend hp should be taken when necessary.
Once three flames are doused and last bit of blood collected, save it and use the lull in the fight to get ready for the Avatar. When ready, extinguish the last flame and the Avatar of Hakkar will be made solid. During this fight care needs to be taken because occassionally the Avatar will curse one of your party, mind controlling him/her and turning them against the rest of you. Decurse or CC that character if your able to, especially if it's someone who could easily kill one of your clothies if left unchecked. Eventually the curse will wear off and they'll return to normal. Otherwise it's like a previous poster said. The fight is a typical tank and spank.

**How it works:**
You summon the boss with the egg or with the scroll, and it's simply a tank and spank fight against the avatar, with no mobs spawning at all or anything.

**Links:**
The boss itself: http://www.wowhead.com/npc=8443/avatar-of-hakkar
The egg: http://www.wowhead.com/item=10465/egg-of-hakkar
The scroll: http://www.wowhead.com/item=10818/yehkinyas-scroll
The blood: http://www.wowhead.com/item=10460/hakkari-blood

**Comment by flumby** [comment]
Interesting, thank you for that research I think I have only ever ran this dungeon on tbc retail like twice and that was many years ago.  I maybe should of looked at wowhead before wowwiki.

**Comment by flumby** [comment]
Confirmed.

**Comment by fvicaria** [comment]
Hakkari Bloodkeeper drop the item
 
![image](https://user-images.githubusercontent.com/9414661/36339434-8d6c8dcc-13bd-11e8-9f0c-4cadea4e6149.png)

**Comment by fvicaria** [comment]
I used the egg on the altar and it spawns the NPC.
![image](https://user-images.githubusercontent.com/9414661/36339591-2585d322-13c1-11e8-9137-64214259a7f6.png)

**Comment by fvicaria** [comment]
The boss is spawned from the item http://www.wow-mania.com/armory/?item=10465 
and is provided for the quest http://www.wow-mania.com/armory/?quest=3528

**Comment by philoudu16** [comment]
The boss spawns indeed, but he is barely scripted...

This is how the encounter should look like:
https://www.youtube.com/watch?v=44e3dJysjfk

Nothing of this happens on this server. When you use the egg, the Avatar spawns and you can target it from the start, and not a single add will spawn, so the fight is way more boring than it should be.
(**basically just READ my report at the top of the issue...**)

So YES you can kill the boss, but it doesn't work the way it should...

**Comment by fvicaria** [comment]
All points raised in the issue were invalid.
If the boss is not scripted is a totally different issue.

**Comment by philoudu16** [comment]
UPDATE:

Avatar of Hakkar was still targetable as soon as i used the egg, and no adds were spawning.
(encounter still doable, but still not working as intended)
