### ISSUE TITLE
[Spell] Blood Tap

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#2284]
[This spell](http://www.wow-mania.com/armory/?spell=45529) is having some trouble at the moment, this problem has persis before but i didn't notice it until today:
- How it should work:
+If you have no blood runes on CD => It turns one blood rune into a death rune
+ If you have all your blood runes on CD => It activates a blood rune, and turns it into a death rune
+ If you have a death rune on CD and a blood rune NOT on CD It turns your blood rune into a death rune AND activates another death rune
Infomation taken from [here](https://us.battle.net/forums/en/wow/topic/2089200649)
- How it actually work now:
+If you have no runes on CD => It turns one blood rune into a death rune (working properly)
+ If you have all your blood runes on CD:
           1) If you are in blood spec (which i use as a tank spec): It activates a blood rune, and turns it into a death rune (working properly)
           2) If you are in frost spec (which i use as a dps spec): It doesn't active a blood rune, just turn a blood rune into death rune the next time it become active.

**Comment by squalllh1989** [comment]
This problem can be clearly see in some situation: when all of your blood rune and plague rune is on cd, you wanna active Blood tap to get 1 death rune and use pestilence to refresh the plague (glyph effect) before they fade, you can't because blood tap won't give you 1 extra blood rune right away at the moment you need it.

**Comment by Keader** [comment]
@Dranah Can you confirm it?
If is confirmed i will try fix today.

**Comment by Magabro** [comment]
When both of your Blood Runes are already converted to Death Runes with Blood of the North (using Blood Strike or Pestilence) Blood Tap will not recognize them as a Blood Rune and will not reactivate them

To reproduce:
1) Level 80 Death Knight talented with Blood of the North talent. http://www.wow-mania.com/armory/?spell=54637

2) Use both Blood Runes with either Blood Strike or Pestilence skill.  These runes immediately convert to Death Runes and go on cooldown

3) Active Blood Tap and see your Blood Runes (which have already been turned to Death Runes) are still on cooldown.

Repeat again but use Blood Boil and your Blood Rune will activate.

Separately, using Blood Tap while only 1 Blood Rune is on cooldown with convert tha unused Blood Rune into a Death Rune.  Blood Tap should prioritize the rune on cooldown and activate it as a Death Rune instead of the unused Blood Rune.

**Comment by RusenGobel** [comment]
This is not fixed. Can you please fix it?
