### ISSUE TITLE
[Boss] Gunship

### ISSUE THREAD

**Issue by LooneyBin** [WoWManiaUK/Redemption#2290]
Currently then warriors cant use charge or intercept on the Gunship encounter, been like this for the last year, since i joined here basicly.
It's not a game breaking thing, just an annoyance, especially considering that Feral cats can use their Charge without issues.

Skills in question:
http://www.wow-mania.com/armory/?spell=100

http://www.wow-mania.com/armory/?spell=49376

https://imgur.com/a/e0Cf7

Video from Retail:
https://www.youtube.com/watch?v=hDMNM4nywN0

2:21 or so, the Bear charges a mob without issues.

**Comment by Dranah** [comment]
Doubt feral cat's leap is even considered a charge effect. (It does not have the 1#effect charge on its armory table, it has some jump effect). Also uses slightly different pathing.
Intercept: http://www.wow-mania.com/armory/?spell=47996
I suppose bear charge http://www.wow-mania.com/armory/?spell=16979 is also affected, since you linked a video for that.
Is this problem present everywhere on both ships or is it just certain areas/angles?

**Comment by LooneyBin** [comment]
Guess you're right about the Cat charge, also what i thought.

it's on both ships, 10 norm, 10 hc, 25 norm, 25 hc, it's the same all places.

just used that Video since it was the first i found, and that i know is 100% legit, that showed that a charge was used (and not a feral cat "leap")

**Comment by fvicaria** [comment]
There is no restriction on that on the gunship. What could be is an issue with elevation and LoS.
This is not a charge or gunship issue, it is a much more general issue. You are supposed to have a fixed path when performing a charge and this does not happen on the gunship.
Unfortunately, we will not be looking at this at this point.

**Comment by LooneyBin** [comment]
Fair enough.
and as i said, not a game breaking thing, so we'll manage anyway.

**Comment by Zunrin** [comment]
If ever you look at this again in the future, mages can't blink either (even when the ship isn't moving before the encounter starts)
