### ISSUE TITLE
[Talent] Restorative Totems

### ISSUE THREAD

**Issue by Hajzlopuc** [WoWManiaUK/Redemption#2444]
Hello,

I would like to report an issue with the shaman's [Healing Stream Totem](http://www.wow-mania.com/armory/?spell=58757) when paired with the talent [Restorative Totems](http://www.wow-mania.com/armory/?spell=16206)

Without any talent:
https://puu.sh/Ac374/0fded003c6.jpg
With 3/3 Restorative Totems talent:
https://puu.sh/Ac38x/2a8ecae5b6.jpg

As you can see, value is boosted only by +11 at the moment, I guess only the base value is boosted.

This could maybe help? https://github.com/TrinityCore/TrinityCore/issues/2165
https://github.com/TrinityCore/TrinityCore/pull/4273
(Maybe glyph is also bugged, couldn't test it by myself because haven't found any in AH)

**Comment by Dranah** [comment]
Confirmed.
Both the talent Restorative Totems (16206) and the glyph of HST (41533) only boosts the base 25 value of the heal. These effects stack properly with each other, but the spell power bonus is added only afterwards, unaffected by these modifiers, which is unintended.
Purification (16213) talent and the ICC buff scale correctly.

**Comment by Dranah** [comment]
UPDATE:
- The spell power coefficient got fucked up, it appears to be ~15% per tick now, as opposed to the 8% it was properly before.
- Restorative Totems multiplier still does not scale properly with spell power, but the values no longer match the previous where only the base value was affected.
I suspect the two may be related, because the difference in expected value vs actual healing seems to be the 8% extra spell power coefficient after the 1,45 modifier is applied.
Based on my tests, it's like the spell calculates itself as (25+(0,08x SP)) x 1,45 + 0,08x SP (hint: that second 0,08% SP added after the multiplication is not intended)

**Comment by Keader** [comment]
lul, it's not fixed yet.
@Dranah  new fix in dev, please test.

**Comment by Dranah** [comment]
No change, the SP coefficient is still added twice.
The spell is as much overpowered now as it was underpowered before.

**Comment by Keader** [comment]
Wtf?
I removed the duplicated call o.O

**Comment by Dranah** [comment]
Still not good.
Spell power coefficient double-dips.
ICC 30% buff double-dips.
However the 20% modifier from Glyph of Healing Stream Totem seems to work properly as of now.

**Comment by Keader** [comment]
Ok, test again tomorrow @Dranah. (20:47 PM here lul)
Let me know how broken is xD

**Comment by Dranah** [comment]
Ok, as we discussed with Keader, this spell cannot be fully fixed due to core issues.

Here is a template for a possible workaround:
- Take the "overpowered" version of script (mod1, for keader) that uses this formula:
( (BaseValue + coeff x SP) x modifiers + coeff x SP ) x bugged modifiers = current heal

Bugged modifiers: 10% purification, 30% ICC boost
Other modifiers: 45% Restorative totems, 20% Glyph of Healing Stream Totem

- Modify spell power coefficient to 4,45%

Result Examples:
Outside ICC > Resto / non-resto, with 1500 healing bonus, no glyph:
Intended healing: 236 / 148, pre-fix state (underpowered): 162 / 148, Mod1 (overpowered): 394 / 271
After workaround:  232 / 157

Outside ICC > Resto /non-resto , with 3000 healing bonus, no glyph:
Intended healing: 432 / 271, Pre-fix state (underpowered): 310 / 271, Mod1 (overpowered): 746 / 517
After workaround: 423 / 291

Outside ICC > Resto/non-resto shaman 3000 healing bonus, yes glyph:
Intended healing: 518 / 325, Pre-fix state (underpowered): 323 / 276, Mod1 (overpowered): 841 / 571
After workaround: 479 / 322

Inside ICC > Resto / non-resto, 3000 healing bonus, no glyph:
Intended healing: 561 / 352, Pre-fix state (underpowered): 371 / 352, Mod1 (overpowered): 1155 / 777
After workaround: 658 / 338

Inside ICC > Resto / non-resto, 3000 healing bonus, yes glyph:
Intended healing: 674 / 422, pre-fix state (underpowered): 382 / 358, Mod1 (overpowered): 1316 / 869
After workaround: 752 / 493

Inside ICC > Resto / non-resto, 4500 healing bonus, yes glyph:
Intended healing: 980 / 614, pre fix state (underpowered): 596 / 518, Mod1 (overpowered): 1929 / 1278
After workaround:  1086 / 716

Compared to having half or double the intended healing, the numbers show this workaround results realistic healing numbers in all types of gear, spec and situation.
And the best part is, that based on wowwiki and some wowhead comments, pre-3.3.5a the spell coefficient used to be 4,45% for HST, before it received a boost from blizzard. Which means people can't say we "took it out of our arse". (PS: its a complete coincidence that this coefficient seems to work out the most balanced with the current bugged formula)

**Comment by Dranah** [comment]
UPDATE:

After changing spell coefficient to 4,45%, the spell now calculates with the following formula:

((BaseValue + 0,0827 x SP) x modifiers + 0,0445 x SP ) x bugged modifiers = current heal

Means the spell power coefficient you changed only affects the second SP component. May as well set it to zero and it will likely stop double dipping?

**Comment by Dranah** [comment]
Purification and ICC buff still double-dips. No change at all.

**Comment by Keader** [comment]
Nothing more can be done here.

**Comment by Dranah** [comment]
This fix needs to be reverted as it conflicts with the new core update.
HST now has no spell power coefficient.
