### ISSUE TITLE
[Item] Murkblood Escape Plans

### ISSUE THREAD

**Issue by moontouched** [WoWManiaUK/Redemption#2450]
Hello,

I would like to report an issue with the item [Murkblood Escape Plans](http://www.wow-mania.com/armory/?item=32726)
I cannot get the quest from the item. Right clicking it says i do not meet the requirements, even if i do.
![wowscrnshot_043018_000407](https://user-images.githubusercontent.com/36900407/39411020-6c09b21a-4c0a-11e8-8354-6bfe4b226f59.jpg)
![wowscrnshot_043018_000418](https://user-images.githubusercontent.com/36900407/39411021-6c982aea-4c0a-11e8-979d-0d3d7d739f80.jpg)
![wowscrnshot_043018_000423](https://user-images.githubusercontent.com/36900407/39411022-6d812164-4c0a-11e8-8dee-bc2cd951397a.jpg)

GM Metaxa confirmed he cannot take it aswell, even if he is Exhalted and told me to report it.
Thanks you!

**Comment by Zunrin** [comment]
You need to have completed http://www.wow-mania.com/armory/?quest=11075 first.

**Comment by moontouched** [comment]
Okay, but the previous quest, [Rise, Overseer! ](http://www.wow-mania.com/armory/?quest=11053)
but the NPCs in Netherwing offer nothing else but dailies for me. All i have available to take as quests are dailies (even those for higher reputation standings than what i have) and n actual quests

**Comment by moontouched** [comment]
Okay, but the previous quest, Rise, Overseer!  is not available*

**Comment by fvicaria** [comment]
![image](https://user-images.githubusercontent.com/9414661/39418668-8dacccd8-4c53-11e8-870e-45a40c2d496b.png)

![image](https://user-images.githubusercontent.com/9414661/39418682-a398397e-4c53-11e8-9d02-c7f42184bd71.png)

@moontouched: Thanks for your initiative to try to improve the game, most people don't even bother reporting issues. However, this is your 4th issue and all 4 were closed as invalid. I would advise you to talk to some of the testers on how to confirm and verify certain conditions before logging the issue here as it can consume the very limited time developers have to fix stuff.
Please continue to be vigilant and report everything you are 100% sure is broken here.

**Comment by moontouched** [comment]
All four of them were confirmed by GMs in game, they redirected me to posting them here.
One thing working for you might not be working properly for someone else, you know. The are lots of variables in this game. I could give you my account details so you could go and seee for yourself once and for all. Even though i don't think you'd be able to log in any of my chars since last night's Weeble "help" with one of those issues. I'm quitting this player unfriendly server anyways.

**Comment by fvicaria** [comment]
The GMs were wrong.

**Comment by GMZinius** [comment]
### For notes on this issue 

You cannot loot this item unless you have completed [The Netherwing Mines](https://tbc.wowhead.com/quest=11075/the-netherwing-mines).

Players atm are able to loot this item before they have completed the requirements for this to actually drop
