### ISSUE TITLE
[Quest] Anatoly Will Talk

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#2469]
Found a bugged quest in Grizzly Hills: http://www.wow-mania.com/armory/?quest=12330. Even when bringing Tatjana with her horse to the NPCs, quest is still not completed as you can see on the screenshot below.
![1](https://user-images.githubusercontent.com/30184491/39965271-23449d1a-5696-11e8-8862-5275dec442b4.png)

**Comment by TheManiax** [comment]
**How it should work:**
Player has to use [[Tranquilizer Dart]](http://www.wow-mania.com/armory/?item=37665) on [Tatjana](http://www.wow-mania.com/armory/?npc=27627), this will turn [Tatjana](http://www.wow-mania.com/armory/?npc=27627) to [Tatjana (Unconscious)](http://www.wow-mania.com/armory/?npc=27632) and [Tatjana's Horse](http://www.wow-mania.com/armory/?npc=27626) will change from hostile to friendly.
Then the player has to jump on the horde (ride) and the horse have to move to [Sasha](http://www.wow-mania.com/armory/?npc=26935) to complete the quest.
**How it works:**
Everything works untill the part that the horse has to move to  [Sasha](http://www.wow-mania.com/armory/?npc=26935) on its own. Instead you can move it to  [Sasha](http://www.wow-mania.com/armory/?npc=26935) but the quest won't get completed.

---
The work around at the moment is to use [[Tranquilizer Dart]](http://www.wow-mania.com/armory/?item=37665) on [Tatjana's Horse](http://www.wow-mania.com/armory/?npc=27626) instead of [Tatjana](http://www.wow-mania.com/armory/?npc=27627) herself. This way the horse moves on its own (incase you ride on it) and the quest will be completed.
Overall the quest is doable with this work-around, but it is not working as intended.

---
![image](https://user-images.githubusercontent.com/14857593/39965951-669f0128-56b8-11e8-8a0d-a20197a5ce90.png)
