### ISSUE TITLE
QUEST: On Ruby Wings

### ISSUE THREAD

**Issue by Dramorabg** [WoWManiaUK/Redemption#2511]
When trying to kill Antiok, he doesnt lose the "Immune to all damage" aura he has.. No matter what you do.. Even if you dismount the drake.. Reported by: Dramorabg

**Comment by TheManiax** [comment]
The NPC looses his Immunity buff after like 10 second.
That might be stuck, but seems ok at the moment.
Please try again @Dramorabg

**Comment by 0p3ngl** [comment]
It appears as though his shield dropping is tied to him killing your ruby dragon that you're riding instead of him falling from the giant when the giant dies. This isn't how it should be, but it certainly does work and make it possible. Just stay on your ruby dragon instead of dismounting like you're supposed to - let him attack you until your dragon dies then kill him.
