### ISSUE TITLE
[Quest] Hints of a New Plague?

### ISSUE THREAD

**Issue by shanorr** [WoWManiaUK/Redemption#2525]
This is not a new issue but since the other person that had the same problem was never helped and the issue was closed I am forced to start a new issue. 

This quest is not working. You can not talk to npc, Kinelory as directed in the quest.

To get the problem to reproduce you must have the quest just before this one to kill the courier.
![2018-06-08](https://user-images.githubusercontent.com/29113579/41188284-e94895dc-6b6f-11e8-8333-a33816972d93.png)

Please see also the closed issue for this same problem.

**Comment by fvicaria** [comment]
Please follow the procedure described below before creating a new issue:
[How to Properly Report an Issue](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue)

This will help developers identify and fix the issue quicker. Incorrectly or unclear reports will simply be deleted.

**Comment by WhitephoenixTheBunny** [comment]
NPC Kinelory: http://www.wow-mania.com/armory/?npc=2713
Quest: http://www.wow-mania.com/armory/?quest=657
Start of Chain quest: http://www.wow-mania.com/armory/?quest=659

**Comment by shanorr** [comment]
I di read those before I made a new issue??? Did I do something wrong?

**Comment by WhitephoenixTheBunny** [comment]
To be easier to tester check issues, you need give links, like the ones i posted. Issues not proprelly reported can be closed

**Comment by shanorr** [comment]
I see. Just thought this was already in the other report. Ty for explaining.

**Comment by WhitephoenixTheBunny** [comment]
If i confirmed the bug, i dont know why u are closing it

**Comment by TheManiax** [comment]
@shanorr 
1- The report title (quest name) is wrong.
2- There are like 6 quest with the name [Hints of a New Plague?], we don't know which one you mean unless you give the link.
3- Referring to a previous report? link the previous report.
So nice of @WhitephoenixTheBunny  to go through internet to realize what you really mean, while your report is really lacking proper info
Now the report is confirmed, it means you are right and the bug is there, you don't need to close the report
You can leave the rest to Developers, they will do as needed
I will re-open the report.
