### ISSUE TITLE
[Hunter Pet Ability] Swipe

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#2532]
Swipe:
[http://www.wow-mania.com/armory?spell=53533](url)

**How it should work:**
Swipe should do the damage it is stated in the tooltip when it goes on cooldown. Which scales with the level of the ability.

**How it works:**
Swipe is doing always between 1 and 8 damage despite being level 1 or level 5. At level 69 the skill is not even registering on the combat log nor doing damage despite going on cooldown.

What you need to fix is the scaling of the ability cause i think it is doing its level 1 damage always which can go from 6 to 8 dmg.

![wowscrnshot_061218_103522](https://user-images.githubusercontent.com/40045543/41300925-8a29ba30-6e2c-11e8-9cf1-cea31c57bb9a.jpg)

**Comment by Dranah** [comment]
It's even worse than that. Looks like base damage is okay but the AP coefficient is negative...

Swipe base damage is 42-58 at lvl 80 just like on the screenshot above, which comes down to 23-26 damage after armor mitigation and the pet having a penalty for being unhappy because I can't bother to feed him while testing. (sorry PETA)
It does that damage properly so long as the hunter has NO gear equipped at all.

However.... Equipping one piece of gear that adds roughly 300 attack power resulted in the damage going down to 7-14 per hit, a second piece resulting in being about the 1-8 damage, and a 3rd piece of gear literally annulled its damage effect. "Bear casts swipe" shows up on combat log but there is no damage paired to it anymore. No other condition has changed between the tests.

**Comment by crulinjr** [comment]
Still not fixed. What i do to try it out is disabling every ability but
Swipe. My pet will only auto attack and cast Swipe when available. Swipe
goes on cd but still doesnt do damage (no yellow number which describes the
use of an special ability). It wont appear on the combat log unless the
ability is dodge or parried. However it does consume focus.

2018-06-18 8:26 GMT-05:00 Keader <notifications@github.com>:

**Comment by Keader** [comment]
Yeah i got weird results now too
Still looking it.

**Comment by crulinjr** [comment]
if it is the ap coefficient cant you just "buff" the ability? or how is it
coded? maybe i can help

2018-06-18 9:23 GMT-05:00 Keader <notifications@github.com>:

**Comment by Dranah** [comment]
crulin are you testing on the PTR?

**Comment by crulinjr** [comment]
no i tested it on live. Should i try to test on the PTR? if so, how do i
access the PTR?


2018-06-18 13:41 GMT-05:00 Dranah <notifications@github.com>:

**Comment by Dranah** [comment]
Well i just tested it and it's definitely not working properly yet.
Anyone can access the PTR by choosing "test server" tab on the realm selection, and select "Frostmourne".
However, only people in our tester and dev team have GM commands, other people start with scratch at lvl 1. If you don't want to test that way, you have to leave it to us to confirm the fixes.

**Comment by crulinjr** [comment]
i wouldnt mind leveling a hunter in the PTR if the exp would be x10.  If
thats not possible ill wait for you to test it out and confirm the fix.

2018-06-18 14:05 GMT-05:00 Dranah <notifications@github.com>:

**Comment by crulinjr** [comment]
how is the fixing coming up? still nothing? if i can help pls dont hesitate
to tell me, ill do what i can.

2018-06-18 14:13 GMT-05:00 Bgil20 <alvaro.vigil90@gmail.com>:

**Comment by Keader** [comment]
Yeah, now is fixed (in ptr)
I just need remove the comments

**Comment by Dranah** [comment]
Looks correct now. + 300 AP on the hunter now raises the swipe damage from 25-26 to 95-100, instead of reducing it to zero.

**Comment by crulinjr** [comment]
Nice! Thank you so much for trying so hard to fix It. Should i try it on
live now?

**Comment by Dranah** [comment]
not until this thread is closed, means janitor didnt implement it to Red yet
