### ISSUE TITLE
[Spell] Distract

### ISSUE THREAD

**Issue by lemonlimes** [WoWManiaUK/Redemption#2533]
I've seen previous topics about this bug a while ago too, but the same issue seems to have arisen. When i use the skill 'Distract', enemies don't turn towards the centre of the green circle about 90% of the time, they  just totally ignore the skill altogether. Only about the other 10% of the time does it work correctly.

**Comment by Dranah** [comment]
Spell ID 1725
Must note that the target of the spell must be out-of-combat for the effect to work.

Problem seems to be mostly with mobs that patrol. Using distract on them results in the first cast simply stopping their movement scheme, and only the 2nd cast turning them (and a regular player cannot cast twice due to the 30sec cooldown on the spell)

The spell seems to turn players and static mobs correctly.

**Comment by Dranah** [comment]
Mobs that patrol will now properly be turned by Distract.
