### ISSUE TITLE
[Quest] Torch Catching

### ISSUE THREAD

**Issue by mephorash** [WoWManiaUK/Redemption#2550]
http://www.wow-mania.com/armory/?quest=11923

Players should be able to use the quest item Unlit Torches(http://www.wow-mania.com/armory/?item=34833) to throw a torch into the air and catch it, which rethrows the torch into the air, consecutively for 4 times to complete the quest.
Currently the quest item Unlit Torches casts an ability called Fling torch (which i could not find on armory) which does nothing, so the quest is not doable.

**Comment by fvicaria** [comment]
Pretty sure both of them work. But we will check.

**Comment by WhitephoenixTheBunny** [comment]
Re-opening the issue. After last resart those quests: Torch Tossing and Torch Catching (alliance start at: http://www.wow-mania.com/armory/?quest=11731, horde start at: http://www.wow-mania.com/armory/?quest=11922) and respective dailies ( http://www.wow-mania.com/armory/?quest=11921 and http://www.wow-mania.com/armory/?quest=11924) are not working proprelly.

I saw more ppl complaining about the same, and since it's the last day, a lot of ppl cannot finish the achievments and makes #2553 also broken.

**Comment by wow-mania** [comment]
Please re-test on dev. I have reapplied the fix.

**Comment by WhitephoenixTheBunny** [comment]
In Dev working, not in Red :/

**Comment by wow-mania** [comment]
Cool, I will re-apply to Redemption tomorrow.

**Comment by TheManiax** [comment]
@wow-mania Please extend the event for at least one more day. It finishes today, so applying it tomorrow can only effect next year if you don't extend it.
