### ISSUE TITLE
[Achievement] City Defender

### ISSUE THREAD

**Issue by NightSeekerr** [WoWManiaUK/Redemption#2571]
Achievement "City Defender" (http://wow-mania.com/armory/?achievement=388) is not working. It requires you to kill 50 enemy players in any of your home cities. I am at 36/50, I kill a Horde in Darnassus and I'm still at 36/50. I delete my cache and the problem persists. Same thing with the Horde guy that killed me in Orgrimmar, the kill doesn't count for his achievement.

**Comment by squalllh1989** [comment]
Confirmed, the Achievement doesn't count atm.

**Comment by wow-mania** [comment]
What exactly is the issue the tracking of the kills or the actual Achievement being given?

**Comment by Dranah** [comment]
I have to reopen this because its probably a side effect of previous fix.
The achievement works now, but also counts credit if you kill a regular mob (non player) that grants experience , inside the city.
Though mobs are scarce inside capitals, there are several class quests that spawn creatures inside the town which grant experience, and therefore credit for this achievement too. (warlock summon quests, some elementals for mages, etc)

**Comment by Dranah** [comment]
Works as intended now.
