### ISSUE TITLE
It's All Fun and Games (A)

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#2602]
Hello dear GMs and developers,
I am sorry, but I have to bring your attention once again to this quest: http://www.wowhead.com/quest=12887/its-all-fun-and-games.
Before we start, YES I use your launcher, YES I am on the right spot.
So the problem is that Eyesore Blaster http://www.wowhead.com/item=41265/eyesore-blaster does not damage the Ocular http://www.wowhead.com/npc=29747/the-ocular . Also the Oculaar does not attack me, no matter in what position to it I am.
With regards and best wishes,
Greywolf59; ingame Geshoia

**Comment by Dranah** [comment]
The quest works:
https://www.youtube.com/watch?v=wapShCx1NSs&feature=youtu.be
Recorded 5minutes ago

**Comment by Greywolf59** [comment]
Hello again, thank you, I will ask a GM, but before that. one thing to pinpoint: Your Eyesore Blaster does channel although for one second. My channels for about 0.1s and then it ends. And charackter itself. I do not know, never had any issue till now, not that I would play here for a long time.
Thanks for your fast response and advice.

**Comment by Dranah** [comment]
@Greywolf59 As you can see, we have some testers - like myself - who check out these reports. We don't just say out of our ass that the quest works, we say it because we test it if a concern arises. If we find it works for us, and does not work for you, then the problem is with your character, not the quest itself. 

Character-specific problems can arise with ANY quest, enemy or objective , not only this one. The reason this quest receives so many false reports is simply that every melee-dps is forced to complete it for their head enchant, and some of those don't even have the capacity to understand the quest objective. Warriors don't wear intellect for a reason - they don't want their clothes to be smarter than they are.

Your case does sound different, but as it is character-specific, only a GM can help you. They tend to shoo players off to report bugs here, so make sure you explain them that it affects YOU alone. Github is made only for fixing general bugs that origin from server script and affect every player.

Hope your problem gets solved!

**Comment by Greywolf59** [comment]
Id did, my thanks belong to whole team. I would like to apologise if my writing seemed harsh. You are doing a great work here on Mania. Keep it up and thank you again!
