### ISSUE TITLE
lmp attack damage

### ISSUE THREAD

**Issue by thenegativehunter** [WoWManiaUK/Redemption#2633]
i started leveling up a warlock.
lmp attack damage is too high. like 4 times of it's fireball. you have an awesome core, but a meh database
voidwalker also seems to be too high. i mean the attack damage itself is still higher that my own shadowbolt.

**Comment by Dranah** [comment]
This has been broken recently. I dont know if someone is tweaking the pet damages, but definitely wasnt like this before.

**Comment by thenegativehunter** [comment]
well make sure to check this for other pets too. i mean i didn't play blizzard to know how much damage other pets had but it's seems too high.

**Comment by Dranah** [comment]
Voidwalker shows same behavior with a +2,3 DPS being added per lvl regardless of other stats

**Comment by Keader** [comment]
@fvicaria any idea here?

**Comment by wow-mania** [comment]
Nothing has changed and this for a very long time. It has been corrected in the past.

**Comment by Dranah** [comment]
Update:
After testing pets at lvl 80 too, it can be said that this increased melee dmg is fairly closer to proper pet damage of 3.3.5 for melee pets than what we had before.
So i suggest instead of removing this effect overall, simply correct low level damage scaling (this state pretty much makes pets op lvl 1-60 because the dmg growth is not supposed to be linear. At those low lvl brackets, the damage is supposed to grow slower)

Example for scaling:
Right now a pet gains, roughly +2,5 dps when he levels up, both when he is lvl 5, when he is lvl 50 or lvl 78. Obviously at lvl 5 this amount of increase is OP, even at lvl 30 it is fairly imbalanced. But in total it is ~ 200 melee DPS added up over 80 levels. To this comes what he gets from player stats, resulting a more or less healthy melee damage at lvl 80.

To match intended values, a lvl 1-10 pet should only receive 0,5 DPS upon lvlup, 10-20 about 1 DPS , 20-30 around 2 DPS, and so on. At lvl 50 should receive ~ 3 DPS, 60-70 around 4 and in the lvl 70-80 bracket easily 5 dps per lvl up. This is just an example. Basically divide the same +200 dps over 80 levels  , but in a way so that low lvls gain dps slower, higher levels faster.

**Comment by thenegativehunter** [comment]
but how is that going to be implemented in the code? i mean just writing a bulk of code and adding it shouldn't be the best option. a hidden buff/passive is better.

**Comment by Dranah** [comment]
i dont know a thing about how this is coded, only what is happening in game atm. im a tester not a dev xD
i merely suggest that this change isnt fully reverted, because at lvl 80 it doesnt do bad to melee pets behavior

**Comment by Dranah** [comment]
imp damage has been fixed
other pets are under tweak
