### ISSUE TITLE
Kaw is missing

### ISSUE THREAD

**Issue by ggosse52** [WoWManiaUK/Redemption#2638]
The target of the quest "Kaw; the mammoth destroyer" is missing
he is supposed to be on his mammoth "Moria"
Ive checked many times, waited for him to spawn. Checked onmore than one character.
Nope, he seems to be on vacation

**Comment by Dranah** [comment]
He is spawned separately on the wooden platform, not mounted on the mammoth. 
Moria needs to be killed first to make him attackable, as well. 
It is possible that the unattackable kaw is spawned, but moria isnt - this happens when someone kills moria and then wipes on Kaw. You need to wait for the mammoth to respawn , kill it, and then kill kaw. It takes well around 10minutes so its likely you've been unlucky.

**Comment by ggosse52** [comment]
Ok. Thanks for that
I'll look for him on the platform
