### ISSUE TITLE
[Quest] Amped for Revolt

### ISSUE THREAD

**Issue by GM-Gathios** [WoWManiaUK/Redemption#2664]
http://wow-mania.com/armory/?quest=13374

For this quest you'll need to man a bomber and shoot at targets.

None of the targets can be hit. The turrent can be aimed and be shot, but none of the missles impact.

**Comment by wow-mania** [comment]
Pretty sure it works.

**Comment by TheManiax** [comment]
There is a small issue, though the quest can be done with a work-around.
Spell [[Anti-Air Rocket]](https://www.wowhead.com/spell=59622/anti-air-rocket) 
If you try to **aim** at an enemy in the air, you can never hit it. the rocket will not hit any target in the air this way.
But if you **target** the enemy in the air by clicking on it and choosing it as your target, then use  [[Anti-Air Rocket]](https://www.wowhead.com/spell=59622/anti-air-rocket) , there will be 2  rocket fired instead of one.
One rocket will hit the enemy which you have chosen as your target by clicking on it (and any other target within 10 yard of it) , the other rocket will go to where you are aiming.
Overall, it's impossible to aim at any unit in the air. But doable if you target it and then shoot at it.

**Comment by wow-mania** [comment]
That is as-is. This is the best we could do on previous fixes.
