### ISSUE TITLE
[Quest] Foolish Endeavours

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Redemption#2678]
Quest 11705

https://www.wowhead.com/quest=11705/foolish-endeavors

How it should work:

  You confront the NPC, Garrosh Hellscream appears, and you kill Variden the Flenser with his help.

How it's currently working:

Working as intended up to a point. Around 20%, the event despawns abruptly without giving completion.

**Comment by TheManiax** [comment]
It doesn't happen all the time @TenmanWoW .
Do you know how exactly to reproduce this?
I know it sometimes goes wrong, but what's the conditions to bug it?

**Comment by Dranah** [comment]
Not sure about it because its been a long time ago that I did this quest, but I believe this had something to do with where players are positioned. Never really had problems when I went into melee, but I recall not getting credit when I just stood at safe distance shooting at Variden. Might have been completely unrelated, but is worth a shot.
Note I am still locked out of PTR so i cannot test anything. On red all my 25 chars have already completed this.

**Comment by wow-mania** [comment]
This is a a typical case where the player does not do at least 50% of the damage.
The helper NPC is just "to help" not to do all the work.

**Comment by Dranah** [comment]
Wrong @wow-mania 
This quest does not require 50% of damage to be done by player.
It is impossible for a player to do more than 50% of boss health, because the helper NPC does way more DPS than any player at lvl 70. 
A level 70 can pull 800-900 DPS if he doesn't suck, Saurfang does 1500~ 
And note this is NOT a group quest, a player must be able to complete it alone, even if he levels as Resto spec, which does maybe 200-300 dps. So its completely normal that Saurfang does all the damage. 

Some facts:
Wowhead comments say even if you die on the pull to the adds and then just watch, you still get credit after Saurfang solos him.
After testing on PTR, it appears that the event despawns 100seconds after engage, regardless of how much damage you had done (but obviously, with higher damage the boss dies sooner than 100sec)
This is an unintended feature.

Some theories:
Might have something to do with Shadowstalker Getry not joining the combat as intended, on retail videos he is fighting alongside you, and based on retail comments, the only means to fail this quest is when Shadowstalker Getry dies. Because the event is linked to him somehow, if he dies or despawns, so does the event.
Now, here Shadowstalker Getry does not fight at all. He stands there, out of combat, and i suppose he resets after that fix amount of time.

**Comment by wow-mania** [comment]
I have done this many times and it works.

**Comment by Dranah** [comment]
It only bugs if 100 seconds pass after the pull. You can reproduce steadily with that.

**Comment by wow-mania** [comment]
I will search for any timers.

**Comment by wow-mania** [comment]
Should be better now. The quest however needs to have a fail time. I am forcing Getry to despawn.

**Comment by wow-mania** [comment]
Applied to Red/Ely just need restart.
