### ISSUE TITLE
[Core] Disarm

### ISSUE THREAD

**Issue by Hokapt69** [WoWManiaUK/Redemption#2681]
Good afternoon

This afternoon I was playing on your server.
and a monster made a skill the disarm and my char lost 5% of crit that never came back to win or to have the 5% of crit had to change the weapons, this happened to me near bootybay in STV with a mob barselik.

**Comment by wow-mania** [comment]
Please check the wiki on how to report an issue. This gives us absolutely no lead on how to check it.
Also if I understood correctly what you described is impossible to happen. Unless you give me screenshots and links I can't do anything about it.

**Comment by Hokapt69** [comment]
before atk
![wowscrnshot_082018_184135](https://user-images.githubusercontent.com/42549679/44357098-1d221000-a4a9-11e8-9dce-71bc8e702f80.jpg)
afther the kill
![wowscrnshot_082018_184329](https://user-images.githubusercontent.com/42549679/44357153-3460fd80-a4a9-11e8-830c-a300fe593f00.jpg)
Changing weapon to get the 5% again 

![wowscrnshot_082018_184340](https://user-images.githubusercontent.com/42549679/44357185-4a6ebe00-a4a9-11e8-8e16-a3d3f7355988.jpg)
![wowscrnshot_082018_184347](https://user-images.githubusercontent.com/42549679/44357217-56f31680-a4a9-11e8-9b72-c5c2b4fcf3d6.jpg)

**Comment by Dranah** [comment]
As unbelievable as it is, I managed to reproduce this.

Steps:
1. Take a whatever level character with high dagger skill and low Unarmed skill
(This means he will have high crit chance when using daggers, and low crit chance when being unarmed - thats just how weapon skills work)
2. Get Disarmed while attacking a mob, this basilisk (NPC ID 1550) is good for testing, he casts it very often
3. Gain a skill-up in Unarmed while you are disarmed
= your crit chance sets itself to the Unarmed level of crit chance, which is very low since you don't have Unarmed skill
4. Disarm expires and the crit chance does not set back to the dagger skill's intended crit chance until you swap weapon/ level up / gain dagger skill

Now, as far as I know, it should work like:
- While you are disarmed, you should have the low crit from Unarmed skill, if you were a lazy boon who didn't skill it up
- When disarm expires, you should regain your normal weapon skill stat and the crit chance that belongs to it.

Right now, the system is not re-checking the crit chance of skill stat until you gain a skill up or swap weapon, which means Disarmed players retain their maxed weapon skill chance from whatever weapon they are wielding until they gain a skill up in Unarmed. And when Disarm expires, they won't get back their weapon skill until they gain a skill up with their Weapon skill. (and if that is already maxed, they have to swap weapons)

**Comment by wow-mania** [comment]
Does it remain after relog?

**Comment by Dranah** [comment]
Yes it does. It requires swapping weapons, or gaining a weapon skill up to re-check values.
