### ISSUE TITLE
[Boss] Thorim - Lever exploit

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#2701]
In some situations, Lever is created after Thorim, creating a Exploit.
When it happens, it is possible use before kill adds in thorim's room.

**Comment by Bartok14** [comment]
I hate to say this but we did this boss tonight and there is another bug where a spark starts going down the hallways. This one shots anyone that is in the hallway. This is not supposed to happen, its only supposed to happen if we have no one in the arena. We had 7 people in the arena tonight and the spark still went down the hallway and caused a wipe for them.

**Comment by Keader** [comment]
With no reproduce step, i cant do nothing.

**Comment by Dranah** [comment]
@Bartok14 this issue used to exist on 10man and the trigger was touching the first mob in gauntlet on the first attempt of the ID. That was fixed.
Zarrock did mention he faced this problem on 25man recently, and i've been trying to repro but no success so far. Any extra information you can provide could be very helpful.
Note the boss has a yell emote "worthless" something like that, when he releases the Lightning Orb, which indicates when the wipe mechanism was exactly triggered. Do you perhaps remember what your raid was doing in that moment?

**Comment by squalllh1989** [comment]
about the issue of the wiping lighning ball, it still happen in 10 man recently, we figure out that: when you use the level trigger when at least 1 mob still alive, you can open the hallway, but when you go in, the wiping lighing ball will come. So people don't actually wanna exploit this bug, because if you exploit it intentionly or mistakenly, you will wipe yourself that attempt. In our last ulduar 10, our raid caller already know about this, but he doesn't see the last mob still alive and he pull the trigger, then we have the lightning ball come :)

**Comment by squalllh1989** [comment]
so basicly for the lighning wiping ball to not come wrongly, we need to fix the bug that make the trigger can be use before all add in the gauntlet died.

**Comment by Dranah** [comment]
Ahh i see... i never tried that. Hopefully now both problems are fixed then.
