### ISSUE TITLE
[Spell] Mirror Image

### ISSUE THREAD

**Issue by squalllh1989** [WoWManiaUK/Redemption#2712]
Spell: [Mirror Image](http://www.wow-mania.com/armory/?spell=55342)
How it should work: After the spell ended, all the threat of the mirror image add up together to the mage's threat.
How it work right now: (Not happen all the time, but recently happen alot) After the spell end, all the threat of the mirror image add up together to the mage's threat AND the mage suddenly get 2-3 million threat come from no where added to him, which will over aggro the tank, which should not happen.

**Comment by Dranah** [comment]
This happens if the mage is affected by a threatwipe during the mirror's duration (by boss, or using invisibility)
This problem arose when trying to fix mirror fully wiping your threat.
See https://github.com/WoWManiaUK/Redemption/issues/2349 
So we have 2 options:
- Mirror image blocking your threat for 30sec and then you start off zero
- Mirror image mostly working properly, but when there's a threatwipe during the effect, it gives you 4million threat in the end
I do agree that the first one is less troublesome, it is however less blizzlike as it will always be bugged, not just occasionally. It basically removes threat as a worry for mages overall.

**Comment by squalllh1989** [comment]
no this is not because of threatwipe, there is no suck thing in rs25hc hallion during first phase, or first lk25hc phase 1, yet his bug happen there, and i'm sure that i don't ever used invisibility there when tried to do my best dps in those moment.

**Comment by squalllh1989** [comment]
or maybe it's because the mirror image is trying to do threatwipe again like before, but it's not that because of threatwipe mechanic or invisibility that this bug happen

**Comment by Dranah** [comment]
In that case, we need reproduce steps, since as you said, it doesnt happen every time.
The only way i can reproduce this issue is with threatwipes.

**Comment by squalllh1989** [comment]
idk, having a raid right now, will gonna try it

**Comment by Dranah** [comment]
Well, what I can confirm here, which was already discussed on previous threat, is that threat modifiers during Mirror Image are bugging your aggro.
Hand of Salvation currently gives 2mil threat per second to a mage with Mirror active.
Invisibility (and any other complete threatwipe) adds 4,1mil threat.
We are looking for a solution to this.
If you can report any other source that causes such issue, feel free to do so.

**Comment by Dranah** [comment]
No change.

**Comment by Keader** [comment]
i forgot to put fixed label o.o

**Comment by Keader** [comment]
we got some improvements today, but is to a fix yet.
Will work on it tomorrow night again

**Comment by Keader** [comment]
Test now
Fixed i think.
