### ISSUE TITLE
[Mechanic] Death Knight Runes

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2722]
After blood tapping, one rune will be stuck on ready even though it's not ready, which causes crucial mistakes thinking the rune is up but the spell isn't working and therefore wasting DPS

Reproduce steps: Use the following rotation of
 Icy Touch -> Plague Strike -> Obliterate -> Blood Strike -> Blood Strike -> Empower Rune Weapon -> Obliterate -> Obliterate -> Obliterate -> Blood Tap -> Pestilience -> Blood Strike

You'll realize after you use Pestilience and attempt using Blood Strike, there's a blood rune stuck on being ready when it's still on cooldown.

**Comment by wow-mania** [comment]
Can someone reproduce this one please.

**Comment by Dranah** [comment]
Ok after I made some tests I have the following experience:

1) What Ashamed reported is a visual glitch that requires very fast key press to reproduce, like not a tester pace of rotation, but a DK trying to win DPS-race pace of pressing keys (destroy the keyboard):
Blood tap has a half-second-ish delay on refreshing rune status visual when used, you can see it sparkles up every rune for a moment (not sure why, when it only affects one rune)
The point is if you spam keys very fast and consume a Blood Rune very quickly after Blood tapping, it will show no change in rune status even though your Blood Strike did go off and consumed a blood rune that was just reset by Blood tap but you did not see it reset because you consumed it too fast. This means you will see a Blood rune coming off cooldown, but it actually isn't because it was already reset, used and back on a longer cooldown, but since the visual status didn't update when tapping, it just shows you finishing the original cooldown it had and then showing ready even though it isn't.

2) Having both your blood runes converted to death runes leads to Blood tap failing. 
This is produced by a frost or unholy DK who is specced into his Blood strike and pestilence converting Blood runes to death runes when used. 
How the talent should work is "whenever you hit with blood strike or pestilence, there is a 100% chance that the blood rune becomes a death rune when it **activates**"
And if you use blood tap before the cooldown finishes, it should activate one of those runes as a death rune immediately.
How the talent actually works is that as soon as the rune is **depleted** by blood strike or pesti, it is converted to death rune while it's waiting to recharge. This leads to blood tap not doing anything when used, because it cannot find a target "blood rune"
Reproduce steps:
Blood of the North or Reaping talented +
Blood strike > Blood strike > Blood tap > no active blood rune

3) Having one of your Blood Runes active as a death rune and the other Blood rune recharging as a blood rune, Blood Tap fails to reset the recharging Blood Rune.
Steps to repro:
Have Blood of the North or Reaping +
Blood strike > wait 10sec (at this point you have 1 ready blood rune and 1 ready death rune > blood strike > wait 5sec > blood strike (at this point you have 1 recharging blood rune and 1 ready death rune> blood tap > the blood rune wasn't reset.

**Comment by Keader** [comment]
It's a desync problem, it exist in TC since always
We have no idea how fix it o.o
