### ISSUE TITLE
[Spell] Corruption

### ISSUE THREAD

**Issue by Braytonx** [WoWManiaUK/Redemption#2748]
After the recent fix of warlocks I joined my guilds 25 heroic and instantly noticed my dmg output has pretty much been halved wich seemed way to much for it only affecting my corruption. So I went to test something myself and found a couple talents on wich the math don't seem right.

Empowered corruption (32383) this talent is increasing your corruption dmg by 36% of your Spell power.
In my test I had a base SP of 3149 (removed all items that could proc anything). 
Corruption dmg before getting Empowered corruption: 889 (with improved corruption)
Corruption dmg after getting rank 3 Empowered corruption: 1097 (208 dmg increase) 

36% of 3149 = 1133,64
Corruption dmg should be: 889+1133,64 =2022.64

After learning Siphon Life (63108) my corruption dmg became: 1147
1097x1.05= 1151,85
Here is missing another 4,85 dmg.

After learning Shadow Mastery (18275) my corruption dmg became: 1297
1147x1,15= 1319,05
Here is missing 22 dmg.

After learning Contagion (30064) my corruption dmg became: 1347
1297x1.05= 1361.85
Here is missing 14 dmg.

Since these changes the damage of affliction warlocks has been lowered so much that they are pretty much not viable to take to a raid since any other spec that is in a raid to just do pure dmg does way more. If I was leading raids atm I wouldn't take affliction locks to 25 man Heroics cuz of their low dmg.

**Comment by Dranah** [comment]
Empowered Corruption's 36% increase applies to the entire corruption spell, therefore 6% per tick.
(In contrary to Everlasting Affliction which applies the 5% bonus per-tick)
6% of your 3149 spell power is 188 damage, this extra damage is increased by Improved Corruption to 208 bonus damage.

Improved Corruption, Siphon Life, Shadow Mastery and Contagion have a problem with their bonuses stacking additive instead of multiplicative, that's why you have a tiny portion of damage missing. They should grant a total of 1,10x1,05x1,15x1,05 = 39,46% bonus , however they only add 35% atm.
This problem is already reported in another thread, and is waiting for a core fix.

**Comment by Dranah** [comment]
https://github.com/WoWManiaUK/Redemption/issues/2738

**Comment by Aristo14** [comment]
Thats what i was thinking but still there seems to be something wrong after the fix of sp rolling. 

the #2738 was allready an issue before the fix so it cant account for this much decrease in dmg right? 

Im not a warlock so cant test things or claim to know in dept about them, just think there is something to be figured out.

**Comment by Dranah** [comment]
It isn't only the SP rolling which got fixed, there was a core fix on DOTs double dipping talent boosts.
Before fixes, talents like Improved Corruption applied twice to the spell.
Once to the SP bonus they received by coefficient, and then again to the total damage of the spell.

#2738 indeed existed since forever, but wasn't possible to notice with every other bug making the spell so OP.

**Comment by Braytonx** [comment]
Yeah I knew the damage of affliction warlock would be lower but this is just extremely low. So low the spec isn't even viable anymore while affli is supposed to be the strongest warlock spec.

**Comment by Dranah** [comment]
All I know about this "strongest warlock spec" debate is that on simcrafts (a computer simulation modelling a tank and spank fight with an ideal player in ideal gear, ideal buffing and whatnot) affliction scores something like 200 dps above destro and around 300 above demo. 
So the difference is marginal and therefore depends a lot on individual gameplay.

Since further investigation was requested, I decided to look through some logs from 2010 on http://www.worldoflogs.com and analyze warlock dps in ICC, and i've yet to find a parse where affliction is performing any special.

What the logs show is that while ICC was in progression state (2010 spring and early summer), decent raids use mainly demo locks for their buff and sometimes destro for their burst and aoe stun. It's extremely rare to find any afflocks on these logs at all, as it was simply not viable before the high haste levels provided by near-BIS icc gear. 

Parses from end summer, 2010 aug/sept when people were already top geared, have more afflocks employed, understandably. This is closest to the current situation on mania. You can still hardly find an average warlock pulling above 14k as affliction (much more common as demo), and for most of the time they are around the 8th-10th spot on meter, behind warriors, rogues, mages, hunters, and ferals.

The best affliction performance I could find is a Method raid speedkilling 25hc bosses, where the near-bis afflock pulls around 16-17k on bosses, which is only enough for the 8-10th spot on the meter. 
The demo lock is usually above him, except for Festergut, where he is 160 dps above the Demo. 

I'd emphasize, this is a Method raid in high end gear killing bosses insanely quick roughly 3 weeks before cata prepatch, and in almost every fight the top dps source of the afflock is Shadow bolt.
Taken from Festergut -
Average Shadow bolt hit: 10,1k
Average Corruption non crit tick: 5,1k
This is the highest afflock damage I have found so far on the ICC parses from before 2010 october when the cata pre-patch hit.

I've made a test in WoWmania now after the fixes:
Tester char is a near-bis warlock (using a staff which is suboptimal), no profession bonuses, with some raid buffing (but using totem of wrath instead of a well-geared demo lock's buff, which is also a DPS loss) produces an average 5,3k corruption tick damage over a 2minute steady rotation, given that you are rolling your t10 proc as you should. 
Result
Average Shadow bolt hit: 10,4k
Average Corruption noncrit tick: 5,3k

The numbers match...
