### ISSUE TITLE
[Spell] Ranged Weapon Specialization

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Redemption#2765]
ID 19507

This hunter talent should increase all ranged damage dealt by the hunter by 5%. This includes auto shots and all special attacks that require a ranged weapon. (does not include traps and pet dmg)

How it works atm: 
Does not affect half the spells it should.

**Test before talent**
Auto shot: Hit 743-762 / Crit 1486-1522
Steady shot: Hit 734 -747 / Crit 1683-1718
Aimed Shot: Hit 1233-1250 / Crit 2838-2875
Chimera: Hit 1197-1221 / Crit 2755-2808
Arcane shot: Hit 1210 / Crit 2783
Multi Shot: 1234-1250 / Crit 2835-2875
Volley: Hit 666 / Crit 1531
Serpent Sting: 508/tick

**Test with talent**
Auto shot: Hit 743-759 / Crit 1486 - 1522 = NO CHANGE
Steady shot: Hit 767-782 / Crit 1764-1795 = increased properly
Aimed shot: Hit 1233-1250 / Crit 2840-2870 = NO CHANGE
Chimera: Hit 1197-1221 / Crit 2753-2808 = NO CHANGE
Arcane shot: Hit 1271 / Crit 2923 = increased properly
Multi shot: hit 1234 -1250 / Crit 2840-2870 = NO CHANGE
Volley: Hit 666/ Crit 1531 = NO CHANGE
SS: 533/ tick = increased properly

Needless to say i'm testing without procs and other talents or effects that could possibly affect my dmg.

**Comment by GMWeeble** [comment]
When you make reports can you also include the armory post of the spell so we can find it easy.

**Comment by Dranah** [comment]
I did include the ID of the talent, as I always do.
Or did you mean the spells i've tested with? Ah well here it goes.
Auto shot - ID 75
Arcane Shot - ID 49045
Chimera shot - ID 53209
Aimed Shot - ID 49050
Multi shot - ID 49048
Serpent Sting - ID 49001
Steady shot - 49052
Volley - 58434

**Comment by GMWeeble** [comment]
No I mean with the spell ID link from the armory.

**Comment by Dranah** [comment]
I do not trust mania's armory, it's full of errors and wowhead is outdated past 5 expansions. That's why I only use ID numbers taken from in-game, instead of links.
But here it is, anyway:
http://www.wow-mania.com/armory/?spell=19507
http://www.wow-mania.com/armory/?spell=19508
http://www.wow-mania.com/armory/?spell=19509

**Comment by GMWeeble** [comment]
Yes, but its is not only about what the armory's info is, it is also that we know what spell where it is from etc.

**Comment by Thrashattack** [comment]
Char: 
 - Troll Hunter 
 - Level 80
 - No items except bow, axe and arrows level 1
 (http://www.wow-mania.com/armory/?item=12282, http://www.wow-mania.com/armory/?item=2504, http://www.wow-mania.com/armory/?item=2512)

 - No pet
 - No Auras or buffs 

Talents:
 - Focused Aim x3
 - Lethal Shots x5 
 - Mortal Shots x5 
 - Aimed Shot x1 
 - Careful Aim x3 
 - Go For The Throath x1 
 - Rapid Killing x2 
 - Efficiency x5 
 - Concussive Barrage x2 
 - Readiness x1 
 - #### Ranged Weapon Specialization x0  (Game ID 19509) 


Target: 
 - Expert's Training Dummy (Level 60 - Mechanical) 

Tested Spells:
      
Auto Shot : 62 - 66 (Max crit : 130)
Aimed Shot : 79 - 83 (Max crit : none)
Chimera Shot 
Multi Shot : 401 - 405(target 2) 401 - 405(target 1) 404 - 405(target 3)
Volley : 388

### After 3 Points in Ranged Weapon Specialization

Auto Shot : 62 - 66 (Max crit : 130)
Aimed Shot : 79 - 83 (Max crit : none)
Chimera Shot - -
Multi Shot : 401 - 405(target 2) 401 - 405(target 1) 404 - 405(target 3)
Volley : 388

After tests i could confirm the issue.
I belive i don't need to test chimera shot,
since it is related to a single talent.

**Comment by crulinjr** [comment]
any update on this one?

**Comment by Dranah** [comment]
No work has been done on this yet by the devs. There are currently many threads open and this is lower priority I guess. Be sure we'll post if there is anything.

**Comment by Keader** [comment]
Test now

**Comment by Dranah** [comment]
UPDATE:
- All abilities are properly boosted now, except Volley. Details below:
Note: may it have something to do with the fact Volley is not considered a ranged attack (as per the aspect of viper issue)? I do not think this is intended.

**Test before talent**
Auto shot: Hit 657-673 / Crit 1314-1346
Steady shot: Hit 659-674 / Crit 1520-1543
Aimed Shot: Hit 1105-1121 / Crit 2541-2576
Chimera: Hit 1137-1161 / Crit 2617-2668
Arcane shot: Hit 1017 / Crit 2339
Multi Shot: 1105-1121 / Crit 2541-2578
Volley: Hit 646 / Crit 1485
Serpent Sting: 382/tick

**Test with talent**
Auto shot: Hit 691-706 / Crit 1384-1406 = Increased properly
Steady shot: Hit 697-703 / Crit 1591-1598 = increased properly
Aimed shot: Hit 1162-1178 / Crit 2670-2709 = increased properly
Chimera: Hit 1195-1220 / Crit 2748-2801 = increased properly
Arcane shot: Hit 1067 / Crit 2454 = increased properly
Multi shot: hit 1161-1178 / Crit 2670-2704 = Increased properly
Volley: Hit 646/ Crit 1485 = NO CHANGE
SS: 401/ tick = increased properly

**Comment by Dranah** [comment]
As-is, then
