### ISSUE TITLE
Mall vendor "Penny Maniac" selling wrong hunter set

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#2772]
So the tier 8 vendor is selling the Conqueror Scourgestalker Battlegear; however, when you buy it even though the name is correct, the gear that you get is actually the Valorous Scourgestalker Battlegear.

If you compare the icon from the gear (ill add screeshots comparing these icons) the Conqueror helmet from the MALL  vendor is different from the Conqueror Helmet you can buy on Dalaran. 

Also, if you check on the internet for Conqueror Scourgestalker Battlegear you get the BLUE color gear. But the one you buy from the MALL vendor is a RED colour gear which indicates its the Valorous one.

Ill link to wowhead: https://www.wowhead.com/item-set=-87/conquerors-scourgestalker-battlegear

Comparing the 2 Icons:

![wowscrnshot_100218_082415](https://user-images.githubusercontent.com/40045543/46360042-341f5a80-c630-11e8-84b1-87eefca54287.jpg)

So in the end if nothing will change i please want the full refund of my MP please.

**Comment by TenmanWoW** [comment]
Hello! I looked into this and below is what i found.

http://www.wow-mania.com/armory/?item=46274   (Conqueror's Headpeice)


Ingame vendor in question (After purchasing)
![wowscrnshot_100218_121711](https://user-images.githubusercontent.com/25806987/46365253-b82c0f00-c63d-11e8-8fc3-813e1cb938f8.jpg)
![wowscrnshot_100218_121705](https://user-images.githubusercontent.com/25806987/46365255-b82c0f00-c63d-11e8-9c70-43638a7f30b8.jpg)

**Comment by TenmanWoW** [comment]
This is a graphical issue. The icon of the T8 item bought in the mall is that of the Valorous set. The T8 helm sold in Dalaran has the exact same stats and set bonuses as the one one sold in the mall.


![wowscrnshot_100218_122643](https://user-images.githubusercontent.com/25806987/46365541-849db480-c63e-11e8-8118-4d3de9e31084.jpg)
![wowscrnshot_100218_122640](https://user-images.githubusercontent.com/25806987/46365542-849db480-c63e-11e8-9c11-4008829a03f2.jpg)

**Comment by crulinjr** [comment]
You actually buy the Valorous set because if you try the parts you buy at
the mall, they are RED. The Conqueror is BLUE.

**Comment by TenmanWoW** [comment]
I am confused by what you mean by "red gear".

**Comment by WhitephoenixTheBunny** [comment]
I think he means visual, I am right?

**Comment by crulinjr** [comment]
Yes visually. I see red but others can see it as purple. So the conqueror
set is not red/purple but blue

**Comment by TenmanWoW** [comment]
Okay, its visual issue. Good catch.

**Comment by crulinjr** [comment]
hehe ty but i already bought my parts what can i do?

**Comment by wow-mania** [comment]
As I said if it is color only, it is not an error. We don't specify color only the set. All textures are a possible choice. We don't yet write psychic software to know which color the player wants.
If you are not happy open a ticket and ask nicely to the GM that replies as he/she will be doing you a FAVOUR.

**Comment by crulinjr** [comment]
Actually every set has a specific colour. The model is the same but the
colour changes depending on the set you are wearing. You have a black
colour model that comes from non tier parts which drop from trash and
bosses, then you have the red model which is the Valorous set and then you
have the blue model which is the Conqueror set. So if the Mall vendor
offers the Conqueror set you should be getting the the blue model set. This
is important because that set comes from 25 ulduar, a hard to gather people
to come raid. Its more about getting what you bought. And having to put a
ticket every time is more troublesome forma both the GMs and forma the
player.

**Comment by wow-mania** [comment]
Again, the set is wotlk, and no change was done so what you said is wrong.  There is no official set color, only the one used to display it on a particular website.
Every single item available on 3.3.5a is here so feel free to collect the ids and tell us which one is the "right" one for you.

**Comment by crulinjr** [comment]
I have provided a lot of proof to say that im not wrong. If that would be
the case by searching for the Conqueror Scourgestalker Battlegear on the
Internet i would be getting as a result the red/purple model and not the
blue one. Other devs have already said im right.

It is an error that you may or may not want to fix, however It is indeed an
error. The icons are not the right ones and the visual colour of the set
that is offered is not the correct one. You are providing a great service
and im just trying to help.  Conqueror set is visually blue so there is no
other day around this. I will talk to an ingame GM to help me out cause i
love that set.

**Comment by wow-mania** [comment]
You provided nothing mate.  Anyways I am done talking here.

**Comment by crulinjr** [comment]
I provided links and screenshots. I can do It again if you want.

**Comment by TheManiax** [comment]
@wow-mania 
There are 2 set of items with the same name, I give example of one of the items

1. [[Conqueror's Scourgestalker Headpiece]](http://wow-mania.com/armory/?item=46274) Being sold by Penny Maniac in Mall
2. [[Conqueror's Scourgestalker Headpiece]](http://wow-mania.com/armory/?item=46143) being sold by [Bragund Brightlink <Mail Armor Merchant>](http://wow-mania.com/armory/?npc=29523)

There is no way for the player to see if Penny Maniac is selling the first type(red) or the second type(blue)- Cause it only shows the itemset name, no ID, no item preview.
So that's what may make a player unhappy, Because he was expecting to receive the second type, but he got the first type instead.
It's not a bug, it's just lack of data being shown on the vendor NPC, which can make players expect something other than what they are buying.

----

As the first type is for 10man raid, and second type is for 25man raid, I suggest to change the NPC's dialogue from
`Hunter - Conqueror Scourgestalker Battlegear (DPS) (200MP)`
to
`Hunter - Conqueror Scourgestalker Battlegear (10 man) (DPS) (200MP)`

**Comment by crulinjr** [comment]
The ulduar raid has not changed sine retail and if you look in wowhead for
the tier 8 10 normal you will get the valorous scourgestalker battlegear.
You should decide which of the two you want to sell and name it
accordingly. If you want to sell the 10 man gear named it valorous and sell
the red model one if you want to sell the conqueror named it conqueror and
sell the blue model

**Comment by Dranah** [comment]
Ok so, not only the vendor is displaying wrong but also mania's website.

The item set "Conqueror's Scourgestalker Battlegear" exists in game as the ulduar 25 tier set and has the following item IDs (based on wowhead: 46143, 46142, 46141, 46144 and 46145)
This item set is blue, period. It's been blue since 2009.

Now, there was another item set added on patch 4.0 cataclysm which responds to the "Scourgestalker Battlegear" name on wowhead, and has item IDs 46274, 46273, 46275,46276 and 46277.
These are the item IDs currently sold by Penny Maniac.
I think it's safe to assume that it's not intended, as this set never existed on wrath 3.3.5 and no longer exists in game on live either, it is obsolete. 
(On cataclysm, it probably served as a recolor transmog)
For whatever reason, this set item IDs have same item names on mania's website database as the ulduar ones, which leads to confusions.
So I'd say players rightfully ask why Penny Maniacs selling a cata-transmog recolor version of the set, instead of the original one.

As it is a custom feature, as Crulin says, you have the right to leave it as-is however it makes no sense.

**Comment by TheManiax** [comment]
**How it works:**
Penny Maniac is currently selling these 5 items as Tier 8:
1. [[Conqueror's Scourgestalker Handguards]](http://www.wow-mania.com/armory/?item=46273)
2. [[Conqueror's Scourgestalker Headpiece]](http://www.wow-mania.com/armory/?item=46274)
3. [[Conqueror's Scourgestalker Legguards]](http://www.wow-mania.com/armory/?item=46275)
4. [[Conqueror's Scourgestalker Spaulders]](http://www.wow-mania.com/armory/?item=46276)
5. [[Conqueror's Scourgestalker Tunic]](http://www.wow-mania.com/armory/?item=46277)

These are not even Wotlk items, they are added in patch 4.0.1.13131 -> [Proof](https://www.wowhead.com/item=46274/scourgestalker-headpiece)

**How it should work:**
Penny Maniac should sell these 5 items as Tier 8:
[[Conqueror's Scourgestalker Tunic]](http://wow-mania.com/armory/?item=46141)
[[Conqueror's Scourgestalker Handguards]](http://wow-mania.com/armory/?item=46142)
[[Conqueror's Scourgestalker Headpiece]](http://wow-mania.com/armory/?item=46143)
[[Conqueror's Scourgestalker Legguards]](http://wow-mania.com/armory/?item=46144)
[[Conqueror's Scourgestalker Spaulders]](http://wow-mania.com/armory/?item=46145)

-----
@crulinjr  equip your current Tier 8 and ask a GM in-game to read this post and do as follow:
```
.additem 46273 -1
.additem 46274 -1
.additem 46275 -1
.additem 46276 -1
.additem 46277 -1
.additem 46141
.additem 46142
.additem 46143
.additem 46144
.additem 46145
```

**Comment by TheManiax** [comment]
LoL @Dranah , I was typing =))

**Comment by Dranah** [comment]
yeah i saw no response to my text on discord so i thought i had to do it myself xD

**Comment by crulinjr** [comment]
Thanks dranah you always have my back.

**Comment by crulinjr** [comment]
Oh well i tried to do what you told me but the GM said that the report is still open and that he wont help me.

**Comment by wow-mania** [comment]
Thanks @TheManiax.
I will try to apply this tomorrow.
Is there any other set like this?
