### ISSUE TITLE
[Boss] Krystallus

### ISSUE THREAD

**Issue by TenmanWoW** [WoWManiaUK/Redemption#2780]
NPC - 27977

Shatter - 50810

How it should work:  Engaging boss results in a periodic countdown in which all party members turn to stone.  Boss then casts shatter, dealing damage to each party member based on proximity to each other.  Upon casting shatter, the stone debuff is removed and the cycle repeats itself.

How it is currently working: Engaging boss will result in the periodic countdown in which players get turned to stone. However, after the boss casts shatter and deals MASSIVE damage (Was an instant party wipe last night, still testing damage on Dev), the stoned debuff remains for as long as it takes for the boss to cast shatter again. Players are unable to act for a full 15 seconds while the boss continues damage output.

Repro: Go to HoS and engage boss. He will initiate a 4 second countdown and at the end, you will be stone. He will then continue to hit you for 10 seconds, cast shatter, you will remain stone while he hits you for another 10 seconds. The second shatter cast seems to break the stone. On Red, this is a wipe.

Supporting screenshots in order.
![wowscrnshot_100518_121103](https://user-images.githubusercontent.com/25806987/46549901-186abd00-c899-11e8-9b2b-f3869931c910.jpg)
![wowscrnshot_100518_121107](https://user-images.githubusercontent.com/25806987/46549907-1b65ad80-c899-11e8-8652-71c47fdf1bca.jpg)
![wowscrnshot_100518_121116](https://user-images.githubusercontent.com/25806987/46549913-1d2f7100-c899-11e8-8aa4-3744d7ee2d01.jpg)
![wowscrnshot_100518_121119](https://user-images.githubusercontent.com/25806987/46549915-1f91cb00-c899-11e8-9509-de6d3f41e4cc.jpg)
![wowscrnshot_100518_121126](https://user-images.githubusercontent.com/25806987/46549919-20c2f800-c899-11e8-8b1b-c484c27be957.jpg)

**Comment by Dranah** [comment]
Ok so there are 3 points in the report, 1 of which i can confirm, and i'd like to add 1more:

1) Wrong timers and cast order - CONFIRMED
Boss is spamming the Ground Slam endlessly and keeps the party stoned, often he casts shatter only half a minute later. Sometimes he shatters without Ground Slam first, which can catch a group off-guard.
How it should work: it should always be a Ground slam > wait for whole party to be stoned > Shatter sequence repeated in regular intervals
The first sequence should be cast after 30seconds, then it repeats every ~15sec until boss is dead.
here's a retail video proof>> https://www.youtube.com/watch?v=weM4N_5_UvY
https://www.wowhead.com/spell=50827/ground-slam > this is the spell that knocks players away, starts stacking slow and in the end turns them into stone

2) Shatter dealing "Massive" damage - INVALID
The shatter is doing intended damage and the boss is doable with a 4k gs party just fine so long as you spread properly, however see point 3)

3) Shatter proc off pets - CONFIRMED
This could explain Tenman's experimental issue with point 2)
Shatter currently takes pets into account, so if you have pets in the group, even just Bloodworms, you WILL take massive damage from the splash damage going off them. 
How it should work: Pets should be ignored by shatter.
See the video I linked above, you can see the warlock takes no damage off the imp standing next to him.

4) Shatter not removing Stone effect - CANNOT REPRODUCE
It properly removes the effect for me.
However due to point 1) it is possible that you are already affected by a new one stacking when the boss shatters, so it locks you back right away

**Comment by Dranah** [comment]
UPDATE:
- Ground Slam - Petrifying Grip - Shatter sequence now properly follows each other every time (fixed)
- The first sequence is cast too soon, after 15-16sec instead of 30~ that is shown on all retail videos. (need fix)
The rest of the sequences happen with proper 15-16sec intervals. 
- Shatter still proc off pets, making the fight much more difficult to handle (need fix)
See this screenshot: https://imgur.com/3ocIWXF

**Comment by wow-mania** [comment]
The first cast is trivial to fix.
The proc on pets I am not sure if it is even possible.

**Comment by Dranah** [comment]
Isnt there something in the script that is currently "friendly units" instead of "players"?

**Comment by wow-mania** [comment]
Should be better now.
