### ISSUE TITLE
[Quest] Kindness

### ISSUE THREAD

**Issue by Thrashattack** [WoWManiaUK/Redemption#2785]
http://www.wow-mania.com/armory/?quest=10804

During this initial quest for farming a Netherwing Drake  there are some npc's refusing to eat their foods. 

I got 2 confirmed ones at: 
61.9 54.6 - Mature Netherwing Drake 
&
62.1 57.7 - Mature Netherwing Drake  

The following screenshots will evidence that they are really not eating, since some of the non-bug draggons run like 40yds to eat the food placed in the feet of a bug dragon. 

### 00:58h SVT 
![0058](https://user-images.githubusercontent.com/23486776/46576667-b051cf00-c99d-11e8-8d89-ae01cad01816.jpg)

### 01:00h SVT 
![image](https://user-images.githubusercontent.com/23486776/46576672-dbd4b980-c99d-11e8-818b-ca485c46c2c9.png)

### Luring Drake
![115](https://user-images.githubusercontent.com/23486776/46576689-4be33f80-c99e-11e8-91df-c214529734e7.jpg)

Also the Item - 31737 (Rocknail Flayer Giblets), obtained from the Rocknail Rippers, are fake. 
When you reach 5 and use to turn in to a Carcass none drake eat, and nothing happens on the ground where should have a carcass. 

### Casting 
![image](https://user-images.githubusercontent.com/23486776/46576708-cf049580-c99e-11e8-9d5c-8a4dce758432.png)

### No Result 
![image](https://user-images.githubusercontent.com/23486776/46576712-e5aaec80-c99e-11e8-9cf0-b2f8364bd6fc.png)

**Comment by Dranah** [comment]
Uh okay so, the quest is doable, there are some cosmetic issues that can make it annoying though.
https://www.wowhead.com/npc=21648/mature-netherwing-drake 
In order:

1) Problem with flying speed of Mature Netherwing Drakes - CONFIRMED
They should be circling the aerial area slowly, so you can choose which you want to lure down by standing underneath. (this is relevant when multiple ppl are doing quest and most drakes are already-fed)
How it works atm: they are flying around extremely fast, it's impossible to choose which one you want to target.

2) Drake not flying back up after eating - CONFIRMED
Drakes should always be airborne unless someone lures them down. Whenever they are done eating, they should fly back up and keep circling in the air. The drakes sitting on ground on @Thrashattack screens are a result of somebody else feeding them before, and they never returning to fly.

3) Rocknail Flayer Carcass and Giblets (id 31372 and 31373) - INVALID
This works as intended, @Thrashattack when you click the 5 giblets it creates a new carcass in your bag, not one on the ground right away. You can then use this carcass like you used other carcasses to place.
(PS: I can see it in your bag on the last screen)

4) Dragon from further away coming to eat the food - AS-IS
This is blizzlike, sometimes the carcass grabs the attention of a further dragon, not the one right above you. (it's probably because of a different fly height but i've no idea)
Here is a video that shows this https://www.youtube.com/watch?v=gj0OX69b52w at 1:50, the guy looks up in the air to see why the drake right above him is not moving, and you can see another flying in from side afterwards. 

I could not reproduce issue where a drake (with no cooldown) would refuse to eat the food, only thing that happened is just that sometimes the food aggros a drake further away and you need to wait for that one to land. Each food can only grab one drake's attention.

**Comment by wow-mania** [comment]
The bad drakes are NPCs that did not reset after feeding.
I am forcing them to do so or despawn.
Increased speed a little.

**Comment by Dranah** [comment]
It is now worse, the drakes you feed do fly back up but then disappear, so you cannot feed them again after 1minute and have to wait out full respawn.
Also their flight speed is still insanely fast, you need to **reduce** their movement speed, not increase. It's impossible to stand under a drake and feed it, they are moving so quickly you can only pray that one will be above you when you place carcass, otherwise it won't grab the attention of any.

**Comment by wow-mania** [comment]
Both have been changed already. It needs restart.

**Comment by Dranah** [comment]
Drakes no longer despawn after being reset.
However their movement speed is still way too fast. You see a drake passing above you, by the time you place carcass its swoosh gone and there is no nearby drake to attract so you just wasted a carcass.

**Comment by wow-mania** [comment]
No change on the speed. You probably need to delete cache.

**Comment by Dranah** [comment]
I deleted cache and i'm using the launcher. And yet the drakes are flying around much faster than on retail video. Much faster than a player on the ground can follow.
Does the quest work? Yes its doable, as it always was, thus the tweaking label.
Does it work perfectly? No, drakes speed does not match retail speed.

**Comment by wow-mania** [comment]
The speed has not changed. I will, however, reduce it a bit more.

**Comment by Dranah** [comment]
I never said the speed changed, the fact it did not change is the problem. it needs to be slower.

Check retail video from 1:50 for drake speed https://www.youtube.com/watch?v=gj0OX69b52w
Check video made in mania, they're soaring: https://youtu.be/IZ45PcnAwgE
PS: video recorded 5minutes ago

**Comment by wow-mania** [comment]
Will stay as is. No change in speed.
