### ISSUE TITLE
Hunter T9 2p bonus

### ISSUE THREAD

**Issue by Undertower** [WoWManiaUK/Redemption#2812]
Issue: The Serpent sting critical strike only deals 2x the damage. It also does not trigger the talent [Expose Weakness](http://www.wow-mania.com/armory/?spell=34503)
How it should be: The Serpent Sting critical strikes should deal 2.3x the damage due to [Mortal Shots](http://www.wow-mania.com/armory/?spell=19490) It should trigger the [Expose Weakness](http://www.wow-mania.com/armory/?spell=34503) talent.

"Hunter Tier-9 2-Piece Set Bonus: Critical damage from Serpent Sting will now work properly with the Mortal Shots and Expose Weakness talents."
Source: http://us.battle.net/wow/en/game/patch-notes/3-2-2

**Comment by Aristo14** [comment]
also will look into this, i feel the 'fix' on serpent chims have caused this.. there is no crit but an increased hit if im not mistaken?

**Comment by Dranah** [comment]
The two are not related.
Chimera-serpent is an instant damage that calculates from 40% of SS total damage, and it now deals critical strikes for a proper 248% (full talented+meta) dmg, its simply not displayed as a crit on the logs, pure visual issue.

Serpent Sting dot-ticks are not normally able to crit, only with the tier. Having the 2piece tier does not affect the Chimera-serpent damage mentioned above, as that calculates with the total damage of the DOT, which is calculated first.
Then the total damage of the dot is divided to X tick damages, which have individually the ability to crit when you have the tier bonus. The issue with this critical damage not affected by talents is something blizzard faced too, it was fixed in the patch note linked.

**Comment by Keader** [comment]
now it should proc Expose Weakness

**Comment by Dranah** [comment]
UPDATE:
- Critical strikes from Serpent Sting dot ticks can now proc Expose Weakness.
- Critical strike damage bonus is still not properly adjusted by Mortal Shots, the spell crits for 200% damage

**Comment by Keader** [comment]
try now

**Comment by Keader** [comment]
Try now²

**Comment by Dranah** [comment]
Serpent Sting now properly crit-ticks for 230% damage with Mortal Shots.
