### ISSUE TITLE
[Quest] A Little Help From My Friends

### ISSUE THREAD

**Issue by Thrashattack** [WoWManiaUK/Redemption#2833]
• http://www.wow-mania.com/armory/?quest=4491 

When you unfortunatly enter in combat while Ringo (http://www.wow-mania.com/armory/?npc=9999) is "dead" he will no longer walk and just stuck in the place where you used the water (http://www.wow-mania.com/armory/?item=11804) to res him

**Comment by squalllh1989** [comment]
maybe you got him stuck in a dead spot, i tried it out in multiple situation, can't seem to reproduce:
- Got in combat after he "dead", just get the mob on me, get back and use water on him: he wake up and follow normally
- Got in combat after he "dead", kill the mob and use water on him: he wake up and follow normally
- Constantly got in combat (keep moving and taunt mob on the way with him follow, with intent to wait for his moment to "dead"): he move foward and back ward all the time, but still follow you, and doesn't "dead" anymore, it seem he has a factor to avoid the situation you report: not going to "die" when you are in combat, so that situation is kind of rare and hard to reproduce.
