### ISSUE TITLE
[Quest] Rise, Obsidion! 

### ISSUE THREAD

**Issue by lothraine** [WoWManiaUK/Redemption#2860]
The {Rise, Obsidion] quest in Searing Gorge cannot be completed. The golem just dissapears.

**Comment by gamer100** [comment]
Obsidion's heart  disappears  right after  kill. Player could not loot

**Comment by Thrashattack** [comment]
I manage to reproduce the entire questchain, escorting Darius and etc. 
So i toke the mentioned quest: 
![image](https://user-images.githubusercontent.com/23486776/48751260-32523a80-ec62-11e8-854e-21637392ff00.png)
 
After the long dialog between Darius , the Dying Archeologist (http://www.wow-mania.com/armory/?npc=8417) and Lathoric, The Black (http://www.wow-mania.com/armory/?npc=8391), we can finally fight Lathoric but at this point Obsidion (http://www.wow-mania.com/armory/?npc=8400) corpse despawns and never respawns again as you can see:  

![image](https://user-images.githubusercontent.com/23486776/48751339-9d9c0c80-ec62-11e8-8304-43152a3cf6f3.png)



I'm not sure if after start the quest the player is Phased and Obsidion is not present with full health in this phase, or if Obsidion corpse should despawn and respawn with full life because in the only evidence i could find the fight is already began 

• https://www.youtube.com/watch?v=MMHvBVoAco4

**Comment by Thrashattack** [comment]
Obs: In GM mode the smart script seems to work fine 

The phase maybe being passed wrong to Obsidion but not for Lathoric (Weird right?). 
OR... 

The Altar is phasing the player, wich have nothing to do with the smart script, and this can be messing things arround, I found a implementation of a condition to gossip the altar but none consensus untill now.
