### ISSUE TITLE
[Core] Combat pet AI

### ISSUE THREAD

**Issue by zonefrost** [WoWManiaUK/Redemption#2879]
I have a suspicion that the following issues are related:
1: mobs under a priest's Mind Control spell do not attack or use abilities.
2: mobs under a warlock's Enslave Demon spell do not attack or use abilities.
3: hunter pets under the Eyes of the Beast spell do no attack or use abilities.

in all 3 instances, the units can be controlled normally in every other aspect, target enemies and even assume a battle stance, but will not move towards the target, auto-attack and abilities will not trigger when clicked/pressed.

![wowscrnshot_113018_055402](https://user-images.githubusercontent.com/42932816/49293511-3998f580-f465-11e8-9395-3e90e0ca0f7b.jpg)
![wowscrnshot_113018_055714](https://user-images.githubusercontent.com/42932816/49293516-3dc51300-f465-11e8-8913-628907501be7.jpg)
![wowscrnshot_113018_054755](https://user-images.githubusercontent.com/42932816/49293490-2ab24300-f465-11e8-8e9b-794afae98149.jpg)

**Comment by Dranah** [comment]
Flawless logic, awful research skills.
This has already been reported and is waiting for a core fix, since it's a major core problem:
https://github.com/WoWManiaUK/Redemption/issues/2586

**Comment by Dranah** [comment]
I'm not sure why you're offended, I meant it when I said you applied flawless logic when making your report. 99% of players would fail to connect that these spells are related. Ever thought perhaps you shouldn't take everything in a negative read?
Either way, there is nothing that can be done about it right now, as the same core issue is responsible for all charmed creatures misbehaving. Keader has described that in his post, the issue is the .possess command itself.

I have tested (and always been using) special abilities of mind controlled mobs (prime example: adds on Grand Widow Faerlina or Instructor Razuvious) and also pets controlled by Eyes of the Beast, and they all work as intended. Only auto-attacks and autocasts do not.
Here is a screenshot with a hunter's pet using specials under Eyes of the Beast:
https://imgur.com/bzwZ6Qx

**Comment by zonefrost** [comment]
> 
> 
> I'm not sure why you're offended, I meant it when I said you applied flawless logic when making your report. 99% of players would fail to connect that these spells are related. Ever thought perhaps you shouldn't take everything in a negative read?
> Either way, there is nothing that can be done about it right now, as the same core issue is responsible for all charmed creatures misbehaving. Keader has described that in his post, the issue is the .possess command itself.
> 
> I have tested (and always been using) special abilities of mind controlled mobs (prime example: adds on Grand Widow Faerlina or Instructor Razuvious) and also pets controlled by Eyes of the Beast, and they all work as intended. Only auto-attacks and autocasts do not.
> Here is a screenshot with a hunter's pet using specials under Eyes of the Beast:
> https://imgur.com/bzwZ6Qx

how can you not see how someone would take 'flawless logic' followed by 'aweful research skills' as being sarcastic and condescending? anyway, I could not get my hunter pet to use special abilities such as spirit strike

**Comment by Dranah** [comment]
There could be problem with a specific pet or specific ability. But definitely not a general issue. If you can give details I will look into that.

**Comment by Dranah** [comment]
I investigated this matter a bit further and I can say the following:
- Abilities that require melee attacks such as ones used on "next melee" will not work while the creature is charmed, for same reasons they can't attack or auto-attack either.
- Other special abilities work as intended, including spirit strike, I can use it without problems within its 30 yard range everywhere. Only if i run out of focus, I cannot use it until I regen it back.

Also I found at least 3 other, different issues with the named spells while testing, for which I will open separate reports.
