### ISSUE TITLE
Quest "Hot and Cold"

### ISSUE THREAD

**Issue by Dragonil1** [WoWManiaUK/Redemption#2890]
Before I speak to the GM , i couldn't even see "The Smoldering Scraps".
That was solved , but when I was supposed  to use "essence of ice , it didnt't work.

Thank you in advance, and congratulations on everything

**Comment by WhitephoenixTheBunny** [comment]
[Hot and Cold](http://www.wow-mania.com/armory/?quest=12981)

**Comment by TenmanWoW** [comment]
I looked at this. I am unable, upon giving myself the quest, to see the piles of smoldering iron that is the target of the essence of ice. The Essence drops normally from the correct mob. However, upon approaching the anvil, there is nothing to use it on.

![wowscrnshot_120418_193139](https://user-images.githubusercontent.com/25806987/49484433-acef8e00-f7fc-11e8-829b-6265aeda966b.jpg)
![wowscrnshot_120418_192727](https://user-images.githubusercontent.com/25806987/49484434-acef8e00-f7fc-11e8-84d6-f9488b5f49dc.jpg)
![wowscrnshot_120418_192019](https://user-images.githubusercontent.com/25806987/49484435-acef8e00-f7fc-11e8-8715-c8938d16e7b8.jpg)
![wowscrnshot_120418_192010](https://user-images.githubusercontent.com/25806987/49484436-acef8e00-f7fc-11e8-973f-925e4d7ec584.jpg)

**Comment by WhitephoenixTheBunny** [comment]
Okay, this a side quest from [Sons of Hodir](http://www.wow-mania.com/armory/?faction=1119), the questline was fixed sometime ago (#2798) I believe this a phase issue, since I have just made the quest on Redemption and everything was working perfectly. As to a GM to check your questline, if you aren't missing any requirement

Screenshots from Redemption:

![image](https://user-images.githubusercontent.com/31921098/49485246-18a01e00-f832-11e8-9454-da584ba59d3d.png)
![image](https://user-images.githubusercontent.com/31921098/49485265-2ce41b00-f832-11e8-9dc9-08e5fa37fa7b.png)
![image](https://user-images.githubusercontent.com/31921098/49485372-a1b75500-f832-11e8-983f-1507c0ae3e61.png)

**Comment by GM-Gathios** [comment]
Checked it, the player did not reward Forging an Alliance.
