### ISSUE TITLE
[Quest] The Clutches of Evil

### ISSUE THREAD

**Issue by TheHellbringer** [WoWManiaUK/Redemption#2897]
NPC Captain Adams (Westguard Keep) should give this quest, but i can not get it.
https://www.wowhead.com/quest=11157/the-clutches-of-evil

I submitted a ticket, but the GM could not do anything.
I use your client and launcher. Deleted cache but nothing helped.

**Comment by wow-mania** [comment]
You first need to complete: 
![image](https://user-images.githubusercontent.com/12248683/49699025-bc3b5680-fbc3-11e8-91c8-8ac1a4eb95bb.png)

http://www.wow-mania.com/armory/?quest=11501

**Comment by Rushor** [comment]
that prev quest is actually wrong..

No prequest is required. Currently xou need to do http://www.wowhead.com/quest=11501/news-from-the-east#comments first in order to get https://wowgaming.altervista.org/aowow/?quest=11157.

That#s wrong according to this video https://www.youtube.com/watch?v=JE80Vhj2zeI&feature=youtu.be&t=2m4s and that text:

http://de.wowhead.com/quest=11157/das-gelege-des-bosen#comments:id=1868349:reply=878219
Liz7 am 2015.06.25 (Patch 6.1.2)
Pretty late, but I wanted to point out that this quest has no prerequisites. It can be the very first quest you do in Northrend (I just checked with my free level 90 char in WoD). If it doesn't show maybe your level is too low or too high (activate "show low level quests" on your mini map in the latter case).

**Comment by Rushor** [comment]
][Howling Fjord] The Clutches of Evil - Prevquest has been removed.
