### ISSUE TITLE
Auction House not working

### ISSUE THREAD

**Issue by Boobarnes** [WoWManiaUK/Redemption#2904]
The Auction House isn't working properly, and by that, I mean that I can click on some items for sale and buy them, but others are completely unclickable. For example, on 11 Dec I was trying to buy glyphs for my rogue. I clicked glyphs, rogue, saw the list, and could not buy many of them. I noticed it depended on the seller: I couldn't buy from Aurelione, who had a ton of glyphs there, but other users who'd posted a few glyphs I could buy from. I have tried relogging and deleting cache; no luck.

It's not just me--it's been a common complaint in world chat for the last 2 days. My own 2-4 items for sale have been selling. It seems that those who sell a lot, however, can't sell anything, and we can't buy from them. Thanks for looking into this.

**Comment by wow-mania** [comment]
This has already been fixed.

**Comment by Kazurax3k** [comment]
Hello, as of July 29th 2019, this issue is still a problem. The details are the same, what appears to be random items cannot be selected, and therefore cannot be bought or bid on. The items look like they are the same on all my toons. I have disabled Auctioneer, and the same items are still not able to be highlighted. If there is more info I need to provide I'll be happy to do so.

**Comment by jeyrella** [comment]
Multiple reports that this has regressed again.  Is being looked into.
