### ISSUE TITLE
[Spell] Death Wish and Enrage interaction

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Redemption#2923]
Death Wish and Enrage are stacking, when supposedly they shouldn't.
EDIT: Alot of things are inappropriately stacking, check comments below.

Proof of unintended behavior:
![enrage n dw](https://user-images.githubusercontent.com/16576459/50226738-a8a2a380-03ac-11e9-9df2-a46baf406587.png)

I get enrage proc then use Death Wish and Rend. After Enrage fades, I use Rend again, damage ends up dropping.

Proof that it shouldn't stack: http://wowwiki.wikia.com/wiki/Enrage_(warrior_talent)
Patch 2.1.0 (22-May-2007): Death Wish and Enrage no longer stack: with both Death Wish (+20% damage) and Enrage present, the greater effect will be picked (Death Wish).

Spell ID: http://www.wow-mania.com/armory/?search=Enrage#talents (Enrage)
http://www.wow-mania.com/armory/?spell=12292 (Death Wish)

**Comment by Ashamedlol** [comment]
Also, a bigger proof in a later on patch: http://wowwiki.wikia.com/wiki/Tricks_of_the_Trade
Patch 3.1.0 (14-Apr-2009): Hysteria, Tricks of the Trade, Enrage, Wrecking Crew, Death Wish, Arcane Power, Owlkin Frenzy, Beast Within, and Avenging Wrath damage bonuses no longer stack together.; Will now begin following the first damaging attack.

This involves ALOT of spells/talents that shouldn't stack.

**Comment by Dranah** [comment]
Confirmed, we just checked out several sources with Ashamed and none of these effects are supposed to stack on 3.3.5a.

**Comment by Ashamedlol** [comment]
Spell IDs: 
1) Tricks of the Trade: http://www.wow-mania.com/armory/?spell=57933 / http://www.wow-mania.com/armory/?spell=57934
2) Hysteria: http://www.wow-mania.com/armory/?spell=49016
3) Arcane Power: http://www.wow-mania.com/armory/?spell=12042
4) Avenging Wrath: http://www.wow-mania.com/armory/?spell=31884
5) Owlkin Frenzy: http://www.wow-mania.com/armory/?search=Owlkin+Frenzy
6) The Beast Within: http://www.wow-mania.com/armory/?spell=34471
7) Wrecking Crew: http://www.wow-mania.com/armory/?search=Wrecking+Crew

Rest (Enrage, Death Wish) are already mentioned in the main topic.

**Comment by Keader** [comment]
wrecking crew already do not stack with enrage.

**Comment by Ashamedlol** [comment]
Sure thing Keader, but all those spells shouldn't be stacking with each other, not just enrage+WC.

**Comment by Keader** [comment]
@Ashamedlol I cant reproduce issue with spells that you mentioned https://github.com/WoWManiaUK/Redemption/issues/2923#issuecomment-448798257

In ptr.
Fixing main issue (enrage + death wish)

**Comment by Keader** [comment]
Try now Enrage + Death Wish

**Comment by Dranah** [comment]
UPDATE:
- Enrage can now proc once Death Wish expire (fixed)
- Death wish and Hysteria are now exclusive, with Death Wish being the dominant effect (fixed)
- Avenging Wrath and Hysteria are now exclusive, with Avenging Wrath being dominant (fixed)
- Hysteria still stacks with Enrage (need fix)
- Hysteria and Arcane power overwrite each other (need fix - Arcane power should be dominant - while mages aren't meant to be target for hysteria, this allows room for trolling them with removing their buff)
- Hysteria now overwrites the effect of beast within - this doesn't work out, the hunter's BW effect grants reduced mana cost and fear immunities as well, which is cancelled by hysteria this way. Need to fix it somehow to allow the buffs to coexist but only give the higher damage boost part (need fix)
- Tricks of the Trade (57933) effect now overwrites BW the same way as Hysteria, same issue, need the two effects to coexist with only the higher damage boost applied (need fix)
- Tricks of the Trade still stacks with Enrage ( need fix) However you cannot make Tricks just overwrite Enrage. Because warrior tanks (often target for tricks) can use Enrage effects to consume for Enraged Regen, however cannot use Tricks (tricks is not an enrage effect). The two effects should coexist with only the stronger damage boost applied.
- Death Wish now overwrites Tricks of the Trade / prevents it from being applied. This could be a problem mainly if you had a Fury tanking a dungeon and the rogue tried to transfer threat, but truthfully this scenario is negligible. Good as is.
- Tricks of the Trade and Arcane Power overwrite each other. This need fix. Arcane power should never be overwritten by tricks. AP being dominant effect can work, as mages are seldom the target for threat transfer.
- Tricks of the Trade is overwritten by Avenging wrath and cannot be applied to targets under the effect of AW. This is a problem for paladin tanks during burst not being able to receive threat transfer. Need to fix them to allow effects to coexist with only the stronger dmg boost applied (need fix)

The list of interactions may be incomplete but I think you got the point. Some effects cannot just overwrite each other because they have other side effects too. In those cases, if you can't fix it properly, better let those spells just stack like they did before.

**Comment by Keader** [comment]
The fucking table is just not working.
I will do my last try here tomorrow.

**Comment by Keader** [comment]
Ok, found the main issue, i think i fixed already
Waiting janitor back :/

**Comment by Keader** [comment]
Try now.
Some issues i put to not stack same effect, will be both active but not stack same effect

**Comment by Dranah** [comment]
UPDATE:
- Hysteria now overwrites enrage ( fixed)
- Hysteria no longer overwrites Arcane Power ( fixed)
- Hysteria now overlaps with Beast Within with the stronger (20%) physical damage buff applied ( fixed)
- Tricks of the Trade now overlaps with Beast within, and the damage component will no longer stack at least for physical attacks - not perfect, but improvement
- Tricks of the Trade now overwrites Enrage - this is not very good, should coexist
- Death wish and Tricks now coexist with only the stronger (20%) damage boost (fixed)
- Arcane power stacks fully with Tricks damage boost for 20%+15% (need fix)
- Avenging wrath now coexist with Tricks and their damage components no longer stack for physical attacks at least - not perfect but improvement

In general, the remaining issue seems to be with Tricks of The Trade only effectively overwriting physical damage components and still fully stacking for spell damage.

**Comment by Dranah** [comment]
Seems this issue cannot be fixed. Tricks of the Trade will remain able to stack with spell damage boosts for now.
