### ISSUE TITLE
Female Goblin players make male goblin sounds in combat

### ISSUE THREAD

**Issue by Hellcion** [WoWManiaUK/Redemption#2939]

**Comment by wow-mania** [comment]
Cannot reproduce. Get our client.

**Comment by wow-mania** [comment]
Where was I rude? You enter an issue with just the title and don't bother to describe. You obviously did not read our guide on how to create an issue. You are lucky I replied at all.
Instead of being so damn sensitive and wasting time on a stupid answer you could take 2 minutes to read the document and fill in a proper bug report to help the developer confirm or dismiss it.

**Comment by wow-mania** [comment]
I will take a look at it.
It will require a client update so it will not be an immediate fix.

**Comment by Dranah** [comment]
@Hellcion , he did begin with "Cannot reproduce".
That means he looked into it but could not find the problem you were talking about.
I myself have no problem with the female goblin voice, it sounds female also in combat...

**Comment by Hellcion** [comment]
Thank you for looking at least. Appreciate the time and effort you both
took.

Regards!
