### ISSUE TITLE
[Reputation] Steamwheedle Cartel

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#2958]
Hi,

The 4 Steamwheedle Cartel factions (Booty Bay, Gadgetzan, Everlook and Ratchet) can be gained reputation with by [the following ways](http://wowwiki.wikia.com/wiki/Mobs_which_affect_reputation_with_Steamwheedle_Cartel). As seen, all 4 of the different city factions have mobs that can grant them rep until exalted. Those mobs are usually mobs that grant full rep for another city and stop granting it at revered, but they should still grant 50% spillover reputation to the other 3 factions. 

> Do keep in mind that when grinding pirates for SteamWheedle Cartel, their respective cities (those you get 5 rep with per kill) will no longer grant ANY rep after achieving revered. They still will give 2.5 rep with all others though. To get exalted with all the steamwheedle cartel, I grinded the pirates south of ratchet until Gadgetzan was exalted, and then switched to the pirates in the cove in Tanaris to finish off Everlook and Ratchet. - Marivel ([Wowhead](https://www.wowhead.com/achievement=2336/insane-in-the-membrane#comments)).

The issue on wow-mania however, is that the spillover rep isn't granted if those mobs aren't granting full reputation for their respective faction, although they still should. I have tested it with the Venture Co. members and Bloodsail Buccaneers in Stranglethorn Vale (should grant 2.5 rep with all but BB), the Southsea Freebooters south of Ratchet (should grant 2.5 rep with all but Ratchet) as well as with the Southsea Pirates in Tanaris (should grant 2.5 rep with all but Gadgetzan.

So, currently being revered with all 4 of the Cartel factions, I am unable to gain rep with any of them by any way. 

Any help? 
Thanks

**Comment by Keader** [comment]
@Dranah or @WhitephoenixTheBunny can confirm it and gime a reproduce case?

**Comment by squalllh1989** [comment]
Confirmed that the reputation gain for those faction by grinding mob stop at revered. This problem has involved many kind of npc, which the reporter already has a link [here](http://wowwiki.wikia.com/wiki/Mobs_which_affect_reputation_with_Steamwheedle_Cartel)
Let's use an example: the [Southsea Freebooter](http://www.wow-mania.com/armory/?npc=7856) will give you this kind of amount of rep if you kill them with your rep with all 4 faction not at revered: 

![wowscrnshot_010819_122339](https://user-images.githubusercontent.com/27235989/50811524-4f8db600-1341-11e9-8ebb-fdbcb1abea3d.jpg)

5 with Gadgetzan
2 with Booty Bay, Ratchet, and Everlook

If your reputation with Gadgetzan reach revered, then the mob won't give you gadgetzan rep anymore, but STILL WILL GIVE YOU REP WITH OTHER 3 FACTION EVEN IF YOU REACH REVERED WITH THEM, that's how it should work.
How ever, it didn't work like that at the moment: when you reach revered with the faction that the mob give you the most rep (in my example with the Southsea Freebooter, it's the Gadgetzan), the mob won't give you any kind of rep anymore. My guess is that the problem is due to the fact that in the armory, the mob have the information like this:
![3](https://user-images.githubusercontent.com/27235989/50811756-67b20500-1342-11e9-80a3-71b5bc9e2363.png)
So the system check, if you doesn't revered with Gadgedzan then it give you reputation with all other, if yes, then you won't get any rep anymore. The right case of gain rep should be like this (for this mob):
![3](https://user-images.githubusercontent.com/27235989/50811828-c1b2ca80-1342-11e9-8d0b-fc7abaa15fd5.png)

**Comment by Keader** [comment]
Cool, I will search the reason.
Ty for confirm

**Comment by Keader** [comment]
This was a hard onde.
Fixed.

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/50914791-4713a900-142f-11e9-80c1-b0f0519823ec.png)
