### ISSUE TITLE
[Quest] Just Following Orders

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#2959]
See ticket https://github.com/WoWManiaUK/Redemption/issues/1147 - this is an exact repeat, same screenshots can be referenced.
http://www.wow-mania.com/armory?quest=12540   "Just Following Orders"

Seen today, all NPCs   http://www.wow-mania.com/armory/?npc=28217  do not respond to player - there is only a greyed question mark.
GM Vousalan witnessed, resetting them had no effect.
Client 2.5.0 through launcher, cache cleaned

Just to be clear, the impact of this not working is that the following chain of 10+ quests and thus access to the dailies are locked out if this quest cannot be completed (plus the Into the Basin achievement)

**Comment by wow-mania** [comment]
As an exact repeat you need to see what the cause was.
Quest works.
Having said that I will give the benefit of the doubt and yet again waste my time testing something that I know it works.

**Comment by WhitephoenixTheBunny** [comment]
That happen when someone dies, abandon or give up on the quest, since you have 7 (i think) oracles, sometimes you need reset more than one, and more than once.

**Comment by wow-mania** [comment]
Server restarted about 9 hours ago so they should all be fine now.
I can't believe people are incapable of completing such an easy quest.
I will however check npc and try to make it idiot-proof.

**Comment by Dranah** [comment]
The problem here is what Phoenix says, that if players "use" the npcs before you, but don't finish the chain, they won't properly reset and you can't do anything about it. They don't even have to be an idiot, simply leave the quest chain unfinished for whatever reason (maybe went to sleep or popped an RDF), but the result is same, people who try to interact with the NPC after just won't be able to until the server restarts. Which could be days to wait and 7 NPCs total isn't a lot for a server with 500 online average.
Steps to repro:
1. Take quest and speak to target NPC (28217)
2. NPC becomes a quest-ender, with the grey question mark to offer you to hand in the quest when it is complete and he is no longer possible to speak to. (by anyone)
3. If you choose to complete the quest, it gives a follow-up that you may leave or take, if you don't, whether you abandon the quest or not, the NPC is left in the same state, it does not matter, you leave the NPC behind being broken and unable to use, and it will not reset until server restart.
4. The only way the NPC will be able to reset is if you complete the 2nd quest too (the escort) at the end of which the NPC despawns. Then after a short time he'll respawn.

**Comment by wow-mania** [comment]
Sorry, this will stay as is. I will not be spending hours trying to cover for people not finishing a simple quest.
If the quest is completed the NPC resets properly. There is no easy way to cover for people leaving it at the point.
If I figure out a way to cover for people not following the "normal" flow of actions I will cover for it. In the meantime, it will stay as is.

**Comment by wow-mania** [comment]
I know. I will research and see if I find a better alternative.

**Comment by Dranah** [comment]
This is still in progress.

**Comment by wow-mania** [comment]
@Dranah please test now on dev.

**Comment by Dranah** [comment]
Excellent, the NPC is now always available to be spoken to and also to hand in quest (grey question mark) at same time.

**Comment by WhitephoenixTheBunny** [comment]
I just tested it also
