### ISSUE TITLE
[Dungeon][NPC]New Aggro Range and Possible Damage

### ISSUE THREAD

**Issue by Eldracc** [WoWManiaUK/Redemption#2975]
After the new aggro range patch me and my guild experienced real big problem after it in dungeons First we did Pit of Saron Heroic and it worked just fine with me as tank but when we did DrakTharon Keep Heroic in the room just before the first boss with the ghouls and abominations we got killed super fast. Their we pulled the half room which im sure you did not do in retail by aggroing the closest ghouls next to the door. They also hit kinda hard but im not sure if that's a effect from the aggro range or it somehow being changed and we tried with 2 diffrent tanks and failed, we have done this dungeons many times before so it's not a new player mistake.
So we left and did Ahn'kahet Heroic and in the room after the entrance room with the pool, they also hit realy hard(much harder then before) and we had to get a tank with ICC gear in to help.
Im not sure if it's our fault or it's the new patch but they do feel more hard hitting and the aggro range just slightly to big for some dungeons that it should not happen.
I did send a ticket to a gm and he said it could be possible about the damage but didnt know about the aggro range being to big.
All im asking is to atleast see if something wrong has happen.

Thanks
This happen at around 21:00 11-1-2019

**Comment by wow-mania** [comment]
This is as is. Not an issue. Aggro is still 70% of what it was in retail. 
Different does not mean wrong.

**Comment by Dranah** [comment]
I have just made a run in FoS PoS Draktharon and Ahnkahet heroic and could clear all smoothly. 15-20min per dungeon.
I cannot report a difference in aggro range or damage of mobs.
Note I am a multiboxer and my chars have ~4,5k gs each.

Based on your description @Eldracc , I can give the following advice: the pull in the first boss room of DTK depends on waiting out the right moment because there are two abominations patroling. Chain aggro works as intended, which means if the aboms are around the ghoul parties, aggroing any of the enemies will also aggro all the rest.
If you pull at the right moment, only one group (3-4 ghouls) aggro, whom you can easily handle. Given that your melee DPS attacks from behind. Each ghoul cleaves, so standing in front of them can easily oneshot a melee from 3-4 cleaves.
Nothing has changed with the last patch. Some tanks know how to pull at the right moment, some don't. Some DPS knows where to stand to not get cleaved/poisoned, some don't.

As for Ahn'kahet, there is a specific mob "Plague Walker" who reduces the health of the party in an increasing manner over time. If you don't focus on killing this mob, you'll end up having 10k health to begin with and that will make each hit on you feel much harder than it really is. I reckon that happened to you as I cannot find the mobs hitting any harder than before, they barely tickle me. My tank has 39k health fully buffed and never went below 85%.
I also have to note here that the Spell Flingers are completely broken and their main nuke shadow blast does almost zero damage. This ability is supposed to be capable of near-oneshotting your tank unless it is interrupted, and generally this mob is supposed to be the most dangerous among all the trash. And they are doing no damage here, making the AK trash overall much easier than blizzlike.

**Comment by Eldracc** [comment]
> This is as is. Not an issue. Aggro is still 70% of what it was in retail.
> Different does not mean wrong.

I agree, but this aggro does feel slightly off in some dungeons

**Comment by Eldracc** [comment]
> I have just made a run in FoS PoS Draktharon and Ahnkahet heroic and could clear all smoothly. 15-20min per dungeon.
> I cannot report a difference in aggro range or damage of mobs.
> Note I am a multiboxer and my chars have ~4,5k gs each.
> 
> Based on your description @Eldracc , I can give the following advice: the pull in the first boss room of DTK depends on waiting out the right moment because there are two abominations patroling. Chain aggro works as intended, which means if the aboms are around the ghoul parties, aggroing any of the enemies will also aggro all the rest.
> If you pull at the right moment, only one group (3-4 ghouls) aggro, whom you can easily handle. Given that your melee DPS attacks from behind. Each ghoul cleaves, so standing in front of them can easily oneshot a melee from 3-4 cleaves.
> Nothing has changed with the last patch. Some tanks know how to pull at the right moment, some don't. Some DPS knows where to stand to not get cleaved/poisoned, some don't.
> 
> As for Ahn'kahet, there is a specific mob "Plague Walker" who reduces the health of the party in an increasing manner over time. If you don't focus on killing this mob, you'll end up having 10k health to begin with and that will make each hit on you feel much harder than it really is. I reckon that happened to you as I cannot find the mobs hitting any harder than before, they barely tickle me. My tank has only 39k health fully buffed and never went below 85%.
> I also have to note here that the Spell Flingers are completely broken and their main nuke shadow blast does almost zero damage. This ability is supposed to be capable of near-oneshotting your tank unless it is interrupted, and generally this mob is supposed to be the most dangerous among all the trash. And they are doing no damage here, making the AK trash overall much easier than blizzlike.

I did wait for the abomination to be as far as possible and was able to pul only 2 ghouls group but did not work out well for either of our tank, and we have done it before.

As for Ahn'kahet i just never experienced it before neither did any other in my guild but if it's just in my head i can accept, i just feel like it's slightly.
