### ISSUE TITLE
[Towers controlled] -  Hellfire 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#2990]
**_Towers controlled in Hellfire_** 

- Noticed that on my map it shows 3 horde towers 
- Only 2 are displayed on screen 

![wrong](https://user-images.githubusercontent.com/39439201/51291237-bcbade80-1a06-11e9-8457-ec9ade9eacdc.jpg)

**When its actually 3** 

![123](https://user-images.githubusercontent.com/39439201/51291258-cc3a2780-1a06-11e9-91f3-c20e7bbe35b6.jpg)

**Comment by wow-mania** [comment]
This is because there is no one on the other base or refresh delay.
You need to have an active presence there. You can probably fly to another base but sometimes it will not update instantly.

![image](https://user-images.githubusercontent.com/12248683/51310816-5dc58b80-1a3f-11e9-98b3-a170e9954aa2.png)
