### ISSUE TITLE
[Spirit Healer/ NPC] Wintergrasp Horde GY 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#2997]
NPC - https://www.wowhead.com/npc=31841/taunka-spirit-guide
GY nearest FP -  https://www.wowhead.com/npc=30870/herzo-safeflight

- Needs fixing too please :)
- Timer finishes and doesnt res us, so you have to click Taunka 
- He res us with only half life/mana

![taunka spirit guide](https://user-images.githubusercontent.com/39439201/51434881-30f5bc00-1c6b-11e9-8858-c012b34d9cae.jpg) 

![taunka map](https://user-images.githubusercontent.com/39439201/51434891-921d8f80-1c6b-11e9-875f-21426969794f.jpg)

![half](https://user-images.githubusercontent.com/39439201/51434896-c1340100-1c6b-11e9-90bf-993aff0f256c.jpg)

**Comment by squalllh1989** [comment]
this happen before when i do pvp, i think it happen when the alliance capture all the workshop, which lead to the disable of all graveyard's resurrection. Since the horde won't be in control of any base, any horde player that die will be spawn as a spirit at the horde spawn point near the broken temple workshop. And since all base are controlled by alliance, the system will stop resurrect player as it think the horde didn't control the broken temple to be allowed to do that, which lead to the must of click on the spirit guide and chose to resurrect there by yourself, with only 50% of mana and hp

**Comment by squalllh1989** [comment]
I have seen this many time when pvp as a horde player, not sure if alliance will have this problem as well since i didn't play wintergasp as alliance a lot.

**Comment by wow-mania** [comment]
Still need steps.

**Comment by Echinaceax** [comment]
its the same fix that was done for the Ally side also was reported and fixed i see :)

Wintergrasp Graveyard #2688

**Comment by Keader** [comment]
Try now.

**Comment by Echinaceax** [comment]
Thanks Keader 
Report back when tested :)
