### ISSUE TITLE
[Hunter Pet talents] Dual spec BM / MM

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#3024]
(Dual spec) BM and MM (Ally) 

- Pet talents are resetting when i switch specs from BM to MM and vice versa 
- Tested with and without "dismiss pet" 
- Tested on the wolf and cat Pets so far

Wolf - https://www.wowhead.com/npc=17280/shattered-hand-warhound

**BM**

![1 bm 20 wolf](https://user-images.githubusercontent.com/39439201/52178014-37d31180-27c9-11e9-9bf0-47c01d72563f.jpg)

switched BM to MM (talents reset) 
- used "dismiss pet" 
- All 16 talents reset
- Tested both _with_ and _without_ "dismiss pet" spell

![bm too mm reset cat without dismiss pet](https://user-images.githubusercontent.com/39439201/52178410-6ef7f180-27ce-11e9-9efe-b6f5e7c8094f.jpg)

- then MM to BM 

![2 bm 16 and 4 unspent](https://user-images.githubusercontent.com/39439201/52178295-f6dcfc00-27cc-11e9-9002-c451c2738b62.jpg)

Cat - https://www.wowhead.com/npc=731/king-bangalash

BM to MM
- Talents reset / and vice versa
- Tested _with_ and _without_ "dismiss pet" 

![bm too mm reset cat without dismiss pet](https://user-images.githubusercontent.com/39439201/52178368-e8431480-27cd-11e9-9ea2-ca494ca40cab.jpg)

MM to BM 
- Talents reset 0/20
- Tested with and with "dismiss pet" spell

![mm to bm cat](https://user-images.githubusercontent.com/39439201/52178382-10327800-27ce-11e9-93d1-7d405cd47559.jpg)

- Spend all 20 in BM

![20 spent cat](https://user-images.githubusercontent.com/39439201/52178493-93a09900-27cf-11e9-8fc4-29ca05e5dd6c.jpg)

Switched BM to MM
- All 16 reset again

![all mm reset again](https://user-images.githubusercontent.com/39439201/52178494-97ccb680-27cf-11e9-9be7-c7db437c838b.jpg)

- Seems the talents are not saving the last know spec

**Comment by Dranah** [comment]
This is not a bug, happens because BM has 4 extra talent points that the system can't handle without full reset when u switch spec. Not sure if it worked same way on retail, but this has been looked at before and isn't possible to improve.

**Comment by Dranah** [comment]
There are 2 things at play here:
1. Pets are not affected by dual spec. So the same pet cannot have two different talent builds saved.
2. The 4 "wandering" talent points you only have on BM spec are not possible to keep saved when you aren't BM.
Usually, the system does not do anything to your pet talent build, it stays the same on both spec.
I.eg. If your pet has a 16 talent point build, when you switch spec, those 16 points remain intact. (for example when switching MM > Surv)
However when you are switching MM > BM, you gain 4 extra talent points that the system has no idea where to put. This is why you end up with 16 points from the previous build and 4 unspent.

When you're switching from BM to MM, a different issue comes up. You have 20 talent points spent, but MM spec allows having only 16. The system cannot identify which were the "last 4" talent points you had spent and deduct/erase. All it can do is reset the whole thing and then take away 4 points.
You can try out switching from BM to MM with only 16/20 points spent on your pet, those 16 points won't reset. It only happens if you spent all 20.

This issue has been noticed and looked at when we were fixing pets disappearing on dismiss/respec and cannot be improved. I don't have any evidence that on retail it worked differently. Even if it did, there's nothing that can be done about it.

Note: The system only checks for talent points for active pets. You can have a BM pet (typically exotic) with 20/20 talents spent, and a MM pet with 16/16.
As long as you always stable your pet before switching and only summon BM pet on BM spec, and MM pet on MM spec, their talents will never be reset.

**Comment by Echinaceax** [comment]
Thanks Dranah 
yes i totally understand as you've explained. i knew if i had Exotic pet out (as i always do in pvp) that i wouldnt have a problem switching from Exotic to another Exotic pet coz of the 20/20 yes. i only noticed this when switching to BM as you know.

thank you for explaining :)
