### ISSUE TITLE
Warlock quest for succubus

### ISSUE THREAD

**Issue by vlade1997** [WoWManiaUK/Redemption#3043]
Hello, I tried to do quest for succubus, I managed to take the first part from Silvermoon and go to Undercity and after I did not get the next quest, I made one ticket and a gm told me to try here to find the solve. My ingame name is Ayumu

https://wowwiki.fandom.com/wiki/Quest:Carendin_Summons   ( first that does not apper on Carendin that normally it should be able to pick)

https://wowwiki.fandom.com/wiki/Quest:Devourer_of_Souls_(Undercity) ( the next one )

Tried to find a link from wowhead but...useless

@wow-mania

**Comment by wow-mania** [comment]
Please read our wiki on how to log an issue. 
If you did not get the quest what is that did not work? how it should work etc? You gave me nothing here sorry.
100% sure the quest works by the way.

**Comment by Dranah** [comment]
Your report does not include what race you play. The chain is slightly different for each.
Assuming you're BE since you started in silvermoon, I have just tested with a blood elf - Alamma gives you 'Carendin Summons' and Carendin properly offers you the next one that is "Devourer of Souls". It does not even require the previous to be handed in, so I imagine perhaps you already picked that one up without noticing.
The quests work perfectly fine.

**Comment by vlade1997** [comment]
i cant take the Carendin Summons from Carendin, im orc and a gm said to take it from Silvermoon......

**Comment by vlade1997** [comment]
So it all started when I wanted to start the quest for succubus, I find orc I knew I was starting from Ogrimmar. I did not find anything there, so I made a ticket in the hope that someone helped me, answered me a gm and told me to start from Silvermoon and in Undercity at Carnedin, but I have nothing to him, I checked in Ogrimmar and there is no quest to get the pet.
I do not know what else to say

**Comment by wow-mania** [comment]
I will take another look.

**Comment by Dranah** [comment]
@vlade1997 this is the start of chain quest you're looking for: https://imgur.com/oImwW1h
Works as intended testing with a fresh level 20+ orc.

**Comment by vlade1997** [comment]
> @vlade1997 this is the start of chain quest you're looking for: https://imgur.com/oImwW1h
> Works as intended testing with a fresh level 20+ orc.

I know it but i dont have it

**Comment by Dranah** [comment]
That could be a personal issue with your character then, since it works fine otherwise. You may need to create a new ticket and have a GM help you.
Make sure you let them know it was tested and is NOT a general issue. GMs always send people here in the first place to make sure it's fixed if it's a general problem - but if it's not, they can probably just add the quest for you.
