### ISSUE TITLE
[Arena] Ring of Valor

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3052]
http://wow-mania.com/armory/?zone=4406

**Current Behaviour**
The lift's are not going up and the arena does not start which leads to players needing to leave and requeue for arena.

**Expected Behaviour**
The lifts are supposed to move up and the arena is supposed to begin.

(I stood and waited for 3+ minutes waiting for the arena to start lol)

A suggestion is to disable the arena on Redemption until it is fixed.

**Comment by Kitzunu** [comment]
No change, the elevators are not going up so the arena game cannot begin.

I flew up to check on the arena, and it's like it's frozen, there is no movement, the pillars are also in the ground.
![image](https://user-images.githubusercontent.com/24550914/52903331-08d28c00-321c-11e9-857e-5b611eb61c4e.png)
Screenshot was taken after 5 minutes of waiting.

**Comment by Kitzunu** [comment]
I just discovered that when you are in RoV it says 0 Players remaining in each team, whereas in the other arenas it says 1 player remaining in each team.

RoV
![skarmklipp](https://user-images.githubusercontent.com/24550914/52948844-eacf6d80-337a-11e9-80a5-3eecdb7c139a.PNG)
Other Arenas
![skarmklipp2](https://user-images.githubusercontent.com/24550914/52948846-ed31c780-337a-11e9-9ae8-bd40cb915b7c.PNG)

**Comment by Kitzunu** [comment]
It is way better than before, the elevators are moving and so are the other towers.

However, there are still small issues, such as the endscreen.
How it looks like:
![image](https://user-images.githubusercontent.com/24550914/52971116-8af6b800-33b6-11e9-92a9-d1250e5f83b1.png)
How it should look like:
![image](https://user-images.githubusercontent.com/24550914/52970968-fe4bfa00-33b5-11e9-8c2f-af2facad8c84.png)

Then there is the issue with the Player Remaining, on one of my screens it says 1 in each team, and on my other screen it says 0 in each screen
Player 1
![image](https://user-images.githubusercontent.com/24550914/52971010-20457c80-33b6-11e9-990e-3efd552283de.png)
Player 2
![image](https://user-images.githubusercontent.com/24550914/52971004-1a4f9b80-33b6-11e9-9971-0fbb2474f60c.png)

Then there are purple crystals at both "big pillars"
![image](https://user-images.githubusercontent.com/24550914/52971079-61d62780-33b6-11e9-82ae-38449c2e700a.png)

You also have no flag on your back for which team you are in.
RoV
![image](https://user-images.githubusercontent.com/24550914/52971105-803c2300-33b6-11e9-897e-e3533ec63583.png)
Other Arena:
![image](https://user-images.githubusercontent.com/24550914/52971363-71a23b80-33b7-11e9-9cd6-7f0f7d9b1790.png)

**Comment by wow-mania** [comment]
This was all removed and fixed.

**Comment by Kitzunu** [comment]
The issues I mentioned still persists.
The arena is working, but those issues, along with them I PMed are still there

**Comment by wow-mania** [comment]
Please retest

**Comment by Kitzunu** [comment]
The Arena is functioning now.

Elevators moves, Shadow Sight spawns correctly, Player Remaining problem fixed

**Comment by Echinaceax** [comment]
Link to 15 year old video https://www.youtube.com/watch?v=YgNjXPeGsvc

Reopening this issue, because many issues found. 

- [ ] The elevator should start at bottom not from the top, and start moving when all player are in. 
https://i.gyazo.com/de063b331c6096f519757828fbe37dcc.mp4

**What should happen** 
- [ ] Elevator should start at the bottom on entering the Arena
- [x] 5 secs after they reach the top the gates drop  (missing gates atm)
- [ ] All 4 pillars should start level with the ground.
- [ ] The 2 bigger pillars should go up after 25 secs. then after a further 25 seconds the big pillars go down and the smaller pillars going up. This is the first time the fire bars are supposed to activate. Right now the fire bars activate at the start and never again.
- [x] Fire bars always activate with the smaller pillars going up. The big pillars and smaller pillars cycle at 25 seconds each

we cant find gate objects atm @Rushor 
This is what they look like 
We will talk to you more in the dev channel on discord

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/7ae01cfc-451d-445c-8b79-4f29842aa42a)

**Comment by Lumber-Jack-2** [comment]
fences added,
objects spawn fixed for live realm apply
elevator should start at ground

**Comment by Maine1** [comment]
@Rushor Elevators spawn still above. Battle starts too early now with players still below. After getting ported to the top. elevators are stuck on the bottom.

**Comment by Lumber-Jack-2** [comment]
all fixed

**Comment by Lumber-Jack-2** [comment]
- pillars up always now, the collision from ivory is deactived, all others cillisions from pillars are active
- elevator starts at top
- fences added and will drop on start
- elevator/pillars and aoe effect interaction fixed

**Comment by Echinaceax** [comment]
also checked the achv is given 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/211432de-fa4a-44cc-885a-ead2e71122ac)
