### ISSUE TITLE
[Pet] Risen Ghoul

### ISSUE THREAD

**Issue by bluemonstrr** [WoWManiaUK/Redemption#3086]
The base HP of the ghoul should be 13380 at level 80, currently it is spawning with 5.9k from a character with 9.6k hp and no talents.

![image](https://user-images.githubusercontent.com/33989250/53421563-b834fe80-3992-11e9-898e-d3746862f44e.png)
![image](https://user-images.githubusercontent.com/33989250/53421604-c84cde00-3992-11e9-8d6a-fb189bd54a3f.png)

It is also dying constantly to any aoe in raids, assuming it's because they're not spawning with any resistances? Either way, a ghoul will 100% die now on any Sindy/LK fight from random aoe damage.

As far as I know, no pet should die to Blistering Cold.

**Comment by wow-mania** [comment]
Where are you getting that info from? Can you back it up with info from 3.3.5a

**Comment by Dranah** [comment]
Base HP of ghoul has never been 13380 on wotlk. (I believe that is the cataclysm value)

Since the last stat fixes, ghouls health and bonus stamina is 100% blizzlike.
I know that may sound impossible, but here's a little comparison: 
Video from retail 3.3.5a with a well-geared PVE unholy DK with 3/3 Ravenous dead and glyph of the ghoul. https://www.youtube.com/watch?v=Cp3nIhf2tfk
1999 stamina and 27931 health on the DK, 22932 health on the ghoul.
Recreating a DK with matching stats on mania, the ghoul has now the exact same 22932 health.
![wowscrnshot_022619_183454](https://user-images.githubusercontent.com/31132743/53433753-4e9a0c00-39f5-11e9-8219-f79394b269f0.jpg)

As for the AOE reduction, ghouls do not innately have reduced AOE damage taken.
It requires the unholy talent Night of the Dead 2/2.
With the talent, AOE damage taken is properly reduced. Here's damage of blistering cold on a ghoul with 2/2 NoTD 
![wowscrnshot_022619_183724](https://user-images.githubusercontent.com/31132743/53433884-a59fe100-39f5-11e9-90d6-09e78d43b67b.jpg)

I hope this answers all your questions.
