### ISSUE TITLE
[Spell] Explosive Shot + Aspect of the Viper Interaction

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#3088]
How it is working atm: While Aspect of the Viper is active, Explosive Shot 2nd and 3rd ticks are NOT regenerating any mana from that source. 

How it should work: While Aspect of the Viper is active, every tick from Explosive Shot SHOULD regenerate the fixed amount of mana.

https://wow.gamepedia.com/Aspect_of_the_Viper

**Comment by Kitzunu** [comment]
http://wow-mania.com/armory/?spell=60053
http://wow-mania.com/armory/?spell=34074

![image](https://user-images.githubusercontent.com/24550914/53449844-1f969100-3a1b-11e9-922c-e6e6f48eaded.png)
Confirmed, only one of the Explosive Shot Proccs triggers Aspect of the Viper

**Comment by Keader** [comment]
Dont think so... if i remember right just initial damage should regen health.
Gamepedia is wrong. It say that all ticks of Volley should regen mana and it's a lie.
I realy belive that this issue is invalid.
@Dranah can make some research here?

**Comment by crulinjr** [comment]
" Aspect of the Viper caused each ranged attack (including the initial application of  [Serpent Sting], all three charges of  [Explosive Shot], all three missiles of  [Multi-Shot], **but not including the ticks of Serpent Sting or the damage of  [Volley]**) to generate a percentage of the Hunter's maximum mana. "

**Comment by Keader** [comment]
yes i miss read it.
But i still dont belive that it's a bug.
Since it can be considered a DOT, and checking aspect of the viper, dots cant proc it.

**Comment by Kitzunu** [comment]
I cannot find any up to date info that backs this.
Aspect of the Viper is not found on WoWHead
Explosive Shot only have Changelog and Comments from BFA.

I have checked forums but have not found anything that backs it either.
Only info about this I find is on WoWWiki and WoWPedia

**Comment by crulinjr** [comment]
Well both sources seems to be really accurate in terms of how AotV work. Ill keep searching.

**Comment by Dranah** [comment]
As far as I know, explosive shot is not really considered a DoT, it's more like missiles. And the wowwiki page regarding this is fully accurate to 3.3.5 because patch 4.0 removed mana as a resource for hunter and the ability Aspect of the Viper too.
I've found that the effect of explosive shot eventually re-checks the 50% damage penalty from aspect of the viper on each charge. Meaning, if you turn off viper after first missile, it will cause the remaining charges to deal full damage. (This part works on mania too)
So i'd say, since each charge of the spell is checking separately for viper aspect active to deal half damage or not, it should also be checking mana restore on each. i.eg. if you cast ES with viper aspect and then turn off after the 2nd missile, the first two missiles should deal half damage and both should restore mana, the 3rd one will do full damage and not restore mana.
That's my 2cent.

**Comment by Keader** [comment]
Well, i will trust in this one.
Fixed.

**Comment by Dranah** [comment]
Each charge of Explosive shot that fires while aspect of viper active now restores mana as well as dealing half damage.
