### ISSUE TITLE
Glyph: Glyph of Flame Shock

### ISSUE THREAD

**Issue by Aristo14** [WoWManiaUK/Redemption#3102]
Hello all, 

let me start with refering to an earlier report: https://github.com/WoWManiaUK/Redemption/issues/2716

I did read that one and it did clarify a lot. 

However by using the calculations from that report about the crit bonus damage, I did find some 
discrepencies: 

### **results in game**
1113 dot (100% + 50% crit bonus) meaning 100% = 742
dot with glyph in game is **1279**

2812 Flame Shock (100% + 50% crit bonus) meaning 100% = 1874,6
FS with glyph in game is **3233**

### **how it should be**
1113 dot  = 742 without crit bonus 
742 *1.8 = **1335,6**   
_(resulting in a -56.6 difference in game versus expected)_ 

2812 FS = 1874,6 without crit bonus
1874,66 *1.8 = **3374.4**   
_(resulting in a -141.4 difference in game versus expected)_ 

As allways, thanks for your effort and time!

**Comment by Dranah** [comment]
I just made a test and maths checks out for me (just like it did last time when report #2716 was checked). Test char without talents and minimal gear, no procs etc
Flame shock initial non-crit: 429
Flame shock tick noncrit: 131
Flame shock initial crit without glyph: 643
Flame shock tick crit without glyph: 196
Flame shock initial crit glyphed: 771
Flame shock tick crit glyphed: 235

429 x 1,5 = 643
131 x 1,5 = 196
429 x 1,8 = 772 (the 1 digit difference comes from the actual calculation being 429 + (429 x 0,5) x 1,6. The system rounds down at each partial-calculation which is why a digit is lost here and there)
131 x 1,8 = 235

It is unclear to me if you're using any talents, bonuses or the crit damage meta that could affect your test results.

**Comment by Aristo14** [comment]
I was actually looking into it again myself as well. 

My base number is too high because it allready got some extra crit bonus.. making the calculation wrong. 

Sorry for wasting your time, my apologies for the inconvenience.

**Comment by wow-mania** [comment]
@Dranah Thanks for that.

**Comment by Aristo14** [comment]
I re-read the former report again.. 

There are 2 different calculations in there, making it hard to understand. 
My previous calculation is wrong indeed.. i forgot the elemental furry bonus. 
Making my base number wrong. 

Sorry for wasting your time, apologies for the inconvenience.
