### ISSUE TITLE
Ruby Sanctum/Baltharus the Warborn, random target loss during encounter.

### ISSUE THREAD

**Issue by svijetlonosa** [WoWManiaUK/Redemption#3110]
During the encounter with Baltharus the Warborn
https://www.wowhead.com/npc=39751/baltharus-the-warborn
 in raid Ruby Sanctum, players experience  random loss of target on Baltharus the Warborn.
That should not happen while you fight him, apart from moment it use  https://www.wowhead.com/spell=74509/repelling-wave  and clone him self

**Comment by Drostthehunter** [comment]
Same thing used to happen on Rotface 1 year ago in Icecrown Citadel, people randomly losing focus of target, and it happens again on Baltharus for the past 2 weeks since you did fix his health points issue.

**Comment by svijetlonosa** [comment]
yes , but i see post is closed so i will not bother with reporting things aynmore , there is enough GMs and testers to do so

**Comment by Kitzunu** [comment]
I will look into this issue tomorrow when I have time

**Comment by Dranah** [comment]
@svijetlonosa janitor does that all the time, it does not mean that the report is ignored
Testers still look at it as soon as they can and if we find something that can be reproduced, it'll get reopened and fixed.

**Comment by svijetlonosa** [comment]
yes my choice to spend my time and energy that non can give back to improve server for everyone, it is not game braking i can easy re target, it is just irritating and everyone complains for it . So after spending time on it to explain best i can and know how you just get ignore/close.
As i told i wont waste my time anymore , as here only if you pay big or you are staff or friend of staff some one will listen to you . thx for reading. ones gain here good luck and good bye

**Comment by Kitzunu** [comment]
@svijetlonosa me and dranah will look into this issue tomorrow.
But as she said, sometimes Janitor closes issues. That doesnt mean they wont be tested.

**Comment by Echinaceax** [comment]
@svijetlonosa 
Try not to take this personally ..your not the only one this happens too believe me.
It Certainly isnt about who pays BIG (i dont pay big) and has happened too me too.
Janitor closes them prematurely yes. but has all testers can still see and work on closed issues thats not a problem for us.

Reproducing can be the biggest issue, so the more info you can give when you make a report the easier it is for testers to get together and get the same bug as you did and that can help a real lot

**Comment by svijetlonosa** [comment]
Can i kindly ask to stop tagging me in those posts, and when tester compare them self to rest of population on server is just LOL , not same rules apply to all, just see who is getting promotions , how is it getting them and why and who is winning events :)
so please leave me out of this :)
and how to reproduce it got to damn RS start encounter with boss  and you will see , for last 2 weeks 25 players say same thing and all you can not reproduce it , do you know where RS is ? 
But enough about i'm out of this so pls do not tag me in your posts :) thx in advance

**Comment by Echinaceax** [comment]
Very well

**Comment by Dranah** [comment]
Since svijet says it's an unimportant minor issue, a mere annoyance that is easily fixed by re-targeting the boss, I suppose it's no use wasting our time on this.
I'm too busy getting promotions and winning events anyway.

**Comment by svijetlonosa** [comment]
usual professional behavior of server staff (GMs, tester...) 
keep up the good work :) :D 
wonder if some one other wrote report how it would be don :D

**Comment by Dranah** [comment]
If someone else wrote the report, perhaps they would have focused on collecting more details and providing the necessary information to reproduce the issue instead of wasting the same energy to mock testers/staff.
Nonetheless we have looked into the issue (both me and kitzunu) and could not find a way to reproduce it. Yes, we went into RS and spent 10minutes punching Baltharus, killed him multiple times and never once he dropped target randomly. Thus the label - cannot reproduce.
It is possible that something specific (a spell players use, a debuff, the way he's positioned, etc...) triggers the problem, which is why we asked for more information. Something that could narrow the wide range of options to a number that can be reasonably checked out. 
If your attitude towards this is that "it's your problem why should i help, it's not important to me anyway" then we have no ways to go on and rightfully ask ourselves, why should we care if you do not?
In contrary to your claims, testers are not staff members. We are just players, who put time and effort volunteering to help fix bugs. We have no contract that says that we should tolerate being trashed. If you do not respect or acknowledge our effort, and don't seek to help our work by cooperating and answering our questions properly (not with bullshit rant about how we're too stupid to go into RS), I don't understand why you expect us to give our heart and soul to help you.
