### ISSUE TITLE
[Ruby/Spells] Baltharus Enervating Brand applied to too many players

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#3127]
Was stacking even if player has distance > 12 yards.
Reported by @TheManiax  on discord.

**Comment by Dranah** [comment]
There is nothing wrong with the range check.
The problem is that the amount of brands applied by the boss are wrong. He brands too many players as main targets.

**Comment by wow-mania** [comment]
Is this a valid issue at all?

**Comment by Dranah** [comment]
Yes and i modified the title to reflect to the problem. The stacking was crazy but has nothing to do with the range check that Keader/Maniax described. I have asked keader to revert his fix and fix the actual problem behind it, which is the number of targets for the spell https://www.wowhead.com/spell=74505/enervating-brand

**Comment by Dranah** [comment]
UPDATE:
A little extra info
https://www.wowhead.com/spell=74502/enervating-brand is the main cast by Baltharus , on 1 player every 30s
https://www.wowhead.com/spell=74505/enervating-brand is the splash effect for players within 12 yards of the main target, can hit unlimited player count every 2sec while the main brand is active on the main target.
**How it should work:** 
There should be only 1 main target for the brand every 30sec when the boss casts it, regardless of difficulty.
/A little explaination and evidences/
- Nowhere it is stated in the spell's description or boss guides for Baltharus/RS that the brand should hit multiple targets.
DBM cannot differentiate the two spell IDs, so on most videos it's impossible to see how many main targets there are, but I found some where it's clearly distinguishable:
Here's a video from 2010 june a week after the launch of RS, where you can see how the stacking behaves: https://www.youtube.com/watch?v=TgFWwiU_t_Q
0:58 Enervating Brand on Integrity (main target)
Boss receives one stack of Siphoned Power (this would be impossible with multiple main-targets)
1:00 Enervating Brand on Carvilla (secondary target)
Boss receives +2 stacks one for the main target (Integrity) and one for the secondary (Carvilla)
1:03 Enervating Brand on the entire melee camp as the rest of the melee DPS moves back and stacks up on the main target, Boss receives 9 extra stacks, making it a total of 12.

And here's a video from 10man too https://www.youtube.com/watch?time_continue=38&v=aDUVgJjIyJg
0:38 Enervating Brand on Cassettte (main target)
You can see on his clear raid UI that there is one target with 2 debuff (cassette himself) and 3 more appears with just one (secondary targets, you can see each of their name in Cassette's range check window)

**Comment by crulinjr** [comment]
I am doing a RS just right now and the Enervating Brand is stacking despite beign further than 12 yards from everyone and the boss

**Comment by Dranah** [comment]
@crulinjr let's clear up some confusion. 
- The 12 yard range check is done between the target of the main brand (74502) and other, non-branded players nearby. 
- This range check works as intended, targets within 12 yards of the original target of 74502 receive the secondary effect (74505) from the brand, targets further do not. This has never been broken.
- The original target of the main brand (74502) always receives a stack of the secondary effect (74505) every 2sec, regardless of where he is or what he does. Distance from the boss is irrelevant. This is also intended.
- This means the boss will receive a minimum of 5 stacks (74505) from each brand (74502), even if the original target of 74502 is absolutely isolated. This is also intended. 
- More commonly however, the brand will hit at least 6-8 secondary targets while the main target runs out with it, and the boss will get a stack for each, averaging out in 20-30 stacks total per brand on 25man difficulty.
- The problem is currently that the main brand (73502) is applied to 10 targets instead of one. This means, it absolutely doesn't matter where they move, all the 10 brands (74502) keep adding stacks of 74505 to their own target and boss, and also people within 12 yards. 
This is the bug under fixing.

UPDATE:
Enervating brand (74502) is now only cast on one target at a time.
