### ISSUE TITLE
[Dungeon] NPCs 1 HP bug

### ISSUE THREAD

**Issue by Yhato794** [WoWManiaUK/Redemption#3135]
Can you do something about this is getting really annoying a lot of mobs in dungeons get stuck on 1HP we are forced to finish with 2-3 mobs attacking us. 
I'm sorry i can't help more but i can't really understand what is causing the bug it appear to me to be random.
![WoWScrnShot_031819_112203](https://user-images.githubusercontent.com/29119984/54523971-05dccf80-4971-11e9-8566-65994b579bc1.jpg)

In the screenshot there are 2 adds stucked at 1HP and that bugged out Arthas in combat and we couldn't finish the dungeon. 
Can you take a look into this thanks in advice

**Comment by Kitzunu** [comment]
Which NPC's are in this state?

**Comment by wow-mania** [comment]
First of all, go read the wiki on how to log an issue. Your feelings do not add any information to the issue.

**Comment by Yhato794** [comment]
Well today it was in The Culling of Stratholme, but i got the same bug in Fos/Pos/Hor

**Comment by Kitzunu** [comment]
@Yhato794 it would help A LOT if you could give me the Names, IDs or Links to the NPCs that this happened to. 
Im sorry to say but having 1 screenshot with 0 information doesn't help at all

**Comment by Yhato794** [comment]
I'm sorry i can't remember the NPCs in Fos/Pos/Hor. I guess you can just fix the Patchwork Contrust in my screenshot and if i got more bug i can idk post it here will that be good? 
https://www.wowhead.com/npc=27736/patchwork-construct

**Comment by WhitephoenixTheBunny** [comment]
The issue may not be only related with the NPC
I have done CoS 2 days ago and I didn't had the bug
That's why we need all the info possible to reproduce the issue.

Dificulty of the instance
If you wiped or not
if someone died and ran back
If someone was ress'ed
classes and races in the party

The bug can be caused by "n" things and need be analised :)

**Comment by Yhato794** [comment]
@WhitephoenixTheBunny ye agree the bug is really random but in that stratholme run we didn't wipe and no one was ress'ed

**Comment by Yhato794** [comment]
@Kitzunu I'm sorry i wish i could help more but i didn't run that stratholme with a tester mind set taking note of everything it just happened. I hope you can solve it

**Comment by Kitzunu** [comment]
@Yhato794 Quick question, do you know which spec the DK had?

**Comment by Yhato794** [comment]
@Kitzunu Unholy

**Comment by sarahkay88** [comment]
J just ran halls of lighting hc https://www.wowhead.com/halls-of-lightning and this happened on  the boss https://www.wowhead.com/npc=28587 one of the minions he summons stayed at 1hp and wasn't attackable. leaving the group in combat bug. (
We haD an ele shammy, resto shammy, hunter, warrior and a lock. just before we pulled the hunter left the party ) and our lock had died - if this helps at all) It didn't effect our game play tho. the minion didn't move

**Comment by WhitephoenixTheBunny** [comment]
Did warlock use Rain Of Fire?

**Comment by sarahkay88** [comment]
Nope

**Comment by sarahkay88** [comment]
But then again I just ran col of strat hc with lock n shammy n had no issues so good luck trying to work this one out.

**Comment by Dranah** [comment]
i'll run a couple dungeons myself and see if i figure anything.
One thing i can surely tell is that this bug is only about 2months old, that's when the first occasions happened , never before i've heard/seen of such. 
So it must have something to do with one of the updates near the beginning of february.

**Comment by WhitephoenixTheBunny** [comment]
Me and kit, thought that DK could cause it, unholy...
I have speced my dk to unholy, but no bug
Also i saw ppl speaking over warlock and rain od fire...

dunno really

**Comment by Yhato794** [comment]
It happened again with Falric first boss of hor, again with an unholy death knight.
https://it.wowhead.com/npc=38112/falric
![WoWScrnShot_032019_122616](https://user-images.githubusercontent.com/29119984/54681048-b41c7c80-4b0b-11e9-84ac-3cdeb015a0fe.jpg)


I screened the dk talents maybe is one of those that bugs the npc
![WoWScrnShot_032019_122857](https://user-images.githubusercontent.com/29119984/54681109-dd3d0d00-4b0b-11e9-9e65-ecda090596ab.jpg)
![WoWScrnShot_032019_122859](https://user-images.githubusercontent.com/29119984/54681123-e1692a80-4b0b-11e9-9042-e3346bad4a5b.jpg)
![WoWScrnShot_032019_122902](https://user-images.githubusercontent.com/29119984/54681125-e332ee00-4b0b-11e9-8dd7-f6c175d23350.jpg)

I hope that will help

**Comment by WhitephoenixTheBunny** [comment]
I have a request:
When you get the bug, and try the boss again, ask to the UH DK to NOT summon gargoyle...

I have been trying using uh dk, but i sux at it :/ and i can't manage reproduce the bug

**Comment by Keader** [comment]
Ok, we need a reproduce case...
without it, is impossible to me fix.
But looks like is caused by DK... because i cant find nothing in Creature script that can cause the bug.

**Comment by Yhato794** [comment]
@WhitephoenixTheBunny  We disbanded after that but you should test Hor with a UH dk + demo lock i believe is some interaction between them

**Comment by WhitephoenixTheBunny** [comment]
@Kitzunu have ran a HoR HC with an unholy dk and bugged, and it didn't had a warlock

**Comment by Keader** [comment]
Ok, i think that is caused by ```SPELL_AURA_MOD_INCREASE_HEALTH```
Kitzunu send me a old trinity fix about it.
Checking if fix was applied in wow mania, i found some weird checks, that can make a creature has a weird health values.
I make adaptations and put more close of trinity behavior.
I think that will fix it, but since i cant reproduce... @wow-mania  need deploy it to Redemption and check if new reports will appear

**Comment by Dranah** [comment]
Managed to reproduce issue with unholy DK's scourge strike on Falric on Redemption , however a number of other factors are still unclear as not every scourge strike cast triggers the bug.
may or may not be related to fix https://github.com/WoWManiaUK/Redemption/issues/3050
![WoWScrnShot_032119_004657](https://user-images.githubusercontent.com/31132743/54727200-c8e22a00-4b76-11e9-8377-018b04f9ff86.jpg)

I may not be able to reproduce it on PTR due to the other factors mentioned, so either you push fix to Red, or revert it for a while until I get the missing information needed to steadily reproduce on PTR too.
Tomorrow, it is.

**Comment by Dranah** [comment]
UPDATE:
Ok I managed to reproduce the issue on PTR.
It requires a DK to use SS with at least 1 disease on target (to be eligible to proc SS - shadow), and a debuff active on the death knight which modifies their damage and healing negatively.
This is what baltharus, BQL, falric and all those dungeon trash where it occured has in common, the presence of a debuff effect that reduces damage and healing. 
It's most likely caused by https://github.com/WoWManiaUK/Redemption/issues/3050 fix, as a side effect it seems that Scourge strike - shadow acquired the ability to benefit from these debuffs, causing some kind of error which results in the spell healing for 2147million and bugging the mob it strikes.

**Comment by Dranah** [comment]
It seems fixed. Was an unintended line in the SS fix.
Thanks to everyone who gave feedback and information about where they have encountered this issue, it has greatly helped to find the root of the problem. 
Unholy DKs will retain the fix on improving scourge strike shadow but it should no longer bug enemy mobs.
