### ISSUE TITLE
[Spell] Harvest Soul

### ISSUE THREAD

**Issue by Neliha** [WoWManiaUK/Redemption#3174]
**Links:**
I do not have screenshots, but it happened to a few of us raiding LK in 10hc/25hc. Will update it with screenshots if necessary once I get them.

**What is Happening:**
Once we get all grabbed to go into Shadowmourne, certain players (both next to the edge and the ones who are placed more towards the centre when grabbed) sometimes get pulled over the edge of the platform. This causes them to fall down once we get back out after the Shadowform phase. It has happened 3 times now, and it's becoming annoying to have to wipe because a couple of people fall. We tried centring ourselves more to the middle, but some characters would still be pulled out and over the edge. 

**What Should Happen:**
I don't think that when the LK grabs you and pulls you in, the characters shouldn't move as much when getting "strangled".

Please, have a look into this.

**Comment by wow-mania** [comment]
As-is.

**Comment by Dranah** [comment]
Yeah ok, I see the issue.
On retail videos, the mechanism drags each person towards LK.
On mania... well it works fine as long as nobody moves. But in a usual raid situation where LK is non stop dragged around and people are moving around too, the following keeps happening:
- Some far people aren't moved at all
- Most people are dragged towards some imaginary spot 10-15 yards away from the LK in a random direction
- Sometimes different players travel towards different spots, i.eg. one group is moved from A>B, other from B > C, etc.
- There are people being moved away from LK, not towards.
I understand if this is difficult to make fully blizz-like, but this needs an improvement.

How it should work:
People near LK (like in melee range) are not moved at all.
People further away are moved straight towards the LK.

Retail vid: https://www.youtube.com/watch?v=lO8KFr6oIZ0

PS: I've tested a few theories like if the spell has some delay on snapshotting LK's position or something, but it does not seem to be the case. I could not find a pattern yet how the spell chooses the "focus point" for where to aim players, if it uses one at all (i am sceptical because then it wouldnt be possible that 2 different players are moved into 2 very different spots)

**Comment by Keader** [comment]
Try now.

**Comment by Dranah** [comment]
Looks much better to me. I can no longer reproduce people being dragged in stupid directions.
I still found sometimes ppl not moved, but we can live with that.
