### ISSUE TITLE
[Spell] Thorns 

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Redemption#3183]
**Links:**

[Thorns](http://www.wow-mania.com/armory/?search=thorns#abilities)
**What is Happening:**
 Dont scale with lvl

**What Should happen:**

need to scale with lvl.

![image](https://user-images.githubusercontent.com/6819293/55917002-4507e480-5bee-11e9-9a64-fe46b7bd3d8b.png)

**Comment by WhitephoenixTheBunny** [comment]
Tested on Redemption:

Rank 1
![image](https://user-images.githubusercontent.com/31921098/55940110-5d502180-5c37-11e9-846d-4b7322e0316d.png)

Rank 2
![image](https://user-images.githubusercontent.com/31921098/55940132-67722000-5c37-11e9-88a4-c64bfa786ae5.png)

Rank 3
![image](https://user-images.githubusercontent.com/31921098/55940160-72c54b80-5c37-11e9-986d-d5b31942afad.png)

Rank 4
![image](https://user-images.githubusercontent.com/31921098/55940190-81136780-5c37-11e9-995b-0fc58a17148c.png)

Rank 5
![image](https://user-images.githubusercontent.com/31921098/55940223-95576480-5c37-11e9-8b14-14b1edc378dd.png)

Rank 6
![image](https://user-images.githubusercontent.com/31921098/55940269-ae601580-5c37-11e9-81aa-20d12d8ab55c.png)

Rank 7
![image](https://user-images.githubusercontent.com/31921098/55940301-be77f500-5c37-11e9-856f-7dc5434c1c37.png)

Rank 8
![image](https://user-images.githubusercontent.com/31921098/55940331-cdf73e00-5c37-11e9-82ed-c284c75a5d75.png)


Did you trained ranks on trainer?
Did you verifie if the Spell on your action bar is the higher one?

**Comment by Echinaceax** [comment]
@WhitephoenixTheBunny 
He forgot to mention ...he is a lvl 11 warrior at the time and i (80 Druid) buffed him with thorns
So his lvl 11 warrior was doing 101 dmg

**Comment by Dranah** [comment]
The problem is the spell power coefficient.... the ranks work fine, and higher level druids' spell is also properly ranked down when a low level player receives it,
It is the low rank penalty that does not work, which is meant to reduce the spell power coefficient for lower ranks once the caster druid has outleveled it. This penalty should also be applied if the spell is downranked because of being cast on a lower level player.

There was a similar issue with life tap's penalty, which you can't find on github here because it was taken to the exploit section, so i'll copy over the important part:
**The penalty is calculated as : (22+maxcastlevel -casterlevel) / 20 = % of the full SP coefficient of the maxrank, where maxcastlevel is the highest level before learning the next rank and casterlevel is the current level of the caster.**

**Maths:** 
Thorns has 8 ranks. Rank 8 is learned at level 74 and there is no higher rank. This means for a level 80 character, rank 8 receives the full spell power coefficient which is 3,3% per hit.
On my test char, this is +29 damage at 893 spell power, making it total 73+29=102
Rank7 is learned at level 64, and since you can learn the next rank at 74, the maxcastlevel for this rank is 73.
Using the formula:
(22+73-80) / 20 = 75%, so the Rank7 spell must receive 75% of the total SP coefficient, which is 0,75 x 3,3 = 2,475%.
Rank6 is learned at level 54, and the maxcastlevel is 63, since you can learn the next rank at 64.
Using the formula:
(22+63-80) / 20 = 25% of the total SP coefficient, so 0,25 x 3,3 = 0,825%.
Rank 5 and below would give a negative result with the formula, which means the SP coefficient is simply zero.

Summary -
How it should work:
Rank 1-5 Thorns should have zero spell power coefficient due to the low rank penalty.
Rank 6 should receive 25% of the normal 3,3% coefficient, being 0,825%.
Rank 7 should receive 75% of the normal 3,3% coefficient, being 2,475%
Rank 8 should receive the full 3,3% coefficient per hit.

How it works atm:
All ranks of thorns receives the same 3,3% SP coefficient. While there is no sense to downrank Thorns when in a level 80 environment, the spell becomes immensely powerful for lowbies that receive a lower rank version of the spell, because it retains the full SP coefficient from a level 80 caster.

**Comment by Keader** [comment]
try now

**Comment by Dranah** [comment]
Well, we made a workaround, so the spell works good now if a level 80 targets a lvl 80, and also if a level 80 debuffs a very low level.
Numbers are slightly off in the level 60-70 range, but nothing gamebreaking.
Not fully blizzlike, but it is functional.
