### ISSUE TITLE
[Client] Transmog Staff's & Polearms Wrong Displayed

### ISSUE THREAD

**Issue by Mageone** [WoWManiaUK/Redemption#3190]
**Links:**
Hello,
I bought today a Guardian Spire from Harrison Jones, the seller of Artifacts from Mall, i did transmogrified my staff Dying Light and now the spire goes down. It's up side down.
![Clipboard02](https://user-images.githubusercontent.com/49594781/56083495-6eaf4e80-5e2e-11e9-8dc9-c6b9a6a5e6b8.jpg)
![Clipboard03](https://user-images.githubusercontent.com/49594781/56083496-70791200-5e2e-11e9-8f0b-b8686ce16fe8.jpg)
![Clipboard04](https://user-images.githubusercontent.com/49594781/56083498-7242d580-5e2e-11e9-8512-2c037a8cc201.jpg)

I bought in the past a Magna Unleashed to transmogrify my staff and i had same trouble. I hoped this problem will be fixed with the new staff from today, but nothing... It looks bad, not neccessary.  Did i waste 10 Transmog Token and 10Maniac Points or i can hope to be fixed this problem? I didn't think that i have to google if it's any bug or trouble or wasted money if i wanna transmogrify the staff.

**What is Happening:**

**What Should happen:**

**Comment by wow-mania** [comment]
Please add links to armory.
This is a client-side issue and can't be solved without a client update.

**Comment by Mageone** [comment]
Thanks for the quick reply!
The link of artifact bought today, Guardian Spire [http://us.battle.net/wow/en/item/150217](url)
The link of my Dying Light staff is [http://us.battle.net/wow/en/item/50181](url)
The link of the other artifact with same problems, Magna Unleashed [http://us.battle.net/wow/en/item/150218](url)
I did delete the Cache folder and updated the client. I use WoW Mania client.

**Comment by WhitephoenixTheBunny** [comment]
They're more, I will add the links ASAP

**Comment by WhitephoenixTheBunny** [comment]
I just have googled all Staves and polearms sold by Harrison Jones, and all are upside down
Since I can't get the WoW-Mania Armory links, I will give ID (mania ones) and Name.

Staves:
150116 - Aluneth
150108 - Scythe of Elune
150109 - G'Hanir, the Mother Tree
150118 - Ebonchill
150120 - Fu Zan, the Wanderer's Companion
150121 - Shilun, Staff of the Mists
150137 - Ligh's Wrath
150138 - T'uure, Beacon of the Naaru
150143 - Ulthalesh, the Deadwind Harvester
150144 - Scepter of Sargeras
150194 - Lunarcall
150193 - Envoy of Goldrinn
150195 - Nightmare's Afflication
150196 - Manascythe
150197 - Sunkeeper's Reach
150198 - Eldertree
150199 - Crystaline Awakening
150200 - Deadwood Keeper
150201 - Warden's Crown
150202 - Night's Vigilance
150121 - Eagle's Rebirth
150217 - Guardian Spire
150218 - Magna Unleashed
150219 - Aegwynn's Fall
150220 - Eternal Magus

Polearms
150213 - Spear of the Alpha
150221 - Woolomancer's Charge
150216 - Bear's Fortitude
150215 - Forests' Guardian
150214 - Serpentstrike

**Comment by Mageone** [comment]
Many thanks!

    Pe joi, 18 aprilie 2019, 10:35:29 EEST, Janitor <notifications@github.com> a scris:  
 
 
Closed #3190.
