### ISSUE TITLE
[Boss] Professor Putricide 25hc - Oozes

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#3209]
How it works atm: Today i got targetted by the Green ooze on 25HC while having the Orange Variable on me. 
https://wowwiki.fandom.com/wiki/Professor_Putricide

How it should work:
While having either Green or Gas varible during transition you CANT be targetted by the other one until the debuff runs out.

**Comment by Kitzunu** [comment]
http://wow-mania.com/armory/?spell=70353 10hc
http://wow-mania.com/armory/?spell=74119 25hc
You have the Gas Variable! **You will be targeted with things that also have the Gas trait** and are unable to harm Ooze creatures. *Instant, lasts 1 minute*

http://wow-mania.com/armory/?spell=70352 10hc
http://wow-mania.com/armory/?spell=74118 25hc
You have the Ooze Variable! **You will be targeted with things that also have the Ooze trait** and are unable to harm Gaseous creatures. *Instant, lasts 1 minute*

To me, by reading the tooltip of the different spells, this sounds like a valid issue.
This would go for both Heroic dificulties

**Comment by crulinjr** [comment]
Why is it closed?

**Comment by Dranah** [comment]
It's invalid. The oozes cannot target the same target with their fixates, but Variables do not affect their targetting. Mania armory is not always depicting blizzlike state.
Here is a retail video where you can see: 
https://www.youtube.com/watch?v=tTY443f4UTM
At 2:04 "Khary" (red cross rogue) is targeted by the Red Ooze while having the green Ooze variable debuff.
At 2:21 "Endz" (rogue marked with skull) is targeted by Green Ooze while having the red Gas Variable

Also, according to wowwiki, on 10heroic there aren't even meant to be variable debuffs...
"In 10-player mode, there are no Variable debuffs, but he still spawns both a Volatile Ooze and a Gas Cloud at the same time instead of casting Tear Gas. "
So i'm not sure what those spell IDs are at all which you say belong to 10hc o_o
