### ISSUE TITLE
[Raid] Sunwell Plateau

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#3223]
We were running Sunwell Plateau and ran into an issue where 2 of out guys died somewhere after the 3rd boss the Poison Dragon one. They tried to get back in but got ported to a different instance of the raid. Tried a to remove and resummon but it didn't work.

**Comment by Kitzunu** [comment]
Please read CONTRIBUTION.md and use the issue template when you log an issue.

Thank you

**Comment by Kitzunu** [comment]
You are not really giving us any information.

Please provide which boss
Which location
How to reproduce

I will close the report until more info is added

**Comment by Bartok14** [comment]
This appeared to be an issue for 2 members of our raid group. They had joined us for the first 3 bosses of Sunwell Plateau we were in the same raid instance, then after we killed the 3rd boss Felmyst, we started making our way up the zig-zagging ramp (see image). I'm not sure if they were with us at this point as the appeared to be afk after the felmys fight, but I know that our raid group was still working our way up the stairs when they both died. When you die in a raid you are supposed to be able to run back to the entrance and re-enter the same instance. They ran to come back into the raid but for some reason it teleported them into a separate instance of Sunwell Plateau. We tried kicking them, letting them hearth, and re-summoning them but nothing worked and they could not phase back into our instance. 

I can only assume the following, either trash respawned in the Dead Scar and killed them, or somehow died from trying to go out of bounds in the fire area, or they died by falling from the stairs, which I doubt. I would not know how to reproduce this problem other than completing the first 3 bosses of Sunwell Plateau, have someone kill the trash on their way up the stairs and have someone stay down in the Dead Scar where you first encounter Brutallis. Another possibility is that those Explosive Fire Adds that you encounter later in the raid somehow made it down there and one shotted them. Which makes sense since they seemed to die instantly. 

I would not assume this to be an addon issue or ui problem as I wiped a few times in here and I have an extensive UI. I also do not know if they are using your client but I assume they must as they have been playing for a long time on this server. 

Some other notes about the raid are that we wiped on the first boss, and once on Brutallis, and once on Felmyst, so it's possible that might have had something to do with it.

https://www.wowhead.com/npc=25038/felmyst

![Felmyst](https://user-images.githubusercontent.com/32959403/56993151-bf7eb100-6b69-11e9-8860-1de28edcec44.jpg)
![Sunwell Plateau](https://user-images.githubusercontent.com/32959403/56993155-c1e10b00-6b69-11e9-9157-ada615862caa.PNG)

**Comment by Kitzunu** [comment]
Thank you for your added info :)

**Comment by Dranah** [comment]
So 2 people got bugged and supposedly there are two problems
1. Why they died?
2. Their raid ID bugged

For the first one, the way you're guessing around tells me they didn't provide any useful information about it, so it most likely wasn't a bug. People die to random stuff while afking...

For the second, I don't think this has anything to do with Sunwell, Sometimes raid IDs behave weird, even reset for no reason. It happens when someone zones out, either because they die and release, or because they finished the instance.
I've seen this happen with level 80 raids too, my Ulduar ID time to time disappears, and if I wipe and get ported out, I have to clear the bosses again. People raiding ICC have reported similar anomalies, people doing a full run, and then not having an ID an hour later...

It'd be nice to know if those two people still had their IDs when they tried to zone in again, or it was reset like in the above cases.
Usually the whole raid leaves the instance together, so they aren't separated, but in your case only the two who died and released got separated.
If this happens, the only way I found to rejoin the groups is to have EVERYONE go out, disband the raid, remake with a leader that still has the ID, let him enter first, and then the rest of the group follow. This way the people who lost their ID can pick up ID from the one who still had it.
Sometimes it leads to everyone losing the ID when they zone out to remake, and you have to re-clear.

Note: this ID problem is impossible to reproduce, as I said it can happen in any instance. There is a slim chance that your case is a different bug, but I doubt...

**Comment by Keader** [comment]
Without a repro case is impossible fix.
