### ISSUE TITLE
[Boss] Zuramat the Obliterator

### ISSUE THREAD

**Issue by Bartok14** [WoWManiaUK/Redemption#3227]
**Links**
https://www.wowhead.com/npc=29314/zuramat-the-obliterator

Ran a Random Heroic Dungeon got ported into The Violet Hold. Everything worked pretty much as intended but for the second boss we got Zuramat the Obliterator. We killed him without any issue but once he was dead he had left some sort of floating ball that seemed to keep shooting us with shadow bolts. This persisted for the rest of the instance about every 5 seconds. 

After you kill him there isn't supposed to be any persistent effects. We tried moving to all parts of the room but bolts kept shooting at us no matter where we were. Even after the instance was finished and we killed the last boss the shadow bolts persisted. Took some screen shots for you to see and linked the boss from wowhead. Not really sure what caused this maybe we dps the boss down to fast or killed at a weird time for when it cast the ability. 

![image](https://user-images.githubusercontent.com/32959403/57006100-fecdf180-6bab-11e9-9d63-a53ce9c15755.png)

![image](https://user-images.githubusercontent.com/32959403/57006103-042b3c00-6bac-11e9-931d-6966895bca0a.png)

![image](https://user-images.githubusercontent.com/32959403/57006105-0ab9b380-6bac-11e9-87e1-b217e397bb13.png)

**Comment by wow-mania** [comment]
Need more info.
What was the NPC or Object

**Comment by Echinaceax** [comment]
> Need more info.
> What was the NPC or Object

npc - https://www.wowhead.com/npc=29314/zuramat-the-obliterator

**Comment by Dranah** [comment]
https://www.wowhead.com/spell=54369/summon-void-sentry this is the ability that summons the balls and these https://www.wowhead.com/npc=29364/void-sentry are the balls summoned
May happen at random if you kill the boss in an unlucky timing, since as you can see, the summon ability has a hidden 1sec cast, and there's also a bit of delay on the ball to pop up. If the boss dies with a spawn in progress, it will persist because the only trigger to despawn it is the death of the boss (who is already dead at this point)
Need to add an extra trigger, like a timer or a periodic check if the boss is still up.

**Comment by wow-mania** [comment]
Will fix today

**Comment by sarahkay88** [comment]
So this happened a few months bk to a group I was with. We killed ut real fast n then shadow bolts persisted. So it kind of depends on how much damage your group does to whether or not it happens. But it's not hard to heal through and didn't effect the rest of the dungeon per say. Just keeps u in combat.

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/62971839-a5ac6580-be0a-11e9-82a4-e6f42b3e5b88.png)
keep happening
