### ISSUE TITLE
[Talent] Spirit Tap for Priest (Shadow) (Sub 80)

### ISSUE THREAD

**Issue by D0nV170** [WoWManiaUK/Redemption#3258]
**Links:**
Level:
3: http://wow-mania.com/armory/?spell=15336
2: http://wow-mania.com/armory/?spell=15335
1: http://wow-mania.com/armory/?spell=15270

I do not know if the improved version is also bugged, but here it is:
2: http://wow-mania.com/armory/?spell=15338
1: http://wow-mania.com/armory/?spell=15337

**What is Happening:**
At levels 22- 28 at least, the talent Spirit Tap is not activating after killing a mob that gives experience.

**What Should happen:**
The talent should give the buff that increases spirit when something that gives experience is killed.

Please try to do this on a toon that isn't 80 before just assuming it can't be reproduced. I'm not the only one having this issue.

**Comment by D0nV170** [comment]
![Spirit Tap](https://user-images.githubusercontent.com/50318236/57264604-68c91980-7038-11e9-9d7d-e057750ea1bc.jpg)

**Comment by WhitephoenixTheBunny** [comment]
I will test it soon.

**Comment by Dranah** [comment]
Spirit Tap | Rank 3
Gives you a 100% chance to gain a 100% bonus to your Spirit **after killing a target** that **yields experience or honor**. For the duration, your mana will regenerate at a 83% rate while casting. Lasts 15 sec.

It requires you to
1) Land the killing blow
2) Have the mob give EXP

It's therefore harder you get it to proc in a party where you don't often deal the last hit to the enemy.
It procs properly if you do a killing blow on a mob which isn't grey to you.
Except that one in a million case that your screenshot shows.
This is an extreme case that I did manage to reproduce but hardly requires fixing. Let me explain what happened:
You were level 28 when you started fighting the level 22 Bear. In this state he still gives you exp. So you did receive exp when you killed it, however... you dinged 29 by the kill, and a lvl 22 mob grants no exp to a level 29. Therefore the talent didn't proc, because you were already level 29. 
This can only happen if the kill causes you to level up and by leveling up the mob gets into the "grey level" range for you.
