### ISSUE TITLE
[Talent] Hack and Slash - Wrong display

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#3273]
How is it working: Hack and Slash (http://www.wow-mania.com/armory/?spell=13964) is not been triggered by Sinister Strike (http://www.wow-mania.com/armory/?spell=48638) nor Killing Spree (http://www.wow-mania.com/armory/?spell=51690). It IS proccing from Fan of Knifes (http://www.wow-mania.com/armory/?spell=51723) but with a low proc rate. 

Only Melee Test: 
1. Sample: 1002 Melee - 1002 Total Strikes
    Expected Result: 1002*5% = 50.1 HnS hits
    Actual Result : 54 HnS hits

 Obs: The other 4 can be due the standard deviation.
![WoWScrnShot_051419_105237](https://user-images.githubusercontent.com/40045543/57736446-954ee800-766d-11e9-86e4-f154100e4f5a.jpg)

Melee + Sinister Strike Test: 
2.  Sample: 805 Melee + 200 SS = 1005 Total Strikes
     Expected Result: 1005*5% = 50.25 HnS hits
     Actual Results: 41 HnS hits

Obs: 41 HnS hits are the expected result from 805 * 5% which are the HnS procs from only the MELEE hits.
![WoWScrnShot_051419_110713](https://user-images.githubusercontent.com/40045543/57736475-b31c4d00-766d-11e9-8a34-0819dd0ffbc5.jpg)

Melee + Killing Spree Test: 
3. Sample: 923 Melee + 80 KS hits = 1003 Total Strikes
    Expected Results: 1003*5% = 50.15 HnS hits
    Actual Results: 46 HnS hits 

Obs: 46 HnS hits are the result from 923*5% which is the numer of HnS hits from only the MELEE hits.
![WoWScrnShot_051419_112053](https://user-images.githubusercontent.com/40045543/57736567-18703e00-766e-11e9-8941-114b04085f49.jpg)

Melee + Fan of Knives Test:
4. Sample: 407 Melee + 647 FoK hits = 1054 Total Strikes
    Expected Results: 1054*5% = 52.7 HnS hits
    Actual Results: 29 HnS hits

Obs: I saw some HnS hits on the HC dummy so it is indeed proccing from FoK but on a really low proc rate. 20 HnS hits are the expected result from 407 Melee hits but you can add some due cause i did saw some hits on the HC dummy.
![WoWScrnShot_051419_114353](https://user-images.githubusercontent.com/40045543/57737713-422b6400-7672-11e9-8f87-ae9acb21f797.jpg)

How it should work: Hack and Slash should proc from the skills listed above. (https://wowwiki.fandom.com/wiki/Hack_and_Slash)

**Comment by volkangul** [comment]
Great post, thank you for taking your time, this leads to %2.5 - 3.5 total dps loss. Since the Rogue class heavily relies on Auto Attacks. Also Dps intentisive phases like under the Effects of Bloodlust / Adrenalin Rush makes very important to proc H&S from special attacks.

**Comment by crulinjr** [comment]
Thanks really appreaciate it

**Comment by Keader** [comment]
To make my test easy, i disabled it proc with melee hits, and make it only proc with spells.

![image](https://user-images.githubusercontent.com/7120913/57851892-174b2800-77b8-11e9-8c55-2cf642815efd.png)

As can you see, Sinister Strike is proccing normally the talent.


About Killings Spree, is only proccing with main hand attack:

![image](https://user-images.githubusercontent.com/7120913/57852014-64c79500-77b8-11e9-9d73-f5b99aacc45f.png)


And about Fan of Knives, it trigger on cast, not when it hit 1983981839182392 targets xD

**Comment by crulinjr** [comment]
1. On FoK it should trigger on every target hit with the same 5%. I was
hitting at most 4 targets but spent a lot of time spamming FoK.

2. HnS damage source should be ONLY the MH weapon. It has nothing to do
with KS.
The report about KS was about KS NOT proccing HnS.

3. The SS test: Your sample size is too low also i see some melee attacks
in that test. Also again i think that you test ssmple is missleading since
you got 10 HnS procs from apparently ONLY 40 total strikes.

Please stop closing reports just like that without any kind of reply
oppprtunity.

**Comment by crulinjr** [comment]
Something to add is that you said you disabled the ability to proc HnS from
Melee attacls right? That would only mean that on those 10 SS you did you
had 10 HnS procs which shouldnt be the case. Something is NOT working as
intended.

**Comment by crulinjr** [comment]
Here is another example of Hack and Slash proccing from the Off Hand: I did
1001 Total Strikes got 56 procs from Hack and Slash. If you notice the
damage from my non Crit Hack and Slash procs goes from 449 to 1327. This
can ONLY mean that the source of Hack and Slash damage comes from the Off
Hand aswell. Maybe the code from the test realm is not the same from the
live realm since having 10 Hack and Slash procs from 10 Sinister Strikes is
not possible same with having 36 Hack and Slash procs from 70 Killing Spree
Strikes. Hack and Slash should also proc on EVERY target hit by Fan of
Knives with the same 5%.  You said if triggers on cast which does not
explain at all what you are trying to say, should it proc once per Fan of
Knives or should it proc when you cast Fan of Knives not when the hit
lands? Please be more clear on your statements. Im trying my best to do the
same.

**Comment by crulinjr** [comment]
If you just close the report no one else can chip in with information
regarding this issue so please open it again.

**Comment by crulinjr** [comment]
Keader on this subject please check this screenshot. I was hitting 3
dummies with Fan of Knives. Every Fan of Kives hit counts as 2 since
Recount counted 600 hits on 3 targets i used Fan of Kives around 100 times.
I did Fan of Knives spam without auto attacking the dummies, however, as
you can see on my recount, there are 10 melee hits registered which is
strange. There is also 2 Hack and Slash procs. This demonstrates unsual
behavior on this Talent. Specially with Fan of Knives since the Expected
procs from Hack and Slash should be 600*5%= 30.

**Comment by Dranah** [comment]
Ok so let's clear up some things...
1. Hack and slash can proc off both melee and offhand attacks, assuming both slots are equipped with a sword or axe. However **the extra attack must always be done by the main hand weapon**, so the damage of the extra attack is gonna be a main hand hit, even if the proc came from the offhand.
2. Hack and slash is limited to one target. It procs off "attacks" on your current target, regardless of how many other targets are hit. This means casting FoK will only count the attack that is hitting your current target.
3. HnS cannot proc off missed attacks, so your calculations are off by default because you take a total melee count to calculate with, rather than the actual hits.
4. Keader, please do not use manipulated GM tests. We both know how reliable they are. 
So how do you make a test that has only SS and no melee? Easy. Turn your char by approx 60 degrees while standing on the hitbox edge of the training dummy. This allows you to cast SS but your melee swings won't land because "facing the wrong way". HnS has however no restrictions to having to face to your target, so it can still proc.

Here's my test done this way, and as you can see, **Sinister strike DOES proc HnS.**
And now comes the plot-twist: this proc is displayed as "melee", simply. Which means, in a real-time test with melee attacks and all, the HnS procs coming from special attacks do not get an own flag on recount but are merged into your "melee". Which is why your numbers are so off. 
See screenshot: 77 SS with 2 HnS procs displayed as regular melee attacks
![HNS](https://user-images.githubusercontent.com/31132743/57886328-3b951c00-782d-11e9-93b9-4a95c2423178.png)
On the combat log you can see the extra attack has proc'd.

So what needs fixing here?
- Hack and Slash proc must always use main hand damage to calculate damage
- HnS procs done by special attacks should display separately on the recount (tweaking issue)

**Comment by crulinjr** [comment]
Dranah how do you know HnS is limited to 1 target only?

**Comment by crulinjr** [comment]
Reading this makes me think HnS proc from every hitting melee (including
miss).
https://www.engadget.com/2010/05/25/theorycraft-101-melee-haste/

**Comment by Keader** [comment]
> Keader, please do not use manipulated GM tests. **We both know how reliable they are**.
> So how do you make a test that has only SS and no melee? Easy. Turn your char by approx 60 degrees while standing on the hitbox edge of the training dummy. This allows you to cast SS but your melee swings won't land because "facing the wrong way". HnS has however no restrictions to having to face to your target, so it can still proc.

First, comes down from your princess pedestal.
Your arrogance is affecting the person you are, you're better then it, i know that.
It's a proc spell, it means that will proc when conditions match. Conditions can be changed by 2 things:
1 - Proc Flags.
2 - AuraScripts.

This spell has 2 proc flags.
Proc Flag 1 - Proc when melee (auto-attack) hit a target
Proc Flag 2 - Proc when damage spell that use melee weapon hit a target.

If i need check if a spell can proc it, without have any melee wrong proc, just need disable melee proc flag.
And set it to 100% proc chance, to always get a result.
None of edits change the fact: If sinister strike was proccing before, will proc now too.
So, if GMs tools should not be used by tests, those tools should not be implemented in first place.

And about: "HnS procs done by special attacks should display separately on the recount (tweaking issue)"
Nothing that i can do.
Server will always merge damage effects in only 1 log, because all of then should get same mods (positive and negative)

**Comment by Dranah** [comment]
@Keader Princess lol?
I asked you politely to not try to prove that something is working by using a method that players don't understand, and in some cases (maybe this one is different) creates an artificial situation that may not reflect what happens in the real gameplay.
Maybe this case is different. But in many other cases, an artifical GM dummy test is not reliable to prove that the spell will do what it should in the real gameplay. There were countless examples of that before, I have run into this error myself and you did too. I don't see how it is arrogant to point out that we need some "down to earth" method of testing, not some dev magic here.
I can accept if the recount cannot be fixed, I simply don't understand why HnS triggered by melee attacks is flagged as "Melee(Hack and Slash)" while HnS triggered by spell attacks are flagged as "melee"
Why the difference?

PS: you yourself said it, that you know im "better than that". So why interpret my comment wrong, why twist my words and make it sound like I acted like a bitch?
