### ISSUE TITLE
[Boss] Sindragosa - Hunter's should not be getting unchained magic. 

### ISSUE THREAD

**Issue by crulinjr** [WoWManiaUK/Redemption#3293]
This issue is related to #2593. However i just found this thread from mmo-champion where it states hunter's should not be getting the debuff at all if there is not another possible candidate then it just skips it. https://www.mmo-champion.com/threads/698132-Sindragosa-and-Unchained-Magic

Quote 1: "Unchained Magic is a 'smart' debuff, much like the -healing debuff ret pallies and enhance shamans receive on General Vezax. Each time it's cast, it's put on 1 healer and 1 ranged dps caster (ele sham, warlock, mage, spriest, boomkin). If there is no ranged caster, that instance of the debuff is skipped, and only a healer gets the debuff."

Quote 2: "It works like stated above

1 Caster DPS + 1 Healer is afflicted.

In the case of 0 Caster DPS (Hunters are excluded here, they get the melee debuff, Chilled to the Bone)

1 Healer is afflicted.

We downed her last night on 10-man, and I was the only Caster DPS present (Warlock). 100% Uptime on Unchained Magic on me during Groundphases, with no way to remove it. T'was great fun jumping around 50% of the time."

**Comment by wow-mania** [comment]
Can you show me where it says hunters don't get hit please.

**Comment by crulinjr** [comment]
Yes, no problem

Quote 2: "It works like stated above

1 Caster DPS + 1 Healer is afflicted.

In the case of 0 Caster DPS **(Hunters are excluded here, they get the melee debuff, Chilled to the Bone)**

**Comment by wow-mania** [comment]
Still just a quote from some forum

**Comment by Dranah** [comment]
https://github.com/WoWManiaUK/Redemption/issues/2263
Same thing more explanation.
I have compiled several forums data with retail videos and logs to gather the intended way of its mechanic.

@crulinjr 
Hunters USED TO be immune to the buff, but blizzard realized this leads to exploits. After the realm first kills have been going to all-hunter groups, they modified the spell so that it CAN target hybrids, so long as there are no other targets.

The problem here is that currently the spell does not differentiate in priorities.

**Comment by crulinjr** [comment]
When is this stated? There is no changelog registered

**Comment by Dranah** [comment]
Blizzard never lists exploit fixes anywhere, just like mania lol.
