### ISSUE TITLE
[Talent] Improved Devouring Plague doing too much damage in PvP

### ISSUE THREAD

**Issue by Vastdog** [WoWManiaUK/Redemption#3326]
**Links:**

https://ibb.co/S3BfRwy
https://ibb.co/LQKcr6q
Priest Spell: http://www.wow-mania.com/armory/?spell=48300
Priest Talent: http://www.wow-mania.com/armory/?spell=63627

**What is Happening:**

I have ~1600 Resilience and am getting hit by Improved Devouring Plague for 9k + dmg, this is too high....Espesially, with the amount of resil I have. If you think about this with dots + a partner and this Imp Dev Plague...you are pushing 15k+ DAMAGE PER SECOND in PVP against people with pvp gear

**What Should happen:**

It should do less damage. Maybe it is bypassing resil somehow.

**Comment by wow-mania** [comment]
Can someone confirm this? I highly doubt it is valid.

**Comment by Dranah** [comment]
As odd as it is, it is valid. Probably a new bug, since it used to work fine.

**How it should work:** Improved Devouring Plague must be always a fixed 15% of devouring plague's total damage. When used against a player, it should calculate from the damage Devouring Plague does after the mitigation of resilience. Imp. DP itself does not take any mods in consideration afterwards.
**How it works atm:** Improved DP seems to calculate its 15% damage from devouring plague's total damage BEFORE the enemy's resilience. This leads to the spell doing much higher damage than 15% of what DP actually does on the target. Essentially ignores resilience values, the damage done against a player with 1k resil is same as against a dummy.

**Comment by yeahpallypowa** [comment]
its 30% instantly not 15% 
http://www.wow-mania.com/armory/?spell=63627

**Comment by Dranah** [comment]
I was testing with rank1 of the talent, thus the 15%. At this point it doesn't matter if you test with 1/2 or 2/2 if it does the exact same damage on 1k resi as on zero, then something is wrong.
However, thanks for pointing it out.
