### ISSUE TITLE
[Quest] More Torch Tossing

### ISSUE THREAD

**Issue by jarvik76** [WoWManiaUK/Redemption#3354]
http://www.wowhead.com/quest=11926/more-torch-tossing.

**What is Happening:**
The red arrows, that should indicate which target to hit, do not appear. Or appear for 3 marks and then disappear for 15 seconds+

It seems maybe related to 
https://github.com/WoWManiaUK/Redemption/issues/1327
Which seems very similar in nature.  Perhaps regression issue?

**Comment by jarvik76** [comment]
Ahhh
See   https://github.com/WoWManiaUK/Redemption/issues/2550.  Comments on this seem to suggest this same issue was seen last year and a fix was applied.

**Comment by WhitephoenixTheBunny** [comment]
there is something with timers.
I have tested the quest so far 5 times. And the issue (visual arrow above a brazier) is random.
Sometimes is after the 8th, others it start with no visual arrow at all.

The issue: the red arrow aren't instant (sometimes), they take between 3 at 15 second to visually appear. since it have timer, it make the quest dificult, not impossible, but dificult as hell.

The quest can be done, however, hiting randomly the brasier, but again, since it have timer it make it very dificult.

**Comment by wow-mania** [comment]
Will change timers a bit.

**Comment by wow-mania** [comment]
I have update dev a bit.
This quest is meant to be difficult.

**Comment by WhitephoenixTheBunny** [comment]
Tested, still some delays on arrow.
I think it will be dificult have a 100% functionables visual arrows.

Even without arrow, there's a brazier selected, trowing randomly a torch is a solution in the waiting.

I don't know if there's much you can do over it. We had that last year, and the fix wasn't 100% also.
