### ISSUE TITLE
[Spell] Raise Ally

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#3363]
After using the spell [Raise Ally](http://www.wow-mania.com/armory/?spell=46619) on a party/raid member the player (who was turned into a Ghoul) can't be ress'ed, no confirmation windows appear.
Player need release and run back.

Last fix on it #2568

**Comment by wow-mania** [comment]
Need confirmation.

**Comment by WhitephoenixTheBunny** [comment]
Just retested with more players, in Redemption, no ress appear on the dead one after being turned into a Ghoul

**Comment by Drostthehunter** [comment]
I have done the testing with  Phoenix, after i got turned into a ghoul, neither did Rebirth or Ress were able to ressurect me, there is no window poping!

**Comment by Dranah** [comment]
Confirmed.

But need to clarify 1 thing.
Raise ally itself qualifies as a battle rezz, except you become a ghoul rather than to return to your own body. For its duration, you are alive and your body won't interact.
(In this state you shouldn't even have a physical corpse left behind, only when you cancel the effect or it expires , but thats a different story)

Point being, while the effect is active (the player controls ghoul) they must not receive rezzes, however once the effect is expired, or clicked off, they return to their corpses and must be able to receive a rezz again.
This part doesn't work right now, even after the effect is over and you are back to your corpse with the release option, you won't see new brezz option pop up when someone tries to rez you.

**Comment by Keader** [comment]
Fixed.
If you get any ress while you are dead, you can accept and cancel raise ally.

**Comment by Dranah** [comment]
Rebirth auto cancels raise ally effect and throws you back into your corpse for accept. Might not be fully blizzlike but I don't suppose it really matters.
