### ISSUE TITLE
[NPC] Deadmines Edwin VanCleef Hits 4 hits in one

### ISSUE THREAD

**Issue by bennyboy055** [WoWManiaUK/Redemption#3369]
**Links:**
http://www.wow-mania.com/armory/

**What is Happening:**
VanCleef destroyed me with his attacks i couldnt tell how many hits per attack but it looked like 4-6. was hitting my Night Elf Druid in bear form for 120 each hit and destroyed me in 2 rounds. Please fix this. Its EXP weekend and i lost out on the exp bonus from Random Dungeon Finder also lost out on Maniac Points.

**What Should happen:**

Possibly lower attack rate? Or Lower damage im not sure how VanCleef usually attacks.

**Comment by Dranah** [comment]
This problem is valid.

**The boss has 2 issues:**
1) All of his melee attacks are doubled, he hits twice every swing by default.
2) He has an ability called "Thrash" which grants him 2 extra attacks. He is SPAMMING this ability non stop, so his default 2 melee swings always get added 2 extra, making it a total of 4.

**How it should work:**
He should only melee attack once per swing.
He should use Thrash only time to time, approx every 30seconds.

Here's a video proof where you can see the combat log running showing he only attacks once per swing, and time to time getting 2 extra attacks right after (but not too often)
https://www.youtube.com/watch?v=6B3jazz95wg

**Comment by wow-mania** [comment]
The boss has Dualwield that's how it is.
Also I can remove thrash but not a big deal.

**Comment by Dranah** [comment]
Any source for his dual wield apart from his animation?
It is not stated anywhere and you can clearly see on the video link that he is swinging only 1 time. The combat log shows everything and this video is from pre-nerf state vanilla.
I highly doubt they would have doubled his attacks since then.

**Comment by Keader** [comment]
Invalid :/
In sniffs shows he casting ```SPELL_DUAL_WIELD = 674``` when encounter start, so he has dual wield...
And about Trash spell, it is a proc spell.
It has 35% of chances to give 2 extra attacks.
with proc flags:
```
  4 (0x4) - Successful melee attack
  16 (0x10) - Successful attack by Spell that use melee weapon
```
So, everything looks correct here.

**Comment by Keader** [comment]
Found the problem, fixed.

**Comment by Dranah** [comment]
Works good now!
