### ISSUE TITLE
[Spell] Acid Spit (Underbog - Ghaz'an)

### ISSUE THREAD

**Issue by Triise** [WoWManiaUK/Redemption#3407]
**Links:**https://www.wowhead.com/npc=18105/ghazan#abilities

**What is Happening:** Acid breath seems much wider than just a cone in front of the boss. Also Acid spit damage seems too high, it one shot our healer today.

**What Should happen:** Acid breath should only hit players in front of him. Acid spit should not one shot people.

**Comment by wow-mania** [comment]
As-is.

**Comment by Dranah** [comment]
https://www.wowhead.com/spell=34290/acid-spit
Acid spit damage is in the range 2-2,5k and that is intended. (some lvl 60 healers can have less than that hp, yes... blame vanilla items not having stamina)
The targeting however is cucked. The ability should hit 1 random target, but currently it hits ALL targets available.
**How it should work:** Hit one random member every time.
**How it works atm:** Hits every member every time.

Acid Breathe cone is working as intended.
Illustrated:
![ghazan](https://user-images.githubusercontent.com/31132743/61996545-a1a3e800-b095-11e9-8957-98692779e0c8.png)
The warrior in this position is not taking damage from the breathe, despite being in front, he's outside the cone at which it hits. Frontal spells hit in 180 degrees in front (blue line), frontal cone spells however allow the group to position at the sides like my test char, which is much needed due to the tail swipe hitting in the back.
PS: the boss has a stupid visual design and a giant hitbox, sometimes making it difficult to determine where he really faces. The best you can do is watch the tank's position for reference.

**Comment by Triise** [comment]
Thank you for testing this, I knew something was very off. It's so hard to
tell exactly while playing

**Comment by Dranah** [comment]
It no longer hits every member, but it seems to target strictly the main tank now. It should select random target, not always the top threat.

**Comment by Dranah** [comment]
No change, still only targets the main tank.

**Comment by Keader** [comment]
@Dranah STOP NOW !
Janitor not builded it yet ._.

**Comment by Dranah** [comment]
Still no change.

**Comment by Keader** [comment]
Tested again and is working.
