### ISSUE TITLE
[Boss/Spell] Omor the Unscarred - Orbital Strike and Shadow Whip

### ISSUE THREAD

**Issue by Triise** [WoWManiaUK/Redemption#3414]
**Links:** https://www.wowhead.com/hellfire-ramparts

**What is Happening:** Omor the Unscarred Has a knock back that can send you over the edge of the Ramparts, currently if you are knocked off, you are removed from the instance and sent to your hearth location.

**What Should happen:** After falling off the edge, you should fall to your death and be sent to the closest graveyard according to your faction.

**Comment by Keader** [comment]
When you fall of the edge, you are teleported to Hellfire Basin, in this location:

![image](https://user-images.githubusercontent.com/7120913/61994000-4b11bc00-b04b-11e9-87e7-d157236fc20c.png)

I cant reproduce your issue.

**Comment by Triise** [comment]
You have to be inside the ramparts instance fighting Omar, and wait for his
knock back to send you off the ramparts. I see you are not in the Ramparts
instance there

**Comment by Triise** [comment]
I was Teleported to my hearth location

**Comment by Dranah** [comment]
If you had entered ramparts manually, it causes you to fall to Hellfire Basin as Keader posted. It literally throws you off where you exit the dungeon. 
If you are inside the dungeon via RDF, however, zoning out teleports you to wherever you were when accepting the queue, just like when zoning out of RDF. (suppose it can sometimes be your hearth position, if you were in some impossible spot when accepting the queue...)

Both cases, the problem is that you are zoned out of the instance at all, because the boss forgets to pull you back after throwing you up.

**How it works atm:**
https://www.wowhead.com/spell=30637/orbital-strike throws the tank up in the air, inflicting damage
https://www.wowhead.com/spell=30638/shadow-whip is missing, the boss does not pull tank back to himself after throwing them in the air
This results in the tank flying outside the platform and zone out of the instance.

**How it should work:**
After the orbital strike, the boss should cast shadow whip in a few seconds to pull the tank back to himself.

**Comment by Dranah** [comment]
The boss now pulls you back as intended.
