### ISSUE TITLE
[Dungeon] Halls of Stone - Brann bronzebeard fight

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3433]
Issue: the different attacks from the sculptures are not working.

how it should be: In the different phases the different heads should do different things as shown in the proof below

>The first trap is multiple small direct damage spells on random players, the second is a slow-moving AOE orb that will give a dispellable debuff increasing the damage taken by anyone having it, and the third is a beam creating a pulsing AOE zone that you can't stand in

>P1: Think Rajaxx in AQ20. Some elites, some not. They don't have that much hp. An aoe heavy group is very nice, but I have done it will full melee. The mobs are mostly all melee, with a few casters near the end.
P2: The waves continue. It is much more balanced between melee and caster mobs. **Now there are big purple orbs to watch out for. They will charge up in front of the giant statue faces, then launch towards a target If you get hit with it you get a very nasty debuff (50% or 100% more damage taken, depending on difficulty) and it unleashes some AoE shadow damage.** If the tank gets hit, it is basically game over. The debuff is magic, so it can be removed if you're quick.
P3: The waves continue. The orbs continue. **There is now a giant laser beam that does solid damage, 500 a second or so. Stay out of it. Do not stand next to Brann as it will hurt him also.** There are also Golem giants that come out. They do solid damage and have an AoE knockdown effect. While individually not that devastating, getting knocked down in a laser or while an orb is heading towards you is.

https://www.youtube.com/watch?v=4rbBGdwM5pY

**Comment by Keader** [comment]
How is working now? What's not working? This post is confusing

**Comment by Kitzunu** [comment]
atm, the "sculptures" are just turning white eyes but does nothing.

**Comment by Kitzunu** [comment]
the eyes should turn red and do the different attacks mentioned above/video during the different phases

**Comment by wow-mania** [comment]
What is the NPC id or link?

**Comment by WhitephoenixTheBunny** [comment]
Objects IDs:

Tibunal Head - Center = 191669
Tribunal Head - Left = 191671
Tribunal Head Right = 191670

(mania armory doesn't provide links)

**Comment by wow-mania** [comment]
Neither does wowhead.com

**Comment by WhitephoenixTheBunny** [comment]
I have been searching, but by video linked by Kit, they should shoot you and be a harder fight
ATM is a boring one ... tank and spank + aoe adds

**Comment by WhitephoenixTheBunny** [comment]
@wow-mania FOUND THEM
They have names -.-

> Brann will stop and allow you to rest after clearing this trash, talk to him again to begin the encounter. There are three large faces surrounding your party in the room. If you are facing the exit, they are (clockwise) **Kaddrak, Abedneum and Marnak.**
> https://wowwiki.fandom.com/wiki/Tribunal_of_Ages

Wowhead links:
Kaddrak: https://www.wowhead.com/npc=30898/kaddrak
Abedneum: https://www.wowhead.com/npc=30899/abedneum
Marnak: https://www.wowhead.com/npc=30897/marnak

**Comment by Dranah** [comment]
Note: one of them is invisibly meleeing the group again after the encounter ends , getting ya stuck in combat.
This was reported before https://github.com/WoWManiaUK/Redemption/issues/1672 https://github.com/WoWManiaUK/Redemption/issues/1739
and the only improvement made was that if you port out of the instance, now it will leave you alone and not re-engage combat.

How it should work: the computers should be casting spells during the encounter and never melee.
How it works atm: the computers dont do anything during the encounter other than visual effects, but when the fight ends and players head for the chest to loot, it engages with them in melee combat you can't get rid of, since they are invisible.

**Comment by Dranah** [comment]
Missing spells of the computer NPCs:
Kaddrak (active from p1): https://www.wowhead.com/spell=50988/glare-of-the-tribunal
Marnak (active from p2): https://www.wowhead.com/spell=51000/dark-matter
Abedneum (activate from p3) https://www.wowhead.com/spell=51125/searing-gaze

**Comment by Dranah** [comment]
This is a boss encounter that's far too easy and boring right now. Not a tweaking issue.

**Comment by corrinr** [comment]
Just did this fight on heroic and it doesn't seem to be working quite right still. The damage from the statues was constant on every party member--the first guy didn't choose random people to damage, it just kept shooting at each of us constantly throughout the fight. The healer had to keep rejuv/regrowth up on everyone the entire time.
![WoWScrnShot_082919_212130](https://user-images.githubusercontent.com/48542141/63989753-21fba580-caa7-11e9-9183-e1acae5154ec.jpg)
![WoWScrnShot_082919_215011](https://user-images.githubusercontent.com/48542141/63989762-27f18680-caa7-11e9-869d-3658e0455f8e.jpg)
This is all just from HoS heroic. The warriors swapped who was tanking partway through, but the healer and dps still took 250-400k damage each from that fight and the druid did 2 million healing to keep us alive. I don't think the fight would be survivable with a lower geared healer, or even with a decently geared holy pala bc lack of aoe/HoT. I also took a lot less damage than everyone else and was feigning every time the cd was up--in the moment I couldn't tell if it was affecting the statue aggro or not but it may have been and I doubt it's supposed to. I don't have a screen but I'm also pretty sure the statue damage we were taking throughout was at least 1500 a hit, not 500 as it's supposed to be.

**Comment by corrinr** [comment]
I would strongly suggest reopening this issue and taking another look at the encounter. Since my last comment, I just did the dungeon on my holy paladin and even with another paladin tank, a DK, and shaman who stopped DPSing to help heal, we wiped multiple times because of the constant statue damage. Also, after our second or third wipe, Brann was fine and continued with the encounter as if nothing had happened and opened the door to the last boss. All the mobs were congregated towards the front even though we weren't even in the room after the second or third wave. These weren't fresh 80s either, we were all fairly well geared.
