### ISSUE TITLE
[NPC] Ambassador Hellmaw

### ISSUE THREAD

**Issue by corrinr** [WoWManiaUK/Redemption#3439]
**Links:**
https://www.wowhead.com/npc=18731/ambassador-hellmaw
http://www.wow-mania.com/armory/?npc=18731

**What is Happening:**
Currently, he is patrolling in circles around the room and is attackable/will aggro at any time, even with some or all of the trash in the room still alive. I reset the instance and he was still patrolling, I was able to kill him twice without clearing the cultists and he aggros if you're close to the doorway when he walks by.

**What Should happen:**
He is supposed to be banished until all ritualists have been killed, then begin to path around the room.

**Comment by wow-mania** [comment]
As-is

**Comment by Dranah** [comment]
This is a legit issue and can cause problems to groups with the crowd aggro. You should be able to clean the room first without worrying for the boss engaging if you walk too close.

**Comment by Dranah** [comment]
The boss now doesn't seem to engage nor he is possible to get in combat with until you clear the entire room. This solves a part of the problem, but since he is still patrolling and you can hit him (he just ignores you and resets hp), it will confuse people a lot. 
Can you make him stand still and have his aura up that keeps him banished until the criteria to engage him (clearing the room) is met?
>https://www.wowhead.com/spell=30231/banish this is the effect that should be active on him before the room is cleared.
this is the coords where he must be banished until he is eligible to engage
![WoWScrnShot_082019_134036](https://user-images.githubusercontent.com/31132743/63344352-88b6eb80-c350-11e9-8eb0-fb0a960dabf6.jpg)

**Comment by wow-mania** [comment]
If you reopen please specify why

**Comment by Dranah** [comment]
No change, he isn't banished as he should be.

**Comment by wow-mania** [comment]
Re-checked and it works.

**Comment by Dranah** [comment]
He is still walking around not banished. Sure he refuses to enter in combat, but not that it works as intended :D
![WoWScrnShot_082219_172610](https://user-images.githubusercontent.com/31132743/63527776-0110de80-c502-11e9-952f-e823b6cadc84.jpg)
