### ISSUE TITLE
[Quest] Tempering the Blade A/H

### ISSUE THREAD

**Issue by Takarashune** [WoWManiaUK/Redemption#3487]
**Links:**
![WoWScrnShot_081719_040310](https://user-images.githubusercontent.com/54194745/63205394-eecb1680-c0a3-11e9-9be5-ca2872491141.jpg)

**What is Happening:**

I was doing the Battered Hilt questline. I was on the quest: Tempering the Blade. And proceeded to Forge of Souls. Due to the Quest i used the item. My character threw it but the Quest did not finish. Now my Item is gone and the Quest is not finished.

**What Should happen:**

The Quest should be finish so i can proceed to the next step of making the Weapon.

Screenshot send.

**Comment by GMKronos** [comment]
![WoWScrnShot_081619_211220](https://user-images.githubusercontent.com/54194900/63205501-c8d55000-c06a-11e9-80ec-ece67d201867.jpg)
![WoWScrnShot_081619_211222](https://user-images.githubusercontent.com/54194900/63205502-c8d55000-c06a-11e9-93c3-a0e15e20a7c0.jpg)
![WoWScrnShot_081619_211225](https://user-images.githubusercontent.com/54194900/63205503-c8d55000-c06a-11e9-9176-c019458845d2.jpg)
 I was able to confirm that this issue is happening on GM Kronos.

**Comment by Kitzunu** [comment]
Stand on the thing and it will work.

**Comment by Kitzunu** [comment]
@Rushor could you look into widening the area of what the quest is able to be completed from so players dont have to stand ontop of the cruisible

**Comment by WhitephoenixTheBunny** [comment]
Yeah, because when I did it, I needed abandon and retake the quest... and re run the thing to do the quest.
