### ISSUE TITLE
[Quest] Broodling Essence

### ISSUE THREAD

**Issue by IvanLlanas** [WoWManiaUK/Redemption#3519]
Broodling Essence (quest): http://www.wow-mania.com/armory/?quest=4726
Draco-Incarcinatrix 900: http://www.wow-mania.com/armory/?item=12284
Black Broodling: http://www.wow-mania.com/armory/?npc=7047
Broodling Essence (item): http://www.wow-mania.com/armory/?item=12283

The Draco-Incarcinatrix 900 works ok on the Black Broodlings but after killing them no red crystal is spawned, so no Broodling Essence can be obtained.

**Comment by WhitephoenixTheBunny** [comment]
![image](https://user-images.githubusercontent.com/31921098/63639809-11ef5a80-c690-11e9-8656-b5737dd32d91.png)
![image](https://user-images.githubusercontent.com/31921098/63639814-17e53b80-c690-11e9-9e66-8ae723d35167.png)

But, if you use the same mob while the red aura / mark still visible in the floor it does not spawn
![image](https://user-images.githubusercontent.com/31921098/63639827-4b27ca80-c690-11e9-95f3-82e47327abae.png)

Is that the issue you enconter?

**Comment by IvanLlanas** [comment]
The Draco-Incarcinatrix can only be used on alive black broodlings. On corpses you get an "Invalid target" message. The Draco-Incarcinatrix can be shot on them (before killing them) of course and they get a purple/black aura. Then on killing them they should spawn a red crystal, like the one on the screenshot, and I could loot the essence from them, but these crystals do not spawn.

**Comment by wow-mania** [comment]
Works

**Comment by WhitephoenixTheBunny** [comment]
@wow-mania something is wrong with the quest actually


![image](https://user-images.githubusercontent.com/31921098/63641230-bc707900-c6a2-11e9-9b44-f51ebabbadfe.png)

I went check on live, and took the quest (i had missed that one my loremaster :P)

As the aura made by the crystal doesn't despawn you can't progress in the quest because the crystal won't spawn:


![image](https://user-images.githubusercontent.com/31921098/63641248-0b1e1300-c6a3-11e9-9a44-8cadbd54a075.png)

![image](https://user-images.githubusercontent.com/31921098/63641258-3143b300-c6a3-11e9-901c-4a09add6f38c.png)

If more than one player on quest some won't be able to do it. Only with a server reset....

The despawn timer should be decreased...

**Comment by WhitephoenixTheBunny** [comment]
After mob killed no crystal:
![image](https://user-images.githubusercontent.com/31921098/63641284-a1eacf80-c6a3-11e9-8fd0-adb0a676acae.png)

**Comment by Kitzunu** [comment]
Whats the id of the aura

**Comment by Kitzunu** [comment]
I dont understand the issue?

**Comment by IvanLlanas** [comment]
Initially, Player1 has the quest and goes to Burning Steppes. He tags a black broodlings with the item Draco-Incarcinatrix 900 and kills it. After dying, a large crystal and a **red aura** spawn where the corpse is. He loots the crystal and gets the broodling essence. The crystal despawns but **the aura does not**. Player1 does that 8 times to get the 8 essences required for the quest. The previous 8 broodlings killed respawn in time.
Later, Player2 comes to do the same quest. He tags **one of those 8 broodlings** (previously killed by Player1) and kills it, but no new crystal and aura spawn as long as the old aura stays still in game.
Those red auras should despawn when the crystal does or just a few players can complete the quest until all the broodlings population get tagged.

**Comment by Rushor** [comment]
fixed in dev
