### ISSUE TITLE
[Dungeon] Halls of Stone heroic

### ISSUE THREAD

**Issue by corrinr** [WoWManiaUK/Redemption#3556]
**Links:**
https://github.com/WoWManiaUK/Redemption/issues/3433 See previous issue.
https://www.wowhead.com/npc=150865/brann-bronzebeard
https://www.wowhead.com/npc=28234/tribunal-of-the-ages

**What is Happening:**
The statue attacks during the Brann Bronzebeard encounter are not functioning as they should. They are consistently dealing large amounts of damage to every party member without seeming to stop. The fight is just barely survivable even with a very well geared healer, and for lower geared healers it currently requires anyone with healing abilities to stop DPSing and help heal to avoid a wipe. Additionally, the encounter seems to keep running as if party members were continuing to DPS the adds, even when no one was in the room. I just ran it as healer and we wiped several times. Brann should not have survived the several waves of adds that spawned while we were all regrouping outside the room, but he /yelled his usual signal for the end of the encounter and Sjonnir became accessible. We weren't able to get back in the room to loot the chest and it didn't give us any emblems, but we were able to do the last boss and finish the dungeon. 

**What Should happen:**
The fight should be difficult, yes, but right now it's almost a guaranteed wipe depending on your healers and the group's composition. I posted a screenshot in the other issue's thread from the first time I ran the instance since the fix and we only survived because we had a druid healer in partial PVP gear who healed around 2 million HP during the instance. The statues should be choosing a random person every couple of seconds to deal damage to, not consistently dealing damage to everyone every couple of seconds. It's extremely frustrating and stressful as a healer because again, in the other issue's thread you can see that each party member was taking between 250-400k damage during the instance. The way the fight works now makes it extremely hard for a group of 187+ geared fresh 80s and frustrating for higher geared players trying to get emblems.

![WoWScrnShot_082919_212130](https://user-images.githubusercontent.com/48542141/64107378-0232de80-cd40-11e9-8f2a-4070d87468ea.jpg)
![WoWScrnShot_082919_215011](https://user-images.githubusercontent.com/48542141/64107379-02cb7500-cd40-11e9-882c-fc0026967b1a.jpg)

**Comment by Keader** [comment]
I found 2 problems there.
each trigger should cast in diff player, (all triggers was attacking same player).
And spell should be casted each 2 sec, was 1.5 sec before.
Test now in ptr please.

**Comment by Dranah** [comment]
original issue https://github.com/WoWManiaUK/Redemption/issues/3433
things that happen when jani closes thread before its tested :D

**Comment by Dranah** [comment]
Well, the spells were added after the previous report, however the fight is still cucked.
1) https://www.wowhead.com/spell=50988/glare-of-the-tribunal (kaddrak) hits every party member instead of 1 at random and there are eventually two Kaddrak npcs casting it on each player.
![kaddrak](https://user-images.githubusercontent.com/31132743/64477571-653bcf80-d19d-11e9-950d-f207e1fc1569.png)
This is the most urgent problem.
2) Abedneum is also duped and double casts Searing gaze.
3) Marnak's Dark matter also doesn't quite function the intended way. Instead of an orb headed out towards someone, able to debuff whoever touches it, it seems to only cast a debuff at 1 target at a time with no orb visual anywhere, however there's a source of damage on logs and recount "dark matter target's dark matter hits xx for 5k damage" which I cannot localize and this is not intended.
![darkmatter](https://user-images.githubusercontent.com/31132743/64477980-16dcff80-d1a2-11e9-9eca-488acafe39e9.png)
There is a stalker npc called "dark matter" but he doesn't actually do anything, so i don't know where the damage is coming from, that spell should deal no dmg.

**Comment by corrinr** [comment]
Something weird is still going on with this dungeon :( The Tribunal encounter now works much better, but we got caught in the laser beam and wiped still. Once we all ran back, Brann continued his /yell speech as normal and the door to Sjonnir was open, but Sjonnir didn't spawn. We tried going back to Brann, killing all remaining adds and activating him as if he were going to open the door, but still no spawn, although the doors did close behind us as if the encounter was starting after we had kicked 2 people in preparation to leave since it was not completable. I'm not sure if the issue is triggered by a wipe, by the specific way we handled the wipe, or if it's an issue no matter what bc of some adjustment to the Tribunal encounter, but right now the dungeon isn't able to be completed in at least one situation (and probably many people will wipe in phase 3 of Tribunal until we get used to the mechanics).
