### ISSUE TITLE
[Spell] Replenishment

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#3586]
This spell http://www.wow-mania.com/armory/?spell=57669 is not working as it was originally mentioned. The spell is caused by Empowered WInter talent, link is here: http://www.wow-mania.com/armory/?spell=44561.

**How it should work**
This will add special bonus to mana regeneration and this bonus is working in both situations: while player is casting and not casting

**How it works**
for 5 seconds after casting there is 0 mana regeneration even with this spell. This causes the talent absolutely  useless and it completely denies its very purpose.

**Comment by Dranah** [comment]
It does regen mana while casting, but it was changed to tick every 5seconds like the tooltip actually says so.
Earlier it did 0,2% mana per second, now it does 1% every 5seconds. 
It's a 3.2 patchfix: 
Patch 3.2.0 (04-Aug-2009): This buff now grants 1% of the target's maximum mana over 5 seconds instead of 0.25% per second. This applies to all 5 sources of Replenishment (Vampiric Touch, Judgements of the Wise, Hunting Party, Enduring Winter Frostbolts and Soul Leech).

It still gives the same amount of mana, just in bigger chunks (the effect doesnt get "clipped" by being refreshed or so, it steadily awards 1% mana every 5seconds when it is active.)

**Comment by cathyr1** [comment]
Thanks for explanation. Tested now again and seems it is as you described.
