### ISSUE TITLE
Spell [Vanish] - Rogue - Does not remove combat in Bosses.

### ISSUE THREAD

**Issue by volkangul** [WoWManiaUK/Redemption#3587]
**Links:**
https://wowwiki.fandom.com/wiki/Vanish
http://www.wow-mania.com/armory/?spell=26889
https://classic.wowhead.com/spell=1856/vanish

**What is Happening:**
Casting "Vanish" ability does not remove "Combat" from the Rogue while fighting againts Bosses.

**What Should happen:**
The Rogue should immediately out of combat when the ability is performed. The Agroo drops but the Rogue remains in "Combat" which means Potion cooldowns ( Haste,Healing) are not refreshing. Normally a Rogue does Pre Pot ( before boss pull), then uses 2nd potion after that uses " Vanish " to gain new 1min cooldown on 3rd Potion. This is in the DPS Rotation of Rogues. Currently  "Vanish" does not remove the Rogue from "Combat". The 10 seconds of "Vanish" ability should grants to Rogue  "Additional" +++ Stealth Level in order to drop "Combat" which means even "Bosses" should not detect the Rogue while under the "Vanish" buff.

**Comment by Dranah** [comment]
That's how it should work. You can't drop combat during bosses to reset potion cooldowns since some early BC patchfix.

**Comment by volkangul** [comment]
Can you exactly tell me which patch fixed that? I checked all of data and there is no thing such as fix. Also i used to do that tripple potion usage back in Retail. Here are patch datas for you. I m not defending i m %100 sure but it must be checked.

https://wowwiki.fandom.com/wiki/Patches/3.x
https://wowwiki.fandom.com/wiki/Patches/2.x

**Comment by Rushor** [comment]
hm i also remeber a mechanic that constaly keeps all member in combat during  a raid/bossfight, called aggro pulse

**Comment by volkangul** [comment]
I even checked Vanilla. There is no fix to that until Cataclsym Expansion.

https://wowwiki.fandom.com/wiki/Patches/1.x#Vanilla

Hope it helps.

**Comment by volkangul** [comment]
> hm i also remeber a mechanic that constaly keeps all member in combat during a raid/bossfight, called aggro pulse

Yes you are right. But it only should NOT effect the Rogue in 10seconds of "Vanish" buff which should grants +370 level in that period.

https://wowwiki.fandom.com/wiki/Stealth_(mechanic)

**Comment by Rushor** [comment]
i think such fix is critical for specific encounters right now

**Comment by Dranah** [comment]
Stealth level has nothing to do with being in combat or not. Players cannot exit combat on bosses on WOTLK, this is not even up to debate, read wiki or anything: 
https://wow.gamepedia.com/Combat
"Some classes have abilities that remove them from combat instantly. However, if they are dotted they will usually be brought back into combat the next time they take damage. Note that these abilities no longer remove you from combat during Boss Fights (only at the end of wipes if you time it correctly). "
Hotfixes like this aren't listed in patch notes, I only recall it was done on BC because I was reading an article about it when fixing the ability.
Cause yeah, the combat wipes used to get you out of cb on mania, before we eventually fixed them not to. They can only exit you from combat if you are the last man standing in the fight and even that will often fail depending on the encounter.

**Comment by Kitzunu** [comment]
In a boss fight vanish should only drop aggro, not combat. So it works as intended, we worked on it for long.

Unless there is info that is stronger than what gamepedia states (like a youtube video from that patch) this will not be reconsidered. Same as feign death.

**Comment by Keader** [comment]
@Rushor combat pulse is for keep players in combat, yes. But not change the fact that some spells should not drop the combat. (because if do, cooldowns like potions will reset anyway)
