### ISSUE TITLE
[Boss] Sindragosa timers and tail smash

### ISSUE THREAD

**Issue by shadownib** [WoWManiaUK/Redemption#3617]
**Links:** 

**What is Happening:**Everything with Sindragosa can be improved ( Tombs , Tail smash , the speed, that sindra fly up :https://www.youtube.com/watch?v=fAOF9-2Tuk4&feature=youtu.be : for Air phase is Not correct , the animation of the Tombs did Not exist or at least not correct as well)

**What Should happen:**First Ice Tombs should have their animation , Sindragosa should fly up one idea slower (like this: current time watch from 1:32 until 1:38 thats at 6 sec time ofc based on the speed she flying https://youtu.be/iB51PSXlfF8?t=90) , so the timing for " air phase tombs announcement will get correct +/- 1 sec ( because ATM the AIR tombs announcement is early / faster at least with 4 ~ 5 sec ) another thing is Tail smash:https://youtu.be/o89tT2o87r0?t=52, should Not kick you or even 2 ~ 3 ppl in same time AWAY like 40 + yards , it should just knock you on your back for 1 global CD.
P.S. those 3 things MUST be fixed its so silly to me and FOR PPL WHO CARE
P.S. don't act like "what's wrong with sindragosa"
P.S. Quality Above all

in case u care for the quality of game-play or u wanna help about it my discord is : Shadownib
#5184

**Comment by shadownib** [comment]
P.S. The English have nothing with the game-experience , and it must be used from ppl who care.

**Comment by shadownib** [comment]
just saying for people who are scared... : If everything which i report get real , it won't affect the game in the HARD way : it will be pretty much enjoyable

**Comment by shadownib** [comment]
about the ice tomb animation i can explain a lot , until u got me + prof why is that needed for me and for ppl who know how to use it.

**Comment by Kitzunu** [comment]
Suggested title: [Boss] Sindragosa

**Comment by wow-mania** [comment]
No.

**Comment by Dranah** [comment]
Well, I can confirm the following issues in this encounter:
1) Tomb Animation missing. Cosmetic but should be fairly easy fix.
**How it should work**: When the beacon expires, Sindragosa releases a frosty orb towards the player, which forms up a tomb upon landing with a 1- 2sec animation to build. During this time the player is already stunned.
**How it works atm**: When the beacon expires, the player snaps into a tomb all of a sudden. The orb released by sindragosa hits them afterwards, it looks a bit silly.
2) Tail Smash is hitting you inside the hitbox everywhere and knocks you very far instead of just knocking you down like on retail. This is a problem that is nowhere "good enough".
**How it works atm:** I am currently getting tailsmashed even at this position which should be a completely safe area:
![tailsmash](https://user-images.githubusercontent.com/31132743/66257984-f8b5ef80-e79f-11e9-98b7-84ea583f0f88.png)
I marked the spot where the tail smash hits with a purple X.
It should hit targets within 20 yards from that spot in the back, area marked with Red.
I marked the extra area where it hits us here with green, this should be a safe zone but somehow getting smashed.
**How it should work:** Should never get tail smashed on the side. Should knock down targets in place, instead of making them fly out miles to the back. While this is not obvious based on the tooltip of the spell, it can be clearly seen on retail videos how melees near the rear (usually ferals) are only quitting their attacks after the smash lands since they get knocked down, but don't actually get moved.
3) Air phase: Sindy is missing the 3seconds window during which she lifts up vertically before going to her designated spot to begin shooting tombs. This also leads to the Frost Beacons going out 3seconds earlier than intended, cutting people short on time to position.
**How it should work:** Sindy should spend 3seconds lifting vertically, during which she is still in range to DPS. She then spends 3seconds to fly behind, and marks tomb targets with Frost Beacon only at the 6-7th second of the air phase.
**How it works atm:** She instantly gets out of range and moves straight to the back. Frost Beacons the first set of players very early, 3seconds into the air phase.
4) Timers for beacons in p2. Minor difference but should also not be difficult to correct.
**How it works atm:** tombs in p2 are going out every 15seconds on mania
**How it should work:** tombs in p2 are going out every 16seconds on retail

@wow-mania I have doubled checked back until 2017 and these specific issues have never been worked on before.

**Comment by Dranah** [comment]
https://www.wowhead.com/npc=36853/sindragosa
https://www.wowhead.com/spell=70126/frost-beacon
https://www.wowhead.com/spell=71077/tail-smash
https://www.wowhead.com/spell=70157/ice-tomb

**Comment by Keader** [comment]
- [ ] Tomb Animation missing
- [ ] Tail Smash is hitting you inside the hitbox , is a general range issue. Not even in TC has a solution for this yet. Cant be fixed for now...
- [ ] Air phase: Sindy is missing the 3seconds
- [ ] Timers for beacons in p2

Rest is fixed :)

**Comment by Dranah** [comment]
1) Tomb animation is improved, not fully blizzlike, but good enough 
2) Tail smash - it appears this might have been changed around with patch 3.3.5a, altering the effect, but reducing the range at which it hits. Needs fixing to match retail 3.3.5 videos.
3) air phase fixed
4) timers fixed

**Comment by Dranah** [comment]
We made a workaround for the tail swipe. Will no longer hit players on the side of the hitbox and will now only throw you back by 20 yards as intended.
