### ISSUE TITLE
[Spell] Sindragosa : Unchained Magic / Instability proc off actions that should not proc

### ISSUE THREAD

**Issue by shadownib** [WoWManiaUK/Redemption#3627]
**Links:** https://www.wowhead.com/spell=69762/unchained-magic and link with that " What is Happening in Wow-Mania " https://youtu.be/npJQRXWL3OM 

**What is Happening:**First issue is: When i use nitro boots it gives me Instability stack , second issue is : spell Penance gives stacks of Instability on cast and also on Hits it means at least 5 or 6 stacks just by using it ( it must be based only on spell casting , Not on Hit above i gave link for info how it should be )

P.S. My friend who is playing warlock is also complain that he gets instability on hit ( I'll check his streams and cut some profs about it )

**What Should happen:** When u are using whatever spell it must count only 1 stack of instability even if the spell is channeling like Divine Hymn etc

**Comment by shadownib** [comment]
forgot the Penance link of " What is happening" - > https://www.youtube.com/watch?v=kOm8D6W7tAc&feature=youtu.be

**Comment by shadownib** [comment]
And here is my Friend stream how he gets instability from Shadow bolt hits as well ( one time when he cast shadow bolt and one more time after the Bolt Hits the boss that's 2x instability stacks for one spell ) https://www.youtube.com/watch?v=6j3vM3ogmk0&feature=youtu.be u can see it clearly easy.

**Comment by Dranah** [comment]
I just tested and the results are as follows:

1) The spell does not give stacks on-hit, it works on cast as intended. - INVALID
2) There seems to be an issue with each tick of penance being considered a separate cast. I can confirm you currently get stacks for each tick of penance, which is not intended. - NEED FIX
3) I could not reproduce the issue with affliction warlock's shadow bolt, and it's pretty difficult to tell based on your friend's steam what triggered the extra stack of instability, since it can proc off also spells that are not on the GCD (i.eg. something macroed to his attack) - INVALID
4) I can however confirm that the spell currently gives stack when items (trinkets, nitro boosts, healthstones, even potions etc) are used. These effects work with /cast just like spells (i.eg. /cast 13 is your first trinket) therefore it makes sense that they are considered a cast, however based on some retail videos I would say this is not intended at all.
Here's a footage of a disc priest using a healthstone with Unchained Magic and he does not gain any stacks, unlike here on mania: https://www.youtube.com/watch?v=_QlSOWPwsfk
So this is an issue that needs fixing. On-use items should not give stacks.

**Comment by shadownib** [comment]
My warlock friend don't have any macro for his shadow bolt , and the instability stack should be just at the end of the cast, which we cannot see on the stream ( because it is on Hit ) maybe is only shadow bolt and penance broken I'll see soon as mine Arcane/ Fire mage

**Comment by shadownib** [comment]
Here is more than clear when the shadow bolt should give the instability stack ( the guy is not casting anything else than just shadow bolt , so it gives the instability at the end of the cast ) that's it.https://youtu.be/B_HZPgLVBGE?t=23

**Comment by vladyy32** [comment]
I am the warlock from that video. I am not using any macros. If u watch the video at 0.25 speed you can see that I am casting Curse of Agony right after that Shadow bolt and from that curse it is my first Instability stack, this is okay by now,still I didnt get instability by casting Shadow bolt but by hitting the boss with it, which is not correct i should take a stack from my shadow bolt when i press it not when it hits my target. later in the video you can see that I have proc of instant shadow bolt cast, I press shadow bolt then and i get instability for pressing it and a second later 1 more for dealing damage which is not correct. I will list every instability stack from what it is and if it is normal or not. So the first: it is from pressing Curse of agony right after i cast shadow bolt and i dont take instability from casting shadow bolt which is not correct, i should be.
second: it is from casting Corruption dot on that tomb which is correct
third: it is from that first shadow bolt cast where i didnt get instability(the one i casted before taking the first instability stack with curse of agony) and it is incorrect because i should have taken it when i casted it at first place
fourth: before i get a fourth stack u can see that i am casting Haunt from which I DO NOT TAKE A STACK BUT I AM SUPPOSED TO and after Haunt I use my trinket u can see it popping up with 3mins of cooldown and that its buff is appearing in left of my curse of agony debuff from the Tellmewhen add-on. I SHOULDN'T BE TAKING INSTABILITY FOR USING MY TRINKET. And also, 1 more thing when you use a trinket which u must press it is not a cast it activates by a command of /use not /cast(like a spell) and that is a prove that the trinket shouldn't be giving an instability stack. Same goes for the nitro boots because it is not a /cast command but a /use one
fifth: now the way to see it from where the stack is coming from is by looking at my action bar and see me casting Corruption and right after i Click key 3(corruption) I get the fifth instability stack and that is how its supposed to be.
sixth: since i have that instant shadow bolt proc and i cast it just when i receive the sixth instability stack u can easily make a conclusion that the sixth stack comes from that instant shadow bolt but it is not because in the same time my haunt spell hits the boss and one more time i should have gotten this stack when i casted haunt at the 4th second and not when it dealt its damage at the 6th second. You can see it(haunt) dealing damage on my addon in left it is the top spell which does 4515 damage, again, i should have taken instability when i casted haunt not when it did damage.
seventh: this is clearly from unstable affliction which is correct
eight: this one is also tricky and again it is from dealing damage and not on cast you can see just when i take that 8th stack my addon shows that shadow bolt crits for 17541 on the left. That is the instant shadow bolt cast which i did earlier. I shouldnt have taken instability by doing damage but by casting it earlier.
ninth: it is from drain soul which is correct.
The conclusion is that you currently take instability stack by hitting the target with a spell that it is not instant but it is a castable spell(for example shadow bolt/Fireball/Frostbolt/( I would add Arcane blast but AB does instant damage although you still cast it for a second or two so that means if i miss an arcane blast i wont get any instability stacks? :D)/Haunt and so on), which it shouldnt be working like this, and also you take stacks from instant spells like Corruption, curse of Agony which is normal. The right way for this to work is to take stack when YOU PRESS shadow bolt/Haunt and not when Shadow bolt/haunt deals damage.

**Comment by shadownib** [comment]
Here is more than clear when the shadow bolt should give the instability stack ( the guy is not casting anything else than just shadow bolt , so it gives the instability at the end of the cast ) that's it.https://youtu.be/B_HZPgLVBGE?t=23

**Comment by Rushor** [comment]
adding a 1 sec procc cooldown can fix most issues

**Comment by Keader** [comment]
Is wrong

**Comment by Damnlife** [comment]
If it will be how its is supposed to be then okay but if by breaking something else you fix something then, no thank you :D

**Comment by Damnlife** [comment]
what is wrong, Keader

**Comment by Keader** [comment]
rushor suggestion xd

**Comment by Damnlife** [comment]
That sounds promising ;d

**Comment by Dranah** [comment]
- /use and /cast command does the same thing
- The original report stated it gives stack on **both** cast and hit, which is invalid
- For 99% of spells and abilities it procs on cast as intended, I have confirmed penance to be an exception and proc on both
- Can now confirm also that shadow bolt is giving on hit INSTEAD of cast, and this seems to be the case for every damaging attack with a travel-time, i.eg. frostbolt, haunt, etc, as well, they are all giving stacks when landing instead of when being launched. Probably the "extra" stack was actually added by your haunt just with a giant delay, i can't think of anything else because I cannot reproduce shadow bolt giving double.

**Comment by shadownib** [comment]
@Dranah what i meant by " gives stacks on Both cast and hit " is : instant spells like corruption etc are on cast , and spells like shadow bolt are on Hit ( sry i hope everything is clear as possible now )

**Comment by Damnlife** [comment]
As i stated, @dranah my friend got confused that i take double stack on shadow bolt because it was pretty hard to notice that right after my first Shadow bolt cast i cast Curse of agony, you can watch the video on 0.25 speed and you will notice how i pop curse of agony and the debuff shows on my tellmewhen addon in the bottom middle of my screen. Though i still get stacks on hit from those travel-time spells.

**Comment by Keader** [comment]
Fixed.

**Comment by Damnlife** [comment]
But what about the stacks being given on hit instead of cast

**Comment by Keader** [comment]
Nothing that i can do about that in our proc system, sorry :/

**Comment by shadownib** [comment]
So basically u are trying to say in the simple langue : you cannot fix it bcuz of the server core ? Not with that core that's it ? Аre we so limited playing in wow-mania ? 
I just wanna understand clear what is the server Future , I'm not trying to be disrespectful or any sort of rude

**Comment by shadownib** [comment]
because my point was to bring my friends to play in mania  ( and they do come in ) should i tell them that we have to stop playing this game , bcuz not gonna join / playing in LOLTEN ( meaning )
P.S. we did some basic support to the server and expecting the basic boss mechanics to work. We always gonna do if the server reserved over time.

**Comment by Keader** [comment]
Yes and No.
Core Spell Proc System that we are using now, has no support to change when spell will proc.
So we need update to new proc system (same proc system that we have in cata server).
I will try port it in january, but until there i cant do nothing about it.

**Comment by shadownib** [comment]
Ty for the Explanation , in this way is it possible the Tombs animation duration , to be increased at least with one more second ? ( not based on players needs , ofc based on previous blizzlike Player experience )
