### ISSUE TITLE
Sindragosa ability timing issues

### ISSUE THREAD

**Issue by Flux13** [WoWManiaUK/Redemption#3654]
The timing on the Blistering Cold and Frost Tomb abilities in phase 2 of the Sindragosa fight seems to be syncing up so that the tomb hits right as the raid is being pulled in for Blistering Cold. This causes the majority of the raid to be tombed unavoidably. Usually the tomb should freeze the selected player just before the Blistering Cold pull happens.

We had this issue repeatedly on the second Blistering Cold during phase 2 of the fight on 25 Heroic difficulty. All other Blistering Cold/Frost Tomb combinations were timed correctly. I'm unsure if this issue only affects this difficulty or not.

**Comment by wow-mania** [comment]
Time is correct. We have fine-tuned it a lot already. E

**Comment by Dranah** [comment]
I encountered this issue before but I cannot consistently reproduce.
The timer is normally fine, blistering happening 2-3seconds after a tomb has already frozen.
The problem is that sindy sometimes snaps and casts blistering 2-3sec earlier than usual for no reason which overlaps with a tomb forming. I could not find the cause of it yet and it does not happen in every raid (2 out of 3 though). 
Oddly, to me it fucks up the 4th blistering every time, not the second.

**Comment by Flux13** [comment]
It was happening pretty consistently yesterday even though I don't recall having a huge issue with it earlier. The person marked for the tomb got pulled in with the rest of the raid right before they got frozen. Ruined a couple attempts that were sure kills :(

**Comment by jarvik76** [comment]
We have experienced this issue as well in our guild runs in the past few weeks.  Only seems to have been a relatively recent phenomenon from recollection.

**Comment by wow-mania** [comment]
#3662
