### ISSUE TITLE
overpower not procking correctly on shields

### ISSUE THREAD

**Issue by Vircy** [WoWManiaUK/Redemption#3678]
**Links:**

**What is Happening:warriors are not getting the prock on overpower when rend deal damage on shields**

**What Should happen:overpower should prock regardless , even when the rend damage is done on a shield**

**Comment by Keader** [comment]
and should? '-'

**Comment by Vircy** [comment]
i don't want to be wrong and bring you to a wrong direction , but as i
remind from retail servers it used to be so, i'll be looking for some links
to prove it right or else

Il giorno mar 12 nov 2019 alle ore 01:27 Keader <notifications@github.com>
ha scritto:

**Comment by Vircy** [comment]
i saw some posts on MMO champion saing that the dmg on a shield won't proc
it, nothing from blizzard forums thou

Il giorno mar 12 nov 2019 alle ore 02:14 Tommaso Ugolotti <
tommasougolotti@gmail.com> ha scritto:

**Comment by Kitzunu** [comment]
A tip for research is to check videos from the time (9-10years ago), wowhead comments from the patch and wowwiki/gamepedia for patchnotes and various other forums since Blizzard has removed all old content from their forum when they converted to the new forum.

If you could link to that MMO Champion post it could help Dranah and Keader in their research :)

**Comment by Dranah** [comment]
As far as my research goes, this is intended, multiple sites confirm that.
And in general, proc tooltips worded with "deals damage", "takes damage" "damaging attack" require the attack to actually deal damage to trigger, this includes every on-damage trinket proc and talent ability as well.
This means it can proc if the spell does at least 1 point of damage (partially absorbed) but not if fully absorbed (0 damage).

In contrary, spells which proc on "attacks", "hits" or "critical hits" should proc also when fully absorbed. Most of them have been fixed in the past, but not all. Hence i'm off to report Art of War which currently cannot proc on absorbed criticals here.
