### ISSUE TITLE
[Quest] Fate, Up Against Your Will

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Redemption#3723]
https://www.youtube.com/watch?v=yXnAZZC6OTU

**How it works:**
The script for Kor'kron Elite and Thrall is not correct and gets stuck in a small loop

**How it should work:**
Should work as the video above

**Comment by Rushor** [comment]
okay this was a hell of a script.

3 scripts were there
2 were wrong
1 needed to be updated to work for both horde an alli depending on which faction > entries has to be changed

all fixed now

![I](https://i.imgur.com/CY5eood.jpg)
![I](https://i.imgur.com/Bj2LQmy.jpg)
![I](https://i.imgur.com/osY5A4k.jpg)
![I](https://i.imgur.com/ywWZ1q8.jpg)

in order to trigger the event you need to step closer here: https://i.imgur.com/8hjzG7L.jpg. then the event starts
