### ISSUE TITLE
[Talent] Bloodsurge

### ISSUE THREAD

**Issue by GMWeeble** [WoWManiaUK/Redemption#3752]
[Talent](https://wow-mania.com/armory/?spell=46915) Is not working as it should. You should be able to use [Slam](https://wow-mania.com/armory/?spell=47475) As an instacast after Bloodsurge procs. However this does not work and will require you to cast slam even if bloodsurge has proced.

The tooltip does correct and say that the spell is "Instant"

**Comment by wow-mania** [comment]
Pretty sure this works as I remember fixing this a while back. Can someone confirm please?

**Comment by Dranah** [comment]
I triple checked all the previous reports on slam and bloodsurge and none of them match this problem. We fixed the tier bonus, the amount of stacks being consumed, the spell being able to cast while moving, etc, but now the spell simply began ignoring the effect entirely, since last night. 
We have an open report on Slam's damage, but in theory, that hasn't been pushed yet because the thread is still open, so it can't be related (besides, we only fixed the talent Improved Charge to not affect it)
spell ID 47475 slam ability
spell ID 46915 Bloodsurge talent
Spell ID 46916 Slam! proc

How it works atm: Slam ignores the bloodsurge procs with or without t10 bonus. Still has a cast time and does not consume proc.
How it should work: When Bloodsurge procs, slam must become instant cast, possible to cast while moving and consume 1 stack when used.

**Comment by jarvik76** [comment]
Re-tested, confirmed is now instant cast and consumes proc.

**Comment by Dranah** [comment]
Yeah, none of you bothered checking the t10 huh :D 
https://github.com/WoWManiaUK/Redemption/issues/1929 now we're back to this state, consumes both stacks.

**Comment by Keader** [comment]
It's not same issue.

**Comment by Keader** [comment]
ah fuck, fixed it too.

**Comment by Greywolf59** [comment]
Hello! Sadly I have to inform you that it will probably be a different issue. Arms mandatory talent Improved Slam https://www.wow-mania.com/armory/?spell=12330 also does not work. I went throught the launcher today, deleted csche. Reseted my talents and learned this again. Still it does not work. Tooltip on dlam now says 0.5 cast but in reality it is casted for basic time as it would be without the talent (or slightly less but I can't really tell nor do I think so).

**Comment by Keader** [comment]
@Greywolf59 did you tested on ptr?

**Comment by ZXCVBNMFGH** [comment]
Divi told me online that this was fixed and I should "turn it on and off again". Done, with cache cleared and the problem is still there. Bloodsurge procs, but does not allow a no-CD Slam.

**Comment by Kitzunu** [comment]
It is not on live yet. Divi is wrong

**Comment by Greywolf59** [comment]
Ptr? is that a test server? I am not a tester. I tested on normal server.

**Comment by Dranah** [comment]
PTR=PublicTestRealm
Please open a new report for different issue and it'll be investigated.

**Comment by Greywolf59** [comment]
I did now ;)

**Comment by Greywolf59** [comment]
....And it disappeared

**Comment by Rushor** [comment]
well done @Keader
