### ISSUE TITLE
[Game Interface] Number of players online

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#3755]
Today when I logged in the game, I´ve discovered a very unpleasant change that I hope is only mistake and could be fixed. I see only 49 players online instead of **the real number** (with a note that only 50 is visible). Please don´t make this useless view permanent, this was one of the greatest advantage of this server to always know how many ppl are online.

![image](https://user-images.githubusercontent.com/30184491/69977611-66c22d00-152b-11ea-87ae-bc08af33a297.png)

Thanks a lot for the fix.

**Comment by Kitzunu** [comment]
I can confirm.

This could be a change to improve server performance. But don't quote me on that.

I will put this as confirmed and wait for Janitor to comment on the issue.

But dont forget you can check the online amount here as well: http://wow-mania.com/server

**Comment by wow-mania** [comment]
As is

**Comment by cathyr1** [comment]
This had been correct since the very start of the server until Yesterday. All I need is to return this state that lasts till Yesterday and don´t let the unsolicited state to lasts. Thanks.

**Comment by Keader** [comment]
@cathyr1 use https://github.com/WoWManiaUK/Redemption/issues/3755#issuecomment-560487895

**Comment by cathyr1** [comment]
I know it is on the website but why can´t that be easily ingame if it was for entire 4 years. Why that change? It won´t help anyone.

**Comment by Kitzunu** [comment]
As I said, it could have been to boost the performance of the server.
That interface takes a lot of performance, lowering the amount it loads will increase the performance, and to be fair, you could only see 50 anyways.

But that is my theory to why it got reduced

**Comment by cathyr1** [comment]
I could see 50 but this is absolutely not important. What was important was the other number that said how many alliance or horde exactly is online at the moment.

**Comment by Kitzunu** [comment]
I spoke with Janitor and I was right. The reason for this change is:
When hundreds of players are online, calling the who command (writing /who) causes lag to 1. The Server, 2. The Client.

The number of players shown in the /who section has been reduced to increase the performance of the Server and the Client. So technically this was changed to fix a bug and the stability of the server.

Of course, we apologize if this causes any trouble for you, but it should not be too big of a deal since these numbers can easily be found on the website.

To conclude: It was changed to remove a Client and Server lag caused by this command when there were hundreds of players online.
