### ISSUE TITLE
[Quest] the black knights fall

### ISSUE THREAD

**Issue by bigyoda7** [WoWManiaUK/Redemption#3827]
**Links:**
 [The Black Knight's Fall]

**What is Happening:**
squire cavin wont give the option for fighting the black knights fight

**What Should happen:**
when you talk to him you should be able to start the fight

**Comment by Rushor** [comment]
https://github.com/WoWManiaUK/Redemption/issues/1394

**Comment by Oganku** [comment]
This quest works, I did it about a week ago. You need to make sure you're using Crusader Rhylla's charger. If you mount any other tournament mount, the squire will not offer you the option to fight the black knight. Reading the quest text indicates this is required in order to complete it. I'd say as-is.

**Comment by wow-mania** [comment]
Pretty sure it works.
