### ISSUE TITLE
Stranglethorn Fishing Extravaganza

### ISSUE THREAD

**Issue by Zenitic** [WoWManiaUK/Redemption#3828]
**Links:**

**What is Happening: For some reason it would seem that the Stranglethorn Fishing Extravaganza isint firing up. The pools of tastyfish spawned a little early so i caught 40 speckled tastyfish and stayed beside the npc. I arrived at the npc about 5 mins early about 13:56 server time and gave up trying to get it to work about 14:24 server time. If I were to make a wild guess I would say maybe it didnt reset properly after one of the tournaments I have zero experience though so that's just a guess.**

**What Should happen: at 14:00 server time the NPC Riggle Bassbait should have activated the fishing tournament quest but never did.**

**Comment by Oganku** [comment]
Links: https://wowwiki.fandom.com/wiki/School_of_Tastyfish
https://wowwiki.fandom.com/wiki/Stranglethorn_Fishing_Extravaganza

The fishing event actually starts an hour later than indicated on the calendar. Although the fish spawn an hour earlier than said. So basically:

How it is right now: [Schools of Tastyfish](https://wowwiki.fandom.com/wiki/School_of_Tastyfish) spawn at 13:00 SVT and calendar indicates the event should begin at 14:00 SVT. You can only turn-in the fish from 15:00 SVT onward however.

How it should work: According to links above, wowhead comments from 3.3.x, the competitive portion of the fishing event should begin at 14:00 SVT and last 2 hours or until a player wins. Since it is a competition, and wowhead comments very clearly show that fishing efficiency and speed are important, the [Schools of Tastyfish](inks: https://wowwiki.fandom.com/wiki/School_of_Tastyfish) should spawn exactly at 14:00 SVT too. It should not be possible to fish those prior to the event starting and simply sitting next to the NPC awaiting turn-in. 

It is possible to complete right now, but the calendar times are misleading and the competitive aspect of the event is sort of not present, unless multiple players are just sitting with the fish already pre-fished and spamming the NPC as soon as it allows turn-ins.

**Comment by Rushor** [comment]
timer adjusted to 14:00:00. will apply this soon
