### ISSUE TITLE
Wind Rider Sabamba in Warsong Hold

### ISSUE THREAD

**Issue by mropo85** [WoWManiaUK/Redemption#3963]
**Links:**

**What is Happening:**
I received an email when hit lvl 70 that clearly says that I can learn Artisan AND Cold Weather Flying from WInd Rider Sabamba. She doesnt teach it. I spoke with GM Aymelek about it.

**What Should happen:**
She must teach it as clearly noded in the email (see attachement)
![Unknown](https://user-images.githubusercontent.com/58222022/71978105-d60df980-321a-11ea-80e4-9a37161d3089.jpeg)

**Comment by jarvik76** [comment]
When inspecting Sabamba, she has NPC ID of 35135.   Sabamba's ID on armory is 35133.
https://www.wow-mania.com/armory/?npc=35133
   
NPC 35135 is actually Maigra Keenfeather, the Alliance Flying Trainer instead
https://www.wow-mania.com/armory/?npc=35135

Suspect that Sabamba is perhaps not offering training as the player is likely seen to be opposite faction due to referencing the Alliance Flying trainer NPC ID?
![image](https://user-images.githubusercontent.com/46089380/72000104-7cb5c280-323a-11ea-8ce1-bac43bd62a51.png)

**Comment by Rushor** [comment]
works fine https://i.imgur.com/dbvvs0c.jpg
