### ISSUE TITLE
[Zone] Free-for-all PVP flag in some spots in The Barrens

### ISSUE THREAD

**Issue by frongsrus** [WoWManiaUK/Redemption#4004]
**Links:**  
One spot this happens, with Mapster coordinates   
https://i.imgur.com/GQ25krx.jpg

Another spot with coords. Check minimap in both to see relationship of location to bridge    https://i.imgur.com/zQKfriC.jpg

When going into the subsection flagged FFA, the phrase "Southern Barrens" pops up.  Minimap shows bridge  https://i.imgur.com/Y4couTq.jpg

Move a bit to the side so that "Southern Gold Road" shows, and PVP sword flag disappears   https://i.imgur.com/TYANffc.jpg

**What is Happening:**
Head south in the Barrens and cross the bridge into the southern half.  If you step to either side of the Gold Road, a tone will sound, your character gets a "sword" icon, and you are PVP flagged as a "free for all" PVP area.

Walk a little bit in any direction so that your subzone area changes, and the flag goes away. 

Additional notes: running the 2.5.5 client from Launcher,  tested by deleting cache and disabling add-ons.  

**What Should happen:**
This is not a Free-for-all PVP area and therefore the player should not be flagged.

**Comment by Dranah** [comment]
This does not only happen in the barrens, some leveling areas has been flagged as FFA by Janitor on purpose to encourage world pvp, but it never really did work out and got kind of forgotten since. Hardly anyone ever notices it since everyone minds their own business when leveling for most part, but yeah, it isn't actually a bug.

I'd suggest however revising this decision @wow-mania and removing the FFA flag as it only confuses players and never really served its purpose.

**Comment by wow-mania** [comment]
As-is.
