### ISSUE TITLE
[ICC] Crusader Halford - Missing Emotescript

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4016]
Added full script for Crusader Halford http://wotlk.cavernoftime.com/npc=37696

**Comment by Kitzunu** [comment]
Works good, if I should nitpick a bit these are the only misc things

1. Doesn't hold the burning rod in his hand when he walks from the fire to the water
2. he is a split second or two too late, because the animation of Steam Burst happens during the kneel down effect. Not once he is actually kneeling,
