### ISSUE TITLE
[LFG] Add Dungeon Cooldown for player for 3 minutes if they deny the proposal/popup

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4049]
Added dungeo cooldown debuff for player for 4 minutes if they deny the proposal/popup

**Comment by Kitzunu** [comment]
Is this blizzlike?

**Comment by Kitzunu** [comment]
Okay, I got it explained for me that this was from a suggestion.

But then I suggest: Wouldn't it be better to do so IF the player declines 3 times in 5 minutes, they get deserter? because to always get deserter on 1st decline kinda sucks. I.E you need to go to the toilet as it pops or smt in the neighbor hood of that

**Comment by Rushor** [comment]
will reduce it to 5 minutes

**Comment by Rushor** [comment]
okay 3 min now
