### ISSUE TITLE
[TOC5] Grand Champions

### ISSUE THREAD

**Issue by cooperonie** [WoWManiaUK/Redemption#4059]
Hello,

So this has been a thing I've noticed before and i ran into it again today.
In TOC 5 HC the first encounter (after the horsie phase) the bosses just go "idle" when they die.

they just stop attacking, keep standing and stare at you ..
Also the wow targeting stays on them .. i'm assuming if they'd die it'd switch targets.

Quick example: the 2 bosses on the right are "dead" but you probably can't tell..
![TOC](https://user-images.githubusercontent.com/2728624/73118381-acabd800-3f53-11ea-9002-5537ecdb84c4.png)

**What Should happen:**
They should "die" as in go lay on the floor or something..

PS: could be happening in TOC5nm also.. haven't been there recently.

Thank you,

**Comment by wow-mania** [comment]
Probably reverted code. Wait until monday.

**Comment by cooperonie** [comment]
Issue is still present, i had the same thing happen yesterday in TOC5HC.

**Comment by Kitzunu** [comment]
Confirmed. Seems like they have some check so that they cannot die.

How it works:
1. They stop at 1 HP
2. When all are defeated they run back to the gate and despawn

How it should work.
1. They should die.
2. When all 3 are dead they should respawn to then run back to the gate and despawn.

Source: https://www.youtube.com/watch?v=2hdiug6WVy0

**Comment by Rushor** [comment]
Can make them kneel instead

**Comment by Keader** [comment]
Test now pls.
