### ISSUE TITLE
[Achievment] The Faceroller

### ISSUE THREAD

**Issue by cathyr1** [WoWManiaUK/Redemption#4082]
This achievment http://www.wow-mania.com/armory?achievement=3803 seems bugged.

**How it should work**
When Eadric the Pure http://www.wow-mania.com/armory?npc=35119 throws his hammer against a target player, the action bar of this player will change so he will see  only one button with this hammer and can use this ability against the boss.

**How it works**
When the boss throws his hammer against a target player, he only gets damage but no bar changes so he cannot use the hammer against the boss to complete this achievment.

**Comment by Oganku** [comment]
The achievement works fine. When the boss throws his hammer, he first casts a stun on his target. The target then has to have the stun dispelled (I believe it's classified as magic, but I usually break it with human racial) in order to catch the hammer. Once it's caught, action bar does change properly.

**Comment by Kitzunu** [comment]
Do you know if that is intended or of it is only half broken @Oganku ?

**Comment by Oganku** [comment]
It's 100% intended. Takes 30s to verify by looking at wowhead comments.
