### ISSUE TITLE
[Quest] If He Cannot Be Turned

### ISSUE THREAD

**Issue by GMBrontes** [WoWManiaUK/Redemption#4103]
**Links:**

**What is Happening:**
Players need to kill General Lightsbane. After the kill the quest isnt completing.

**What Should happen:**
After the kill, the quest must be completing in questlog

**Comment by Kitzunu** [comment]
I am 90% sure this works since it worked in the past and nothing has been touched since. 
But I will test this on Dev later today.

**Comment by Kitzunu** [comment]
Since this is a quest where you get assisted by other NPCs the issue you are facing might be that you did too little damage compared to what the NPCs did.

**Comment by Rushor** [comment]
can add sth for that if you wish

**Comment by Kitzunu** [comment]
Be my guest ^^

**Comment by Dranah** [comment]
The player should receive credit for tagging the mob
Doing more damage than the npcs is not only not required, but in case of some quests is also plain impossible (i.eg. level 70 quest where the npc deals ~2k dps, you can't outdamage it...), so this needs to be fixed.

**Comment by wow-mania** [comment]
This is not how it works here. You need to do at least 50% damage. This is a well-known requirement here. The npc is there to assist not do all the work.

**Comment by GMBrontes** [comment]
Hello, I had this ticket multiple times and players are really trying to defeat the general. Must they stop in the quest chain and comeback later when they are better geared?

**Comment by Dranah** [comment]
@wow-mania we know how it works here, but it's not blizzlike and not correct.
In order to do at least 50% of the damage, you need more than just not slack - you need to be able to outDPS said NPCs, because math. You cannot deal above 50% damage if the NPCs combined dps is stronger than yours. Most of the helper NPCs in not only this quest, but other quests in northrend as well, deal way over 1k DPS (especially if there are multiple), which is near impossible to achieve for a lvl 70-80 leveler in trash gear, especially if he does not level with a DPS build. Btw we already gone through this argument on Varidus quest and proved this theory wrong....

Now, as source proof, there are several comments from wowhead https://www.wowhead.com/quest=12896/if-he-cannot-be-turned#comments https://www.wowhead.com/quest=12897/if-he-cannot-be-turned#comments that confirm that the only thing you need to do in order to do this quest is **survive** and **tag** the mob, let me list a few:

By Blackboy0 (17,274 – 3·24·175) on 2008/12/14 (Patch 3.0.3)
"Just let them tank it, just deal some Dmg every now and then."

By auxiliry (4,151 – 20·21) on 2008/11/16 (Patch 3.0.3)
"Soloed on a disc/holy priest." 
<<< Note: THAT'S A HEALER. He has no means of doing 50% of general's hp...

The only thing people mention could mean losing credit is if you die. You cannot seem to get credit if you lay dead when the elite falls, but if you run back, and rejoin the fight at 1%, you still do receive credit:

By Pyrofang (155 –  1)  on 2009/09/07 (Patch 3.2.0) |   |  
"LOL
I kinda died.. . .. but when i came back and respawned into my body.. they where still fighting and he was almost dead! HAHA"

By Fricfrac (113 –  0)  on 2008/12/15 (Patch 3.0.3)
--
"If you do die before he's killed run back as fast as you can and res in there, you can join in again and still get credit. Worked for me."

Thats how it should work.

**Comment by Rushor** [comment]
credit should work better now.

**Comment by GMBrontes** [comment]
Thanks guys for solving this so fast!

**Comment by Rushor** [comment]
not on live yet - will be available with next update

**Comment by Kitzunu** [comment]
I just did 34.5k out of 88.2k, got quest credit.
Works
