### ISSUE TITLE
[Talent] Eye for an Eye

### ISSUE THREAD

**Issue by pitstem** [WoWManiaUK/Redemption#4115]
**Links:**
http://www.wow-mania.com/armory?spell=25988

**What is Happening:**
I got into a PvP fight on Bloodmyst Isle, where I happened to instakill the enemy. When I checked my combat log(screenshot provided), it said my Eye for an Eye talent(linked) hit him for over 20000 Holy damage. Now, damage itself is absolutely ridiculous and the talent shouldn't be able to deal so much, but what's even weirder is that it says I overkilled him by nearly 200 million.

**What Should happen:**
The Eye for an Eye talent should not deal that much damage.
![WoWScrnShot_020920_175137](https://user-images.githubusercontent.com/58089094/74105624-2c4ac100-4b68-11ea-945f-bef258e089c1.jpg)

**Comment by Dranah** [comment]
I wonder if you experienced any server lag during the time this happened. I used to see occasional glitches with abilities oneshotting stuff during lag spikes, but otherwise acting normally. 
I cannot reproduce Eye for an Eye doing this , I was testing with the reflected damage proc from Molten armor, as your logs state, but it behaves as per normal.

**Comment by pitstem** [comment]
Hello, I don't think there was any lag while this happened. The game response time was normal and I went Onixia Lair afterwards again without any lag issues. Also, I'd like to point out that this is the first time I've experienced something like this.

**Comment by Kitzunu** [comment]
@pitstem Hello!

Do you have any other useful info we could use to try and reproduce this issue?

Such as Glyphs, Buffs, spells you used etc.
Anything to locate the bug will be appreciated
