### ISSUE TITLE
No rewards and party members are shown as unknown

### ISSUE THREAD

**Issue by Karbaros** [WoWManiaUK/Redemption#4121]
Hi, **I have 2 accounts with the same settings and addons**. Everything is ok with the main account. But with the 2nd account I have the problem that I do **NOT** get any rewards. Party members are shown to me as unknown. After about 2 hours with a **GM** (_Brontes_) I was referred to this page.

_Measures: All addons disabled_ (**no result**)
                          _Cache cleared_ (**no result)**
  _New launcher - for enGB clients only installed_ (**no result**)

What I don't understand is that it works with my main account and not with the other.

![WoWScrnShot_021220_131255](https://user-images.githubusercontent.com/60970390/74337101-f728b380-4d9f-11ea-93c6-600053e9f9eb.jpg)

**Comment by Kitzunu** [comment]
The Unknown label on NPCs and players is caused by a breakdown in the network communication between your computer and the server. If you use a wireless connection, try bypassing this temporarily and plugging your system directly into the modem using an ethernet cable.

If the problem persists, follow the steps below to resolve the issue:

Reset your user interface to make sure your files and addons are not corrupted.
Reset your network devices to make sure your router hasn't become flooded with data.
Update your drivers to resolve any compatibility issues.
Check your network configuration to find any issues with your firewall, router, or port settings.

**Comment by Kitzunu** [comment]
TL:DR the communication of your second client is not properly communicating with the server
