### ISSUE TITLE
[Quest] Supplies to Private Thorsen

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#4175]
Links: [Supplies to Private Thorsen](https://classic.wowhead.com/quest=198/supplies-to-private-thorsen)

What is Happening: When you approach Private Thorsen, the NPC cannot be interacted with to turn in the quest. 

What Should happen: Private Thorsen should have the gold question mark above him with players being able to interact with. According to wowhead comment from 2005, he's patrolling the area as well. 

> For me, he had to be IN THE CAMP to complete it. I ran into him on patrol, but he wouldn't talk to me. When he arrives back in the camp (37,4 STV), the golden ? mark appears and the quest is done.

**Comment by Rushor** [comment]
wasn't that fixed with https://github.com/WoWManiaUK/Redemption/issues/4156 ?

**Comment by bLeyaa** [comment]
It didn't work at the time of posting the issue. 🤷‍♂️

**Comment by jarvik76** [comment]
@Rushor no, #4156 was for Doren for quest "Jungle Secrets", its a different quest & NPC

**Comment by jarvik76** [comment]
I cannot replicate - this seems to be working ok.  
https://youtu.be/PB3hvGfLaG4
He was also active with the ? while in the camp before he started patrolling.

In order to turn in, e has to be in the camp, or at the end the previously mentioned Jungle Secrets quest.
i.e. not actively on the patrol

@bLeyaa Was there any other specific circumstances you can remember?

**Comment by bLeyaa** [comment]
@jarvik76 Ok so, i've just gone to check and he wasn't there by the campfire. Found him patrolling so i followed, which for some reason triggered some kind of event where he fought 2 Kurzen Agents and then i could turn in quest right there on the spot.

![image](https://user-images.githubusercontent.com/61625377/75616381-6b10dd00-5b50-11ea-9245-957df511771f.png)

I didn't turn it in there, followed him back to the camp and then i could still turn it in as soon as he got there. I really have no explanation on what happened on the first time, i believe i went straight from Booty Bay to him with the flight path i have.

![image](https://user-images.githubusercontent.com/61625377/75616433-f25e5080-5b50-11ea-9df7-530ec91cd8d1.png)

**Comment by jarvik76** [comment]
Ok :)  Well, glad it's working for you.  I'll close this now as we can't replicate this and seems to be working even for you as well.   It will stay noted on this ticket for reference in case it happens in the future.
Thanks for your report!

**Comment by Echinaceax** [comment]
for notes, janitor has a player with this issue, so i was asked to check 

Standing at the camp, he has the quest delivery https://i.gyazo.com/f4bb04e4047bc73ed7b2e5a5c8f1a47d.mp4
When he starts his patrol he loses it, Player just need to wait until he returns to camp https://i.gyazo.com/f1db0a4f7ed7e0733224e9c951736462.mp4 as Jey said. no issue with this.

i think the only reason you able to deliver it on his patrol, is because he has to be stood still before the question mark will appear.

noticed 1/4 tests he bugged on his pathing and went through the terrain
