### ISSUE TITLE
[Quest] Jungle Secrets not working - Stranglethorn - 215

### ISSUE THREAD

**Issue by goodebug** [WoWManiaUK/Redemption#4311]
https://classic.wowhead.com/quest=215/jungle-secrets

The quest is supposed to be a simple talk to the npc and get the next quest, however, it seems like Lieutenant Doren is not in mood to talk. A GM tried to help with NPC refresh etc, however, it still didn't work.

He just just complete the quest and proceed me to the next quest.

**Comment by Rushor** [comment]
related to that area restriction. we MUST remove that. else the whole quest will not work

**Comment by jeyrella** [comment]
@Rushor is this related to #4156?

**Comment by jeyrella** [comment]
ok, now Private Thorsen does not offer the quest at all in the first place.

**Comment by Rushor** [comment]
he will offer it after the initial escort is done

**Comment by jeyrella** [comment]
i just completed it, didn't offer it

**Comment by jeyrella** [comment]
https://youtu.be/2j7QI_mKYjo

**Comment by jeyrella** [comment]
relogged and cleared cache, now he *is* offering it, but the ! mark is missing above his head
![image](https://user-images.githubusercontent.com/46089380/77761491-1027b400-7030-11ea-9089-46b3a54daab5.png)

**Comment by wow-mania** [comment]
These quests were working just fine for years

**Comment by jeyrella** [comment]
@wow-mania no they're not, when you have tracking enabled on low-level quests

**Comment by jeyrella** [comment]
The issue was that the hand-in to Doren was not working.

Now the quest physically works, but his pathing is rather odd.
Heading inwards from the first time round after combat, he straight lines down the sides of the valley, rather than coming around the path
https://youtu.be/2j7QI_mKYjo

Heading back outwards on patrol, he goes straight through the terrain down to the valley floor, and straightlines it back up the side of the valley to the path
https://youtu.be/Ph4uXBwcVSg

The rest of the inward pathing works fine, and the quest does technically finish and quest marker is shown.

**Comment by jeyrella** [comment]
Ok I have made a clearer set of videos for this.
There are 2 rounds.  The first round he says "Time for my patrol, I'll be back shortly".
The outward path is correct, the combat is fine,   However the inward pathing is wrong straight lines down the sides of the valley, rather than coming around the path.
https://youtu.be/MYcfNUjkpD4
The hand-in of the quest technically works fine, including to Doren.

2 mins later, he heads back out wiht the speech "I've been gone a long time, I better get back".  This time he clips straight through the terrain down to the valley floor, and "flies" back up the side of the valley to the path.
https://youtu.be/lbU_PoZOvmE
On reaching his end part of the path, he then returns normally, using the correct pathing.

**Comment by Rushor** [comment]
improved the script a bit. the starnge behaviour is realted to homposition. the creature does not update the homeposition during the patrol. try now

**Comment by jeyrella** [comment]
This now works as it should, fully.
Private Thorsen will head out on patrol (""Time for my patrol, I'll be back shortly").  He takes the correct path.  
After killing the 2 agents, he **immediately** offers the quest Jungle Secrets, which player can take.
- If player takes it, Doren is active and the quest can be handed in.
- If player does not take it, then after 2 mins Thorsen says "I have been gone a long time, I better be heading back", and then walks back to the camp with the correct path, and player must (correctly) wait until next patrol.

Looks good :)
