### ISSUE TITLE
[Quest] Ursoc, The Bear God - Grizzly Hills 12236

### ISSUE THREAD

**Issue by CpScotch** [WoWManiaUK/Redemption#4322]
**Links:**
https://www.wowhead.com/quest=12236/ursoc-the-bear-god
https://www.wowhead.com/item=37307/purified-ashes-of-vordrassil
**What is Happening:**
The quest NPC (Tur Ragepaw) needed to start the event gets stuck on his starting position or vanishes half way through the escort section

**What Should happen:**
the NPC (Tur Ragepaw) should be escorted to the end and then summon Ursoc for combat. THE NPC should assist with the combat and then the quest item (purified-ashes-of-vordrassil) should be used on the bears corps to complete the quest.
then the NPC needs to be reset for the next player

**Comment by wow-mania** [comment]
100% it works

**Comment by WhitephoenixTheBunny** [comment]
sometimes when some give up from quest, the npc bug out...

**Comment by svijetlo** [comment]
if you die or reset quest wait for 5+ mins for npc to reset properly to his position

**Comment by jeyrella** [comment]
I have personally seen Ursoc vanish half-way through the escort a couple of times

**Comment by jeyrella** [comment]
Confirmed.   Just tested him, asked Ursoc to tank bear form, and he despawned half-way down the entrance tunnel.  Could not determine a trigger for this.

**Comment by wow-mania** [comment]
I highly doubt this is not working.

**Comment by Rushor** [comment]
he always despawns 5 minutes after spawn  - no matter what. this is some kind of "hard reset" of him. i will increase that timer to 15 minutes :)

**Comment by jeyrella** [comment]
Not sure if this is "the" fix, since it only takes about 1:30 to get to that point in the tunnel.
Have done it 5 times now since fix and there are still two issues noted.  

1)  On one run, Ursoc did not spawn once Tur and myself reached the end point.  Tur issued his taunt speech but no spawn.  At this point the player is stuck and no further progress possible.
![image](https://user-images.githubusercontent.com/46089380/77861752-d6f96a80-720e-11ea-8842-e2215d955972.png)


2)  I noticed that on every run, after the first combat, Tur changes out of his shapeshifted form, reverts back to his natural rageclaw form, runs back to his tree stump, and loses aggro. then runs back to the combat zone and re-engages.
He definitely should not be doing this, see this video where he has stayed in "bear form" all the way to the boss.
https://www.youtube.com/watch?v=3j6Qp2ZcCVY
This alone could be problematic, it is a 2-player quest with the point that Tur assists as a "3rd member" in whatever role is needed.

**Comment by Rushor** [comment]
Related to this Bad reset behaviour for creatures with sai

**Comment by wow-mania** [comment]
Is the quat completable?

**Comment by Rushor** [comment]
not yet due to the despawn issue - i will check that now on ptr

**Comment by Rushor** [comment]
okay 1. issue - ursoc despawns already 30 seconds out of combat on final waypoint reach. this is too short time. will increase that timer to 300 seconds

2 issue. - i will readd his auras depending on which form is active on his resets. looks strange but then he has all his needed auras.

3. will add an update of the homeposition every 2 seconds. then he should no longer run back to the spawnpoint on reset

**Comment by Rushor** [comment]
homeposition will alway be updated now. ursoc will stay longer on the spawnplace. auras for npc should ork better now (not healer yet, but the other 2 dps and tank should work smooth)

**Comment by jeyrella** [comment]
Ok, so ran this a number of times, confirmed this is ready for production, with notes.

1.  Despawn in tunnel appears to be fixed
2.  Spawn at boss location appears to be fixed
3.  Tur correctly stays in bear/boomie forms and re-engages combat after each pack; does look a little odd **but it works**
3.  As mentioned, healer form does not work and reverts to rageclaw form, however **quest is still completable** in this form.   This could be improved in future.

**Comment by Rushor** [comment]
Thank you for the tests
