### ISSUE TITLE
[NPC] Tur Ragepaw - Missing attackstart during event

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4348]
Related to https://github.com/WoWManiaUK/Redemption/issues/4322 i noticed now that the creature is missing an attackstart once Ursoc is spawned.

This is actzally needed and with that change we can remove the unneeded action "despawn on respawn of ursoc". Because if ursoc simply kills Tur Ragepaw if no player is in range the whole encounter will reset properly.

With the fix, both Tur Ragepaw and Ursoc will properly engage in combat.

https://www.wowhead.com/quest=12236/ursoc-the-bear-god

**Comment by Rushor** [comment]
test

**Comment by jeyrella** [comment]
Well, he does, and it respawns correctly too.  However Tur dives straight into combat; https://www.youtube.com/watch?v=3j6Qp2ZcCVY shows there is apprx. 3 seconds pause before he does so, this would be particularly relevant when the healer form is selected because of course you don't want the healer trying to tank :D

**Comment by Rushor** [comment]
okay will adjust that timer

**Comment by Velzevoul** [comment]
I tested couple of times now, Tank and dps shapeshifts works fine. The problem is if you use healer and let him touch or get touched by the bears around the area even once he transforms in his original form, in order for you to keep him as a healer you need to instant kill all the bears and let him go untouched to Ursoc. The timer at starting the fight with Ursoc is around 0.7-1sec so i would say after comparing it with youtube video is good.

**Comment by Rushor** [comment]
Yes we talked about the healer Thing already. That is as-is. Cannot be fixed for now.

**Comment by jeyrella** [comment]
@Velzevoul note that 
a) the video posted was from MoP era, we should be careful to research WotLK era videos.
b) the player starts the combat, not Tur.  Tur only engages after about 3 seconds.

**Comment by jeyrella** [comment]
The despawn needs adding back, it is leading to multiple spawns of Ursoc

**Comment by Rushor** [comment]
actually i fixed that Tur Ragepaw despawns unintended - the despawn of Ursoc was never a issue before, or not mentioned - so i will add that

**Comment by Rushor** [comment]
ursoc will now always despawn 7 minutes after spawn

**Comment by jeyrella** [comment]
Great, fixed.  Now if player fails to kill Ursoc, he will despawn after few mins.
https://youtu.be/kivVkdNba1I
