### ISSUE TITLE
[Item] Maniac's Hacker of the Light

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4485]
**Links:** #3734 
https://www.wow-mania.com/armory/?item=92018

**What is Happening:** The problem mentioned in #3734 is still present. The weapon offers ilvl 284 melee damage while also offering the spell power bonus of a 284 weapon (bloodsurge, terenas, etc.). This generally isn't much of an issue as most people use that axe just for the spell power, but dual wielding those makes enhancement shaman super strong. Blizzard balanced them by nearly halving melee dps of caster weapons while leaving melee dps weapons spell power-less. Having both at the highest level on 2 weapons is absurdly strong. Also the fact that it's a slow weapon (2.60 speed) makes it even more perfect)

**What Should happen:** Either reduce the melee dps, the spell power, or both or just make it impossible to wield both. 

I understand this is entirely to the discretion of devs, but just wanted to remind that this weapon makes the class *a lot* stronger than blizzard intended it to be.

**Comment by wow-mania** [comment]
We will look into this.

**Comment by wow-mania** [comment]
Spell Power reduced to half on both items 92017 and 92017.

**Comment by wardoc94** [comment]
They don't make a big enough impact on enhancement to require a nerf, DK's and Warriors will still out dps an enhancement shaman even with bis gear, i pull about 18k on festergut on my enhancement shaman with these weapons, my warrior does about 20k and my dk about 19k. if you are going to nerf these you'd have to start looking at other weapons also, like recurve, hackers, and headchopper, not to mention the LK set. only thing you will accomplish with this nerf will be sad enhancement players who can finally get invited to raids, and loss of money since the weapons will be unuseable.

**Comment by Tamagucci** [comment]
Hi, for the record, I bought these and own 2x on my enhancement shaman so I can actually say from EXPERIENCE and give some feedback after using these for about 4 months. These weapons are far from "absurdly strong" they're just strong as are allllll of the other maniac 1h axes (str axes on a frost DK??). The weapons are not breaking the game in any way, shape or form. If the argument is that it makes the weapon "non-blizzard", they're CUSTOM weapons, how exactly are they supposed to be "blizz-like" and what was the point in the first place making custom gear? What's happening is a very far down, sub-tier dps class (Enhancement) has become a slightly better sub-tier dps class as Wardoc mentioned above. They're a fun, non-competitive dps class for a raid spots. 

My point is these weapons are gimmicky, fun, theory-crafting items (Custom weapons) being used by a fun, gimmicky dps spec, why does it matter? There isn't another class that even uses them other than enhancement.

**Comment by nhockey** [comment]
People have donated for these as they are. If a "fix" is put in I suggest that it's a new weapon with the proposed stats and that the old weapons are left as is as to not irritate the people who've already spent money on the weapons. Then make the old version of the weapon unavailable from here on out. Just a thought.

**Comment by therealjimboslice** [comment]
I don't agree that having this axe nerfed is necessary. Maybe ban the use of it in arenas. They make enhancement shamans strong but not absurdly strong. I've been playing enhance for a few years on wow-mania and It's a bummer being told you can't raid just because your spec doesn't offer any unique buff or insane damage to the group. It's a super fun spec and this weapon makes it all the better. What if all you can find to fill your raid is an enhancement. Lmao.. You'll feel better if he/she has these equipped. Having bought 4 myself, i can say it's been the best use of my money put into the server and would be bummed to see the item nerfed.

**Comment by GMMetaxa** [comment]
As a similair 2H wep has 800 SP, the 1H wep should have 400 SP, but that should be the ONLY change here. Two of them would give the 800 SP in total.
For the rest these weapons are custom weapons people paid and are paying for. So they should be good.  This change should be applied to 92017-92018 and 92021.

**Comment by wow-mania** [comment]
Will stay as it.
