### ISSUE TITLE
[ICC/Boss] Gunship Cannon's heat

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4533]
**Links:** https://www.wowhead.com/npc=36838/alliance-gunship-cannon
https://www.wowhead.com/spell=70172/cannon-blast

**What is Happening:** Can't be certain for horde, but on alliance, the heat generated by the gunship cannons #1 ability [[Cannon Blast]](https://www.wowhead.com/spell=70172/cannon-blast) only generates the heat after a ~3-4 second delay, making it very awkward to know when to unload the heat with your #2 ability.

**What Should happen:** The heat generated by this ability should be generated instantly upon casting the ability. It used to work, but the last update that fixed the damage from 1000 to 1500 also added the heat delay.

**Comment by svijetlo** [comment]
i did notice this and it gets rly stupid to follow you think i can do one more shoot then you do it and energy from last comes in and you overheat

**Comment by svijetlo** [comment]
i think this is lag related not game on ptr works as charm

**Comment by svijetlo** [comment]
opening this one back as it is now happening on ptr also

**Comment by Keader** [comment]
i will look tonight

**Comment by mamgy** [comment]
I noticed you are getting heat after landing a shot not after firing it. Maybe that's causing "delay".
Basically if you want to preheat gun before fight even starts you will have to wait for the shots to land on the ground.

**Comment by lowbg** [comment]
Exactly as mamgy says the shot from canon is not count on the heat before to land on the ground thats why otherwise you can keep spam and will come on the counter  after the ball fall on the ground . its not bug

**Comment by svijetlo** [comment]
it is bug one need to get energy ones one use spell not ones ball hit target, if you have no valid reference pls do not say smrt is not bug

**Comment by jeyrella** [comment]
@lowbg Heat should be generated from the cannon on skill use, not on ball hitting ground.
Try firing a gun for real.  It gets hot straight away, not after the bullet hits the target.
As @Oganku mentions, this HAS changed recently, it used to work correctly - possibly linked to the change to the damage caused by cannons.

**Comment by jeyrella** [comment]
@lowbg Heat should be generated from the cannon on skill use, not on ball hitting ground.
Try firing a gun for real. It gets hot straight away, not after the bullet hits the target.
As @Oganku mentions, this HAS changed recently, it used to work correctly - possibly linked to the change to the damage caused by cannons.

Watch carefully here for evidence.  You will see that the heat builds as soon as the cannon is fired, not as it lands on the ship.
https://youtu.be/Gr5bjMb_Sl4?t=84

**Comment by Keader** [comment]
fixed

**Comment by svijetlo** [comment]
@Keader  Heat gain works fine now but there is new problem if energy get 100+ there is no Overheat mechanism 
aloso if you are not in combat use of Incinerating Blast will not drain heat you have

**Comment by Keader** [comment]
try now pls.
