### ISSUE TITLE
[Internal] Remove wrong loot drops

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Redemption#4536]
Merge with a little list of removed wrong items + some more:

-- Remove incorrect items from Trelane's Chest / Footlocker / Lockbox and Alterac Granite
-- Incorrect/weird or drops from gameobjects or items
-- Weapon Crates and Armor Crates should contain only weapons and armor
-- Incorrect/weird and/or already drops from gameobjects or items
-- Runn Tum Tuber should drop only from Pusillin
-- Patch 1.4.0 (2005-05-05): Tormented Spirits will drop their Ghostly Bracers every time they die now.
-- DB/Loot: Add reference for Green Hills of Stranglethorn Pages
-- DB/Loot: Add reference for Depleted items (Ogri'la)
-- Add missing bandages to Arathi Basin care packages

This does not need a test

**Comment by jeyrella** [comment]
Can we have some more details around what exactly has changed here please @Rushor ?
e.g. 
" -- Incorrect/weird and/or already drops from gameobjects or items"
-- DB/Loot: Add reference for Green Hills of Stranglethorn Pages     -  _what reference??_

**Comment by Rushor** [comment]
i give you a list in discord

**Comment by jeyrella** [comment]
@Aristo14 for the notes:

- Various spurious item drops cleaned up e.g. lockpicks 0.02% dropping from a snake
- several chests & box contents corrected e.g.  Weapon/Armor Crates containing only weapons and armor
- Un'goro quest items from "Covert Ops Pack" and "Torwa's Pouch" no longer found in random chests
- Runn Tum Tuber now drops only from Pusillin (Dire Maul)
- Tormented Spirits in Tirisfal Glades will drop their Ghostly Bracers every time they "die" (again!)
- Bandages added to Arathi Basin care packages. Because, they care.
- Green Hills of Stranglethorn Pages will now drop much more consistently across a more accurate range of mobs

(last one may warrant a seperate line as it is the most impactful improvementin the list)
