### ISSUE TITLE
[Spell] Campire spell range issue?

### ISSUE THREAD

**Issue by Jonall2010** [WoWManiaUK/Redemption#4558]
**Links:**

**What is Happening:**

**What Should happen:**

**Comment by Rushor** [comment]
which fire man? can you send us a screenshot?

**Comment by Rushor** [comment]
text by author: 

charicter proximity is off/wrong. I am always getting burned buy the fires when I am trying to cook or run past a camp fire. I can not finish the K3 area quest of the minefield because of this and after going through all this BS just to tell you about it I am even more upset. I shouldnt have to join a 3rd party just to report a bug to your server!!

**Comment by Aristo14** [comment]
> I shouldnt have to join a 3rd party just to report a bug to your server!!

Well actually you do and it needs to have specific information so testers can actually test it out for you.
