### ISSUE TITLE
[Quest] "Tokens of the Descendants" creatures not summonable - 11074 - Terokkar

### ISSUE THREAD

**Issue by Tankjnr** [WoWManiaUK/Redemption#4570]
**Links:**
https://youtu.be/HcCq8V1wEc4

**What is Happening:**
after completing the quest for the first time. it hasnt worked again. I am unable to summon the creatures to fight ( having acquired the Time-Lost scroll) to kill them again

**What Should happen:**
after collecting time lost scrolls you should be able to summon each creature on repeat to farm reputation

kind regards
Tankjnr

**Comment by jeyrella** [comment]
https://wow-mania.com/armory/?quest=11074

**Comment by jeyrella** [comment]
Well it tells you in the error message on screen exactly what the problem is...  "Missing reagent: Time-lost scroll.
![image](https://user-images.githubusercontent.com/46089380/82477042-c3f46f80-9ac6-11ea-8f15-ffb7c84c2f95.png)

When you actually have 10 of them, it works just fine.

https://youtu.be/sWEorbYGiU4
