### ISSUE TITLE
[Dungeon] Mobs can go through first door in HoR

### ISSUE THREAD

**Issue by yani** [WoWManiaUK/Redemption#4577]
**What is Happening:**
When a player is locked behind the door in Halls of Reflection. It's possible for the mobs during the waves to target and fly towards that player.

**What Should happen:**
They should only target players inside of the room.

**Comment by jeyrella** [comment]
Can't seem to replicate this.  Can't find a way to get threat on the person locked outside - they can't target mobs inside.
Can you give more details, and do you mean the very first door right by the entrance?

**Comment by jeyrella** [comment]
Found it.

**Comment by Rushor** [comment]
Okay will check

**Comment by yani** [comment]
There was also a bug where if they shadowstep mirror images they bug the waves. But I haven't made a ticket for that yet because somebody just told me.

**Comment by jeyrella** [comment]
@yani please NEVER make tickets because you hear of an issue second-hand - it must always be something you witness yourself.

There was already a ticket for that and has had many attempts at fixing it, if you have more eye-witness detail to add to it preferably with video, then please add it to this ticket instead #4483

**Comment by Rushor** [comment]
Position check will be added

**Comment by Rushor** [comment]
okay try now pls
