### ISSUE TITLE
[Quest] Kalu'ak Fishing Derby incorrect start time - 24803

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#4581]
**Links:**
https://wow-mania.com/armory/?quest=24803
https://wow-mania.com/armory/?npc=38294

**What is Happening:**
Elder Clearwater offers the quest at 1pm server time, despite the calendar stating it is 2pm server time.

![image](https://user-images.githubusercontent.com/46089380/82731411-8da13500-9cfe-11ea-89df-33b8e76db96d.png)
![image](https://user-images.githubusercontent.com/46089380/82731517-6a2aba00-9cff-11ea-9338-e0c8c9e1b58b.png)

At 2pm he then yells the contest is over.
![image](https://user-images.githubusercontent.com/46089380/82731335-fb992c80-9cfd-11ea-934d-0eadeb2ec2b2.png)

**What Should happen:**
As per Wowhead comments the 2pm server time noted in the calendar is correct.
![image](https://user-images.githubusercontent.com/46089380/82731550-a78f4780-9cff-11ea-8fd1-4b4d0dab01cc.png)

This causes confusion and upset for players who correctly turn up at 2pm for the fishing contest only to find it has already ended.
**Please can we adjust the NPC's event start time** to be 1 hour later.

**Comment by jeyrella** [comment]
Note:  this most likely also affects the Stranglethorn Fishing Contest as well.

**Comment by Oganku** [comment]
I actually remember reporting that on #3828 for the stranglethorn vale one and a similar issue was fixed

**Comment by Rushor** [comment]
delayed the yells and starts of texts by 1 hour in his script.

is the spawntimer of the creature working correctly?

**Comment by jeyrella** [comment]
This can't be tested until Saturday.  Suggest release to live and monitor.

**Comment by Rushor** [comment]
yes sure

**Comment by GMZinius** [comment]
> is the spawntimer of the creature working correctly?

- No, Elder Clearwater spawns at 14:03:14 (should be 1400) Realm time
- Seen today that the _event ended announcement_ before Elder Clearwater has even spawned.

(Player local time)
![image](https://github.com/user-attachments/assets/bd7f5165-701d-485e-9231-17c6517b1824)


This event is all mess up, you will see my report @Rushor. let's get this functioning correctly like we did recently for the  Stranglethorn Vale 

We fix from this one https://github.com/fvicaria/WoW-Mania/issues/454
This could be due to the Realm time now being +1 hour difference than it was years ago
