### ISSUE TITLE
tmog fistweapons bugged

### ISSUE THREAD

**Issue by Omnivore85** [WoWManiaUK/Redemption#4595]
**Links:**

**What is Happening:**If you transmog a MH or OH fistweapon to *wrong* hand it will be turned inwards to the character instead of flipped/mirrored 180*

**What Should happen:** It should look the same on both hands and not weird.

**Comment by wow-mania** [comment]
you gave absolutely no info
what is the item id?
add screenshot.

**Comment by Omnivore85** [comment]
Its all offhands in general exept maybe 2-3. What info do you need when it affects 95% of all fistweapons? 
Try to transmog lets say https://www.wowhead.com/item=50315/seven-fingered-claws&bonus=4128 to your offhand and see what happens

**Comment by Omnivore85** [comment]
Screenshot here for example
https://ibb.co/7n9bb4R

**Comment by Oganku** [comment]
I can second this issue. When a weapon is transmogged from one hand to another, its model is simply translated to the other hand. However, some weapons are meant for only the main/off-hand and when transmogged to the other hand, it shows wrong and often facing inside the character's body. 

This issue is very obvious with fist weapons, as most of them are unique main/off-hand designs, but also in some swords.
 
Applying a reflection across the character's center axis (if possible) would fix this issue simply enough, without affecting all other already symmetrical weapons. This would probably need a client update however.

**Comment by wow-mania** [comment]
Most of these are fixed in dev but regardless of that when you log something you need to specify which item(s) you are talking about. If it is one list the one and if it is "all" list "all".

**Comment by wow-mania** [comment]
We just checked this.
If you are trying to transmog mainhand into an off-hand this is what you get. 
This will not be fixed.
However, if this is not the case feel free to send screenshots and item id.
