### ISSUE TITLE
[Quest] Frostsaber provision

### ISSUE THREAD

**Issue by huqboss** [WoWManiaUK/Redemption#461]
Quest http://www.wow-mania.com/armory/?quest=4970 is obsolete.
For Wintersaber and Venomhide raptor way of getting it was changed in patch 3.2 from repeatable high grind quests into 20 dailies given by pet. Unlucky for alliance on wow-mania it was implemented only for horde. I'd like to thank to GM which promised to add this problem here. Ofc just promised..

**Comment by wow-mania** [comment]
![image](https://cloud.githubusercontent.com/assets/12248683/20465108/b49ec8ea-af4d-11e6-8ee6-d896fb31bed5.png)

**Comment by wow-mania** [comment]
Made quest repeatable.

**Comment by huqboss** [comment]
This quest is repeatable. Can do it even 100x a day. Problem is that this quest in patch 3.2 was replaced by doing 20x daily quest for pet to get mount (same mechanic like horde has).

This is proper quest: http://www.wowhead.com/quest=29034/they-grow-up-so-fast

Horde has implemented change from patch 3.2, Alliance not.

**Comment by jarvik76** [comment]
There appears to be a regression issue on this quest, and the follow-up.  They have turned from Repeatable turn-in (correct), back to dailies (incorrect, that was a Cata change)

https://www.wow-mania.com/armory/?quest=4970
https://www.wow-mania.com/armory/?quest=5201
I would suspect also that the final quest available at Revered reputation, is also set to Daily rather than Repeatable:
https://www.wow-mania.com/armory/?quest=5981

**Comment by jarvik76** [comment]
just in case there is any confusion, this post on ownedcore from 2009 in retail wotlk, showing this is turn-in, NOT daily:
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/223383-guide-wintersaber-rep-grinding.html
![image](https://user-images.githubusercontent.com/46089380/68674402-baa1ad80-054d-11ea-9af7-ef9a1500d9a3.png)
