### ISSUE TITLE
Call to arms

### ISSUE THREAD

**Issue by Myzeriel** [WoWManiaUK/Redemption#4642]
**Links:**

**What is Happening:**
got the quest second time yesterday. Had it complete, wanted to turn over this morning.
This morning it wasnt finished, and after 2 AB games won, still not finished.

**What Should happen:**
finish quest after AB game won

**Comment by Oganku** [comment]
Read what I commented on #4634 the last time. It seems they're gonna not touch it since it works fine, just gonna appear like you can turn it in but you can only do it once per day. If they mess with how the quest is given, it might make it worse. Call to arms by far in the best state they've been and I understand the reasoning if they decide to leave it as is

**Comment by wow-mania** [comment]
need to go to correct NPC. this is not retail.

**Comment by Oganku** [comment]
Any call to arms quests. They are daily quests, but are automatically awarded upon entering the corresponding battleground of the week. Once you complete it once, if you enter the bg again, you are given the quest again, but even if you win and complete the quest, you will be unable to turn it in since it is limited to one turn-in per day (daily). Once the daily reset occurs, you can properly see the NPC and turn them in.

**Comment by Myzeriel** [comment]
OMG this is not the same issue! 
Now i cant turn it in not even ONCE A DAY

**Comment by Myzeriel** [comment]
read what i wrote- done it once that day, took it and done it again so i can turn it in the next morning but the next morning it wasnt finished. I did 2 games andd yet it wasnt finished

**Comment by svijetlo** [comment]
ahhhhh i see his problem ......
he did it ones yesterday , 
then could be able to take it again and finish but could not give it in (know issue wont be fix as i know)
then he was thinking i will save me self time and just give it in tomrow as soon i log in 
but quest will not recognize it as of this day so you cant give it in , 
what he need to do it give up one form yesterday take new one and finish it today
daily quests carry DAY ID MARK as i know

**Comment by svijetlo** [comment]
give up old one take new one in future dont do that to save daily like that for next day as it can mess up things

**Comment by wow-mania** [comment]
You can not do that.
