### ISSUE TITLE
[Quest/Event] Torch Tossing - Quest 11731/11922

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4680]
**Links:** Issue #3354 is back.

**What is Happening:** The arrows start appearing after a very long delay after the first few, which makes the quest nearly impossible, unless you're very lucky.

**What Should happen:** The arrows indicating which markers to hit should always appear until the quest timer of 1min30 expires.

**Comment by wow-mania** [comment]
Works. It is supposed to be difficult. Difficult <> broken.

**Comment by jeyrella** [comment]
It is broken.  Completely broken.  Not "difficult".  Completely does not work at all like how Blizzard had it, and is nearly impossible to complete because of it being broken.

**Comment by wow-mania** [comment]
"Completely broken" and "nearly impossible" pick your battle.

**Comment by jeyrella** [comment]
This is not a duplicate.  Torch Catching is NOT Torch Tossing.  They are two different quests.

**Comment by jeyrella** [comment]
https://youtu.be/BzVvWBTKXt0

**Comment by jeyrella** [comment]
https://youtu.be/DwcInqXg75o
Showing:
Big gap between 3rd, 10th and 11th braziers
They can start ok but then stop appearing after 3 or 4 marks
Quest failed because of this.

This is not how it works in Blizzard - it is not a luck-based event.  There is definitely something very broken with whether the marks appear on the braziers.

**Comment by jeyrella** [comment]
https://youtu.be/n1Uo7_Idj2M
This one in Orgrimmar taken on Redemption (since PTR seems to be broken in Org not sure how/why.)

This one shows the mark appearing by the bonfire, and not ever showing on a brazier at all.  After 20 seconds it disappears,  then a few seconds later appears back by the bonfire.

**Comment by wow-mania** [comment]
Please do not reopen issue. There are 2 on the same quest.

**Comment by jeyrella** [comment]
This one taken in PTR in Darnassus showing the same as above.  Marker starts on the player, then big gaps, then doesn't show at all.  Quest fails.
https://youtu.be/fXcVsETAbyA

**Comment by jeyrella** [comment]
Re-opening after clarifying with Janitor this is not the same issue as 4681 - different quest.
@Rushor, lots of videos above

**Comment by jeyrella** [comment]
Torch Tossing quests:
Starters:
https://wow-mania.com/armory/?quest=11922
https://wow-mania.com/armory/?quest=11731
Daily versions
https://wow-mania.com/armory/?quest=11921
https://wow-mania.com/armory/?quest=11926

**Comment by Rushor** [comment]
i am on it now

**Comment by Rushor** [comment]
fixed. https://i.imgur.com/7CiPLgw.jpg  that was a hard one

**Comment by Rushor** [comment]
pls quick check if it work ok now in all the capitals

**Comment by jeyrella** [comment]
- [ ] Orgrimmar
- [ ] Stormwind
- [ ] Undercity
- [ ] Silvermoon
- [ ] Thunder Bluff
- [x] Darnassus
- [ ] Ironforge
- [ ] Exodar

**Comment by Rushor** [comment]
Awesome thank you
