### ISSUE TITLE
[Event] Midsummer event extra alliance tent in Feralas

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#4696]
**Links:** Related to issue #4694

**What is Happening:** There are 2 alliance tents (event locations) in Feralas, but only one has the actual fire that can be desecrated/kindled. 
Fire 1: 
![WoWScrnShot_062420_211136](https://user-images.githubusercontent.com/34783736/85642477-a3887980-b65f-11ea-89eb-41c446989188.jpg)
![image](https://user-images.githubusercontent.com/34783736/85642508-b7cc7680-b65f-11ea-8892-ffb1455388ef.png)

Fire 2:
![WoWScrnShot_062420_211326](https://user-images.githubusercontent.com/34783736/85642541-d3378180-b65f-11ea-8561-84d4e7e7b849.jpg)
![image](https://user-images.githubusercontent.com/34783736/85642565-e0ed0700-b65f-11ea-9091-0b944d4fa3e5.png)

**What Should happen:** Only the fire near Feathermoon Stronghold (#1) should be present. The extra tent is misleading and should not be present.

**Comment by jeyrella** [comment]
Confirmed on PTR.  This location posted above inland from the shoreline was the post-Cata location (due to the Great Flooding).  (https://www.wowhead.com/midsummer-fire-festival-guide#bonfires-kalimdor)
Should be removed.
![image](https://user-images.githubusercontent.com/46089380/85642738-39d19500-b68a-11ea-993b-7eb5856c2f11.png)


The real one in Feathermoon is correctly present.

**Comment by Rushor** [comment]
okay the one from cata is removed now.

**Comment by jeyrella** [comment]
Looking good
![image](https://user-images.githubusercontent.com/46089380/85872765-16acff80-b7c8-11ea-8e70-d14e9d835daf.png)

**Comment by Rushor** [comment]
cool thanks
