### ISSUE TITLE
[Quest] Gambling Debt quest

### ISSUE THREAD

**Issue by sloewen897** [WoWManiaUK/Redemption#4727]
**Links:**

**What is Happening:**
The quest Gambling debt in Howling Fjord at Scalawag Point is not working properly. I am supposed to get the debt from Silvermoon Harry. When I talk to him he gives options - 1)to pay up 2) see what he is selling. When I hit either option nothing happens. I made a ticket and GM said he is not working properly. What should happen is when I talk to him and tell him to pay up he should aggro and attack me, where I defeat him and get his gambling debt. I was asked to report it so hopefully that is the needed information

**What Should happen:**

**Comment by wow-mania** [comment]
Pretty sure this works.
Can someone confirm on ptr please

**Comment by jeyrella** [comment]
Well.  I've done this on no less than 7 toons on live, so it definitely works in some way.

**Comment by jeyrella** [comment]
Confirmed.  Options don't work any more.  This is definitely regression.

**Comment by jeyrella** [comment]
https://wow-mania.com/armory/?quest=11464
https://wow-mania.com/armory/?npc=24539

**Comment by Rushor** [comment]
the issue is actually new, created by some internal gossip updates i think. will work on it

**Comment by Rushor** [comment]
gossip option should work now again.

**Comment by jeyrella** [comment]
hmm.  While it technically "works" not sure if this is right, since he now seems to give you the debt item, and THEN turn agressive after you speak to him.
https://youtu.be/9c2cgg9BFd4

It should be the other way around.  The first gossip turns him angry, you beat him a little, he turns friendly at 50% (working) and you speak to him again to get the reward
![image](https://user-images.githubusercontent.com/46089380/86541625-436ac080-bf06-11ea-97aa-6b7a892af1ab.png)

**Comment by Rushor** [comment]
Hmmm for me that was working. Maybe not everything applied

**Comment by Rushor** [comment]
okay try now again man https://i.imgur.com/aUbRcGf.jpg https://i.imgur.com/zTuI1RJ.jpg

**Comment by jeyrella** [comment]
Fixed :)  
https://youtu.be/yg3CL7jEpm0
