### ISSUE TITLE
The deadly airship

### ISSUE THREAD

**Issue by Sierbahnn** [WoWManiaUK/Redemption#4824]
On some points on the Airship above icecrown you instantly die when you step on them while the ship is moving. I have no idea why that is.

![image](https://user-images.githubusercontent.com/68108749/89189490-5376ce00-d5a0-11ea-8e89-ab24fe3481b4.png)

I have never seen this before, is this something new for the last fix implemented.
It has murdered an alt while it was on a flying mount, standing on the deck, as well.

**Comment by Oganku** [comment]
I believe it has to do with fall damage since the ship is flying. Sometimes you jump on it and die, sometimes you do nothing and still die. It might have to be communication between player's position and server. Maybe devs have an idea for that.

**Comment by svijetlo** [comment]
it is do to fact ship is moving object in game and if you lag a a bit you kinda fall down , also make sure you check combat log and see if one on dragon flying around shoot at yu his flames will follow you no matter where you go and hit you

**Comment by jeyrella** [comment]
Some small places the Gargoyle Ambusher is still in range to attack.
I have a feeling in order to fix this, we'll need to see the combat log of exactly what killed you, and a precise location on the map.  

Standing on the ship itself in that spot where you are does nothing, so it is something about the external environment it passes through, not the ship itself.

**Comment by Rushor** [comment]
try now, no strange falldamage on transport anymore
