### ISSUE TITLE
Wow mania Glorenz wep 25hc

### ISSUE THREAD

**Issue by xruisue123** [WoWManiaUK/Redemption#4834]
**Links:**
https://www.wow-mania.com/armory/?item=50730

**What is Happening:**
Ive gotten the lk wep from 25 hc lk, glorenz sword, and when i want to put in in my main hand, it wont trasnfer my crit to it only in off hand, pls help me with that , tyvm

**What Should happen
it should give crit either main off hand

**Comment by Oganku** [comment]
Equipping any weapon (glorenzelg hc included) in either hand gives the exact same crit amount. You do need to know that gloren itself gives about ~3.5% crit chance, but if you equip alone your crit will go up by about ~8.5% since the cruelty talent will apply from having no melee weapon equipped to having one. 

No issue here
