### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Daka1201** [WoWManiaUK/Redemption#4898]
**Links:**

**What is Happening:**
I get a fatal error, say it is asking for more memory. It is asking for 9 gigs or more. I have 16 gigs

**What Should happen:**

**Comment by Daka1201** [comment]
![IMG_20200824_183643 - Copy](https://user-images.githubusercontent.com/70176684/91103906-96c1db00-e63a-11ea-82a9-e08b897218ff.jpg)

**Comment by Oganku** [comment]
Use the latest launcher pinned in discord's #red-world. This is a common issue for wotlk since the game is old and causes that error since you have more memory than it expects.

https://cdn.discordapp.com/attachments/288054714527121418/697520856494243880/Launcher-2020-03-25.zip

Also for next time, GitHub is for server bugs, not for individual issues.
