### ISSUE TITLE
[NPC] Ambassador Jerrikar - Not resetting to home position correctly

### ISSUE THREAD

**Issue by MariesD** [WoWManiaUK/Redemption#4930]
**Links:**

https://fr.wowhead.com/npc=18695/ambassadeur-jerrikar

**What is Happening:**
I am trying to attack him in the Dragonmaw Fortress in Shadowmoon Valley Outland, but he doesn’t move and “evade” any of my attacks.

**What Should happen:**
He should fight back and get damage from me.

**Comment by jeyrella** [comment]
Working fine in PTR, at least in location where found.
![image](https://user-images.githubusercontent.com/46089380/91775821-f8a6b580-ebe3-11ea-8e18-373c6478276c.png)
He does have an ability that makes him immune for 6 seconds when fighting him.

If he is evading because he gets stuck in terrain, then we need more detail on _exactly_ where you found him.  As in, coordinates.

**Comment by GMZinius** [comment]
Reopening this one 
I had a ticket today about this issue, while the player was offline I tested this myself.

@Rushor 

**Reproduce** 
- Attacking him 
- Die, runaway or (GM on) 

He will now evade.

NPC is'nt resetting correctly after failed kill

**Comment by Lumber-Jack-2** [comment]
had a wrong flag assigned - should be good now

**Comment by GMZinius** [comment]
Thank you @Rushor 
Much better 👍
