### ISSUE TITLE
[Event] Brewfest Drills incorrectly spawning Stormforged Marauders

### ISSUE THREAD

**Issue by Bubunya** [WoWManiaUK/Redemption#4986]
Players never been attacked by dark dwarves directly - not even when players tsart trowing beer at them. They use to go directly to kegs and players quest was to hold/kill enough of them to protect kegs. 
Went to IF brewfest ground and been attacked by tons of dark dwarves even withiut start trowing beer at them.
Tryed another time - same. Clean cash, restart, reboot, grabbed another toon from another account - and this toon been attacked by GHOST dark dwarves - meaning event was FINISHED already and toon was entering Brewfest ground when 5 or 6 dark dwarves just materialized from a fresh air and killed my toon.
Never bodies of dark dwarves been outside of brewfest ground - simply 'cos they NEVER walk at any other directions aside from underground rockets to the kegs. Never dark dwarbes follows players all around Brewfest and way ahead in order to kill them.
Sorry, guys, but something is wrong with agro settings this year.

**Comment by Oganku** [comment]
Next time follow the format please.

The [Dark Iron Guzzlers](https://www.wow-mania.com/armory/?npc=23709) spawn fine, but in addition, some Stormforged Marauders spawn from the swarm of drills. It is 100% caused by the fix for issue #4900 that uses the same drills I suppose. After only a few minutes the area looks like this : 

![image](https://user-images.githubusercontent.com/34783736/93702534-3a40c700-fae5-11ea-8c64-da62e29ddd6f.png)

Should fix asap to remove the extra marauders that will kill any lower level players.

**Comment by Rushor** [comment]
the marauder script will now only run in northrend, in the old world the marauders will not spawn

**Comment by jeyrella** [comment]
Now correctly does not spawn marauders.
https://youtu.be/EKr6DSU8dJs
