### ISSUE TITLE
Damages Issue 

### ISSUE THREAD

**Issue by Mwollfiez** [WoWManiaUK/Redemption#5035]
Hey so i have noticed that weeks ago that Either Resilience or some Specific classes damages are not normal Because i am playing with 980 Resilience and i get Crits up to 9k and i am pretty sure that is not normal i have been playing wow for years and i have never saw these kind of damages in pvp
if we are gonna talk about some specific classes The top of the problem list  they are Hunters i can assure u 100%  their damages are not normal , also come other classes , so please check that out.

**Comment by Rushor** [comment]
you must give us more infos, abou class, spells, talents you used. This issue sounds too general. Combatlog from wow can help aswell.

**Comment by Oganku** [comment]
From my experience with this, it does feel off at times, but every time I'd do the math, it would check out. The problem with hunters is that they can run full pve gear and still have decent survivability because of their class design. (Ranged + deterrence + disengage + traps) 
9 might sound high, but on someone with 0 resilience they'd probably be doing 15k pretty easily. 

Again, if you can come up with math that doesn't check out with the armory formulas for resilience/abilities, please do, but I have not been able to easily pinpoint an issue before.

**Comment by jeyrella** [comment]
Closing until OP provides more clear issues.
