### ISSUE TITLE
[Spell] Intercept (Warrior) hit chance based on spell hit rather than melee

### ISSUE THREAD

**Issue by Oganku** [WoWManiaUK/Redemption#5038]
**Links:** https://www.wow-mania.com/armory/?spell=20252

**What is Happening:** [Intercept](https://www.wow-mania.com/armory/?spell=20252), a warrior ability, uses the spell hit table for some reason, causing it to rarely miss even if the player has sufficient hit for melee spells. No other ability misses, as it should, but this one will sometimes.

Proof from a boss fight on a warrior with 172 (5.25%) hit rating, 8.25% thanks to precision talent.
![image](https://user-images.githubusercontent.com/34783736/95812333-2272f200-0ce3-11eb-8890-3631b8fc246f.png)

**What Should happen:** It's difficult to find evidence, but warriors only have 1 "spell", which is taunt. All other skills should follow the melee special ability hit table. Multiple guides and threads mention warriors only needing 8% for abilities, and I have been unable to find any place where they say intercept (or any other ability) behaves differently.

**Comment by jeyrella** [comment]
As oganku says it's hard to directly evidence something that wasn't documented.  Historic logs wouldn't indicate if a miss was a melee miss or a spell miss (since that historic char could potentially be under the melee hit cap too)
Discussion with Keader that he'll see at the weekend if he can find something in code that would indicate this either way.

**Comment by Keader** [comment]
ok, it will use melee hit chance instead of spell one
