### ISSUE TITLE
damage,item bug 

### ISSUE THREAD

**Issue by pentagramab** [WoWManiaUK/Redemption#5041]
**Links:**
https://drive.google.com/file/d/14O-v5UIseWKZWbmpPQtCtIfP-NmwZHkJ/view?usp=sharing

**What is Happening:**
Two night ago I bought my bis legs sanctified lightsworn legplates with heroic mark.After i bought it i lost 3-5 k dps.Those who has less gs than mine dps more than i do.I tried on dummies,pvp arenas and dungeons but the result is the same.I have not changed any item and i only wore the bis i got.To be sure I bought a new lightsworn panth with eof and i took a video, you will see that the result is in front of your eyes, the item was bugged in my character, i wait fo your support ASAP. 

**What Should happen:**
not lost dps i need to do more dps as usual because i bought bis one!

**Comment by svijetlo** [comment]
there is nothing wrong there that is ret paly i know not what you expect to do on dummy, also pls prio judgment with 4 set , and use some agilility items as your crit is way to low

**Comment by jeyrella** [comment]
This video does not show any comparison between sets and non-sets, or between 264 and 277.  It does not show what gear you replaced.
You're not prioritising judgements, which you should do when you have tier items.

You also seem to be concentrating on typing instead of doing actual damage.

Personally I would take a look at your prioritisation first before blaming a bug.

Please only open a ticket if you have reasonable incontravertable proof of a specific issue with an item.
