### ISSUE TITLE
[Items] Shattrath Flasks do not persist through death

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5066]
**Links:**
https://www.wow-mania.com/armory/?item=35717
And all other similar flasks
**What is Happening:**
The flasks do not persist through death

**What Should happen:**

According to description they should persist through death, same as wotlk endless rage etc.

**Comment by Oganku** [comment]
The flasks **do** correctly persist through death, but the buff is restricted to Tempest Keep, Serpentshrine Cavern, Caverns of Time: Mount Hyjal, Black Temple and the Sunwell Plateau, as indicated by the tooltip. So if you release after dying, you lose the effect since your ghost is outside the instance.

Can't find quickly whether that's intended, but it seems like it wouldn't. If possible make the effect inactive outside of those zones, but not completely disappear.

**Comment by Keader** [comment]
try now.
it has a exploit inside of it hehe.
anyway, both fixed. Now you can release and will not lose the effect.

**Comment by svijetlo** [comment]
hmm now you can use it out side and it will give you bonus stat but it will despair if you die and rea out

**Comment by Oganku** [comment]
Yep, same behavior as before. After releasing you still lose flask effect.
