### ISSUE TITLE
[Spell] Charge & Intercept 

### ISSUE THREAD

**Issue by KyptAMaN** [WoWManiaUK/Redemption#5107]
**Links:** https://www.wow-mania.com/armory/?spell=11578 & https://www.wow-mania.com/armory/?spell=20252

**What is Happening:** Charge ability is being interrupted when some hunters pet stun the warrior and knocks the charge down, so the warrior wont reach the hunter, same happens vs frost mages stuns, the stuns will interrupt the charge or intercept.
Also, the Intercept is at the moment being dodged by players, the dmg it self CAN be dodged, but the stun CANT only if the player that the warriror is attackin uses any type of counter spell (like Icebound fortitude on dks, deterrence hunters, etc...) but its not the case, the intercept stun is being dodged without any type of counter spell.
Another issue, when u intercept a target and u quickly charge right after, (happens alot vs frost mages) the charge wont be effective and the player that u attack will be "immune" it says.  

**What Should happen:** Charge or intercept cant be stopped by any type of pet stuns, freezed or any type of stuns in general.

Intercept should always STUN the target when theres no counter spell for it, it can dodge the dmg of it, but not the stun.

If you quick intercept a target and right after you use charge, the target shouldnt be immune to the stun.

**Comment by Oganku** [comment]
https://github.com/TrinityCore/TrinityCore/issues/18161

It's the kind of issue that's hard to find evidence, because the mechanic simply didn't exist in retail and shouldn't exist here either. Post from TC above mentions it fairly well (especially the last comment). Jumping charges is a commonly discussed strat, and is fine, but getting stopped mid-charge by hard CC is not correct behavior.

**Comment by Keader** [comment]
Is a deep motion master issue, nothing that i can do about.
