### ISSUE TITLE
Tame Beast Spell not working if Beast is under Effect of Freezing Trap

### ISSUE THREAD

**Issue by Willsmite** [WoWManiaUK/Redemption#5119]
**Links:**
https://www.wowhead.com/npc=32481/aotona#comments
https://www.wowhead.com/npc=28011/emperor-cobra

**What is Happening:**
Trying to use Tame Beast Spell on a beast Frozen with Freezing trap results in the Beast not being Tamed. Tested this with 
Non-Exotic Emperor Cobra 

Test 1 - Non Exotic Emperor Cobra in Sholazar- Placing Freezing trap and using Tame Beast - result - The Beast does not become pet when Tame Beast Spell Ends, Beast stays hostile when Freezing trap Effects End
Test 2 - Non Exotic Elite Aotona in Sholazar - Placed Freezing Trap and used Tame Beast - result - Beast stays Frozen without becoming pet and stays Hostile after Freezing trap effect ends
Test 3 - Non Exotic Emperor Cobra in Sholazar - Used Tame Beast Spell - result - Beast is successfully tamed and becomes Pet.
Test 4 - Non Exotic Emperor Cobra in Sholazar - Placed freezing trap ans used Tame Beast - result - Beast stays frozen after Tame Beast Spell ends and then continues to be Hostile once Freezing trap effect ends.
**What Should happen:**
Regardless of using Freezing trap Non Exotic and Normal Tameable Beasts should become Pets after using Tame Beast with right conditions.

**Comment by Aristo14** [comment]
Just went to try since I suspect something else is wrong. 
![Screenshot_3](https://user-images.githubusercontent.com/38132718/98953743-5b2e0300-24fd-11eb-8f25-2b58adf749bf.png)

taming while trapped.

![Screenshot_4](https://user-images.githubusercontent.com/38132718/98953803-6c770f80-24fd-11eb-9bb9-08be24b3857b.png)

Tamed while trapped. 

Make sure you don't have a pet active currently, your previous pet needs to be in stable and also i hope you didnt keep your taming quest pet from lvl 10?

**Comment by GMMetaxa** [comment]
Works.
