### ISSUE TITLE
[Talent] Killing Machine - Death Knight

### ISSUE THREAD

**Issue by bLeyaa** [WoWManiaUK/Redemption#5160]
**Links:** [Killing Machine](https://www.wow-mania.com/armory/?spell=51130)

**What is Happening:** Currently the talent is being procced by more than just auto attacks, causing Killing Machine talent to proc so often it is about three times more than intended.

**What Should happen:** Killing Machine talent should only proc from melee attacks as indicated on the tooltip of the talent.

Logs recorded on WoW-Mania:
![image](https://user-images.githubusercontent.com/61625377/100380567-66ae1d80-3017-11eb-9c6f-24f0da08b0eb.png)
http://www.worldoflogs.com/reports/td6f7jph5ygpji7p/details/0/?enc=kills

![image](https://user-images.githubusercontent.com/61625377/100380593-6dd52b80-3017-11eb-8812-21df417c2c8d.png)
http://www.worldoflogs.com/reports/6qm430yuzrj2ztnr/details/32/?enc=kills

Method logs from WoTLK era:
![image](https://user-images.githubusercontent.com/61625377/100380669-92310800-3017-11eb-8b75-2b01194ac292.png)
http://www.worldoflogs.com/reports/mfxew5mdm3orj505/details/13/?enc=kills

![image](https://user-images.githubusercontent.com/61625377/100380703-a117ba80-3017-11eb-9b9c-91b56a08d1b6.png)
http://www.worldoflogs.com/reports/a28vcl4cx8qhioxm/details/18/?enc=kills

**Keep in mind that also both of the logs that were recorded on WoW-Mania are with a one boss fight less than the retail logs but yet such a massive difference between them.**

**_P.S. When opening the links, go to "Buffs Cast" tab in order to see the above posted screenshots._**

**Comment by wow-mania** [comment]
This needs to be confirmed by a tester.

**Comment by Oganku** [comment]
Expected PPM is 8. I tested for a little while to exclude as much variation as possible. Here are # of procs per minute for each minute tested with regular icc gear on a dummy, for a total of 10 minutes:

1. 18
2. 18
3. 18
4. 18
5. 17
6. 19
7. 16
8. 26
9. 16
10. 17

For an average of 18.3 PPM, which is ~2.28x the intended rate, which is very close to the compared rates of full raid values listed above (~2.5x more procs).

Tests were done with following stats, simply auto-attacking a dummy and keeping diseases up.
![image](https://user-images.githubusercontent.com/34783736/100391290-f3011600-3000-11eb-9ec2-e96022f8dfeb.png)

I do understand PPMs are pseudo-random, but 10 minutes of whacking a dummy + 4 full raid data to compare that **consistently** show a large discrepancy, I say this issue is definitely valid.

**Comment by bLeyaa** [comment]
That's also correct, i forgot to add, about approximate PPM being ~8.

![image](https://user-images.githubusercontent.com/61625377/100392156-efd44d00-3035-11eb-8b82-b990ed6d7b19.png)

![image](https://user-images.githubusercontent.com/61625377/100392132-d6330580-3035-11eb-82b4-f5c0e0f7e525.png)

**Comment by Keader** [comment]
Ok, after search a lot, looks like in wotlk PPM rate is around 5~6.

@Oganku if you test with two weapons, chance is higher. Off hands attacks counts too

Please test now in ptr

**Comment by Oganku** [comment]
Can't really see any difference it seems.

**Comment by Keader** [comment]
Using a DK like:


![image](https://user-images.githubusercontent.com/7120913/100515920-a3386100-315e-11eb-91e1-b09bf1e6aff9.png)

With PPM = 8
[GM] Chance is: 34 (per hit)

With PPM = 6
[GM] Chance is: 25

how you dont see difference? :)
