### ISSUE TITLE
Not possible to disarm environment traps in raid

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5161]
**Links:** https://wow.gamepedia.com/Trap and https://foreveranoob.wordpress.com/2010/01/08/more-icc-traps/

**What is Happening:** Rogue cannot disable the traps in three different places in ICC... there is no option to disarm them when mouseover it

**What Should happen:** Rogue have to be able to disable all these traps, total of five... Two on bottom floor, one after Deathbringer boss and two where the big dogs are (stinky and precious)

**Comment by jeyrella** [comment]
@Keader is this a regression of #3990?

**Comment by Keader** [comment]
dont think so...
in a year, much things can happens lul

**Comment by Keader** [comment]
yeap, not same issue.
issue before was not see this traps.
now we cant interact with it.
I think that this interact thing is handled by client, but i cant test in a clean client because ptr dont allow it lul.
anyway, this is the exactly type of issue that i cant fix without debug to try track what's wrong :/

**Comment by wow-mania** [comment]
As-is for now.
