### ISSUE TITLE
[NPC] Horde inside Alliance Inn at Dalaran

### ISSUE THREAD

**Issue by Ahedonia** [WoWManiaUK/Redemption#5183]
**Links:**
https://imgur.com/a/9E21vPF
https://imgur.com/a/joqB9wi

**What is Happening:**
As it is observable in the screenshots provided, Horde players Perrylock and Prium seem to be able to get into Alliance Inn without being ported out.
This has been reported before for other horde players, tickets created to GM that ends up requesting to make github report, so here we are... AGAIN!
It wouldn't be a big issue, if, of course, they would not just be idiots about it and constant taunt. Anyway, it shouldn't be possible to happen, it's an exploit, it's intended bad behavior, etc etc.

**What Should happen:**
Horde should be ported out when entering an Alliance zone.

**Comment by Rushor** [comment]
so which issues result with that? do they attack players and npcs?

**Comment by svijetlo** [comment]
i see this happen , they also tend to tount npc so it is rather irritating if it is quest npc or some shop

**Comment by Rushor** [comment]
we can make them all unattackable

**Comment by svijetlo** [comment]
or just make that horde get ported out from any ally quarters in dala , it should be like so but it is small exploit that ppl get there not sure how thos

**Comment by Rushor** [comment]
How do they actually get there? Someone knows how to reproduce this exploit?

**Comment by jeyrella** [comment]
Just keep trying to walk in.  It seems that the expulsion spell check is only every few seconds and/or the range of it is not large enough, so if you keep trying eventually you can time it correctly that you don't get expelled.

I think it may be a spell cast by the NPC guarding the entrance [Silver Covenant Guardian Mage](https://wow-mania.com/armory/?npc=29254)

**Comment by jeyrella** [comment]
#3237
#1747

**Comment by jeyrella** [comment]
Note that it's also possible as Alliance to enter the Horde Inn using a fast flying mount - maybe the same spell call.

**Comment by Oganku** [comment]
Yeah, the tp is bound to the guards and they have a fairly small radius, if you jump at the right time, or run fast enough and latency is on your side, it's not very difficult to get inside.

Maybe just make the exclusion check for the entire area instead of only around the guards I guess?

Although players can't attack or interact with the opposite faction's NPCs, so it's fairly irrelevant. All they can do is brag that they got there... Lol

Imo it's not worth messing with, but meh.

**Comment by Rushor** [comment]
Are the opposite npcs attackable? If yes i will change that

**Comment by Rushor** [comment]
checkrange is increased slightly and all the creatures are no longer attackable

**Comment by jeyrella** [comment]
So, @Ahedonia it turns out with research it is/was actually Blizz-like for Horde to be able to enter the Alliance Inn.
What isn't though, is that the NPCs should not be tauntable, so we have fixed that.  
Also, as a compromise over the ongoing badwill it causes, the range check is increased so it is harder (but note, not entirely impossible) to get in as Horde.  (Sidenote:  similarly it is not impossible for Alliance to enter the Horde Inn! ;-)  )

**Comment by jeyrella** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/46089380/102020559-dfc8a700-3d71-11eb-8854-5786396f34e0.png)
