### ISSUE TITLE
[Raid] The Beasts of Northrend not have berserk

### ISSUE THREAD

**Issue by jonathan5er** [WoWManiaUK/Redemption#5201]
**Links:** no link

**What is Happening:** The first three boss in Trial of the Crusader does not have berserk... there is timer, but when reach it nothing happen... we are on last boss but many players die and we still kill him because no berserk

**What Should happen:** After timer for berserk boss should be berserked to deal much higher damage

**Comment by Oganku** [comment]
The enrage on this boss is weirdly super lenient, but does exist. The timer is 'per beast' and not for the entire encounter.
Note that on heroic the 2nd and 3rd beasts enter the fight after a set timer, causing a soft enrage due to the presence of multiple beasts potentially present at the same time.

![image](https://user-images.githubusercontent.com/34783736/102730605-39494c80-4303-11eb-9fa8-2e70088b9763.png)
https://wowwiki.fandom.com/wiki/Beasts_of_Northrend#:~:text=Beasts%20of%20Northrend%20is%20the,and%20Icehowl%20(a%20yeti).

**Comment by jeyrella** [comment]
@Oganku is there an issue here, or not?  Please label either way, and close if not...

**Comment by Rushor** [comment]
i the core there seems to be only 1 enrage for the 2 worms if i see it correct

**Comment by Oganku** [comment]
There is an enrage for when the first worm dies (correct), an enrage for when Icehowl stomps a player, and a 15 minute berserk timer per beast (which is absurdly long, but is still correct).
