### ISSUE TITLE
[Raid] Battle for Mount Hyjal - trash rep missing and loot drop chance

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#5271]
**Links:**
Ghoul: https://www.wow-mania.com/armory/?npc=17895
Claw of Molten Fury: https://www.wow-mania.com/armory/?item=32946
Fist of Molten Fury: https://www.wow-mania.com/armory/?item=32945

**What is Happening:**
1: The very first wave of mobs do not award any Reputation per kill. It is Ghoul-only wave. In further waves the Ghouls and all other mobs do award the rep properly.
2: two linked fist weapons drop from trash so mich that it is actually kinda spammy. The drop chance should be reduced.

**What Should happen:**
Most likely also the 1st wave of trash should award the rep. The fist weapons should not drop SO much

**Comment by Rushor** [comment]
The first wave does not reward rep because of beeing spammable (you know people could abuse rep farming it over and over again.) I would stay that as is :)

Loot is fixed and reduced now:

The loot problem was, that the items: 32946, 32945 were assigned as a pool of loot items assigned to the creature and then AGAIN assigned with a 1 % chance of each item to drop for them. I removed that duplicate stuff. The items 32946, 32945 should now only drop from creatures: 17895, 17897, 17898, 17899, 17905, 17906, 17907, 17916 with a chance of 1 percent to drop from this loot pool:

32589,32590,32591,32592,32609,32736,32739,32745,32746,32748,32751,32752,32755,32945,32946,34009,34010,

**Comment by svijetlo** [comment]
![WoWScrnShot_020521_105433](https://user-images.githubusercontent.com/61908373/107018360-a1170200-67a0-11eb-948a-ce5e8687e49c.jpg)
did not get a single wepon in this time i did it
