### ISSUE TITLE
[Spell] Death Knight- Raise Dead

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#5355]
**What is happening**: When ghoul spells are on cooldown and are unsummoned/killed, and when resummoned again, they spawn  with all of their ability cooldowns reset.

**What should happen**- The ability cooldowns shouldn't reset prematurely when you unsummon and resummon your ghoul again.

**reproduce steps**
1.  Get **2/2 Night of the Dead** and **1/1 Master of Ghouls** from the unholy tree
2. Summon your Ghoul and use **Gnaw** on your target.
3. Unsummon your ghoul ASAP and resummon it again.
4.  Notice how the ghoul spawns with **Gnaw** reset despite 1 minute not being over yet.

**Comment by jeyrella** [comment]
Sorry, we don't take other server's accuracy as a baseline, as there is zero guarantee that those servers are correct. 
If it's unique to this server as you say, what's the basis for comparing to other servers?

In any case, I am having trouble reproducing your steps, although to be fair I am not familiar with DK.  As far as I can see the ghoul has a 30 second cd on gnaw even when resummoned?

Without original documentation on the behaviour as it was in WotLK (and NOT from other servers that may have implemented differently and not necessarily accurately), I'm loathe to say this should be changed.

**Comment by festerhowl** [comment]
I am not asking you to take any other server's accuracy as baseline.  Just like how you do not reset your cooldowns magically when you revive, its similar for the pets. I do not have any problem with this issue, i mean if you think about it its actually nice to have a pet stun every 30 seconds even when the tooltip says that the cooldown is 1 minute. Although if suppose in the future some sort of baseline does arise i don't want to be held responsible for any exploits.

**Comment by Kilju** [comment]
Pets should retain their cooldowns when they die. the CD can visually bug out if you resummon a pet that has died/dismissed, resulting in "Spell is not ready yet" if you try to use them. If cooldowns are supposed to be reset when you resummon your pet, warlock would be quite powerful with being able to make 2x void sacrifices in row against melee gaining 16k shield.

Similary using felhunter spell lock ability and then dismissing it -> resummoning it instantly with fel domination would give you the ability to fully silence 6s without enemy casting or if interrupting a spell, locking them out for up to 12 seconds of casting.

Here a small video made today on classic how pet dying and resummoning affects CD on blizzard server. I can't find anything that would have changed since then.
https://www.youtube.com/watch?v=Wf26h8o0P8k

I see no reason why DK should have advantage over hunter and warlock pets.

**Comment by svijetlo** [comment]
after quite a bit of looking and lod of crap resolution vids i think i can confirms this 
even thos it is not 100% proof 
but pet should not reset cooldowns after you dismiss it or kill it to heal you self 
here is example ; if Dk use Gnaw pet skill (60 sec cd) , then use Death Pact skill to kill ghoul to heal him self , spell Raise Dead has 30 sec cooldown, ones you summ ghoul back it should have leftover time on skills use depending how much time was left on ghoul pet CD minus 30 sec for Raise dead cd
this only goes for Unholy dk speck in to permanent pet

**Comment by svijetlo** [comment]
perfect ...
