### ISSUE TITLE
Wintergrasp

### ISSUE THREAD

**Issue by festerhowl** [WoWManiaUK/Redemption#5369]
**Issues:**

1. Many Horde and Alliance NPCS are not spawning at their intended locations-
         
 - [Commander Dardosh](https://www.wowhead.com/npc=31091/commander-dardosh) and [Commander Zanneth](https://www.wowhead.com/npc=31036/commander-zanneth) always spawn inside the fortress regardless of who is currently controlling wintergrasp.
          
-  most of the other npcs that hand out quests in the zone do not spawn in the right place and can also respawn at the place where the npc was pulled and killed.
                     **_Horde_**-  [Hoodoo Master Fu'jin](https://www.wowhead.com/npc=31101/hoodoo-master-fujin), [Lieutenant Murp](https://www.wowhead.com/npc=31107/lieutenant-murp), [Primalist Mulfort](https://www.wowhead.com/npc=31053/primalist-mulfort), [Siegesmith Stronghoof](https://www.wowhead.com/npc=31106/siegesmith-stronghoof), [Tactical Officer Kilrath](https://www.wowhead.com/npc=31151/tactical-officer-kilrath), [Vieron Blazefeather](https://www.wowhead.com/npc=31102/vieron-blazefeather)
                             **_Alliance_**-  [Bowyer Randolph](https://www.wowhead.com/npc=31052/bowyer-randolph), [Anchorite Tessa](https://www.wowhead.com/npc=31054/anchorite-tessa). [Siege Master Stouthandle](https://www.wowhead.com/npc=31108/siege-master-stouthandle). [Senior Demolitionist Legoso](https://www.wowhead.com/npc=31109/senior-demolitionist-legoso). [Sorceress Kaylana](https://www.wowhead.com/npc=31051/sorceress-kaylana). [ Tactical Officer Ahbramis](https://www.wowhead.com/npc=31153/tactical-officer-ahbramis).
_Note: Some of these NPCs may be spawning correctly but i linked all just in case you find some new bugs_
             
- A soldier is stuck beneath the textures in eastpark workshop.            
                             
                       
2. Unlike the attacking faction, players defending the fort are getting a head start as they don't get teleported inside the fortress when they join the battle for wintergrasp. Players should also get unmounted as soon as they join
3. Everyone should have vision of all vehicles on the map, Currently players can only see friendly vehicles(Not sure if its a good idea to change this, as most of the times the attacking team wins because of the element of surprise)
4. The [Defender's Portal](https://wotlk-twinhead.twinstar.cz/?object=191575) at 44.1, 22.5 is not working.
5. https://wowwiki-archive.fandom.com/wiki/Wintergrasp
![Screenshot (178)](https://user-images.githubusercontent.com/43633844/111243193-a3357180-8626-11eb-9bfd-2745e67e9695.png)
not sure how this works but will be pretty nice to have considering the imbalance. 

6. The wintergrasp tower cannons do not reset fully when they respawn and get stuck facing the way they were destroyed originally. Sometimes players exploit this issue and face the cannon at a direction where it cannot hit anything. 

_pls check accuracy of issue 2 & 3 on retail as there is no source that explicitly mentions 100% how everything is supposed to work_

**Comment by Rushor** [comment]
**Issues:**

1. Many Horde and Alliance NPCS are not spawning at their intended locations-
         
 - [Commander Dardosh](https://www.wowhead.com/npc=31091/commander-dardosh) and [Commander Zanneth](https://www.wowhead.com/npc=31036/commander-zanneth) always spawn inside the fortress regardless of who is currently controlling wintergrasp.
          
-  most of the other npcs that hand out quests in the zone do not spawn in the right place and can also respawn at the place where the npc was pulled and killed.
                     **_Horde_**-  [Hoodoo Master Fu'jin](https://www.wowhead.com/npc=31101/hoodoo-master-fujin), [Lieutenant Murp](https://www.wowhead.com/npc=31107/lieutenant-murp), [Primalist Mulfort](https://www.wowhead.com/npc=31053/primalist-mulfort), [Siegesmith Stronghoof](https://www.wowhead.com/npc=31106/siegesmith-stronghoof), [Tactical Officer Kilrath](https://www.wowhead.com/npc=31151/tactical-officer-kilrath), [Vieron Blazefeather](https://www.wowhead.com/npc=31102/vieron-blazefeather)
                             **_Alliance_**-  [Bowyer Randolph](https://www.wowhead.com/npc=31052/bowyer-randolph), [Anchorite Tessa](https://www.wowhead.com/npc=31054/anchorite-tessa). [Siege Master Stouthandle](https://www.wowhead.com/npc=31108/siege-master-stouthandle). [Senior Demolitionist Legoso](https://www.wowhead.com/npc=31109/senior-demolitionist-legoso). [Sorceress Kaylana](https://www.wowhead.com/npc=31051/sorceress-kaylana). [ Tactical Officer Ahbramis](https://www.wowhead.com/npc=31153/tactical-officer-ahbramis).
_Note: Some of these NPCs may be spawning correctly but i linked all just in case you find some new bugs_
             
- A soldier is stuck beneath the textures in eastpark workshop.            
                             
                       
2. Unlike the attacking faction, players defending the fort are getting a head start as they don't get teleported inside the fortress when they join the battle for wintergrasp. Players should also get unmounted as soon as they join
3. 
4. The [Defender's Portal](https://wotlk-twinhead.twinstar.cz/?object=191575) at 44.1, 22.5 is not working.

6. The wintergrasp tower cannons do not reset fully when they respawn and get stuck facing the way they were destroyed originally. Sometimes players exploit this issue and face the cannon at a direction where it cannot hit anything. 


This will be fixed in this report today

**Comment by Rushor** [comment]
2. Unlike the attacking faction, players defending the fort are getting a head start as they don't get teleported inside the fortress when they join the battle for wintergrasp. Players should also get unmounted as soon as they join

> this should be fixed now. defending team get's ported inside the fortress

Other issues i will handle below tomorrow

**Comment by svijetlo** [comment]
will test all ones you do all of them =)

**Comment by Rushor** [comment]
> 4. The Defender's Portal at 44.1, 22.5 is not working.

Telport Effect should now work correctly for all teleport object cases

**Comment by Rushor** [comment]
> 2. Unlike the attacking faction, players defending the fort are getting a head start as they don't get teleported inside the fortress when they join the battle for wintergrasp. Players should also get unmounted as soon as they join

this should be fixed now. defending team get's ported inside the fortress

**Comment by Rushor** [comment]
> A soldier is stuck beneath the textures in eastpark workshop.

position changed to 4408.473145f, 2389.000244f, 376.319489f, 0.352033f

**Comment by Rushor** [comment]
> Commander Dardosh and Commander Zanneth always spawn inside the fortress regardless of who is currently controlling wintergrasp.

This issue was happening because they were always loading their path inside the fortress. Now they will only load the path when they are actually spawned in the forthress. Also added path for BATTLEFIELD_WG_NPC_ANCHORITE_TESSA BATTLEFIELD_WG_NPC_PRIMALIST_MULFORT

and BATTLEFIELD_WG_NPC_VIERON_BLAZEFEATHER BATTLEFIELD_WG_NPC_BOWYER_RANDOLPH

**Comment by Rushor** [comment]
Point 5 The wintergrasp tower cannons i gonna fix tomorrow. All else is as is for now

**Comment by Rushor** [comment]
Point 5 The wintergrasp tower cannons i gonna fix tomorrow. All else is as is for now
