### ISSUE TITLE
[Spell] Spotlight by Spectral Performer - Karazhan

### ISSUE THREAD

**Issue by womptista** [WoWManiaUK/Redemption#5447]
**Links:**
armory link: https://www.wow-mania.com/armory/?spell=25824
another link that describes the skill spotlight: https://wowpedia.fandom.com/wiki/Spectral_Performer

**What is Happening:**
Spectral Performer is casting the skill as he should be, but the skill is not acting as it should.

**What Should happen:**
Those who stand in the spotlight should get a 20% dmg increase

**Comment by hawker357** [comment]
The buff applied to players and NPCs seen to be different:
![Screenshot (34)](https://user-images.githubusercontent.com/79724094/115867085-84e74080-a432-11eb-9788-814d9f7b09ba.png)
![Screenshot (33)](https://user-images.githubusercontent.com/79724094/115867087-86186d80-a432-11eb-9fa1-f8387e973c47.png)

Is this intentional? From what info I can find it's always supposed to be a 20% increase. So the debuff 32214 is correct.

**Comment by Keader** [comment]
50% buff should be applied only to "spectral performer" friends xD
i will take a look later

**Comment by Keader** [comment]
test now.
