### ISSUE TITLE
[Battleground] Arathi Basin you won't be transported to a valid graveyard if faction changes while resurrecting

### ISSUE THREAD

**Issue by theonykry** [WoWManiaUK/Redemption#5454]
**Links:**

**What is Happening:**
So it happend to me few times already. first i thought its a 1 time thing but it obviously isnt. So what happend: I dead in Arathi Basin. i was then teleported to a graveyard. once the loading screen was done, i was teleported to a graveyard that my fraction did not own anymore. so basically i have to run as a ghost to the closest graveyard that is owned by may fraction. it so happend that the opposing fraction captures said graveyard. in the end i ended up running around as a ghost on a battleground, trying to get rezzed, for almost 5minutes.
2. the secound bug i figured: if i stay still and dont walk to a closest graveyard and wait for my team to recapture it. once it is recaptured, i still cannot see a friendly Ghost healer

**What Should happen:**
1. Not be teleported to a grayveyard that your fraction does not own. 2. If it happends to get captured at the time you get out of loading screen, it should automatically teleport you to a graveyard owned by your people.

**Comment by jeyrella** [comment]
This was raised in https://github.com/WoWManiaUK/Redemption/issues/5059 and could only be fixed for AV.  If keader cannot fix, then it is as-is.

**Comment by svijetlo** [comment]
i seen this happen a lot and it can be rly aggravating at times , but we let mr Kedar decide on this one

**Comment by Keader** [comment]
Hard part here is find a way to reproduce with 100% chance...

**Comment by Rushor** [comment]
When watching av i can Show you how to reproduce, there it is fixed. Maybe that will help?

**Comment by Keader** [comment]
i got a way to reproduce, trying debug it now.

**Comment by Keader** [comment]
Yeah folks, blizzlike bug.
What happens is:

Player click in re-pop -> start load screen while teleported -> when load ends, it send a packet (CMSG_AREA_SPIRIT_HEALER_QUEUE) to add in ress queue.
Problem here is:

Player dies -> repop -> other faction player finish cast in flag -> player is in load screen -> bg remove spirit (because base is taken) -> load screen finish -> has no spirit, so client dont send CMSG_AREA_SPIRIT_HEALER_QUEUE.

And since client dont send CMSG_AREA_SPIRIT_HEALER_QUEUE, we cant add player in queue, so we cant relocate to another cemitery.

**Comment by svijetlo** [comment]
thx for your time man =)
