### ISSUE TITLE
[NPC] Silverbrook residents don't turn hostile following quest 12308

### ISSUE THREAD

**Issue by Xangretor** [WoWManiaUK/Redemption#5458]
**Links:**
https://www.wowhead.com/quest=12308/escape-from-silverbrook
https://www.wowhead.com/item=46108/technique-rituals-of-the-new-moon

**What is Happening:**
After completing Escape from Silverbrook the residents remain friendly.

**What Should happen:**
After completing Escape from Silverbrook they should be come hostile.

**Comment by hawker357** [comment]
Confirmed, Silverbrook Trappers [NPC 26679](https://www.wowhead.com/npc=26679/silverbrook-trapper) and Silverbrook Villager [NPC 26708](https://www.wowhead.com/npc=26708/silverbrook-villager) and Silverbrook Defender [NPC 27676](https://www.wowhead.com/npc=27676/silverbrook-defender) all remain friendly after completing the Escape Quest.
![Screenshot (44)](https://user-images.githubusercontent.com/79724094/116992265-aadfd100-accd-11eb-8c4b-c874aa04c559.png)
![Screenshot (45)](https://user-images.githubusercontent.com/79724094/116992275-addac180-accd-11eb-8734-173550f4067c.png)
![Screenshot (46)](https://user-images.githubusercontent.com/79724094/116992285-b0d5b200-accd-11eb-9427-107bcab09d21.png)

**Comment by Rushor** [comment]
all those creatures are affected 26679, 26708, 27479, 27676, 29269, 29270, 29275, 29492

we cannot make them hostile after quest reward since the phasing system does not work here.

i will make the yellow attackable as a Compromise

(26679, 'Silverbrook Trapper');
(26708, 'Silverbrook Villager');
(27479, 'Slain Trapper');
(27676, 'Silverbrook Defender');
(29269, 'Aspen Grove Trapper');
(29270, 'Aspen Grove Trader');
(29275, 'Aspen Grove Supplier');
(29492, 'Ashwood Trapper');
