### ISSUE TITLE
[Raid] Ruby Sanctum 10 

### ISSUE THREAD

**Issue by hotdoggidy** [WoWManiaUK/Redemption#558]
First Halion attempts since the patch. Couple of new bugs on 10 man that werent there pre-patch. 
-Shadow portals do not despawn/reset with Halion after wipe. (can be entered at start of engage)
-Shadow Orbs may have a visual bug (positioning), multiple raid members dying by cutters when they arent near them.
-Agro on tank intermittently drops and Halion targets next highest threat. (omen)(shadow and physical realms)
![wowscrnshot_120116_114540](https://cloud.githubusercontent.com/assets/23442126/20810056/f4a870b8-b7bc-11e6-81bb-941683eca2de.jpg)
)

**Comment by hotdoggidy** [comment]
P.S. Tanks report General Zarithrian, one of the 3 minibosses before Halion, does no damage whatsoever regardless of his armor debuff.

**Comment by wow-mania** [comment]
Thank you for the info. Feel free to add spell, NPC ids from wowhead or openwow. It will help me a lot.

**Comment by Plege** [comment]
NPC id (as on rising gods website)
General Zarithrian                  39746   https://db.rising-gods.de/?npc=39746
Halion                                    39863   https://db.rising-gods.de/?npc=39863
Portal of the shadow realm     29218   https://db.rising-gods.de/?npc=29218

Spell id (as on db.rising-gods.de website)
Twilight Cutter (channeled)       74768 https://db.rising-gods.de/?spell=74768
Twilight Cutter (instant) 10nm  74769 https://db.rising-gods.de/?spell=74769
Twilight Cutter (instant) 10hc    77845 https://db.rising-gods.de/?spell=77845
Twilight Cutter (instant) 25nm   77844 https://db.rising-gods.de/?spell=77844
Twilight Cutter (instant) 25hc     77846 https://db.rising-gods.de/?spell=77846

Please double check the spell id's and the portal id, not sure if they are the right ones because they weren't listed as spells of Halion (on wowhead)

**Comment by wow-mania** [comment]
Thanks if you can add me to Skype. I will be trying to fix this today and it would be nice to get a group to test it in dev.

**Comment by wow-mania** [comment]
There is a new version on Dev now.

**Comment by Plege** [comment]
i would be available to try it now, sent you a skype request as well for the future

**Comment by fvicaria** [comment]
Dev is open to anyone to try let me know if your char is old and I can update it there.

**Comment by Plege** [comment]
yes it's pretty old, please update Pleger
