### ISSUE TITLE
[Quest] The Touch of Zanzil 

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#5600]
https://classic.wowhead.com/quest=2607/the-touch-of-zanzil

This is in the same quest chain as the other issue I just submitted issues/5599
After laying down in front of the Doc and getting the diagnosis he de-spawns after about 5 seconds.
I had to wait about 10-15 minutes  for him to respawn.

After his diagnosis he either shouldn't despawn, or at least he should respawn immediately after so you can turn in the quest and get the next one.

Here's some random youtube video of someone doing the quest.
https://www.youtube.com/watch?v=A1KqXZh-YU4
He also appears to be missing some minor animations, but that's not the end of the world.

**Comment by jeyrella** [comment]
This has been done by many many rogues, so I am not sure why this is a problem now...

**Comment by fvicaria** [comment]
works

**Comment by Rushor** [comment]
Indeed there are issues - the npc should only start the event once player did the /lay emote on him. Updates that so that the player actually need to handle that emote right on front of the Doctor. Then all will start as intended.

fixed: https://i.imgur.com/2aFW3du.png https://i.imgur.com/5fuzit1.png

**Comment by Rushor** [comment]
Also despawn for him at the end is no longer needed since that was wrong added anyway
