### ISSUE TITLE
[Quest] Spice Bread Stuffing - Slow-roasted Turkey and more ... - (Pilgrim's Bounty)

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#5640]
https://www.wow-mania.com/armory/?quest=14023
https://www.wow-mania.com/armory/?quest=14035
https://www.wowhead.com/quest=14023/spice-bread-stuffing

Across all 6 of the quests in this quest chain the initial text from the NPCs work, but there is no completion text.
<img width="467" alt="image" src="https://user-images.githubusercontent.com/6968045/143511589-20cd91c5-a478-4f69-8397-4723d653903f.png">
<img width="465" alt="image" src="https://user-images.githubusercontent.com/6968045/143511613-d82b25d7-28e8-40e8-baf4-5a2fd45a4b24.png">

When you turn in the quests you should get text before and after you click continue.

**Comment by stealer0517** [comment]
I believe all of the other daily pilgrims bounty quests are affected as well. 
Ex: Slow-roasted Turkey https://www.wow-mania.com/armory/?quest=14035

**Comment by Rushor** [comment]
all texts for all progress and complete addded (remember to delete cache before test)

**Comment by eronox** [comment]
> all texts for all progress and complete addded (remember to delete cache before test)

**Quest 1** (_14023_): Text is added & corrected.
**Quest 2** (_14024_): Text is added & corrected.
**Quest 3** (_14028_): Text is added & corrected.
**Quest 4** (_14030_): Text is added & corrected.
**Quest 5** (_14033_): Text is added & corrected.
**Quest 6** (_14035_): Text is added & corrected.

**Comment by Echinaceax** [comment]
https://wowpedia.fandom.com/wiki/Pilgrim%27s_Bounty


Seems this fix reverted somehow - good job i checked 

Horde and ally all missing quest delivery/complete text @Rushor 
Pheonix said was fine last year 


Alliance https://www.wowhead.com/wotlk/quest=14022/pilgrims-bounty
Alliance [Bountiful Table Hostess](https://wowpedia.fandom.com/wiki/Bountiful_Table_Hostess)
Horde https://www.wowhead.com/wotlk/quest=14036/pilgrims-bounty
Horde [Bountiful Feast Hostess](https://wowpedia.fandom.com/wiki/Bountiful_Feast_Hostess)

B [1-70] [Spice Bread Stuffing](https://wowpedia.fandom.com/wiki/Spice_Bread_Stuffing_(quest))
B [1-70] [Pumpkin Pie](https://wowpedia.fandom.com/wiki/Pumpkin_Pie_(quest))
B [1-70] [Cranberry Chutney](https://wowpedia.fandom.com/wiki/Cranberry_Chutney_(quest))
B [1-70] [Undersupplied in the Undercity](https://wowpedia.fandom.com/wiki/Undersupplied_in_the_Undercity)
B [1-70] [Candied Sweet Potatoes](https://wowpedia.fandom.com/wiki/Candied_Sweet_Potatoes)
B [1-70] [Slow-roasted Turkey](https://wowpedia.fandom.com/wiki/Slow-roasted_Turkey)

![prilgims bount - no text](https://github.com/WoWManiaUK/Redemption/assets/39439201/4950a981-34b6-4135-b851-1a40a1cbe58f)
![cant get enough turkey](https://github.com/WoWManiaUK/Redemption/assets/39439201/02518e3f-9b53-4457-99a7-1de34310c215)
![dont forget the stuffing](https://github.com/WoWManiaUK/Redemption/assets/39439201/7b72c386-4400-4905-b666-0afb3617af2f)
![easy as pie](https://github.com/WoWManiaUK/Redemption/assets/39439201/26266084-bab1-4149-a2ec-3aed98c1c273)
![sharing a bountiful feast](https://github.com/WoWManiaUK/Redemption/assets/39439201/81c89fdd-73b6-423b-afe9-d5afd8cf6d04)
![she says potato](https://github.com/WoWManiaUK/Redemption/assets/39439201/e6f5bd50-6b1c-4ea7-915b-5d54abed93ee)
![we are out of cranberry chuney again](https://github.com/WoWManiaUK/Redemption/assets/39439201/6191eacc-1243-4475-9c2c-d585e4863e7a)

**Comment by Lumber-Jack-2** [comment]
i think last year not both sides got fixed, but yeah now all should be good again (after cache clear)

**Comment by Echinaceax** [comment]
Horde fixed in PTR

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/904434ed-c6b4-446c-96ab-fd006bb9fbf1)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/98dad1c7-cfe6-4124-adba-7582f520c980)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/9f34558c-287b-4730-9a2b-4dca84e1c254)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/1c724116-978a-4e0a-b24e-e418eda619a1)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/3f12cc47-319c-42d7-afee-704ed4b3025d)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/3e16bd51-315b-4a57-b245-4550bd459fc9)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/1a8fd22b-8eb7-4aa9-b976-505a7c027c87)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/e2d02f57-18cf-4a0d-99d9-f30c807836bb)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/0526e159-5795-4f2e-a3c9-80d496a416ca)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/bc24e0d3-f845-495a-b20a-0c0093b30b0e)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/04a64707-9502-42f5-9a0e-7c52fe8ac055)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/0040ea75-ae6f-45b6-a0db-c37e06850dd1)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/eda0e5b3-d9f2-4b2b-991e-d66ebc300a92)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/57411212-5f89-47e8-a767-7ef545f9811c)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/50d2dafc-a57b-45b5-8ac9-868e82693694)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/1786150e-4513-4e7f-83f3-9db1dff9cf3e)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/1e11e731-33ef-457f-bd45-0d3f0742cdd4)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/c24df16f-1315-4356-80a4-74784eb48984)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/79fb6982-6989-4505-9a0d-27b221532445)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/5821ac94-dcc3-4fd5-8793-7424f37fc300)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/3faba1c9-9fdc-4999-b851-899ae531b36c)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/0fbabaaa-4096-41fe-b0dc-88e04ebb1119)

**Comment by Echinaceax** [comment]
Ally fixed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/39066b5e-952d-4245-979e-90fa91a7583a)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/dd7ddaa3-38d1-4a69-b9e2-202e51ad0a4c)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/582261f9-a38f-4284-8290-e8ab53feeabd)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/a5bb5968-2e9c-40d7-900d-e5fb7bc8b1c6)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/c5c69bbb-e477-4f26-bb9a-aedd0a72540f)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/d1b09080-5257-4cea-81c6-5132d6397e68)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/a4884a50-6a5c-4118-b41c-0a86e7acc769)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/3da2ec92-11ab-4217-adc5-c7aea2bf3f45)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/df8cbc75-7768-4501-bc88-21f650e9c3d2)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/92a1bb6b-3b11-46bf-a955-368451f3cf51)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/50223a17-3bda-4070-a5b5-db6b23ee671f)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/fc6e637d-52a7-490b-b246-d027676d1f0e)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/d2c99a1d-9cba-49b1-86f8-52ab303cf690)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/8b03623f-6443-4e56-ad6b-b1ccea8f1a98)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/41efde8c-d98d-493c-90db-cef8d0afc4f3)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/62e48df4-e68e-4345-99a0-78ad551b258b)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/c9b97751-67a3-41b2-af1c-1937d1454289)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/c9baab49-89d4-47fe-a0b7-e89a60956d9d)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/5ff46ee0-71d2-49ec-925e-2be6ae1b71b6)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/28f2bd36-221a-4224-bf7c-1ba6268783be)
