### ISSUE TITLE
[Quest] Basic Chemistry

### ISSUE THREAD

**Issue by amikot** [WoWManiaUK/Redemption#5643]
**Links:**
https://www.wowhead.com/quest=13279/basic-chemistry
https://www.youtube.com/watch?v=HvO7ZRdkyhA
https://www.wowhead.com/item=44010/pustulant-spinal-fluid

**What is Happening:**
First use of quest item is spawning first wave of mobs, but next time I use the item it's not causing any effect (apart of animation of pouring the fluid into the cauldron). I did try many times and only what I got after long time was the same wave of mobs spawned again. No next waves. 
Also quest item cooldown is too long . It's 90 seconds instead of 30s that should be.
Maybe that is the reason of the problems - maybe item is being use too late and that's why no next weaves 

**What Should happen:**
Each use of quest item should spawn next wave of mobs from the cauldron until finally it will be marked as done.

**Comment by Rushor** [comment]
it's timer based, will adjust the cooldown to wotlk value. you are right there

**Comment by wow-mania** [comment]
This works. It is not just a timer. It's chance based. So it will fail most times as expected.
Make sure this is the case before "fixing it".

**Comment by jeyrella** [comment]
@Rushor janitor is correct here.  It is meant to fail very often if you are not in a party.  Be careful and run any changes through me/svijetlo beforehand pls, thanks :)

**Comment by amikot** [comment]
If cooldown time has changed, it had to happen more than 6 years ago - on linked video it's clearly 30 seconds and video was done in 2015. As I remember before 2015 there was no significant changes to previous content (apart of Cataclysm related in Azeroth). This could happen rather in more recent years.
I believe, the quest is marked as group because spawned mobs are too strong for fresh 80 specially clother.   

And after all if there was indeed change from 90 seconds to 30 seconds - why ?   Maybe because people did complain they can't complete the quest ?

**Comment by jeyrella** [comment]
WotLK was 2010, not 2015.  There were widespread (both document and undocumented) nerfs in Cata (and later) content across the entire continent, simply to help solo players complete content as they would be leveling through it, not as part of current content.  
You actually made your own point.  Group quests in particular were radically changed, simply because unlike in WotLK where there would be many many players available, there would be next to none in the area, as it was not current content.

And no, the spawned mobs are perfectly soloable.  I myself have done it at least 6 times solo for Loremaster.  The quest is group  precisely because it needs good timing from several players. or to get very lucky.

So there are two choices.  Find other players to help you with the quest, or find a video from 2010 or earlier where it proves this was a lower cooldown in 2010, and we will happily review this.

**Comment by Rushor** [comment]
https://wowpedia.fandom.com/wiki/Basic_Chemistry?type=revision&diff=2512379&oldid=1618420

Here the proof that the 90 seconds CD are correct, just found it in the history

The Fluid has a cooldown of 90 seconds. The cauldron will need a Fluid sooner than this, which is why at least two players are required. The cauldron will accept more than one Fluids at the same time, but only one will register. Any extra Fluid is wasted. Any hits on you will interrupt the channeling of the Fluid, so make sure that the player whose next turn it is free of aggro.
