### ISSUE TITLE
[Spell/Item] Harvest Soul inside Frostmourne room on Heroic Difficulty in ICC proccing Spell Power trinkets

### ISSUE THREAD

**Issue by Kinkywiener** [WoWManiaUK/Redemption#5662]
**Links:**

Harvest Soul; Spell ID 73655
https://www.wow-mania.com/armory/?spell=73655

Charred Twilight Scale normal; Item ID 54572
https://www.wow-mania.com/armory/?item=54572

Charred Twilight Scale heroic; Item ID 54588
https://www.wow-mania.com/armory/?item=54588

Phylactery of the Nameless Lich normal; Item ID 50360
https://www.wow-mania.com/armory/?item=50360

Phylactery of the Nameless Lich heroic; Item ID 50365
https://www.wow-mania.com/armory/?item=50365

Muradins Spyglass normal; Item ID 50340
https://www.wow-mania.com/armory/?item=50340

Muradins Spyglass heroic; Item ID 50345
https://www.wow-mania.com/armory/?item=50345

**What is Happening:**
Inside the frostmourne room, Harvest Soul debuff procs the trinkets.

**What Should happen:**
The debuff shouldnt proc the trinkets. Internal cooldown is then on during the fight and active trinket buff is active inside the room, which has an impact on the fight. I suggest testing Dislodged Foreign Object and other proccable trinkets as well.

**Comment by Oganku** [comment]
Had time to test both versions of phylactery, muradin's and cts before PTR went down and I can confirm simply having the debuff from aura 76355 is proccing those trinkets by itself. It does not happen for non-magic trinkets such as sharpened twilight scale (haven't tested more though).
I suppose the debuff counts as you dealing damage to yourself instead of taking damage from the environment. 
If PTR comes back up I can test dfo and othere, but I believe it relates to the general proc behavior with harvest soul rather than individual items themselves.

**Comment by Lantanio** [comment]
Warlock's Hellfire spell also deals damage to the caster and can proc spellpower trinkets just off this. Not sure if this is intended or an instance of the same bug.

**Comment by jeyrella** [comment]
> Warlock's Hellfire spell also deals damage to the caster and can proc spellpower trinkets just off this. Not sure if this is intended or an instance of the same bug.

Yes, this is intended; it was changed in cataclysm.

**Comment by Keader** [comment]
fixed

**Comment by Oganku** [comment]
Doesn't proc any of the trinkets mentioned, nor others tested.
