### ISSUE TITLE
[Item]  WoW-Mania's Mall Teleport Stone does not show CD on item

### ISSUE THREAD

**Issue by jeyrella** [WoWManiaUK/Redemption#5705]
**Links:**
https://www.wow-mania.com/armory/?item=90044

**What is Happening:**
There is no on-item visual CD timer for the Mall Teleport Stone, as the db is missing support.
See icon, and tooltip.
![image](https://user-images.githubusercontent.com/46089380/154492766-1b2fe3ed-095d-4aa5-8040-b9737dba85f2.png)
Was fixed on Reign under BWL Github#3320, Franca has fix so can be transported

**What Should happen:**
Visual CD timer should be shown on Mall Teleport Stone

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

https://gyazo.com/8e01a0c4e7dc2395edc7aa9f02f83b69

with addons checked 

![image](https://user-images.githubusercontent.com/39439201/154763041-a0a53c79-91bb-4187-9ff0-1285e734ec87.png)

![image](https://user-images.githubusercontent.com/39439201/154763123-9cf18100-2a2c-4f50-858b-46b1ff3cbd7c.png)

**Comment by jeyrella** [comment]
Additionally, fixed an exploit of Mallstones being usable in BGs to instant exit
