### ISSUE TITLE
[Spell] Avenger's Shield - doesnt bounce to other targets

### ISSUE THREAD

**Issue by piro8888** [WoWManiaUK/Redemption#5708]
**Links:**

**What is Happening:**
on glyph says it hits 2 fewer targets for 100% more dmg but actualy avengers shild always hits only 1 target never jump on another target in pvp and also in pve .

**What Should happen:**

**Comment by Echinaceax** [comment]
https://www.wow-mania.com/armory/?spell=55116

**Comment by Echinaceax** [comment]
@piro8888 
Im not quiet sure what the issue is sorry

Avenger's Shield without glyph hits 3 targets ✔️ 
if all 3 targets at the time are within range set for that spell

![image](https://user-images.githubusercontent.com/39439201/154842720-d39c2747-df99-46f8-beec-16b101bdcb11.png)

Avenger's Shield with glyph, stops the bouncing to other targets by 2 meaning one target but with increased damage
