### ISSUE TITLE
[NPC] Jadefire Trickster - Cause Insanity Resets HP 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5749]
**Links:**
Cause Insanity Spell https://www.wow-mania.com/armory/?spell=12888
Cause Insanity Spell https://www.wow-mania.com/armory/?spell=26079
Npc https://www.wow-mania.com/armory/?npc=7107

### video evidence from live - reported by Franca, video evidence by me 
https://i.gyazo.com/cfc01343484ff10879619575686c4813.mp4

**What is Happening:**
When player gets MC'd by "Cause Insanity" NPC HP resets 

**What Should happen:**

![image](https://user-images.githubusercontent.com/39439201/157685168-eb9bd95b-d20a-44c9-ac18-305ca617c479.png)

**Comment by Rushor** [comment]
I guess because he resets the aggro, will change the mechanic of that for better handling

**Comment by Rushor** [comment]
okay please retest this with 2 players.

we need 2 players on the aggro table, if he casts it then, it will not go reset, but instead attack the second player.

If you solo do it with a pet it resets because the main target is a player

**Comment by Echinaceax** [comment]
Retested

tested with 2 chars, a hunter (no pet ) and a mage, couldnt get them to cast **Cause Insanity Spell** 
then i logged my hunter with pet and bam https://gyazo.com/502a9c938fcbb48272796e47a76d7036 this seems to be the issue hunter and pets

**Comment by mfranca0009** [comment]
### Issues Corrected
- [x] `Cause Insanity` should be cast regardless if there are other players around (e.g., if the player soloing, he will still be afflicted by the MC and the NPC will reset while the player will reset as well). It is claimed to be blizzlike and many people comment on that part specifically because it's "annoying".
- [x] Player pet (hunter, warlock, etc.) should not be MC'd or "charmed" indirectly when the player is. The pet should continue attacking `Jadefire Trickster` and the player who is MC'd should start attacking his own pet (if no other available target is around).

All set 👍

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR https://i.gyazo.com/a22a05604b747cbcc3438cb944fb2dda.mp4
