### ISSUE TITLE
[NPC] Doom Lord Kazzak's Mark of Kazzak is targeting none mana based players - Hellfire

### ISSUE THREAD

**Issue by Slianchroi** [WoWManiaUK/Redemption#5752]
**Links:**
https://tbc.wowhead.com/spell=32960/mark-of-kazzak
https://tbc.wowhead.com/npc=18728/doom-lord-kazzak

**What is Happening:**
Mark of Kazzak from NPC Doom Lord Kazzak, at the Throne of Kil'Jaeden is targeting no mana based players causing instant explosions

**What Should happen:**
Said Mark of Kazzak should only target mana based users and drain their mana. If Mana hits 0% then AoE explosion should happen.

**Comment by Echinaceax** [comment]
Confirmed 
https://i.gyazo.com/5d4bdf7c7907612b12411d0b0fc6f8b9.mp4

**Comment by mfranca0009** [comment]
`Mark of Kazzak` is fixed, however, other problems are present and are also being fixed; will provide a list once completed.

**Comment by mfranca0009** [comment]
### Issues Corrected
- [x] `Mark of Kazzak` corrected to ONLY select mana player targets.
- [x] `Mark of Kazzak` properly reducing 5% of the target's total mana each periodic tick
- [x] `Mark of Kazzak` properly triggering AoE knockback now; it was intermittently or never triggering on mana-only players. It is now separated as its own effect instead of being tied into the mana leech effect.
- [x] `Void Bolt` will now properly cast on the current victim (highest aggro/threat); the wrong spell was trying to be cast but did nothing.
- [x] `Twisted Reflection` is now properly set up to cast only on a player that does not have the highest aggro/threat (e.g., it will not be cast on the tank and is correctly skipped).
- [x] `Doom Lord Kazzak` now has a reduction of health and white melee damage by 30%. This is a confirmed change in patch 3.0.2.

### Confirmed evidence of health/damage reduction
![image](https://user-images.githubusercontent.com/26092980/159402915-9538b2d6-7d3d-45a8-b49f-2e0b76ccb3b9.png)
link: https://wowpedia.fandom.com/wiki/Doom_Lord_Kazzak
