### ISSUE TITLE
[Spell/DK] Scourge Strike shadow damage

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Redemption#5781]
**Links:**

https://github.com/WoWManiaUK/Redemption/issues/5778#issuecomment-1086845775

**What is Happening:**

Formula is incorrect

**What Should happen:**

Formula must be fixed

**Comment by festerhowl** [comment]
https://github.com/WoWManiaUK/Redemption/issues/5778#issuecomment-1086845775
> Damage of shadow part is fixed already (calculation)


@Keader After some more testing i found that Ebon Plaguebringer and Two-Handed Weapon Specialization are being calculated as an additive instead of multiplicative.

For example It is behaving currently as:
Physical portion x 0.36(Three diseases) x  [1.0 + 0.04 (Two-Handed Weapon Specialization) + 0.13 (Ebon Plaguebringer) + 0.15 (Blood presence) + 0.05 (Desolation) + 0.02 (Bone Shield) + 0.10 (Black Ice)]

whereas it should behave as:
Physical portion x 0.36(Three diseases) x 1.04 (Two-Handed Weapon Specialization) x 1.13 (Ebon Plaguebringer) x [1.0 + 0.15 (Blood presence) + 0.05 (Desolation) + 0.02 (Bone Shield) + 0.10 (Black Ice)]

Can you please check if the following modifiers are also affecting spells as additive instead of multiplicative, because ebon plaguebringer & two-handed Weapon specialization(DK) are similar to them:

Counterparts of Ebon Plaguebringer:
https://www.wow-mania.com/armory/?spell=48511 - Earth & Moon
https://www.wow-mania.com/armory/?spell=47865 - Curse of the Elements

Counterparts of Two-Handed Weapon Specialization:
https://www.wow-mania.com/armory/?spell=12711 - Warrior
https://www.wow-mania.com/armory/?spell=20112 - Paladin

If they affect spells as additive then there are no changes needed. If they are multiplicative then that would explain why the shadow part is not doing ~55.6% of the physical portion.
