### ISSUE TITLE
[NPC] Sorlof - Visability issue 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5834]
**Links:**
https://www.wowhead.com/npc=24914/sorlof
https://www.wow-mania.com/armory/?npc=24914

quest https://www.wow-mania.com/armory/?quest=11529

**What is Happening:**
Sorlof has serious visability issues, which makes it difficult for some players to target him and know where he is, resulting in body despawn before player has time to loot (reported to me by a GM that confirmed this)

**What Should happen:**

- [x] Set the proper visibility distance for `Sorlof` so he is seen from the ship (Original Issue)
- [x] `Sorlof` now does not regen health on evading, he was resetting his health every time he moved on his waypoint path.
- [x] Implemented the appropriate spells when firing the cannon, before this, there wasn't a cast time...
- [x] Properly implemented the boss emote that will display `Sorlof's booty falls to the floor` when `Sorlof` dies.
- [x] Respawn time of `Sorlof` has been shortened, via a comment from patch 3.0.3, it stated `Sorlof` should have a quick respawn time; previously it was set to 5 minutes.

### Extra issues found

**Cannon** 
https://www.wowhead.com/spell=45013/big-gun-assault
Which will trigger Cannon Assault after the cast time

Cannon Assault - https://www.wowhead.com/spell=45008/cannon-assault

reference timestamp 0:16 https://www.youtube.com/watch?v=gSbTj6YZAP0

respawn time incorrect (currently 5 mins)
should be lower according to wowhead comments

![image](https://user-images.githubusercontent.com/39439201/169869691-a952ce38-edc5-4936-8a25-dfd58bde8619.png)

reported by player, confirmed by GM

**Comment by mfranca0009** [comment]
All set, with some additional corrections as Echi mentioned because the quest interaction was not proper:
- [x] Set the proper visibility distance for `Sorlof` so he is seen from the ship (Original Issue)
- [x] `Sorlof` now does not regen health on evading, he was resetting his health every time he moved on his waypoint path.
- [x] Implemented the appropriate spells when firing the cannon, before this, there wasn't a cast time...
- [x] Properly implemented the boss emote that will display `Sorlof's booty falls to the floor` when `Sorlof` dies.
- [x] Respawn time of `Sorlof` has been shortened, via a comment from patch 3.0.3, it stated `Sorlof` should have a quick respawn time; previously it was set to 5 minutes.

Will not fix the cannon issue firing a cannonball without facing `Sorlof` at this time, the cannon is not appropriately tracking transport orientation in real-time and seems to update at a slow rate, therefore giving incorrect orientation values and cannot be used to check the cannon orientation compared to `Sorlof` properly.

Cursed sea dog NPCs will be corrected in a different issue as low priority.

**Comment by Echinaceax** [comment]
confirmed all above has been fixed in PTR 

https://i.gyazo.com/e808bce4bcf3899ed851c5b55d1ffbd1.mp4

![sorlof text](https://user-images.githubusercontent.com/39439201/169899439-a7ec178e-510a-4c14-8971-4468ac98d957.jpg)
