### ISSUE TITLE
[NPC] Cursed Sea Dog - Not using Correct actions 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Redemption#5835]
**Links:**

Cursed Sea Dog https://www.wowhead.com/npc=24911/cursed-sea-dog
For reference https://www.youtube.com/watch?v=gSbTj6YZAP0 for visual 

**What is Happening:**

`Cursed Sea Dog` NPCs are missing functionality.

**What Should happen:**

- [x] Correct a core issue when adding a new NPC onto a transport ship. Before the correction, it would add a new NPC onto the transport ship but would overwrite an existing spawned creature, giving it an incorrect display ID, and stealing its global unique identifier (GUID). 
- [x] Majority of the `Cursed Sea Dog` NPCs will now shoot when they are in the appropriate range of `Sorlof`; less than or equal to 150 yards. The majority, as in the ones that are not performing `STATE_USESTANDING` emote state or has no waypoint pathing.
- [x] Two `Cursed Sea Dog` NPCs were added since they were missing next to crates on the transport ship.
- [x] Four `Cursed Sea Dog` NPCs have been given the appropriate emote state (STATE_USESTANDING) via the reference video.
- [x] One `Cursed Sea Dog` NPC was re-positioned and given waypoint pathing on the transport ship to replicate the path on the reference video.
- [x] `The Big Gun` located on the transport ship was re-positioned because it was clipping through the ship and a `Cursed Sea Dog` NPC.
- [x] Re-positioned three `Cursed Sea Dog` NPCs that were standing on the edge of the transport ship for better spacing and in exact positions via the reference video.
- [x] Updated `Sorlof` NPC's waypoint pathing, because he was never walking around `Sorlof's Strand` completely as he should. This was incorrect since the `Cursed Sea Dog` NPCs should have been able to start firing on him as soon as the transport ship gets to the first point closest to the island, `Sorlof's Strand`.

**Comment by mfranca0009** [comment]
### List of issues fixed
- [x] Correct a core issue when adding a new NPC onto a transport ship. Before the correction, it would add a new NPC onto the transport ship but would overwrite an existing spawned creature, giving it an incorrect display ID, and stealing its global unique identifier (GUID). 
- [x] Majority of the `Cursed Sea Dog` NPCs will now shoot when they are in the appropriate range of `Sorlof`; less than or equal to 150 yards. The majority, as in the ones that are not performing `STATE_USESTANDING` emote state or has no waypoint pathing.
- [x] Two `Cursed Sea Dog` NPCs were added since they were missing next to crates on the transport ship.
- [x] Four `Cursed Sea Dog` NPCs have been given the appropriate emote state (STATE_USESTANDING) via the reference video.
- [x] One `Cursed Sea Dog` NPC was re-positioned and given waypoint pathing on the transport ship to replicate the path on the reference video.
- [x] `The Big Gun` located on the transport ship was re-positioned because it was clipping through the ship and a `Cursed Sea Dog` NPC.
- [x] Re-positioned three `Cursed Sea Dog` NPCs that were standing on the edge of the transport ship for better spacing and in exact positions via the reference video.
- [x] Updated `Sorlof` NPC's waypoint pathing, because he was never walking around `Sorlof's Strand` completely as he should. This was incorrect since the `Cursed Sea Dog` NPCs should have been able to start firing on him as soon as the transport ship gets to the first point closest to the island, `Sorlof's Strand`.

### Issues that are still present, and need more thorough analysis related to core **[NOT FIXING AT THIS TIME]**
- NPCs on transports have delayed position updates, therefore distance calculations are not accurate.
- `Cursed Sea Dog` NPC orientations become skewed and incorrect after shooting their rifles, which might be related to being on the transport ship and their positions not updating appropriately because they are delayed.

**Comment by Echinaceax** [comment]
Confirmed fixed the best we can for now in PTR
with the restriction Franca has mentioned above

Visability fix https://i.gyazo.com/d27221bde926672fa164c0ed96592d04.mp4
Sea dogs shot and help with damage https://i.gyazo.com/0c4f62452edc2ee2a85d4d40ed40b47f.mp4

Text added to let players know when to get the booty loot drop for quest complete

![image](https://user-images.githubusercontent.com/39439201/171182370-021cb056-45b9-4d8b-8d36-fc7e365b634a.png)
