### ISSUE TITLE
[Quest] item=51316/unsealed-chest > quest=24916/jainas-locket (cannot turn in the quest).

### ISSUE THREAD

**Issue by Wowtks** [WoWManiaUK/Redemption#5842]
**Links:**
https://www.wowhead.com/quest=24916/jainas-locket
https://www.wowhead.com/item=51318/jainas-locket
https://www.wowhead.com/item=52251/jainas-locket

**What is Happening:**
Jaina Proudmore does not spawn after ICC25NM LK kill and thus, new Shadowmourne users cannot turn in the quest to get the Jaina's locket item. I killed LK with Shadowmourne and looted a sealed chest which then gives me the items to exchange for the various vanity items. I have all the quest items and exchanged all of them except for Jaina's locket because Jaina did not spawn. Thus, the quest item Jaina's locket is still sitting in my inventory.

**What Should happen:**
Jaina Proudmore should spawn after ICC25NM or ICC25HC LK kill. Players should be able to talk to Jaina to exchange the quest item Jaina's locket for the teleport item Jaina's locket.

**Comment by svijetlo** [comment]
is this something new or what as i did this quest on 4 different toons

**Comment by Wowtks** [comment]
I don't know if it's new. It happened to me yesterday and 2 other friends had this exact same thing happen to them too. I didn't ask for timeline and I'm not sure how to prove this other than the fact that I got other items, just not Jaina's locket.

I have tried what I think makes sense:
1. go out and go back into the same lockout
2. entering with a different lockout
3. Wait for another day and enter the original lockout

**Comment by Franciss983** [comment]
I have tried this now because I did not turn the quest before. And I may have a same problem now.

So I had the quest to kill the Lich King: [The Lich King's Last Stand](https://www.wowhead.com/quest=24748).
When we killed the Lich King on 25 man Normal i also got the quest item [Sealed Chest](https://www.wowhead.com/item=51315).

Then I was able to turn these two quests at https://www.wowhead.com/npc=37120/highlord-darion-mograine:
https://www.wowhead.com/quest=24748/the-lich-kings-last-stand#comments
https://www.wowhead.com/quest=24914/personal-property

Once you hand in quest "Personal property" you get the box https://www.wowhead.com/item=51316/unsealed-chest#comments and when is opened youll receive items for following quests, there will (should) be 5 NPCs to turn in the quests to but only in ID of instance where did you kill Lich King.

I havent kill Lich King on Heroic version in my lock-out (ID) this week so NPCs didnt spawn here thats **correct.**
But I did kill Lich King on Normal version of 25 and these NPCs for following quests didnt spawn either. _They should spawn in either 25 man version._

**Comment by Franciss983** [comment]
**Seems like NPCs are not spawning on _normal version of 25 man instance._**
I havent got problem with my Shadowmourne quest before, because I did it on **heroic** version after Lich King was killed.

Quest givers for these NPCs are not spawning after Lich King kill on ICC25 Normal version.
quest: https://www.wowhead.com/quest=24917/muradins-lament
npc:  https://www.wowhead.com/npc=38607/muradin-bronzebeard

quest: https://www.wowhead.com/quest=24916/jainas-locket
npc: https://www.wowhead.com/npc=38606/lady-jaina-proudmoore

quest: https://www.wowhead.com/quest=24919/the-lightbringers-redemption
npc: https://www.wowhead.com/npc=38608/uther-the-lightbringer

quest: https://www.wowhead.com/quest=24918/sylvanas-vengeance
npc: https://www.wowhead.com/npc=38609/lady-sylvanas-windrunner

This one working because this NPC remaining in instance for whole time, is not temporary.
https://www.wowhead.com/quest=24915/mograines-reunion

**Comment by Franciss983** [comment]
Tested on PTR in Heroic and Normal version of ICC 25.

Turning https://www.wowhead.com/quest=24914/personal-property after LK gets killed.
Before openin unsealed chest there is only Highlord Darion Mograine.

Opening reward https://www.wowhead.com/item=51316/unsealed-chest.
And the rest of NPCs did spawn instantly.

**Comment by Franciss983** [comment]
_edit.: only one person per lock out is able to finish these quests, so Wowtks did turn quests before me and the NPCs are now gone. There is a chance that someone did finish https://www.wowhead.com/quest=24916/jainas-locket before Wowtks in that lock out. Getting info of raid members that were in this raid._

**Comment by Wowtks** [comment]
Jaina Proudmoore has appeared now after another week of LK 25HC kill. Only Jaina appeared and the other NPCs for the quest didn't appear. This makes sense because I have turned in the quest items for the other NPCs but not Jaina. It's still unclear whether this is an issue with NM or HC mode but the issue for me has been resolved.
