### ISSUE TITLE
[Raid] Blackwing Lair Portal and Orb issues (2 different issues)

### ISSUE THREAD

**Issue by JormagMania** [WoWManiaUK/Redemption#5951]
**Links:** Orb of Command to enter Blackwing Lair (BWL) once attuned https://www.wow-mania.com/armory/?object=179879

**What is Happening:** First issue - When exiting BWL using the portal, the game puts you inside Upper Black Rock Spire (UBRS) instance.

Issue recorded today:

https://youtu.be/xmpf-OHq_tc

Second issue- When in ghost form, you can't use the Orb of Command to enter BWL:

![Screenshot (3532)](https://user-images.githubusercontent.com/120397554/207406866-9c895fb0-aa2f-4e77-8515-052fe3d7a7a0.png)

**What Should happen:** First issue - The game should put you inside Black Rock Mountain (BRM), outside the UBRS entrance portal

Proof from 2009 at 9:13 minutes:

https://www.youtube.com/watch?v=cUn1cylQbcA

Second issue - You should be able to use the Orb of Command to enter BWL in ghost form.

Proof source:

![image](https://user-images.githubusercontent.com/120397554/207407120-66f6b8c5-8c92-43cf-a7f3-f0f073ed00ba.png)

Thank you.

Jormag.

**Comment by Rushor** [comment]
First issue fixed in PTR

**Comment by Rushor** [comment]
Second issue resolved by adding a resurrect for those who are in dead form and have the quest id: 7761 already rewarded and stand near the orb in 10 yards range. Player get resurrected while teleprting to the raid anyway so this is the best option we can add here

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR 

1, made raid group (this video if the orb works to right place)
https://i.gyazo.com/b762f94d470324f20ade0d6331e44352.mp4

2, Exited via the portal (think its correct now) ?
https://i.gyazo.com/5ca8499fc7d24b3236c7c5ac3f706a44.mp4
2a, went back in 
https://i.gyazo.com/0bf1f4ef15137c7e86cdf5c874b1b3e3.mp4

3, Death res working at the orb now
https://i.gyazo.com/711a8ac57b964963c5f5538b0702b474.mp4

**Comment by Rushor** [comment]
Thanks for the Tests!
