### ISSUE TITLE
[Reputation / Quests] Ebon Blade / Shadow Vault

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#5977]
For reference: https://www.wowhead.com/quest=12898/the-shadow-vault#comments

Questline from the Shadow Vault

![image](https://user-images.githubusercontent.com/31921098/219329747-25cbecd3-a4ac-4a80-b63e-bc590216c53c.png)

The issue:
The quests at Shadow Vault, once entering the new phase, only should be available, correctly, once turning **The Shadow Vault** ([Alliance](https://www.wow-mania.com/armory/?quest=12898) / [Horde](https://www.wow-mania.com/armory/?quest=12899))

![image](https://user-images.githubusercontent.com/31921098/219331311-a791636e-d394-4c9b-a723-1955d79dfabe.png)
As we can see from the quest log, the quest **Shadow Vault** is complete, and not turned in, and several quests are showing up on the mini map.

_NPC offering quests, while I have the **Shadow Vault** on the questlog_ 

![image](https://user-images.githubusercontent.com/31921098/219337871-56ea0280-347d-48ed-bccc-88aff60b9be1.png)

![image](https://user-images.githubusercontent.com/31921098/219337703-cefe8743-ca47-4450-a36f-55ee383886ef.png)

![image](https://user-images.githubusercontent.com/31921098/219333973-c187da24-1ecc-4c91-a534-d1d6340f9258.png)

![image](https://user-images.githubusercontent.com/31921098/219334054-9ce3f5e6-75c6-4bf0-bc04-c9e6ebb7e26e.png)

We can see that several quests are given without meeting their requirements.

1st issue

[The Blackwatch](https://www.wow-mania.com/armory/?quest=13106) should be offered at the same time as **If He Cannot Be Turned** ([Alliance](https://www.wow-mania.com/armory/?quest=12896#conditions) / [Horde](https://www.wow-mania.com/armory/?quest=12897#conditions), as we can see on the condition page:

![image](https://user-images.githubusercontent.com/31921098/219336701-270a02d6-1335-4b23-96b1-fa97114b285c.png)

This quest start a new questline (that will check on a future step)

And from here, we can follow this graphic:

![image](https://user-images.githubusercontent.com/31921098/219329747-25cbecd3-a4ac-4a80-b63e-bc590216c53c.png)

Edit:
After turning Shadow Vault, only one NPC changes

![image](https://user-images.githubusercontent.com/31921098/219391248-933c56af-3bd7-428b-b9f0-0e1808a05452.png)

**Comment by Echinaceax** [comment]
Confirmed bug on PTR 

After picking quest up, all quests are seen including dailies i didnt even unlock yet  

1. [t's All Fun and Games]
2. [I Have an Idea, But First...]
3 [Free Your Mind]
4 [If He Cannot Be Turned]


![image](https://user-images.githubusercontent.com/39439201/219389426-eccfa461-1052-4c27-9daf-92c982b2610d.png)

**Comment by WhitephoenixTheBunny** [comment]
1. [It's All Fun and Games (A)](https://wow-mania.com/armory/?quest=12887) / [ It's All Fun and Games (H)](https://wow-mania.com/armory/?quest=12892)
2. [I Have an Idea, But First...](https://wow-mania.com/armory/?quest=12891)
3. [Free Your Mind](https://wow-mania.com/armory/?quest=12893)
4. a. [If He Cannot Be Turned (A)](https://wow-mania.com/armory/?quest=12896)  /  [If He Cannot Be Turned (B)](https://wow-mania.com/armory/?quest=12897)  
   b.  [Blackwatch](https://wow-mania.com/armory/?quest=13106) (This starts a new questline)
5. [The Shadow Vault (A) ](https://wow-mania.com/armory/?quest=12898)/ [The Shadow Vault (H)](https://wow-mania.com/armory/?quest=12899)
6. [The Duke](https://wow-mania.com/armory/?quest=12938)
7.  7.1. [Honor Challenge ](https://wow-mania.com/armory/?quest=12939)
       ....7.1.1. a. [Shadow Vault Decree](https://wow-mania.com/armory/?quest=12943) 
       ............... b. [Get the Key](https://wow-mania.com/armory/?quest=12949)
       ......................... b.a. [Let the Baron Know](https://wow-mania.com/armory/?quest=12951)
       ....7.1.2. a. [Vandalizing Jotunheim](https://wow-mania.com/armory/?quest=13084)
       ........................... _Daily_. [Leave Our Mark](https://wow-mania.com/armory/?quest=12995)
       ............... b. [Crush Dem Vrykuls!](https://wow-mania.com/armory/?quest=12992)
       ........................... _Daily_. [Vile Like Fire!](https://wow-mania.com/armory/?quest=13071)
       ....7.1.3. [Vaelen Has Returned](https://wow-mania.com/armory/?quest=13085)
       ....7.1.4. [Ebon Blade Prisoners](https://wow-mania.com/armory/?quest=12982)
      .... 7.1.5. [To the Rise with all Due Haste!](https://wow-mania.com/armory/?quest=12806)
      .... 7.1.6. [The Story Thus Far...](https://wow-mania.com/armory/?quest=12807)
       ............... a. _Daily_. [From Their Corpses, Rise!](https://wow-mania.com/armory/?quest=12813)
       ............... b. [Blood in the Water](https://wow-mania.com/armory/?quest=12810)
       ......................... b.a. [You'll Need a Gryphon](https://wow-mania.com/armory/?quest=12814)
       ......................... _Daily_. [No Fly Zone](https://wow-mania.com/armory/?quest=12815)
       ............... c. [Intelligence Gathering](https://wow-mania.com/armory/?quest=12838)
       ......................... c.a. [The Grand (Admiral's) Plan](https://wow-mania.com/armory/?quest=12839) start from [Note from the Grand Admiral](https://wow-mania.com/armory/?item=40666)
       ......................... c.b. [In Strict Confidence](https://wow-mania.com/armory/?quest=12840)
       ......................... c.c. [Second Chances](https://wow-mania.com/armory/?quest=12847)
       ......................... c.d. T[he Admiral Revealed](https://wow-mania.com/armory/?quest=12852)
     7.2 [Eliminate the Competition](https://wow-mania.com/armory/?quest=12955)
     (need complete from here)

**Comment by WhitephoenixTheBunny** [comment]
Aaaaaaaaaand I will need open another report for 
![image](https://user-images.githubusercontent.com/31921098/220143945-fe2c2066-505a-4b1c-8358-bfe3516e7f7a.png)


"arrives soon" (insert suspence muisic)

**Comment by Rushor** [comment]
Till Quest: [The Shadow Vault (A) ](https://wow-mania.com/armory/?quest=12898)/ [The Shadow Vault (H)](https://wow-mania.com/armory/?quest=12899) 

The chain is correct so far, rest fix will be pushed today for test :)

**Comment by Rushor** [comment]
Will be delayed to next week because a other questchain is affected aswell and it must be fixed together.

**Comment by Rushor** [comment]
moved to the private repo @WhitephoenixTheBunny there you can include the other quest chain issue aswell

**Comment by Greywolf59** [comment]
So quick review from me too.

1. [Shoot 'Em Up](https://www.wow-mania.com/armory/?quest=13069) is available from the first visit to freed Shadow Vault (from the start onwards).
It should be available after handing in [Ebon Blade Prisoners](https://www.wow-mania.com/armory/?quest=12982)
https://www.wowhead.com/wotlk/quest=12982/ebon-blade-prisoners#comments:id=846677
https://www.wowhead.com/wotlk/quest=13069/shoot-em-up#comments:id=724332
https://www.warcrafttavern.com/wotlk/guides/icecrown-daily-quests/
https://wowpedia.fandom.com/wiki/Let_the_Baron_Know#Notes

2. [Crush Dem Vrykuls!](https://www.wow-mania.com/armory/?quest=12992)
Available from the start. Should be available after completing [Let the Baron Know](https://www.wow-mania.com/armory/?quest=12951) and plausibly also [Shadow Vault Decree](https://www.wow-mania.com/armory/?quest=12943).
https://wowpedia.fandom.com/wiki/Crush_Dem_Vrykuls!?so=search#Notes
https://www.wowhead.com/wotlk/quest=12992/crush-dem-vrykuls#comments:id=846673
https://www.warcrafttavern.com/wotlk/guides/icecrown-daily-quests/
https://www.wowhead.com/wotlk/quest=12992/crush-dem-vrykuls#comments:id=543485:reply=74844
https://wowpedia.fandom.com/wiki/Let_the_Baron_Know#Notes

3. [Vile Like Fire!](https://www.wow-mania.com/armory/?quest=13071)
Available form the start. Should be offered only after completing Crush Dem Vrykuls! Otherwise same prerequisites and link as number 2. on the list.

4. [To the Rise with all Due Haste!](https://www.wow-mania.com/armory/?quest=12806)
Available from the start. Should be available after completing [Ebon Blade Prisoners](https://www.wow-mania.com/armory/?quest=12982).
https://www.wowhead.com/wotlk/quest=12982/ebon-blade-prisoners#comments:id=846677
https://www.wowhead.com/wotlk/quest=12982/ebon-blade-prisoners#comments:id=481078
https://wowpedia.fandom.com/wiki/To_the_Rise_with_all_Due_Haste!?so=search (table on the right)

5. Three quests in one.
[From Whence They Came](https://www.wow-mania.com/armory/?quest=13171), [An Undead's Best Friend](https://www.wow-mania.com/armory/?quest=13169) and [Honor is for the Weak](https://www.wow-mania.com/armory/?quest=13170), plus their followups after you complete these, are available from the start. They should be offered only after player completes [Parting Gifts](https://www.wow-mania.com/armory/?quest=13168) (opened most likely by [A Short Fuse](https://www.wow-mania.com/armory/?quest=13263) )
https://wowpedia.fandom.com/wiki/Parting_Gifts?so=search#Progression
https://www.wowhead.com/wotlk/quest=13263/a-short-fuse#comments:id=974535
https://www.wowhead.com/wotlk/quest=13168/parting-gifts#comments:id=463575

UPDATE: [Parting Gifts](https://www.wow-mania.com/armory/?quest=13168) has prerequisites in order, opens at proper time, aroudn the time [A Short Fuse](https://www.wow-mania.com/armory/?quest=13263) is handed in and when player gets back from the pit.

6. [Vandalizing Jotunheim](https://www.wow-mania.com/armory/?quest=13084)
Available from the start. Should be available after completing [Let the Baron Know](https://www.wow-mania.com/armory/?quest=12951) and plausibly also [Shadow Vault Decree](https://www.wow-mania.com/armory/?quest=12943)
https://wowpedia.fandom.com/wiki/Vandalizing_Jotunheim?so=search
https://www.wowhead.com/wotlk/quest=13084/vandalizing-jotunheim#comments:id=846669
https://wowpedia.fandom.com/wiki/Let_the_Baron_Know#Notes

That is all for now. I will fill in any other issues in next comment as I take this comment as selfstanding from any other issues that might arise during quest progression as this comment gathers up the issues that are present at the very beginning of starting the Shadow Vault zone.

**Comment by Greywolf59** [comment]
7. [Leave our Mark](https://www.wow-mania.com/armory/?quest=12995) is currently set to require [Vandalizing Jotunheim](https://www.wow-mania.com/armory/?quest=13084).
Leave Our Mark should require only [Let the Baron Know](https://www.wow-mania.com/armory/?quest=12951) and [Shadow Vault Decree](https://www.wow-mania.com/armory/?quest=12943) and it is normally done at the same time with [Vandalizing Jotunheim](https://www.wow-mania.com/armory/?quest=13084).

https://www.wowhead.com/wotlk/quest=12995/leave-our-mark#comments:id=846675 (there is direct arrow to it from the Let the Baron Know branch, unlike Vile Like Fire! daily which should be open only after Crush Them Vrykuls!)
https://wowpedia.fandom.com/wiki/Leave_Our_Mark (table)
https://www.wowhead.com/wotlk/quest=12995/leave-our-mark#comments:id=795263

8. [Vaelen Has Returned](https://www.wow-mania.com/armory/?quest=13085) is currently set as requiring [Crush Dem Vrykuls!](https://www.wow-mania.com/armory/?quest=12992) and [Vandalizing Jotunheim](https://www.wow-mania.com/armory/?quest=13084).
Vaelen Has Returned and subsequently [Ebon Blade Prisoners](https://www.wow-mania.com/armory/?quest=12982) should require only [Let the Baron Know](https://www.wow-mania.com/armory/?quest=12951) and plausibly also [Shadow Vault Decree](https://www.wow-mania.com/armory/?quest=12943)
https://www.wowhead.com/wotlk/quest=13085/vaelen-has-returned#comments:id=846676 (unclear at this part)
https://wowpedia.fandom.com/wiki/Let_the_Baron_Know#Notes
https://wowpedia.fandom.com/wiki/Vaelen_Has_Returned#Notes
https://www.wowhead.com/wotlk/quest=12982/ebon-blade-prisoners#comments:id=457337:reply=58274 (player apparently did both quests at the same time)
