### ISSUE TITLE
About item stat issue

### ISSUE THREAD

**Issue by Arkaci** [WoWManiaUK/Redemption#6020]
Greetings.

![1](https://github.com/WoWManiaUK/Redemption/assets/135339611/43d6d314-93b0-4dc0-af41-e3e694c84523)

![2](https://github.com/WoWManiaUK/Redemption/assets/135339611/51df20bd-001f-4806-b9f1-e46570b61e2e)

As you can see in the pictures I shared, their stats are not visible when they are in my bag and on me. This and many more items have the same problem.  At the same time, I can't benefit from the stat it gives. I tried reinstalling from different computers but it didnt work.

I'm waiting for your helps.

Best regards.

**Comment by Echinaceax** [comment]
thanks for reporting @Arkaci 
this issue was reported here #6019 already, it was checked and found not to be a server side issue. we couldnt reproduce the bug

check you are running the full mania client, delete cache, run the launcher as admin, if the bug is still there for you then disable addons, there is a conflict in your files somewhere

**Comment by Rushor** [comment]
yep 1) addons disable 2) on wotlk client some stats are visually not displayed (item and spell/talents). But that was on retail aswell and is an as-is issue.
