### ISSUE TITLE
[Item] Bitter Balebrew Charm / Bitter Brew / Brewfest Brew Toss not working

### ISSUE THREAD

**Issue by GMZinius** [WoWManiaUK/Redemption#6059]
**Links:**
Item https://www.wow-mania.com/armory/?item=49116
NPC The Black Brewmaiden https://www.wow-mania.com/armory/?npc=36024
Spell https://www.wow-mania.com/armory/?search=Bitter+Brew#spells
Spell https://www.wowhead.com/wotlk/spell=48249/brewfest-brew-toss
item brew https://www.wow-mania.com/armory/?item=33929

**What is Happening:**
Notice people saying that this wasnt working, so I checked it.
- She is inactive

**What Should happen:**
- When a player /wave to the The Black Brewmaiden she should give player a Brewfest brew ID 33929
- When a player uses the trinket, The Black Brewmaiden should participate in the fight using Bitter brew spell and melee dmg `atm she stands there inactive`

![image](https://github.com/WoWManiaUK/Redemption/assets/108176634/9c3c4493-310a-4444-ad2d-514912ba1598)

**Comment by Lumber-Jack-2** [comment]
this one i can handle now

**Comment by Lumber-Jack-2** [comment]
the /wave mechanic is added and the despawn after 0 seconds, aswell as the follow movement.
for the dmg part - the enemy must attack the Black Brewmaiden, then it will do dmg

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR for the part stated from Rushor 

- [x] Brew given when summoned and player /wave at her
- [x] Movement follow https://i.gyazo.com/ca7457617086732f1ca41861b1f240b5.mp4
- [x] Enemy attack https://i.gyazo.com/f0af3577febef0ca160d95944585699c.mp4

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/c733f77d-5f49-4da0-81b2-63c7ea20efce)
