### ISSUE TITLE
[Quest] Great Bear Spirit - Text missing

### ISSUE THREAD

**Issue by stealer0517** [WoWManiaUK/Redemption#6061]
https://www.wowhead.com/classic/quest=5929/great-bear-spirit
https://www.youtube.com/watch?v=E9lEZ8hIwJQ

The text from the Great Bear Spirit NPC is missing, every page is just "greetings, (character)". 
Your characters responses are there, it's just the text from the bear that is missing.

**Comment by GMZinius** [comment]
Thank you for reporting @stealer0517 
Confirmed bugged
- The Text above the clickable dialog on each page are indeed missing.

**Comment by Echinaceax** [comment]
Fixed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/9e7ce5d7-9335-4d2e-b4f9-54531af4ea9f)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/8b261180-9a4b-43e2-a9d4-48a702b2965b)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/9bc08723-4be5-44c4-8861-46fd81ef3726)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/bf92a12f-82b4-4fa7-bdd8-91da162c23b2)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/1b45236b-f77b-4169-950e-e6c97cbca26f)
