### ISSUE TITLE
IGM- Auction Sold (No currency recieved)

### ISSUE THREAD

**Issue by Nightowlamerz** [WoWManiaUK/Redemption#6064]
**Links:**

**What is Happening:**
I get the mail notification and go to mail box I see "Pending sale" and on the bottom where the money suppose to be it says" Money not sent yet"
But then I see the delete timer. 

This has happened more then once already.
![Mail](https://github.com/WoWManiaUK/Redemption/assets/145604557/14fdefe9-68c7-4e98-b685-bae47a32ccfd)

**What Should happen:**
I should receive the currency for item sold in Auction House.

**Comment by Echinaceax** [comment]
@Nightowlamerz 
this is actually reported by a GM internally 
the "pending mail" does actually auto delete in 60 mins (instead of 30mins)
the actual sale mail comes in 30 mins of that "pending mail being sent

i will close this one atm, coz it will be fixed in the internal report, but thanks for reporting

**Comment by Nightowlamerz** [comment]
Thank you for explaining that to me.

**Comment by Echinaceax** [comment]
> Thank you for explaining that to me.

Your welcome @Nightowlamerz
