### ISSUE TITLE
Dungeon Quest Brother Against Brother not providing credit for Lakka

### ISSUE THREAD

**Issue by bigchipbag** [WoWManiaUK/Redemption#6068]
**Links:**
https://www.wow-mania.com/armory/?quest=10097

**What is Happening:**
The kill credit for the boss is fine but then only the person who interacts with Lakka to let them out is given credit for the action. Two other players with the quest were left with only the credit of the boss kill, and the NPC was despawned. 

**What Should happen:**
All players should get credit for freeing lakka.

**Comment by Lumber-Jack-2** [comment]
all players should get the credit now

**Comment by Echinaceax** [comment]
Fixed in PTR 

Mine 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/2344eed7-2124-48e8-8985-9326b2eef9e7)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/880a3a0d-78c6-430d-8e3f-48e66592ad5f)

Maine 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/b05eb0f4-0c36-4cc4-a22d-66a525c47127)
