### ISSUE TITLE
Fixing ZulAman NPC Hex Sticks

### ISSUE THREAD

**Issue by vandamark** [WoWManiaUK/Redemption#6106]
In ZulAman when you turn in the hex sticks to transform the frogs into npcs, the food vendor Gunter only spawns around 50% of the time after you turn in all hex sticks. I see that the npcs have duplicates of several, for instance there were 3 Metzis and 3 Fudgericks in one run. It seems those duplicates are taking the place of the food vendor Gunter as there are only around 12-20 frogs. After you use hex sticks on all of them, you can't spawn more, therefore no Gunter.

There should be 1 of each npc.

![Fudgerick](https://github.com/WoWManiaUK/Redemption/assets/73784106/03d6716f-87de-41be-912c-4412fe6e246b)

**Comment by Echinaceax** [comment]
thx for reporting, we can check on this @vandamark

**Comment by Echinaceax** [comment]
Tested and no issue @vandamark 

https://i.gyazo.com/5d75200febca55eb76a6b6fe4de68e40.mp4
https://i.gyazo.com/0f7db1fa5d3b9e21d778542195a2c57f.mp4

**Comment by vandamark** [comment]
The Regents vendor always spawns, that's different than the food vendor. Plus it happens half the time so you will need to test more than once.

You may want to check all the frogs because when you do them all, make sure they are all different npcs, there should be no duplicates.

**Comment by vandamark** [comment]
The Regents vendor always spawns, that's different than the food vendor.
Plus it happens half the time so you will need to test more than once.



Nicholas Day
*Content Manager*
MyArea Network, Inc

m: 813-446-7792 <(813)%20446-7792>
a:  500 E Kennedy Boulevard, Suite 101
     Tampa, FL 33602
w:  www.myareanetwork.com

**Comment by Echinaceax** [comment]
food vendor Gunter  is here on my video timestamp 0:22 https://i.gyazo.com/0f7db1fa5d3b9e21d778542195a2c57f.mp4

**Comment by vandamark** [comment]
Ok I see that it worked for you, hoping it does the same for me tomorrow or I will create another ticket. Thank you for helping!

It's strange you didn't get any duplicates when I have like 4 of the same npc in my runs.

**Comment by WhitephoenixTheBunny** [comment]
Do you have a link where it shows that they should not have any duplicate?

**Comment by vandamark** [comment]
There are only 12 frogs so that checks out

https://wowpedia.fandom.com/wiki/Amani_Hex_Stick

Once the hex is removed from the NPCs they move to the front room of the instance. Many of them wander a little bit. The children hurtle around the chamber as children usually do.

Adarrah
Brennan
Christian
Deez
Darwen
Fudgerick
Galathryn
Gunter <Food Vendor>
Hollee
Kyren <Reagents> (reagent vendor)
Mannuth
Mitzi

**Comment by Echinaceax** [comment]
> It's strange you didn't get any duplicates when I have like 4 of the same npc in my runs.

i did get duplicates i just didnt video them.
anyway its only a "could" not a "will" spawn

https://wowpedia.fandom.com/wiki/Gunter

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/0624e5bb-3dbb-4203-9d5f-30fbd7593fe0)

i got Kyren and Gunter in my test

**Comment by vandamark** [comment]
Ok understood. I didn't know he doesn't always spawn. It's strange because that means that there would guaranteed be duplicates. 

Why would they allow for duplicates of the same npc when that clearly looks like a bug to see 4 Fudgericks on the same screen.

**Comment by Echinaceax** [comment]
yes i know, unlucky to get 4  Fudgericks , i got 3 Darwins and 2 Hollee
https://i.gyazo.com/426d4c6fd91309d2a701b33d943391b8.mp4

`There are only 12 frogs so that checks out`
there is actually 19 frogs spawned

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/08835a69-dd7f-42fc-bf02-64d69ebac776)


`Once the hex is removed from the NPCs they move to the front room of the instance. Many of them wander a little bit. The children hurtle around the chamber as children usually do.`

Timestamp 0:48 https://www.youtube.com/watch?v=YRNoPbKWyz4 is same as we have. only thing i notice is that Mania NPC dont have any gossip text 

ofc things changed in Cata so im guessing the npc placements changed too

notes (spawned for me) using 30 Hex Sticks (3 tests) 
Adarrah, Brennan, Christian, Deez, Darwen, Fudgerick, Galathryn, Gunter (food vender), Hollee, Kyren (reagent vendor)
Mannuth, Mitzi

https://i.gyazo.com/816f1a2bc31cd3ef9af3b9b04bcafe89.mp4
