### ISSUE TITLE
[Quest] Post-partum Aggression – Hemet not helping

### ISSUE THREAD

**Issue by Greywolf59** [WoWManiaUK/Redemption#6109]
Naxx realm.

[Post-partum Aggression](https://www.wow-mania.com/armory/?quest=12614) quest is not fully scripted.
[Stampy](https://www.wow-mania.com/armory/?npc=28468)
[Hemet Nesingwary](https://www.wow-mania.com/armory/?npc=28451) does not talk, does not shoot/attacks and does not lay traps.

8y old video, couldn't find older: https://www.youtube.com/watch?v=xbRkQ_pNbTA&ab_channel=GameGuides
1y old wotlk classic (closer to the current state on Mania): https://www.youtube.com/watch?v=W6gtQSMXPFM&ab_channel=DibuckTV

Wowhead comments that add to the claim the fight is missing some action from Hemet:
https://www.wowhead.com/quest=12614/post-partum-aggression#comments:id=517444
https://www.wowhead.com/quest=12614/post-partum-aggression#comments:id=366318
https://www.wowhead.com/quest=12614/post-partum-aggression#comments:id=462171

In all and all currently players have to finish the fight on their own, shouldn't be the case.

**Comment by Echinaceax** [comment]
`8y old video, couldn't find older:`
From what i have seen in 8 year video you linked this has 4 spells on vehicle bar, a hunters mark, which the other 2 videos have 3 same as Mania

I see, Arcane Shot and Immolation Trap Effect from him in the combat log 
I also hear him speaking and attacking 
https://i.gyazo.com/f6b3725c1c37d4fa0e53851a2289db4f.mp4
https://i.gyazo.com/3fcab247dd521569fc24e385241dc76e.mp4

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/5aad6e1e-a626-4cde-bd05-dd820877d24e)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/0924c6c3-f561-4476-bab2-57c064bf6e6f)

So are you meaning visually?
I visually didnt see the trap on the ground but I was on top of him

However 
What I did notice is that if i attacked any other mob other than the quest mob, he doesnt talk or use Arcane Shot and Immolation Trap (so that part is obvious)

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/c6e3a0d7-55ad-4019-b507-d5b331140a6c)

**Comment by Greywolf59** [comment]
I did not check combat log, forgot it exists. But Hemet did nothing. Drake took damage only when I used spell 2 (gore). I did not attack anything else nor was attacked by anything on my way to Slivina.

**Comment by Echinaceax** [comment]
I would check your mania client @Greywolf59, delete cache etc... coz as you see from my test all is working fine (only the trap visual) but that could be coz i was ontop of him and not moving around scared of him

**Comment by Echinaceax** [comment]
Closing for now, no feedback update from @Greywolf59

**Comment by Greywolf59** [comment]
Handed in already when this report was written, there won't be any most likely.

**Comment by Lumber-Jack-2** [comment]
Issues that can be reproduced can Mostly be fixed :)
