### ISSUE TITLE
Lady deathwisperer (does not work as inteded)

### ISSUE THREAD

**Issue by jurrianvg** [WoWManiaUK/Redemption#616]
I've been monitoring this fight for 3 weeks now, we as guild are stuck on this boss. I've watched over 6 video's how people did this in Retail. We do the same as they do. Only problem is that the vengefull spirits hit the target in Retail for 13.4k-16.5k and in here it hits the target for 22-24k i don't think this should happen, same with the frostvolley, it should hit due the mark of the wild and the frost resist aura around 9k to all players but it does in reallity 13-14k dps. this meaning 1 spirit that hits the target + 1 frostvolley mean an instant wipe. Only the damage is the problem, timers and stuff work correctly!

**Comment by fvicaria** [comment]
I have checked with players that did this yesterday and GMs.
This is as is. Your are supposed to run away from spirits. 25HC is supposed to be hard and if you miss the mechanics you die.

**Comment by jurrianvg** [comment]
As i said you should run, but not that het frost volley + 1 of the 2 spirits that hits the group explodes that you instant wipe... it's **not** possible to not get hit by the spirits, because the spawn from you in a 0-15 yard range...

**Comment by fvicaria** [comment]
I will check it again. Are you talking about 25 HC?

**Comment by jurrianvg** [comment]
Yes i mean 25HC

**Comment by fvicaria** [comment]
I will check it and if it is a problem it will be fixed for this Wednesday.

**Comment by jurrianvg** [comment]
We can link you a video if you want to with the damage we take and the video's i've seen so we can clarify this is true :)

**Comment by Plege** [comment]
Here is my analysis of the Lady D encounter concerning Frostbolt Volley and Spirit explosion:

My source is Paragon vs. Lady Deathwhisper 25 hc https://www.youtube.com/watch?v=J2b-68A5Zi0

During the video you can see several times the raid getting hit by frostbolt volley doing around 12-15k damage to the average player. As this is a top guild and one of the world first kills I'm positive they had mark of the wild and frost resist aura on. so the frostbolt volley damage seems fine to me.

Now getting good values for the spirit explosion damage value is hard as they are good at avoiding it but at 5:30 in the video we can see the raid getting hit by the volley and directly after by an explosion resulting in the death of 5 players. As a volley did about 1/3 of the players health in damage and the explosion killed them 25k damage seems legit.

As to what the explosion was i'm almost certain it was a spirit explosion because the adds where killed before the explosion it rules out one of them blowing up and death and decay spawns a few seconds later so that rules dnd out and mc follows after a few seconds after the explosion so it wasn't one of the mc'd either. this pretty much leaves us with the spirit explosion as the only option.

This means (to a full buffed raid and per player hit):
frostbolt volley ~15k damage
spirit explosion ~25k damage
frostbolt volley + spirit explosion likely a wipe 
also shows that both can happen at the same time

If i missed anything please correct me and show your source

Regards

**Comment by fvicaria** [comment]
![image](https://cloud.githubusercontent.com/assets/9414661/21306370/80478708-c5c8-11e6-8d84-b22ca3e32b9f.png)

http://wotlk.openwow.com/spell=72012

You have all 4 versions here.

Come up with official values that contradict this and I will continue to look at it.

**Comment by jurrianvg** [comment]
Hey plege, from what i know from the past is that lady death was over tuned and after some times turned so other guild could kill it, the top guild have much more experience then we do, they kill bugged bosses in legion (end bosses) but they have inside info from GM's and stuff to get this done also. So they can fight it easy and is doable

**Comment by fvicaria** [comment]
We are 3.3.5a. It doesn't matter how it was modified afterwards. We need to follow the resources concerning 3.3.5a only. Always use wotlk.openwow.com or our Armory as reference.

**Comment by jurrianvg** [comment]
Dear GM, read the text, **shadowfrost** in the begin it was shadow as it suppose to be, after it changed to shadowfrost which means it get reduced by shadow and frost resist

**Comment by fvicaria** [comment]
OpenWoW is 100% as it was in 3.3.5a

**Comment by jurrianvg** [comment]
I got a video here https://www.youtube.com/watch?v=j1FNb69vWQI Elemental guild, german guild with a tank's PoV you can clearly see the frostbolt does 14k dmg but he reduces the damage by 5k, in 4:45-4:50 and about the vengefull damage watcfrom 4:45-4:55 you'll see he takes 13k damage and 9k frostbolt damage

**Comment by jurrianvg** [comment]
The time between the fight are from feb 11 (paragon) and the 8th of aug, both 2010, meaning the older video is mostlikely more 3.3.5. then paragon's is

**Comment by Shanksalot** [comment]
I must comment on the fact that you are bringing up "Resistance" from the Druid and/or Pally buffs. Please Keep in mind, in WoW, Resistance was not a damage reduction in the amount of damage you took from that school of spell, but rather a "Chance" to fully resist the spell or not.

**Comment by jurrianvg** [comment]
Well, i used the lichking set (thought it was cheating so got rid of it) but every hit i took was reduced with atleast 60% off the Original hit, sindy's breath does 35k dps or such and i took only 8k every hit.

**Comment by fvicaria** [comment]
I want to start seeing links to reliable references that support what you are saying.

**Comment by jurrianvg** [comment]
What do you actually mean by "reliable references"?

**Comment by fvicaria** [comment]
Blizzard, OpenWoW or our Armory mostly. But I will consider wowhead.com and wowwiki.com if info is not available elsewhere.
You guys are arguing about a 5-feet range spell which is totally avoidable.
Also I have already shown how it was on 3.3.5a. 
I get it, it's hard but that is how it is supposed to be. We have other people doing it just fine.
Don't tell me that they are donators and have awesome gear or whatever, you are supposed to have good gear to do 25HC. I am not lowering the bar.
Unless you show me numbers on actual reference about WotLK I will not change anything.

**Comment by jurrianvg** [comment]
So you confirm the vengefull spirits are actually a 5 feet range spell?

**Comment by Plege** [comment]
pretty sure he argues that the hit radius of the spirit is 5 yards. the explosion is 20 yards as both are written in the spell description

**Comment by jurrianvg** [comment]
But when we did the fight itself, we got people instant hit by the spirits, if my guildleader comes online (i'll send him a mail) if he has it on footage that we got instant hit by some of the spirits.

**Comment by Plege** [comment]
as to the argument the spirits are not avoidable because they can spawn on top a player there is an animation that is working on our server where lady d ''throws'' spirits to the ground and then they spawn there a few seconds after so you actually got time to move away from the spawn point

**Comment by jurrianvg** [comment]
So to sum it up, my video of the german guild isn't valid, paragon's is, resistance does not block every hit in 3.3.5. and i should up because we lack "skill"?

**Comment by Plege** [comment]
not what i was trying to say, my goal is to find buggs in encounters as they are right now and help to fix them so the server has working raid content. but also help to dismiss rumors of buggs that people report because fights seem not to work properly. some fights are darn hard and lady seems harder as i remember her but as long as i can't find proof of a mechanic not working as on retail there is nothing to do about it but to practice the fight and get better at it. imo i rather have retail encounters that require skill and teamwork and sometimes good luck than dumbed down fights that i can easily clear just to get loot.

**Comment by Shanksalot** [comment]
Keep in mind, Lady Deathwhisper and Putricide are the hardest encounters in 25mn Heroic til Lich King. There is a reason so many guilds get stuck on here =D

**Comment by Shanksalot** [comment]
But there have been plenty of guilds on WoW Mania to down her on heroic so far

**Comment by calvinidea** [comment]
Stampeed here. What other changes have been made to this fight? Up till about a month ago, we were one-shotting lady no problem.

**Comment by jurrianvg** [comment]
Dear all gm's you linked me https://www.youtube.com/watch?v=J2b-68A5Zi0 Look at minute 8:45-8:59 you can CLEARY see that the tank takes 13k dmg... due resistances...

**Comment by Shanksalot** [comment]
Vengeful Shades

She will begin summoning these ghosts. Similar to those ghosts you see that spawn after something dies and follows you around doing damage but you can't hurt them back. If you remember those, yea those.

Similar to that, the Shade will follow someone randomly. **If it touches you, you get hurt.** So run away to avoid damage.

Heroic: The Shades will not just hurt one person, but explode hurting everyone within 20 yards. This makes an emphasis on the target of the Shade to run the hell out of the raid and away from people.

**Comment by Shanksalot** [comment]
Dear all gm's you linked me https://www.youtube.com/watch?v=J2b-68A5Zi0 Look at minute 8:45-8:59 you can CLEARY see that the tank takes 13k dmg... due resistances...


Clearly you have forgotten that tanks have built in dmg reduction from talents and specs, so in reality they will take less dmg then other specs.

**Comment by jurrianvg** [comment]
We wipe on the spirits, we get like 22k damage from them (even when it's resisted) i have to admit, our resistances are more consistant with blocking damage then the ones from them, at some point you see the tank gets hits (linked it) for 13988 damage, after the fight was done and the loot dropped he got hit for 18k damage, this is due what you guys say, but we get 22k dmg + frostvolley which equals around 9-14k damage, meaning we take 31-36k dps that is an instant wipe on our part...

**Comment by jurrianvg** [comment]
Paladin tanks:" Guarded by Light,  Reduce spell damage taken by 6%, Shield of templar, reduce damage taken by 3%, so a pally has 9% spell damage reduce, because a spell is not able to be blocked or parried. So lets say he got 13988 damage (like 5k resisted but we do not include that at this point) and let we take the 17k hit he got + eachother divide by 2 to get so 13988+17892 :2 = 15985 damage, we take the 9% damage reduce out by dividing it from 91 and x 100 equals 17565 damage, still not the 22k we take...

**Comment by Plege** [comment]
just to clarify https://www.youtube.com/watch?v=J2b-68A5Zi0  was linked from me and i'm not a gm.
if janitor doesn't want youtube clips as proof for game mechanics it's my fault for bringing them up.

**Comment by Plege** [comment]
i can't follow the calculations 
13988+17892/2=/=15985
13988+17892/2=22934
(13988+17892/2)/91*100=25202.2

**Comment by jurrianvg** [comment]
You put that in the wrong way, mathmaticly Divide goes before + so you divided 17892/2 and after that you did + 13988

**Comment by Plege** [comment]
even without the calculations the video shows that getting hit by spirits + volley = death for most players and this is as was in retail so it is as it should be on our server. this means we need to deal with that and learn to avoid spirits at all cost

**Comment by jurrianvg** [comment]
pleger, come in TS if you are still here (10 man room) so we can discuss

**Comment by calvinidea** [comment]
Ok so from what i'm reading here this is not being classified as a bug. I get that.

So what I want to know, is what has been CHANGED over the last 60 days? Were the spirits BROKEN before and now fixed? The reason I ask this is because we had very little issue passing this boss (2-3 tries tops) up till about 6 weeks ago (or so).

So were things 'fixed' to make it more blizzlike? 

Or the fight made harder to encourage us to buy gear from the server like most members of some other guilds did?

**Comment by fvicaria** [comment]
Yes. It is now closer to retail than before. Having said that, @Emcitementz has identified an issue though. It will be corrected for tomorrow.

**Comment by calvinidea** [comment]
What issue was identified and what is the fix?

**Comment by Plege** [comment]
the Issue: vengeful blast http://wotlk.openwow.com/spell=72012 sometimes triggered procs and damage modifiers wrongfully resulting in excess damage to players

the fix; vengeful blast will now only do the set amount 23160 - 24840 of damage incoming to players, this damage is still subject to damage mitigation like resistances and the like but will never do more than 24840 damage to any player
