### ISSUE TITLE
Mount Warforged Nightmare - Missing the ground mount 

### ISSUE THREAD

**Issue by Helissent** [WoWManiaUK/Redemption#6161]
**Links:**https://www.wow-mania.com/armory/?spell=150328   

**What is Happening:** It can be used only as flying. No ground mount option.

**What Should happen:**  This mount should work like mount Invincible works. Ground mount for cities you can not fly in.
Ground (+60% or +100% speed)
Flying (+150%, +280% or +310% speed)
**This mount changes depending on riding skill and location.**

**Comment by Lumber-Jack-2** [comment]
model related issue, as is

**Comment by Maine1** [comment]
@Helissent To elaborate on rushor's comment, due to imported mounts from other expansions sometimes they have to be set according to mount set rules of 3.3.5a. This is a confliction issue with adding mounts from later expansions that is why we can't always import all the features available from later mounts. Hence the dinosaur mount doesn't have NPC's and so on.
