### ISSUE TITLE
[NPC] Injured Rainspeaker Oracle - Just following Orders

### ISSUE THREAD

**Issue by Dopsche** [WoWManiaUK/Redemption#6162]
[**Links:**](https://www.wowhead.com/wotlk/quest=12540/just-following-orders)

**What is Happening:**
Oracle is already up from the ground. There is no chat option to trigger the spawn of the crocolisk which on kill triggers the quest complete.

SO NPC is standing there with a grey question mark and quest can not be solved and follow-ups are not opened up either.

**What Should happen:**
Oracle should be laying on the ground and should have a chat option. This should spawn a crocolisk . When crocolisk is killed, the quest should be solved.

**Comment by Dopsche** [comment]
Nevermind there are 3 other Oracles

**Comment by Echinaceax** [comment]
we can actually fix this one @Rushor 
i have seen this myself 

Quest Just Following Orders https://www.wow-mania.com/armory/?quest=12540

- [ ] What happens is, players that have completed "Just Following Orders" and that are on the next quest Fortunate Misunderstandings https://www.wow-mania.com/armory/?quest=12570 still get the gossip 
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/b3f855ae-312d-4286-af92-9d5e19fb1eff)

**what should happen is:**

- [ ] players on the "Fortunate Misunderstandings" quest should only get the "im ready gossip"
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/3b16dcae-b34a-49dc-944d-15c330e8f0fc)

this does need fixing because if a player clicks the "pull to their feet " gossip it messes up for the people on the prequest.

**Comment by Echinaceax** [comment]
Looks good on PTR 
Gossip fixed 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/d7f74cfb-6a75-4d5f-96dd-3343e48e34be)

And also checked quest completion 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/d8d085f0-a83e-4e85-82e1-e369dc4aa39a)

Also checked the full completion 
https://i.gyazo.com/cbe2ed7a5eea5148cccf3e617f039981.mp4
Also checked abandoning quest
https://i.gyazo.com/8af443ae7b4b6b05316e863b3fa8a393.mp4
