### ISSUE TITLE
[Spell/Warlock] Siphon Life Glyph/Demon Armor

### ISSUE THREAD

**Issue by Necrosiss** [WoWManiaUK/Redemption#6172]
**Links:**
https://www.wow-mania.com/armory/?spell=63108   - Siphon Life Talent
https://www.wow-mania.com/armory/?item=42469   - Siphon Life Glyph
https://www.wow-mania.com/armory/?spell=47889   - Demon Armor
http://www.wow-mania.com/armory?spell=47892      - Fel Armor

**What is Happening:**
So I have done some testing to above and the numbers look not correct:

All test has be done at dummy in Orgrimmar.

I do with my gear (no procs just basic) 1770 dmg per tick with Corruption (IMPORTANT NOTE: Im using Fel Armor) to the dummy, accord to the Siphon Life talent that should give me back instantly 40% of a heal from the damage done. 

1770-40%=708 back as heal.  To this part is all correct.

If I do change to Demon armor my spell power fall down this is why my Corruption tick now is 1629 but thanks to Demon armor my heal received is increase by 20%. The amount of heal I actually receive after just armor change is now 820. 

So i tried to figure it out what is actual percent of it so I went:

1629-60%= 977    not quite right what I actualy get but maybe its wrong caculation so I did,

1629-40%=651 now +20% from Demon armor 651+20%=781 still not quite the amount I do receive and then I noticed that,

1629-50%=814 and that is the closest that I do receive?

How is it caculated then from where 50% come from?! 

Now it is getting more intrested:

Combine the 2 things togather Siphon Life 40% + Glyph of Siphon Life 25% and Fel Armor ON:

1770 (Corru tick on Fel Armor) 

1770-65%=1150 and the amount I actually receive is 885.. So again I noticed it is 50%?!?!

1770-50%=885 ! 

Now we change armor to Demon Armor again and we do the same 3 caculations:

1629 (Corru tick with Demon Armor)

1629-85% (40+25+20) = 1384

1629-65%= 1058 +20% from Demon armor 1269 

And now the top... 

1629-63% (WHAT?!?)= 1024 and this is the amount I do receive

If my caculation is correct on every single Corruption tick being with Glyph and Demon armor I lose 22% heal. 

I felt like I do receve less heal from my spells recently and now I can clearly see why. Can you please have a look into that?

Thank you.

**What Should happen:**

Corruption should heal warlock more. Possible Demon Armor or Glyph (maybe both) issue.

**Comment by Hajzlopuc** [comment]
Im pretty sure demon armor 20% heal bonus stacks multiplicatively with all healing sources like sihpon life. That means 0.40 x 1.20 = 0.48 = 48%... (if it stacked additively it would be 0.40 + 0.20 = 60%...) You should be healing for 48% of damage done with both up. 

EDIT glyph is also multi not additive, it just make your base 40% siphon x1.25 = 50% and NOT 40+25=65%, then you slap another 1.20 multiplier from demon armor...so final amount is [ dmg x (0.4x1.25x1.20) ]= 60% of dmg is healed with all 3 up

To sum up, 
if just siphon life is up its 40%
if siphon life + demon armor is up its 48%
if siphon life + glyph is up its 50%
if siphon life + glyph + demon armor is up its 60%

so if you are healing for 63% instead of 60%, 50% instead 48%, its actually 5% more than intended but nothing unusual here with rounding errors 

EDIT2 I just realized there is +30% effect of armor talent which makes your demon armor multiplier from 1.20 to 1.26 so that makes us the last scenario with all this shit up

if siphon life + glyph + **_talented_** demon armor is up, formula is 0.40 x 1.25 x 1.26 and thats 0.63 =  **exactly how is your observed 1024/1629 = 0.628 = 63%** in you last test

same with your first test, its siphon life with talented demon armor, formula should be 0.40x1.26 = 0.504 = 50.4%
your numbers 820/1629 = 0.503 = 50.3%

next you tested siphon life + glyph which i already explained it is 0.4x1.25 exactly 50%
your numbers 885/1770 exactly 50% as well

**Comment by Maine1** [comment]
@Necrosiss  after extensive research this is in fact correct values given as stated above by @Hajzlopuc 

This is all working as it should from what i can see and have tested myself to make sure. 
When checking things you can't always simply add base stats and values. If this would be the case corruption would be well Overpowered in PVE!
