### ISSUE TITLE
[Item/Weapon Proc Effect] Nibelung - Valkyr Guardians uncontrollable.

### ISSUE THREAD

**Issue by YggdrasilWotLK** [WoWManiaUK/Redemption#6175]
**Links:**
https://www.wowhead.com/wotlk/item=49992/nibelung#comments (see top comment)
https://www.youtube.com/watch?v=qjvBCL6aDsk

**What is Happening:**
Compared to the latest retail WotLK changes to Nibelung's Valkyr Guardians (see WoW-Head link above re patch 3.3.2 - no changes in Valkyr pet control functionality between 3.3.2 and 3.3.5a), on Mania, these Valkyrs have two shortcomings:
1. The Valkyrs do not follow pet attack commands and cannot be controlled. 
2. The Valkyrs will not engage a target unless a single-target spell is cast or if you take damage from a target. Vector spells/AOE spells such as Blizzard and Hurricane will proc Valkyrs that just wait around for you to take damage or use a single target spell/ability/auto attack. 

**What Should happen:**
1. Valkyr Guardians should be controllable through pet commands.
2. Valkyrs should initially engage and attack the target that procced the spawn, re the YouTube video above.

**Comment by Maine1** [comment]
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/2d4606ce-68f0-4d50-acbb-131ee48b9d6a)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/1a17267b-6b10-4b29-a1e5-338d01784a3f)
![image](https://github.com/WoWManiaUK/Redemption/assets/122736582/e3fcf68d-5482-46a5-bb2a-a2a7c23d7c51)

The Val'kyr's from the weapon do attack the targets which you are in combat with you just have to make sure you have the target right clicked. As in the circle under the target is flashing red/yellow to show you are engaging in combat with it instead of just left clicking to target it without engaging. They work the same as Blood worms from Death Knights and Army of the Dead spell from Death knights. 
The Val'kyr will automatically attack the target if you have right clicked a target to engage in combat. 

These Val'kyrs do NOT have a pet bar to activate them and they didn't have one in retail. The only reason the pet bar is there in this video https://www.youtube.com/watch?v=qjvBCL6aDsk is because the player making the video is a frost mage and he has a water elemental out which makes the pet bar show. This pet bar is only for the controlling of this elemental and not the val'kyrs

**Comment by YggdrasilWotLK** [comment]
My hurricane + Nibelung HC creates numerous valkyrs that stand around and watch my right-clicked target until I cast a single-target spell, auto attack a target, or take damage. This is also reproducible in ICC if need be.

 ![image](https://github.com/WoWManiaUK/Redemption/assets/157967573/7eb15abb-5d2f-43eb-9b30-015349bf36d7)

**Comment by YggdrasilWotLK** [comment]
And re responsiveness to pet commands; in the WoW-Head link, there are confirmed WotLK retail (3.3.x) reports of the Valkyr Guardians responding to commands, not just pet bar clicks. This should include the macroable /petattack and /petfollow, ie. the commands called by the pet bar, but this is not the case on Mania. Regardless, players could back in the day control the Valkyrs from the pet bar attack button on mage elemental and lock pets, and druids through Force of Nature treant pet bar, neither of which work on Mania.

**Comment by Echinaceax** [comment]
> And re responsiveness to pet commands; in the WoW-Head link, there are confirmed WotLK retail (3.3.x) reports of the Valkyr Guardians responding to commands, not just pet bar clicks. This should include the macroable /petattack and /petfollow, ie. the commands called by the pet bar, but this is not the case on Mania. Regardless, players could back in the day control the Valkyrs from the pet bar attack button on mage elemental and lock pets, and druids through Force of Nature treant pet bar, neither of which work on Mania.

Please provide video evidence of this having a pet bar, as Maine has already stated that the pet bar in the video was that of a frost mage elemental

Here is a video from an arcane mage from 2 months ago 0 pet bar 
https://www.youtube.com/watch?v=VdfyMUtymnk

Maine will meet you at the training dummies to show you

**Comment by YggdrasilWotLK** [comment]
The valkyrs dont have a pet bar and never did in retail WotLK either, they simply respond to pet commands whether called through another pet's bar or through commands

**Comment by Echinaceax** [comment]
> The valkyrs dont have a pet bar and never did in retail WotLK either, they simply respond to pet commands whether called through another pet's bar or through commands

Maine is waiting for you in game
