### ISSUE TITLE
[Achievement) Level 10

### ISSUE THREAD

**Issue by WhitephoenixTheBunny** [WoWManiaUK/Redemption#6177]
After watching some people complaining on world cha tabout this achievement not working, and no one bothering to report, I decided level a char 'till level 10 and test, and it's not giving the achievement
![image](https://github.com/WoWManiaUK/Redemption/assets/31921098/8686fad5-b48f-44f6-a907-032330ef4ce4)
![image](https://github.com/WoWManiaUK/Redemption/assets/31921098/07958399-0241-48ea-a99a-b8b7726969e3)

EDIT:
The ppl on world chat were telling it was something recent

**Comment by Echinaceax** [comment]
Fixed in PTR 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/1670536b-03cf-4f18-9df6-df0da471e2fe)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/62d6f337-f54e-433a-b700-57cc2915ab12)
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/0de86d60-64bd-4bc8-8c3b-5b234e379889)

**Comment by WhitephoenixTheBunny** [comment]
i went check my achiev as per gm request, and i saw i do not have anymore my achiev on this toon
![image](https://github.com/WoWManiaUK/Redemption/assets/31921098/fe670d4a-f1c9-42e8-b120-f356218e587a)
