### ISSUE TITLE
Stormwind Flight Master

### ISSUE THREAD

**Issue by Nightowlgamerz** [WoWManiaUK/Redemption#6185]
**Links:**

**What is Happening:**
He is running in place. He shows the flight path symbol but you can't click it.

**What Should happen:**
Click and fly to your destination.

**Comment by Echinaceax** [comment]
thanks for reporting @Nightowlamerz but the Stormwind Flightmaster looks fine to me 
maybe try deleting cache from the mania launcher 

if its been bugged because a Horde has killed it,  then you can ask a GM ingame to reset him next time 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/14ae721c-75a9-436f-9b84-1036f877fe66)
