### ISSUE TITLE
[Item] Tidal Charm and Gnomish o-matic Projector Trinkets are not working as the tooltip says.

### ISSUE THREAD

**Issue by L0dos** [WoWManiaUK/Redemption#6188]
**Links:**
https://www.wow-mania.com/armory/?item=10720
https://www.wow-mania.com/armory/?item=1404

**What is Happening:**

Trinkets are stunning for 1.5 sec and rooting for 10 (half of their durations what the toolbox says) respectively even when diminishing returns are not a factor. When used on a heroic traning dummy it works as it should but the problem is with when used on players.
**What Should happen:**
Should stun / root for the duration it says on the toolbox. No other info on the internet i could find suggesting otherwise.

**Comment by Maine1** [comment]
@L0dos remember that most players in pvp have stun reduction / duration built into specs / meta gems etc. training dummy's can't really count for testing as we know these can give false info when used to test.

**Comment by Maine1** [comment]
Well I did already with the Sap from rogues. Drops from 1 minute to 10 seconds

**Comment by L0dos** [comment]
Hunter freezing traps or sap has a special limitation around them unlike tidal charm or netomatic. Sap incapacitates and freezing trap freezes which does the same thing. They aren't stuns still waiting for u to name a single item / ability that gives %50 stun reduction without diminishing returns. No player talent /racial or meta gem gives %50 stun reduction.

**Comment by Maine1** [comment]
Most players abilities are less via pvp players. Due to how wotLK works and did work back in 2009

**Comment by L0dos** [comment]
We tested tidal charm further today and the charm might be okay. Would love a confirmation still tho. Neto-matic however only roots for 10 secs. And no changes made to the item to have it reduced root time by %50 as can be seen in the SS 
![Screenshot_1](https://github.com/WoWManiaUK/Redemption/assets/33573664/523ec5b2-7209-4abd-a93c-1ce1c6c81ec4)

**Comment by Maine1** [comment]
Yes the charm is working fine. The Neto-matic will be scaling because its such a low level item to use. The more characters / mobs level up the more resistances to lower level items they become. Players even more so than mobs.

**Comment by Echinaceax** [comment]
> Neto-matic however only roots for 10 secs. And no changes made to the item to have it reduced root time by %50

i have spoken to the reporter about the Gnomish o-matic Projector, and we cannot confirm from a wowhead comment if it should be 20 secs in a PvP setting or not. we only can confirm from a forum post listing all engineering tips and tricks 
https://www.reddit.com/r/classicwow/comments/8sz2pz/pvp_and_gnomish_engineering_devices_ranked_by/
![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/8fd3cd7e-8906-46b8-98be-5d8ab1ba9230)

**Comment by Hajzlopuc** [comment]
Every CC in wotlk pvp is maximum 10s duration on 0th DR. Doesn't matter if it's 20s or 60s or 2hours in pve, anything above 10s in tooltip gets reduced to maximum 10sec in PvP (0th DR). 

Sap duration being 10s instead of 60s on players has abolutely nothing with
> "most player characters have stun reduction / duration built into specs / meta gems etc." 

I feel like testers (especially pvpers) should know these basics without even thinking.



So Gnomish Net-o-Matic Projector should last 10s against players and shares DR with other roots.

Tidal Charm tooltip stun is only 3s, it obviously doesn't exceed 10s so its base duration against player should not be reduced at all. It's either successful hit for 3s stun (which can be reduced by talents/meta like any other stun but base duration should still be 3s) or resist against high level (it says "Increased chance to be resisted when used against targets over level 60.") and it shares DR with other controlled stuns.
