### ISSUE TITLE
Scourgebane Draught isn't stacking with flasks when it should.

### ISSUE THREAD

**Issue by L0dos** [WoWManiaUK/Redemption#6189]
**Links:**
https://www.wowhead.com/wotlk/item=22779/scourgebane-draught#reward-from-q

**What is Happening:**
Removes flask or other elixirs when used.

**What Should happen:**

Should stack with other flasks or elixirs. Lots of online comments and videos about it stacking with other flasks and elixirs.

**Comment by Maine1** [comment]
@L0dos we need proof of this working as you say is intended through linking supporting evidence. E.g videos from WotLK 2009 or Screenshots of the evidence from 2009

**Comment by L0dos** [comment]
![Screenshot_1](https://github.com/WoWManiaUK/Redemption/assets/33573664/a66802e0-49ac-4571-bb84-fac54981de76)
Comment on wowhead from 2008 stating it stacks. It had no changes to it since then as can be seen in the next SS

**Comment by L0dos** [comment]
![Screenshot_2](https://github.com/WoWManiaUK/Redemption/assets/33573664/6a34f853-070d-4107-b050-2c8a63f1ba15)

**Comment by Rushor** [comment]
should be able to stack now

**Comment by Echinaceax** [comment]
fixed in PTR 

Scourgebane Draught / Scourgebane Infusion / Water walking
https://i.gyazo.com/308d12ae714cc88085c9a6beb6edb73a.mp4

Scourgebane Draught / Onslaught Elixir
https://i.gyazo.com/07adf88b29be238b12ebc08126a30ad4.mp4

Scourgebane Draught / Mighty agility 
https://i.gyazo.com/a28334eb3541fba20fbab5a339e5f240.mp4
