### ISSUE TITLE
[Boss] The Beast - UBRS

### ISSUE THREAD

**Issue by SamoyedProtW** [WoWManiaUK/Redemption#6195]
**Links:**

**What is Happening:**
The Beast in UBRS does over 10k damage to a prot warrior over 6k gs, this can’t be the correct number, else it would be unbeatable boss in classic

**What Should happen:**

Check his stats please and correct if needed

**Comment by Echinaceax** [comment]
Thanks for reporting @SamoyedProtW 
can you link the boss and we can look into it

**Comment by SamoyedProtW** [comment]
> Thanks for reporting @SamoyedProtW
> can you link the boss and we can look into it

What do you mean link? The Beast, boss in the appendix between Blackwing lair and General Drakkisath, that is his name, giant hellhound

**Comment by Echinaceax** [comment]
> What do you mean link? The Beast, boss in the appendix between Blackwing lair and General Drakkisath, that is his name, giant hellhound

How to report an issue https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/4041e446-0965-47a4-8187-4c851cf67f42)


As with any report players must give the links so that the dev team can check this out 
the link we needed is https://www.wow-mania.com/armory/?npc=10430
and other information like https://wowwiki-archive.fandom.com/wiki/The_Beast and any evidence relating to your report of "this can’t be the correct number, else it would be unbeatable boss in classic" 

@Rushor 
We are unable to verify this atm, have you any information on the Damage that this Boss should be doing?
As we cant go off "this can’t be the correct number, else it would be unbeatable boss in classic"

**Comment by SamoyedProtW** [comment]
> link

If anyone here can help me make wine work on Mac laptop correctly, I will send you screens with combat log and YouTube guides proving it, but until then, I am sorry, my pc power unit burnt out and I can’t connect to the game

**Comment by Echinaceax** [comment]
> If anyone here can help me make wine work on Mac laptop correctly, I will send you screens with combat log and YouTube guides proving it, but until then, I am sorry, my pc power unit burnt out and I can’t connect to the game

This isnt the place for this, you will need to contact Janitor.
once you have sorted this then you can give the info later

**Comment by Lumber-Jack-2** [comment]
its doing around 1000 melee attack on a naked level 80, its totally normal
