### ISSUE TITLE
[Trinket] Super Simian Sphere - shapeshift cant be removed after relog

### ISSUE THREAD

**Issue by Woofles** [WoWManiaUK/Redemption#6208]
[Super Simian Sphere](https://www.wow-mania.com/armory/?item=37254)

**What is Happening:**
If the player logs out with the buff on, the visual buff and the shapeshift state stay even after removing the buff and unequiping the trinket. That makes mounting and using flightpaths impossible. Bug was visible from an alt toon as well.
![image](https://github.com/WoWManiaUK/Redemption/assets/4690356/c1b63526-2711-4177-9bd7-74f51a4f4ddc)
![image](https://github.com/WoWManiaUK/Redemption/assets/4690356/5aedd845-24bb-4809-93dd-4f44a206f7a4)
After a 2nd relog still active.
![image](https://github.com/WoWManiaUK/Redemption/assets/4690356/0391faa6-08d4-4ab7-b859-04500cb92713)

**Comment by Maine1** [comment]
@Rushor [Super Simian Sphere](https://www.wow-mania.com/armory/?item=37254) Is supposed to be removed after buff cancelled or trinket removed.

**Comment by Lumber-Jack-2** [comment]
bubble and transform will now be removed if ape buff is canceled

**Comment by Echinaceax** [comment]
Fixed in PTR https://i.gyazo.com/ef3ccd45298f6ffa3505bdc24e0fd32f.mp4

- [x] When buff is manually clicked off
- [x] When 5 min timer ends
- [x] Unequipping trinket also fixed

Note the 5 mins timer will still remain on logout and only count down when online
on login player can still right click the buff off manually (to remove visual effect)
