### ISSUE TITLE
RS Breath bug 

### ISSUE THREAD

**Issue by lowbg** [WoWManiaUK/Redemption#6211]
**Links:**
https://youtu.be/XiOFz2mPeBA

**What is Happening:**
At some point during phases boss cast Breath and its goes to the group .None of the dps had over-aggro happends 2 times during our pulls  once inside once outside  . as you can see on video noone is even on half way on treat metter

**What Should happen:**
that should not happening

**Comment by Maine1** [comment]
This happened to us but only when we first started raiding. I think its a possible confusion with the boss being reset so many times that it plays with the mechanics. It might also be a core issue but @Rushor will have to check that to see if it is. If all timers and mechanics are set right in the code I don't think that it can be changed?? That being said it doesn't happen to us at all but I think that is due to only having a few wipes per Raid

**Comment by lowbg** [comment]
Someting is wrong in the core that should not happend at all its only in mania  is it either code is with old version or is not been upgraded to the fixed trinity core . Just @Rushor to check  but this is bug  and its not happening first time ! it causing a time waste when happen and player frustration as well!

**Comment by Maine1** [comment]
https://github.com/WoWManiaUK/Redemption/issues/638 Might be related? This never happens to us though not in 2 years at least in the RS's that I do?

**Comment by lowbg** [comment]
2 times in 6 pulls  its not normal !

**Comment by Maine1** [comment]
I will get rushor to re-check code and see if anything is funky with it! Strange it doesn't happen to my group. If the code is fine then it is as is. Unless he can find something that points to a solution

**Comment by GMZinius** [comment]
Thank you for reporting @lowbg 
Please remember how reports work

- Player reports
- Tester checks evidence provided by the player
- Tester comfirmed it is a valid bug

If a tester cannot 100% validate the report, they will internally speak with the Developer to have them check for a few things.  
Note: A Developer has the final say on whether a fix is possible or not, not the tester.

Please keep github reports clear and straight to the point. this helps the Developer to know what to check for.

**Comment by Zl-Si** [comment]
this is old known issue, it used to be fixed 
what is happening during RS fight boss ones he cast debuff  fir/shadow on player will turn towards player that will get debuff
AND if he at same time cast breath whole raid get toasted 
it can happen but it is very rare 
if it happens way to often ones again timer for boss breath skill is out of tune 
i do not remember atm exact timers but breath should come before debuff and be over before debuff on players is casted

**Comment by Maine1** [comment]
> this is old known issue, it used to be fixed what is happening during RS fight boss ones he cast debuff fir/shadow on player will turn towards player that will get debuff AND if he at same time cast breath whole raid get toasted it can happen but it is very rare if it happens way to often ones again timer for boss breath skill is out of tune i do not remember atm exact timers but breath should come before debuff and be over before debuff on players is casted

I don't see any reports for this. I did check. This is why its very important that everything from testing is documented.

**Comment by Maine1** [comment]
Due to low information on this happening and what exactly happened, not being able to see target of target from Halion at the time of the breath it's hard to know what happened at that point in your video. Visual bugs of where Halion is facing have been known in the past also. This doesn't seem to happen to all groups doing Ruby Sanctum heroic and there are atleast 3 groups doing this multiple times a week without issue. Can be reopened at any point should this issue worsen.
