### ISSUE TITLE
[Quest] The Drakkensryd

### ISSUE THREAD

**Issue by Healium7** [WoWManiaUK/Redemption#703]
Going through the pre-req series for The Sons of Hodir and I'm stuck on 6 of 8 "The Drakkensryd" . I accepted the quest from Gretta the Arbiter and I got a warning that I would be flagged PVP if I continued so I decided to wait until I had some uninterrupted time. I logged off right there and came back a few hours later to continue. Now I have no quest in my quest log, no harpoon in my bag and Gretta has a greyed "?" for the quest and a blue ? over her head. I tried back tracking a couple NPCs in the chain but none seem to have the quests to start it again. How do I get to the Sons of Hodir without this pre-req chain?

**Comment by fvicaria** [comment]
As is.

**Comment by thogir** [comment]
Have the same issue, I abandoned the Quest and now it's a greyed "?"

**Comment by Dragonfly414** [comment]
got the same issue... seems not been fixed!

**Comment by Healium7** [comment]
That's why fvicaria said "As is" and closed this thread. 

Let me para phase: 1) Pre-req quest to Sons of Hodir is broken. 2) They don't plan to fix it. 3) Therefore there is no way to acquire the rep needed to min max gear.

That's why I quit playing WoWMania on Jan 16. Good luck all!

**Comment by Dragonfly414** [comment]
I tried posting it on new, and just got telling: its not a bug, you should not abbandon it...
Never abandon it, never got it in my questlog...

Really strange how they deal with it...
They just have to look at the quest... its auto completed, but not at the right questender...
Something with 1 and 0 in the database...

Easy to fix, pity they react like this ...

**Comment by fvicaria** [comment]
The quest is like this. Some quests either you do it or you don't. You won't get a second chance. 
Easy to fix? Why don't you post a fix then?

**Comment by Dragonfly414** [comment]
I cant see where its going wrong in this database... I had once the same issue on my little server and there was on a spot in de DB a 1 instead of a 0... (or the otherside around).
Its because of the autocomplete... if there was something else... than the questender should not have the ? yellow above his head. 
Perhaps the autocomplete part checkup. Like I said, I have to go now... but I think as bug fixers, you all do great at the most quest, I think you should find this one 2....

**Comment by fvicaria** [comment]
As I said feel free to provide a fix. So far all I saw was word like "some field", "some where", "should fix". There are plenty of people with "some knowledge" out there thinking everything is easy but acomplishing very little.

**Comment by Dragonfly414** [comment]
I was always on an trinity core server. Dont know where WowMania is on...

But what I think it could be is this:
I used trinity and Navicat to bugfix thinks... i am not a scripter ..

But could you check the quest template and see what stands by method?


2.Method - usually leave it as it is,but you can change it to 0 or 1,normal for this column is 2.If Method is 0,quest will be auto completed,if it's 1 the quest is disabled

Other thing what can be tried is giving in the ques ender template the quest also to the quest giver.
I am typing this on my telephone now because i g2g to my work...
perhaps later tonight I can check my computer on the total quest line for this quest.

But perhaps these 2 things could be tried...
Because I really think the quest stands on autocomplete and thats why the questgiver has a grey ? and the quest ender a yellow ? But because both only have one template... or quest giver or ender you cant complete it.


Hope you can try this and tell me if it works.
like I said... i am no scripter and dont want to know better... and i have no idea what core this is... but maybe this will work.

Thanks!!

Flamable

**Comment by Dragonfly414** [comment]
Like I promised, I looked up how we had it on our server....
I have tested it on the trinity core and there its easy to get when its abannon:

The total row:
12886	2	67	0	77	0	80	0	0	0	0	0	0	0	0	0	0	0	0	0	128	0	0	0	0	0	13062	13064	0	13064	6	41058	1	0	The Drakkensryd	This is it.  You've passed all the tests of the Hyldsmeet... all but one.  You've risen among our sisters' best and fiercest.$B$BThe final test is at hand.  The Drakkensryd - the true test of a Hyldnir's worth and warrior spirit.  It'll be you, your riding drake, a chained harpoon and a score of your sisters vying for dominance.$B$BShow no quarter.  None will be expected.	Use the Hyldnir Harpoon to defeat 10 Hyldsmeet Drakeriders at the Temple of Storms.  Use the Hyldnir Harpoon on a Column Ornament to exit the Drakkensryd and speak to Thorim when you've succeeded.	Sif... is that you?	Begone!		Return to Thorim at the Temple of Storms in The Storm Peaks.	Hyldsmeet Drakerider Defeated				0	0	0	0	0	0	0	0	0	0	0	0	0	41058	0	0	0	1	0	0	29800	0	0	0	10	0	0	0	0	0	0	0	42841	42865	42887	42876	42863	0	1	1	1	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	165300	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	12340

![knipsel](https://cloud.githubusercontent.com/assets/24796963/23523900/e2d059d2-ff88-11e6-9414-dd25ae8b189f.JPG)

and a picture of it :)
Hope it helps!!

**Comment by fvicaria** [comment]
It's been fixed. Already but thanks anyways.
If you want to contribute more I can add you to our test/dev group. 
Just add me to skype.

**Comment by Dragonfly414** [comment]
Ooh nice it is fixed... got the quest by a GM today. 

I quit my server to do no more fixes because lack of time and just want to enjoy playing wow :)
So thanks for the offer, but not for now... maybe later...

Skype I dont use ;)

Have a nice day!!
