### ISSUE TITLE
[RAID] Eye of Eternity Malygos encounter (updated)

### ISSUE THREAD

**Issue by Readerlady** [WoWManiaUK/Redemption#748]
When doing this dungeon we did not get any of the shields to protect us during phase two. Also once we rezzed after the wipe there was no portal to exit the raid instance.

**Comment by fvicaria** [comment]
Can you link spell names, npc etc. This will help the developers and testers.

**Comment by elagen** [comment]
From what i know of In 25 Man - was about to write a report about it - 10 Man i do not know yet - But will check

Phase 1 Is good (no changes needed)

Phase 2:

In Phase 2 when Malygos goes into the air we are suppose to get Anti - Magic zone that spawn through out phase 2 reducing all magic damage taken while standing inside by 50% -- These Do NOT spawn in Phase 2 of the 25 man run

We Are also Suppose to get these attacks in Phase 2 and we dont 

Arcane Storm: Fires arcane missiles into the air, which strike a random number of targets for 9,425 to 10,575 Arcane damage.
http://www.wowhead.com/spell=61694/arcane-storm

Arcane Breath: Deals 5,000 Arcane damage per second to the whole raid for 5 seconds. Cast at regular intervals. A warning, 'Malygos takes a deep breath,' is given before Malygos uses this. This ability does not effect anyone flying on a disc.
http://www.wowhead.com/spell=60072/arcane-breath

Phase 3 : we only get 1 Attack From Malygos instead of 3

Static Field: Creates a blue, electric-looking orb on a random target. This orb deals 9,425 to 10,575 Arcane damage per second to anyone within 30 yards of it
**(THIS IS THE ATTACK WE GET)**

The 2 Attacks Listed below - we do not get

Surge of Power: Malygos will target a random person and give them a warning that Malygos is focusing on them. Malygos will then shoot a beam at his target, dealing 12,000 Arcane damage every half second for 3 seconds, as well as 5,000 Arcane damage per second to anyone near the primary target for 5 seconds.
http://www.wowhead.com/spell=60936/surge-of-power

Arcane Pulse: Deals 28,275 to 31,725 Arcane damage to anyone within 30 yards of Malygos.
http://www.wowhead.com/spell=57432/arcane-pulse

**Comment by philoudu16** [comment]
The anti magic zones seem to be http://wotlk.openwow.com/spell=56432 (it has a shrinking size and gives a -50% magic damage taken buff)

**Comment by huqboss** [comment]
Some time ago it was also bugged in 10man (anti magic zones didn't spawn at all)

**Comment by wcslanker** [comment]
I've read a few of the previous posts, that were closed for reason I don't know why.... but the bosses are still very bugged in Ulduar. For instance, and this is the biggest bug that makes it impossible to do, the BOSSES do not reset properly if you wipe on them. They evade if you try to attempt them again (if you can even reenter the instance)...... Certain bosses I know what is wrong with them is:

The siege:
-Flame Leviathon (everything is wrong with that encounter, next to no mechanics work on it making hard mode impossible to do)... Pyrite cannot be collected, System Shutdowns, cannot launch players to take out turrets, I believe any passengers die almost instantly, etc.
-XT-002 Deconstructor spawns many more adds than should be scripted
-Razorscale is NOT possible as you cannot shoot him down.

Antechamber:
-The Assembly of Iron theres not too much I can say other than the fact that Stormcaller Brundir is just crazy bugged (runs outside of the room, and his lightning whirl is out of whack).. that's all I can tell about that fight since he's the one that stood out the most.
-Kologarn as I saw in another post does NOT reset if you wipe on him

The Keepers:
-Thorim is the only boss I have done for the keepers, but I know for a fact that the one time I attempted him he did not jump down properly which lead to wipe which lead to him not reset and thus lead to end of the raid.

I do know that fixing these problems will take some time, but I will keep updates on certain mechanics that need fixing. As long as you keep adding comments to what is being fixed or what you have fixed then maybe we can expedite this process... a start to this would be to fix the evading/ only being able to have 1 attempt on each boss.

-Vivamyaggro

**Comment by wcslanker** [comment]
Phase 1 is good? Really now? I'm starting to think the GM's here never played retail.... The Power Orbs don't work properly.
