### ISSUE TITLE
[Quest]: Get to Getry

### ISSUE THREAD

**Issue by gcavalcante8808** [WoWManiaUK/Redemption#762]
http://www.wowhead.com/quest=11703/get-to-getry

When you have found getry you cannot complete the quest and go on with the series (which end in a quest that Saurfang helps to turn the 'boss' down).

**Comment by fvicaria** [comment]
Tested and it works. Please give more info explaining what happened.

**Comment by Readerlady** [comment]
This quest does not work as of 4/1. Getry is standing here but he has no talk option nor is he a question mark so that we can turn the quest in and move on with the quest chain. The next quest is http://www.wowhead.com/quest=11705/foolish-endeavors. This is to kill the NPC that is patting back and forth near the farm.

**Comment by Readerlady** [comment]
Still does not work as of 5/24/2017. Getry is just standing here with no talk bubble or quest completion.
