### ISSUE TITLE
[Event] Crown Chemical Co. 

### ISSUE THREAD

**Issue by Readerlady** [WoWManiaUK/Redemption#784]
I am to venture into Shadowfang Keep and Defeat the insidious undead apothecaries of the Crown Chemical Co. before they unleash their newest, horrific plague. The are not attackable. I need this one for the Love is in the Air achievement. Please check it out and possibly fix it? It was broken last year as well.

**Comment by redhawk816** [comment]
Confirmed!

**Comment by fvicaria** [comment]
I need a lot more info than that.
Please read:
https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue

And complete missing details.

**Comment by redhawk816** [comment]
The Dungeon for the Holiday " The Crown Chemical Co."  http://www.wowhead.com/love-is-in-the-air-2017-guide#boss-apothecary-hummel , Which you queue up through the regular Dungeon Finder. You have to beat 3 Crown Chemical Co. Apothecaries, the main being Apothecary Hummel http://www.wowhead.com/npc=36296/apothecary-hummel.  The problem is non of the Apothecaries are target-able, they are all listed as non target-able Crown Chemical Co. NPC's.  So since we can kill Apothercary Hummel, we don't get the rewards from doing the dungeon: http://www.wowhead.com/item=54537/heart-shaped-box and 1 Maniac Point.   Is that enough info???

**Comment by redhawk816** [comment]
Also, Since Hummel isn't killable we can't get the Achievement http://wow-mania.com/armory/?achievement=4624

**Comment by Readerlady** [comment]
Thank you. That about covers it. There are three apothecaries in the dungeon but they are not named and are untargetable.
