### ISSUE TITLE
[Dungeon] Diremaul (East)

### ISSUE THREAD

**Issue by schwebs** [WoWManiaUK/Redemption#803]
Hey,

The chasing Event with " Pusillin" seems bugged.
Its way too fast while running across the map to its starting point and not to the place where it should appear as boss.

kind regards

**Comment by Kalasbyxan** [comment]
Please read through https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue and provide links for quicker fix :)

**Comment by schwebs** [comment]
http://www.wowhead.com/npc=14354/pusillin
I talked to it at the first point, running twards point 2.
then it was out of sight and i saw it again running from point 3 to point 1 (dung entry).
i killed all the mobs before starting the event, there is no way being that maach faster at the event.

**Comment by hotdoggidy** [comment]
-Enter Diremaul East (43.81 67.41)
-Interact with Pusillin on your left as you emerge onto the broken balcony (npc=14354 previous post) 

Pusillin will taunt you into chasing him around the balcony. The speed at which he runs away is not the issue here. Pusillin should stop at 4 different locations. 2 along the balcony and 2 in "The hidden Trench" right after you exit the balcony. Each time he stops the player/party needs to interact with him to begin the next leg of his chase. At the final position he engages the player/party and summons backup in the form of imps.

Instead, Pusillin is spending a total of 2-3 seconds at each of the 4 "stops" before turning around and pathing DIRECTLY back to his original position at start of dungeon. Once there he does not reset, the next leg of his chase WILL be started by interacting with him and selecting the chat bubble.

To cut this short, a player or party that enter the dungeon MUST interact with Pusillin at his original position for all 4 stages including the ensuing boss fight, which should take place at his 4th position. Im finding it hard to explain this properly. The imp is literally clipping through the environment back to his original position. Screen caps might help get an idea of this little devil's antics. 

Pusillin pathing from first stop back to original position. 
![wowscrnshot_022717_180009](https://cloud.githubusercontent.com/assets/23442126/23388456/8cf321e0-fd1f-11e6-9b90-da7976b24601.jpg)
![wowscrnshot_022717_180020](https://cloud.githubusercontent.com/assets/23442126/23388460/92d980ea-fd1f-11e6-94f0-eeaa8dd3227a.jpg)
![wowscrnshot_022717_180039](https://cloud.githubusercontent.com/assets/23442126/23388463/97d10faa-fd1f-11e6-81f7-511b0dd870b6.jpg)

I have a bunch more screenshots but this is really one of those "you had to be there" moments.
