### ISSUE TITLE
[Quest] Thrusting Hodir's Spear

### ISSUE THREAD

**Issue by Kalasbyxan** [WoWManiaUK/Redemption#81]
The quest (http://www.wow-mania.com/armory/?quest=13003) is completed by using the spear (http://www.wow-mania.com/armory/?item=42769) on a targetted Wild Wyrm (http://www.wow-mania.com/armory/?npc=30275). This allows your character to hook onto the dragon and you can kill the dragon. 

The initial hook onto the dragon does not happen.

**Comment by Bravopatriot** [comment]
I would like to add that since the hook never pulls you toward the dragon, it does leave you with the debuff which places you in combat the whole time. screen shot attached.

![wowscrnshot_070516_232345](https://cloud.githubusercontent.com/assets/19984295/16607528/8daf217e-4307-11e6-83b9-acdc6f1ed057.jpg)
