### ISSUE TITLE
Airplane Quests Icecrown

### ISSUE THREAD

**Issue by YulEb** [WoWManiaUK/Redemption#885]
Hi,
I have the three quests
-Watts My Target http://wotlk.openwow.com/quest=13381
-Leading the Charge http://wotlk.openwow.com/quest=13380
-Static Shock Troops: the Bombardment http://wotlk.openwow.com/quest=13404

where I have to fly with an Airplane given by Karen No http://wotlk.openwow.com/npc=31648 and kill 
-Gargoyle Ambusher
-Bombardment Infantries
-Bombardment Captains
-Frostbrood Sentry

I cant hit the Gargoyles (they kind of jump/dodge every Bullet)
and I only see the Groundunits after the Gargoyles killed me.

The Issue was already mentioned in the Post #266 for one of the quests. It was marked as fixed in November 2016, but i now have the same problem.

kind regards,
laureeny

ps.:Im using your client and the last version of the launcher

**Comment by fvicaria** [comment]
Please read: https://github.com/WoWManiaUK/Redemption/wiki/How-to-Properly-Report-an-Issue
before creating a new issue.

**Comment by fvicaria** [comment]
Works.

**Comment by TenmanWoW** [comment]
Laureeny,

   I went and had a look. While I agree that shooting down gargoyles is a pain (I never was a fan of this quest in retail!), you click on them like you would a normal ground mob in a raid, then fire the rockets at them. You'll notice a faint grey line indicating a path of flight for the rockets. Consider that your aiming reticle.

As for the ground mobs, you have to hit the "Switch to Bombing" button. It looks like a giant grey bomb. Your camera will rotate down and youll be dropping bombs instead of firing rockets. Successful completion of the mission requires you to toggle between the two modes. You can't very well hit ground targets with anti-air rockets and air targets with bombs, now can ya? 

Hope this helps!

**Comment by Brunnr** [comment]
For those still having issues, make sure you select each gargoyle/drake, then fire. I found the right mouse button will also turn your gun, and that combo will shoot the fliers down fast. Clear all the fliers first, then quickly switch to the bomb and drop several, then switch back to guns and check for new fliers. You are in flight for a very long time, and have plenty of time to bomb ground units, so focus on the fliers.
