### ISSUE TITLE
[Quest] Hot and Cold - Hodir Rep

### ISSUE THREAD

**Issue by Ixion73** [WoWManiaUK/Redemption#917]
The drop rate for the quest items, seems exceptionally low

**Comment by Ixion73** [comment]
Well I killed about 30 of the mobs to get 6 drops, this does not equate to 100% to me. Spent 45 mins to get 6 items

**Comment by fvicaria** [comment]
I will check it and see if there is an issue.

**Comment by Ixion73** [comment]
Cheers, may be due to some of the issues you had, was just disheartening to farm like that

**Comment by SaurianDraeni** [comment]
I have recently opened up the Hodir dailies and have been attempting the Hot and Cold quest.
The drop rate for the essence of Ice seems to be 0% at the moment. I have done this quest on other characters in the past and I remember the drop rate to be very near 100% while on the quest.
For the past few days I have killed every Brittle Revenant in the lake area without seeing a single Essence of Ice drop.

**Comment by Echinaceax** [comment]
Thank you for your comment, we will look into this

**Comment by Echinaceax** [comment]
Confirmed bugged 0 Essence of Ice
https://www.wowhead.com/wotlk/item=42246/essence-of-ice

NPC Has totally the wrong loot table and no quest item
in 3 rounds i only got 2 of the same item (Fire shouldnt even be on these)  

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/bd491b58-d237-437f-8161-7acdf4115a6e)

- [ ] Essence of Ice should be 80% drop rate from wowhead

**Comment by Lumber-Jack-2** [comment]
the item was deleted from db, it's fixed now

**Comment by Echinaceax** [comment]
Fixed in PTR
confirmed quest item dropping there now 

![image](https://github.com/WoWManiaUK/Redemption/assets/39439201/8d43dfbf-9df6-4e02-9654-235840877680)

also checked quest completion (acts a little funky if not directly facing the iron when you throw the [essence-of-ice](https://www.wowhead.com/wotlk/item=42246/essence-of-ice) on them, but quest is completable.
https://i.gyazo.com/f51bcee9426b758c288969c69b03571b.mp4
