### ISSUE TITLE
[Core] Fire Leaf Spawns

### ISSUE THREAD

**Issue by Dusticles** [WoWManiaUK/Redemption#923]
Hey! The Fire leaf is created from Firethorn in which it shares a creation with Fire seed which Fire Seed is used for absolutely nothing but to be milled by an inscriptionist, so the Fire leaf is the sought for Herb. Fire thorn only spawns in the Geyser fields in Borean Tundra. Wow mania armory gives no map of the spawns... However! Looking at wow-head there is a larger amount of spawns then I have encountered on the server! I beleive they were added in due to public response to herbing Fire Leaf like myself! Is there anyway we could increase the amount of spawns of the http://www.wowhead.com/object=191303/firethorn
exponentially! I'm not exaggerating in the amount of spawns there are for this Herb for there are a very few that actually spawn in the Geyser fields being the only place they do spawn. 
Also if not exponential increasing spawns.. perhaps tweaking the spawn timers and then adding 5-10 more spawns? It's very frustrating running around for 10 even 25 minutes just to find 1 spawn that has a chance of not dropping Fire Leaf because its brother the Fire seed wanted the spoils!

**Comment by Plege** [comment]
This server tries very hard to be blizzlike. So whenever you want something to change the best chance is to prove that it was different back in the day on retail. A good source for doing so is open wow because it was frozen back when 3.3.5 was live. Be creative, maybe you find a youtube video that proves your point (although it's hard to check for authenticity). But if the thing you ask for is not blizzlike your at the mercy of our devs.

**Comment by fvicaria** [comment]
We have improved it a bit but as Plege said it is as close as Blizzard as we can.
