### ISSUE TITLE
Fel Armor Triggers Cloak Enchant

### ISSUE THREAD

**Issue by vregor97** [WoWManiaUK/Redemption#929]
At first I was puzzed why my Cloak enchant Lightweave Embroidery from tailoring kept proccing out of combat. I just realized that the proc always occurs when Fel Armor heals me passively. I don't think this is supposed to happen. At the moment I have to unequip my cloak before I engage a boss fight so that my enchant is up at the start of the fight. Sorry for wasting time incase this is how it is supposed to work.

**Comment by elagen** [comment]
this was a bug which was in retail also - with fel armor you are regenerating health so that will proc it

**Comment by Igotpooedon** [comment]
Can someone fix this? it's kind of annoying that nothing has been done to prevent it from procking makes it pretty useless for warlocks.

**Comment by tvshadowz** [comment]
Hi there Igotpooedon!

If this issue is persisting then please open an issue here and I'll get on it asap. Please make sure to follow the links below when opening the issue to ensure testers like I have all the information we need:

Please follow this link http://www.wow-mania.com/forums/topic/71 on how to appropriately report a bug. Please place the issue in brakets in the title of your issue, as well as linking items, quests and spells from our armoury here http://www.wow-mania.com/armory/ .

This helps us greatly when it comes to testing and fixing issues with the server. 

Thanks again for the report and your participation in making the server the best that it can be. :)
